- devGuide/en/chapters/04-developing-jsf-portlets.markdown
- develop/tutorials/articles/liferay-faces/accessing-the-portlet-api-with-externalcontext-for-jsf-portlets.markdown
I spoke with Neil about a inconsistency in a Liferay Faces tutorial dealing with the `LiferayFacesContext` and `FacesContext` classes. He recommended we delete the `LiferayFacesContext` reference and use `FacesContext` in the tutorial's code snippet. He characterized the `LiferayFacesContext` class as "semi-deprecated" due to a controversial message in the Liferay Forums, so he'd like to steer away from encouraging the use of that class.
@jhinkey
https://issues.liferay.com/browse/LRDOCS-1520
> Fix - Remove LiferayFacesContext Reference

- develop/learning-paths/mvc/articles/02-writing-a-data-driven-application/02-integrating-persistence-framework.markdown
- develop/tutorials/articles/customizing-liferay-portal/overriding-language-props-hook.markdown
- develop/tutorials/articles/maven/creating-layout-templates-maven.markdown
- develop/tutorials/articles/maven/creating-liferay-hooks-maven.markdown
- develop/tutorials/articles/maven/creating-liferay-maven-plugins-from-command-line.markdown
- develop/tutorials/articles/maven/creating-liferay-maven-plugins-from-liferay-ide.markdown
- develop/tutorials/articles/maven/creating-liferay-portlets-maven.markdown
- develop/tutorials/articles/maven/creating-liferay-themes-maven.markdown
- develop/tutorials/articles/maven/deploying-liferay-plugins-with-maven.markdown
- develop/tutorials/articles/maven/managing-liferay-maven-artifacts.markdown
- develop/tutorials/articles/maven/maven-parent-plugin-projects.markdown
This tutorial was originally written with a workaround in place because for a long period of time, the GA1 artifacts for Liferay 6.2 were not available from Maven Central. Now that the artifacts are available, I tweaked the tutorial to upload archetypes form Maven Central, as we've shown in the past.
I also threw in a commit correcting old links I found throughout LDN. :link: 
https://issues.liferay.com/browse/LRDOCS-1526
> Fix - Update Maven Command Line tutorial

- userGuide/en/chapters/21-configuring-for-high-availability.markdown
The chapter stated an overly limited memory configuration that it shouldn't make (2G). There are portals that legitimately have more than 8G Heap, while 2G might be too much for others. The documentation shouldn't make an assumption about absolute maximum values. This is what I've replaced.
I stumbled upon this statement on https://stackoverflow.com/questions/27273104
> remove recommendation of 2G max JVM memory

- discover/portal/articles/04-configuring-liferay-applications/08-recycling-assets-with-the-recycle-bin.markdown
LRDOCS-1559: https://issues.liferay.com/browse/LRDOCS-1559
Clarified that the default value is true for trash.enabled, and described the behavior of setting it to false.
> De-obfuscation of recycle bin property description

- develop/tutorials/articles/maven/creating-liferay-maven-plugins-from-command-line.markdown
In a previous PR (sez11a#1131), I removed the workaround instructions for generating Maven archetypes when Maven Central did not have the most up-to-date artifacts. I did this because the artifacts on Maven Central were updated to match the latest version of Liferay. Maven Central is again not up-to-date with our latest CE GA3 release, so this workaround is required again. Therefore, I've added a permanent note so we cover both scenarios (updated and un-updated Maven Central), so we don't have to continuously update the tutorial based on Maven Central's status.
> Maven Artifact Generation Note

- devGuide/en/chapters/07-hooks.markdown
- develop/tutorials/articles/07-hooks/07-overriding-and-adding-struts-actions.markdown
https://issues.liferay.com/browse/LRDOCS-1567
Overriding a Struts path that is contained in another Struts action path as a substring causes the custom action to run when either Struts path is invoked. 
Provided workaround for 6.1.x since that's the docs we linked to in the ticket. Will add note to 6.2 devGuide section as well. There is not currently a 6.2 tutorial, so noting it in the devGuide should ensure that when the tutorial is created, the workaround is included.
> BUG workaround: struts hook bug

- discover/portal/articles/09-collaboration-suite/02-managing-events-and-calendar-resources.markdown
- userGuide/en/chapters/09-collaboration-suite.markdown
https://issues.liferay.com/browse/LRDOCS-1603, We did not have a clear description of the Calendar configuration option "Use Global Time Zone". I added some detail on how the Calendar portlet displays times when this op[ptions is selected, depending on whether its viewed by a guest or a logged in user
> Use Global Time Zone calendar option clarification

- develop/learning-paths/mvc/articles/10-creating-web-services-for-your-application/01-creating-remote-services.markdown
- develop/learning-paths/mvc/code/learning-sdk/portlets/guestbook-portlet/docroot/WEB-INF/server-config.wsdd
- develop/learning-paths/mvc/code/learning-sdk/portlets/guestbook-portlet/docroot/WEB-INF/src/com/liferay/docs/guestbook/service/http/EntryService_deploy.wsdd
- develop/learning-paths/mvc/code/learning-sdk/portlets/guestbook-portlet/docroot/WEB-INF/src/com/liferay/docs/guestbook/service/http/EntryService_undeploy.wsdd
- develop/learning-paths/mvc/code/learning-sdk/portlets/guestbook-portlet/docroot/WEB-INF/src/com/liferay/docs/guestbook/service/http/GuestbookService_deploy.wsdd
- develop/learning-paths/mvc/code/learning-sdk/portlets/guestbook-portlet/docroot/WEB-INF/src/com/liferay/docs/guestbook/service/http/GuestbookService_undeploy.wsdd
https://issues.liferay.com/browse/LRDOCS-1621 Added step to remote service learning path: build WSDD. Explained WSDD and WSDL, explained how to generate them, how to check that they were successfully deployed, and noted that generating a wsdd is required for working with the mobile sdk
> Added WSDD step to remote services learning path

- develop/tutorials/articles/application-display-templates/implementing-application-display-templates.markdown
- develop/tutorials/articles/themes-and-layout-templates/embedding-portlets-in-a-layout-template.markdown
- discover/portal/articles/05-document-management/08-liferay-sync-beta.markdown
I incorporated James Falkner's patch to explain that the method must return a Fully Qualified Portlet ID (FQPI). I moved the definition and explanation of Liferay FQPI into a Liferaypedia page and reference it from both the ADT article and the article on embedding portlets in layout templates.
> Fix  - For ADTs, explain what must be returned from getResourceName() method.

- devGuide/en/chapters/06-accessing-remote-services.markdown
https://issues.liferay.com/browse/LRDOCS-1623 Removed discussion of obsolete jsonws.web.service.public.methods property from Dev Guide services chapter; tutorials have already been updated
> LRDOCS-1623 Removed discussion of obsolete jsonws.web.service.public.methods property

- develop/tutorials/articles/service-builder/18-configuring-service.properties.markdown
Remove markup (italics) from title since KB Display portlet does not render it correctly
> Remove markup (italics) from title since KB Display portlet does not render it correctly

- discover/deployment/articles/01-installation-and-setup/14-installing-liferay-on-jboss-7.1.markdown
- discover/deployment/articles/01-installation-and-setup/15-installing-liferay-on-tomcat-7.markdown
- discover/deployment/articles/01-installation-and-setup/16-installing-liferay-on-oracle-weblogic-12c.markdown
CC/ @jhinkey
As a side note, I've linked to the CDI configuration tutorial in the Tomcat, JBoss, and WebLogic 12c deployment sections. GlassFish 3 and Resin are other app servers we specify as being compatible to use CDI with Liferay 6.2, but neither are documented in our Deployment section. Thanks!
https://issues.liferay.com/browse/LRDOCS-1633
> Add links pointing to CDI configuration

- discover/portal/articles/04-configuring-liferay-applications/01-look-and-feel.markdown
- discover/portal/articles/04-configuring-liferay-applications/02-export-import.markdown
- discover/portal/articles/08-personalization-and-customization/03-using-application-display-templates.markdown
- discover/portal/articles/12-using-workflow/02-creating-new-workflow-definitions.markdown
- discover/portal/articles/14-liferay-utility-applications/00-liferay-utility-applications-intro.markdown
- discover/portal/articles/14-liferay-utility-applications/01-capturing-web-sites-with-bookmarks-portlet.markdown
- discover/portal/articles/14-liferay-utility-applications/03-shopping.markdown
- discover/portal/articles/17-using-the-control-panel/05-server-administration.markdown
Throughout discover/portal articles in my crossfunctional areas, I replaced specific references to chapters (e.g., "see chapter 3 for...") with links to articles on LDN and adjusted text as necessary.
> Replace chapter references with links to LDN articles

- develop/tutorials/articles/03-portlet-development/08-localizing-your-portlet.markdown
This addition correctly uses the `welcome-x` key. The 6.2 docs already do it this way. Thanks!
> Add message tag argument

- develop/reference/articles/02-breaking-changes/01-breaking-changes.markdown
https://issues.liferay.com/browse/LRDOCS-473 Add breaking changes document for 6.2 (to appear under dev.liferay.com/develop/reference), add breaking change entry for image utility methods moving from imagelocalservice to imagetool
@jhinkey
> LRDOCS-473 Add breaking changes document for 6.2, document image utility methods move

- discover/portal/articles/03-advanced-web-content-management/08-staging-page-publication.markdown
https://issues.liferay.com/browse/LRDOCS-1728 Add information to remote staging section on valid key lengths for the value of the tunneling.servlet.shared.secret property, explain that the configured encryption impacts key length, explain that it's recommended to use hexadecimal encoding
> LRDOCS-1728 Add information to remote staging section on valid key lengths

- develop/tutorials/articles/01-introduction/00-intro.markdown
Removed table of links and included links in relevant sections of 00-intro.markdown file of develop/tutorials/articles/01-introduction. No ticket entered. @jhinkey
> Altered placement of tutorial links in intro to tutorials

- README.markdown
... I also set the Social Office link to use the 6.2.x branch.
> Update master README, mentioning branch mapping

- develop/learning-paths/mvc/articles/02-beginning-liferay-development/01-developing-apps-with-liferay-developer-studio.markdown
- discover/deployment/articles/05-configuring-for-high-availability/01-liferay-clustering.markdown
Surprisingly, I only had to change this terminology in two Markdown files. I grep searched in `develop/reference`, `develop/learning-paths`, `develop/tutorials`, `discover/deployment`, and `discover/portal`. Most license references dealt with Marketplace licensing or the LGPL license.
https://issues.liferay.com/browse/LRDOCS-1530
> Change "license" to "activation key"

- discover/portal/articles/17-advanced-portal-operation/05-patching-liferay.markdown
https://issues.liferay.com/browse/LRDOCS-1808 Update incorrect explanation of the patching tool's index-info command
> LRDOCS-1808 Update incorrect explanation of the patching tool's index-info command

- develop/tutorials/articles/06-mvc-portlets/02-configurable-portlet-preferences.markdown
- develop/tutorials/articles/user-interfaces-with-alloyui/working-with-the-dom-in-alloyui.markdown
https://issues.liferay.com/browse/LRDOCS-1389 Add references to Java's documentation about the <portlet:defineObjects /> tag
> LRDOCS-1389 Add references to Java's documentation about the <portlet:defineObjects /> tag

- discover/portal/articles/17-using-the-control-panel/02-integrating-existing-users-into-liferay.markdown
https://issues.liferay.com/browse/LRDOCS-1687 Add discussion of Liferay SAML plugin limitation: it can only be used with a single virtual host
> LRDOCS-1687 Add discussion of Liferay SAML plugin limitation: it can only be used with a single virtual host

- discover/deployment/articles/05-configuring-for-high-availability/01-liferay-clustering.markdown
https://issues.liferay.com/browse/LRDOCS-1176 Specify the correct location for the XML files when configuring ehcache settings in a plugin
> LRDOCS-1176 Specify the correct location for the XML files when configuring ehcache settings in a plugin

- discover/portal/articles/17-using-the-control-panel/02-integrating-existing-users-into-liferay.markdown
https://issues.liferay.com/browse/LRDOCS-1531 Update: add note about SAML portlet's property that affects the keystore file and its default storage location
> LRDOCS-1531 Update: add note about SAML portlet's property that affects the keystore file and its default storage location

- develop/tutorials/articles/01-introduction-to-liferay-development/04-customizing-liferay-services.markdown
Fixed some minor typos I saw while reading the tutorial.
> Fix typos in Customizing Liferay Services tutorial.

- discover/portal/articles/17-using-the-control-panel/02-integrating-existing-users-into-liferay.markdown
https://issues.liferay.com/browse/LRDOCS-2051 Update 6.2.x SAML documentation's explanation of SAML SSL required option and its relation to the web.server.protocol property
> LRDOCS-2051 Update 6.2.x SAML documentation's explanation of SAML SSL required option and its relation to the web.server.protocol property

- develop/reference/articles/03-screenlets-in-liferay-screens-for-ios/05-ddl-form-screenlet-for-ios.markdown
No text was edited, only a method signature.
> Edited DDL Form Screenlet for iOS delegate method signature.

- develop/tutorials/articles/04-maven/12-creating-liferay-faces-portlets-with-maven.markdown
- develop/tutorials/articles/06-mvc-portlets/00-intro.markdown
- develop/tutorials/articles/07-jsf-portlets-with-liferay-faces/02-understanding-liferay-faces-bridge.markdown
- develop/tutorials/articles/07-jsf-portlets-with-liferay-faces/03-understanding-liferay-faces-portal.markdown
- develop/tutorials/articles/07-jsf-portlets-with-liferay-faces/04-understanding-liferay-faces-alloy.markdown
- develop/tutorials/articles/07-jsf-portlets-with-liferay-faces/05-understanding-the-liferay-faces-version-scheme.markdown
- develop/tutorials/articles/07-jsf-portlets-with-liferay-faces/06-specifying-the-portlet-xml-file-for-your-jsf-portlet.markdown
- develop/tutorials/articles/07-jsf-portlets-with-liferay-faces/07-using-portlet-preferences-with-jsf.markdown
- develop/tutorials/articles/07-jsf-portlets-with-liferay-faces/08-giving-feedback-to-users-with-validation-messages.markdown
- develop/tutorials/articles/07-jsf-portlets-with-liferay-faces/09-accessing-the-portlet-api-with-externalcontext-for-jsf-portlets.markdown
- develop/tutorials/articles/07-jsf-portlets-with-liferay-faces/10-localizing-jsf-portlets.markdown
- develop/tutorials/articles/07-jsf-portlets-with-liferay-faces/11-communicating-between-jsf-portlets-using-ipc.markdown
- develop/tutorials/articles/07-jsf-portlets-with-liferay-faces/12-contexts-and-dependency-injection-cdi-for-jsf-portlets.markdown
- develop/tutorials/articles/07-jsf-portlets-with-liferay-faces/13-using-the-liferayfacescontext-with-liferay-faces-portal.markdown
- develop/tutorials/articles/07-jsf-portlets-with-liferay-faces/14-leveraging-the-current-theme-with-liferay-faces-portal.markdown
- develop/tutorials/articles/07-jsf-portlets-with-liferay-faces/15-leveraging-the-portal-users-locale-with-liferay-faces-portal.markdown
- develop/tutorials/articles/07-jsf-portlets-with-liferay-faces/16-dynamically-adding-jsf-portlets-to-liferay-portal.markdown
- develop/tutorials/articles/07-jsf-portlets-with-liferay-faces/17-using-predestroy-and-bridgepredestroy-annotations-with-liferay-faces-bridge.markdown
- develop/tutorials/articles/07-jsf-portlets-with-liferay-faces/18-extending-liferay-faces-bridge-using-factory-wrappers.markdown
- develop/tutorials/articles/07-jsf-portlets-with-liferay-faces/98-migrating-from-portletfaces-to-liferay-faces.markdown
- develop/tutorials/articles/07-jsf-portlets-with-liferay-faces/99-building-liferay-faces-from-source.markdown
- develop/tutorials/articles/liferay-faces-bridge-ui-components/00-liferay-faces-bridge-ui-components-intro.markdown
- develop/tutorials/articles/liferay-faces-bridge-ui-components/01-using-the-bridge-inputfile-ui-component.markdown
- develop/tutorials/articles/liferay-faces-bridge-ui-components/02-using-the-portlet-actionurl-ui-component.markdown
- develop/tutorials/articles/liferay-faces-bridge-ui-components/03-using-the-portlet-namespace-ui-component.markdown
- develop/tutorials/articles/liferay-faces-bridge-ui-components/05-using-the-portlet-renderurl-ui-component.markdown
- develop/tutorials/articles/liferay-faces-bridge-ui-components/06-using-the-portlet-resourceurl-ui-component.markdown
- develop/tutorials/articles/localization/00-intro.markdown
It appears most of these sections were carried over from Dev-UAT testing. They're now corrected.
cc/ @ngriffin7a
> JSF Related Topics Corrections

- develop/reference/images/placeholder.txt
The command `ant dist` currently fails in the `develop/reference` directory because it cannot find an `images` directory. I've added the directory so the command runs properly.
> Fix develop/reference dir so "ant dist" works

- develop/tutorials/articles/28-themes-and-layout-templates/embedding-portlets-in-themes-and-layout-templates.markdown
cc/ @mwilliams2014
Based on [this breaking change](https://github.com/liferay/liferay-portal/blob/master/readme/7.0/BREAKING_CHANGES.markdown#taglibs-are-no-longer-accessible-via-the-theme-variable-in-freemarker), embedding portlets in FreeMarker has changed. Julio confirmed this change.
> Embedding portlets in a theme via FTL has changed

- discover/reference/articles/articles.markdown
- discover/reference/articles/configuration-reference.markdown
Hi Rich,
We hadn't created the Discover/Reference/article. I copied it over to master and updated it to point to our 7.0 docs. I imported to LDN just now and it's showing.
> Portal configuration reference for 7.0

- code/sample-content-portlet-lr-workspace/modules/com.liferay.docs.samplecontent/build.gradle
We're using this for training, and the portal.kernel dependency needed a version update to build.
> updated versions in build.gradle

- build-site-common.xml
Hey Rich; we were running into this error because the `discover/reference` directory had no images in its `images` folder. Because of this, the folder was not being created for our `/temp` dir, where our check-images target checks for the directory. I made a minor addition so that the `/images` dir is always created. 
Let me know if you run into any additional issues. Thanks!
https://issues.liferay.com/browse/LRDOCS-2575
> Fix build bug caused by absent "images" dir

- build-site-common.xml
I removed the logic that only recognized files for `.jpg` and `.png` extensions. We're now able to reference `.gif` files or any other media files residing in the `images[-dxp]` folder.
https://issues.liferay.com/browse/LRDOCS-2590
> Support any image/video referenced from the images dir

- develop/tutorials/articles/124-device-api/00-using-the-device-recognition-api-intro.markdown
- discover/portal/articles/03-advanced-web-content-management/10-displaying-site-pages-to-mobile-devices.markdown
I spoke with Mike Han, and Liferay plans on completing a deal with another device database provider in the next few months. I've torn out the references to the Device Recognition Provider app, since we no longer provide it via Marketplace. I'll add the new device database provider docs, when it's available.
This should be added to this week's sprint. This same info applies to the 6.1.x pull I've sent. Thanks!
https://issues.liferay.com/browse/LRDOCS-2592
> Remove Device Recognition Provider content - 6.2.x

- discover/deployment/articles-dxp/02-liferay-connected-services/02-configuring-the-lcs-client.markdown
Fixing broken anchor links in LCS document on registering DXP servers.
> LRDOCS-2652 LCS link fixes

- discover/portal/articles/04-business-productivity/03-using-workflow/01-enabling-workflow.markdown
The paths to the workflow deinfitions was outdated, since they were moved into the kaleo-runtime-impl module a while ago. Also, it wasn't appropriate to mention that the next article is on Kaleo Designer, since this will article doesn't appear on LDN. Deleted that line.
> Updated path to workflow definitions

- discover/deployment/articles/01-installing-liferay/03-installing-liferay-manually.markdown
I was trying to link to a section of the installing liferay manually doc, and noticed that there were first level headings uses (# Heading Title) where second level headings were called for, and thus no anchor was generated. Changed them to second level headings(## Heading Title).
> Headings Fixes in Installing Liferay Manually

- develop/tutorials/articles/04-service-builder/08-using-model-hints.markdown
default-value only applies to UI, some developers think that it is valid for create a default value in the data base column definition
https://issues.liferay.com/browse/LRDOCS-2936
> LRDOCS-2936 6.1.x Tutorial improvement

- develop/tutorials/articles/125-opensocial-gadgets/01-sending-pubsub-messages-between-gadgets-and-portlets.markdown
As discussed on pull request [1630](https://github.com/sez11a/liferay-docs/pull/1630), updated opensocial gadget's xml links
> LRDOCS-2939 Fixed broken links

- discover/portal/articles/06-setting-up-liferay/04-scripting/03-leveraging-the-script-engine-in-workflow.markdown
Hey Rich;
I know the fixed link goes against our new restrictions on source code linking, but since this is not linkable from doc.liferay.com (XML file), it will have to be fully explained in the article. I can alert the original author of this doc (Russ?) about this, but I know we're all busy, so I don't know when this will get resolved.
I figured two wrongs don't make a right, and if we're incorrectly pointing to the source code, we should at least have that link be correct. Let me know if you think tearing out the entire link is better than keeping it in there, and I can make that change too.
Addresses PR liferay#199.
Thanks!
> Workflow Link

- develop/tutorials/articles/01-introduction-to-liferay-development/02-OSGi-and-modularity.markdown
- develop/tutorials/articles/100-tooling/03-blade-cli/02-creating-a-liferay-workspace-with-blade-cli.markdown
- develop/tutorials/articles/100-tooling/03-blade-cli/11-managing-module-projects-with-blade-cli.markdown
- develop/tutorials/articles/120-business-logic-and-data-access/02-service-builder-persistence/02-running-service-builder-and-understanding-the-generated-code.markdown
- develop/tutorials/articles/340-data-upgrades-and-verifiers/creating-an-upgrade-process-for-your-application.markdown
Hey Rich,
As I revisited this tutorial I discovered it's related article links were broken. When I did a global search, I found they were used in a few other tutorials as well.
Thanks
> Replace broken links discovered in the OSGi and Modularity tutorial

- discover/deployment/articles/03-maintaining-liferay/02-liferay-enterprise-search/03-solr.markdown
It's been renamed to simply "Liferay Solr 5 Search Engine".
> LRDOCS-2923 Fix app name

- develop/tutorials/articles-dxp/audience-targeting/02-creating-new-audience-targeting-rule-types.markdown
- develop/tutorials/articles-dxp/audience-targeting/04-tracking-user-actions-with-audience-targeting.markdown
Now that the Audience Targeting Javadoc is published, I've included the links for the highlighted classes in the rule and tracking action tutorials. This also lets us delete the huge list of methods/descriptions, now that they're visible in the public Javadoc.
https://issues.liferay.com/browse/LRDOCS-3006
> Add Audience Targeting Javadoc Links

- develop/tutorials/articles/110-portlets/01-mvc-portlet.markdown
- develop/tutorials/articles/110-portlets/02-mvc-actioncommmand.markdown
- develop/tutorials/articles/110-portlets/03-mvc-rendercommand.markdown
- develop/tutorials/articles/110-portlets/04-mvc-resourcecommand.markdown
- develop/tutorials/articles/110-portlets/05-mvc-portlet-creation.markdown
- develop/tutorials/articles/220-internationalization/04-modifying-module-language-keys.markdown
- develop/tutorials/articles/250-frontend-customizations/02-overriding-core-jsps.markdown
- develop/tutorials/articles/mobile/01-android-apps-with-liferay-screens/01-preparing-android-projects-for-liferay-screens.markdown
- develop/tutorials/articles/mobile/02-ios-apps-with-liferay-screens/01-preparing-ios-projects-for-liferay-screens.markdown
Wrong links, links without the root context (a leading / in the rel. path), and links to github.
> Fixing links

- devGuide/en/chapters/03-developing-portlet-applications.markdown
- devGuide/en/chapters/05-generating-your-service-layer.markdown
- devGuide/en/chapters/13-designing-with-alloyui.markdown
- develop/tutorial-template.markdown
- develop/tutorials/articles/107-service-builder/08-invoking-remote-services.markdown
Hey Rich,
This PR piggybacks off of liferay#223. This fixes all remaining links pointing to 6.2 projects in `liferay-docs`.
> Fix 6.2 doc links pointing to liferay-docs Github projects

- discover/deployment/articles/02-configuring-liferay/02-document-repository.markdown
I couldn't run ant check on another branch of mine because of a faulty image path. Fixed path and rant an check to ensure it's working.
> bad image path in doc repository deployment article

- build-site-common.xml
- develop/tutorials/articles/100-tooling/03-blade-cli/02-creating-a-liferay-workspace-with-blade-cli.markdown
Hey Rich;
This change forces the `dist` targets to generate header IDs for our trackable Markdown files.
I just wanted to be clear, there has never been a time when articles with no header IDs were deployed to LDN/Customer Portal. The `dist` targets always ran the `number-headers` task on the articles, it was just done in a temporary folder where the CE and DXP articles were combined. Since the task was executed outside our *liferay-docs* repo, the changes were never reflected in our trackable files.
With that said, the extra precaution of making sure the header IDs are permanently set is probably good.
Thanks!
> Dist number headers

- build-site-common.xml
- release-site.properties
/cc @jhinkey 
https://issues.liferay.com/browse/LRDOCS-3121 
This is in preparation for the new [docs.liferay.com](https://docs.liferay.com) URLs for app and platform Javadoc.
The tokens are more thoroughly explained in the ticket, but here's a summary:
**CE**
`@app-ref@` = https://docs.liferay.com/ce/apps
`@platform-ref@`= https://docs.liferay.com/ce/portal
**DXP**
`@app-ref@` = https://docs.liferay.com/dxp/apps
`@platform-ref@`= https://docs.liferay.com/dxp/digital-enterprise
> LRDOCS-3121 New tokens for Reference Doc URLs

- build-site-common.xml
- guidelines/liferay-documentation-tools.markdown
There are a few things I did in this PR:
- Updated all guidelines in the `liferay-documentation-tools.markdown` file for accuracy. Many topics in this article were outdated.
- Documented build targets in quick reference section
- Documented tokens
- Renamed a couple targets (`check-images` and `number-images`) to follow naming conventions for the Ant targets. They previously had the word *site* in them (e.g. `check-images-site`), which was a leftover from when we were first migrating over to LDN.
https://issues.liferay.com/browse/LRDOCS-3137
> LRDOCS-3137 Update Tooling Guidelines for liferay-docs

- develop/reference/articles/200-breaking-changes.markdown
Based on brianchandotcom/liferay-portal#45117
@gamerson This may require an update to the Code upgrade tool. The `liferay-ui:journal-article` taglib is available again, but only from the `journal-taglib` module. The `liferay-journal:journal-article` taglib is still available from core too. See [LPS-69321](https://issues.liferay.com/browse/LPS-69321) for further details.
> Updated Breaking Change

- develop/tutorials/articles/01-introduction-to-liferay-development/30-starting-module-development/00-starting-module-development-intro.markdown
- develop/tutorials/articles/100-tooling/03-blade-cli/01-installing-blade-cli.markdown
Hey Rich; this is an urgent documentation fix for the Blade CLI installation instructions. This adds a temporary URL for downloading the JAR that will be updated once we have a permanent *latest* URL. Please see ticket for further details.
Can you review/publish this ASAP? Without this fix, developers don't have access to the latest version of Blade, which has important bug fixes. Thanks!
https://issues.liferay.com/browse/LRDOCS-3131
/cc @gamerson
> LRDOCS-3266 Update Blade CLI installation to use temporary URL

- develop/tutorials/articles/122-ios-apps-with-liferay-screens/08-adding-screenlet-actions.markdown
- develop/tutorials/articles/122-ios-apps-with-liferay-screens/11-progress-presenters.markdown
- develop/tutorials/articles/122-ios-apps-with-liferay-screens/14-custom-cells-list-screenlets-ios.markdown
- develop/tutorials/articles/122-ios-apps-with-liferay-screens/15-sorting-list-screenlet.markdown
- develop/tutorials/articles/122-ios-apps-with-liferay-screens/16-complex-lists.markdown
Image links in several Screens tutorials for the recent port from master to 6.2.x were broken. Now they're fixed.
> Fixing image links in Screens tutorials.

- develop/reference/articles/04-breaking-changes/00-breaking-changes-intro.markdown
Hey Rich,
I've received some complaints about the Contribution Guidelines being published in in our 6.2 Breaking Changes article. I agree, so I've removed the contribution guidelines. Since the 7.0 Breaking Changes on LDN doesn't include these guidelines, it's best to keep all versions of this doc consistent. Thanks!
> Guidelines for Breaking Changes shouldn't be published on LDN

- discover/deployment/articles-dxp/01-installing-liferay/09-installing-liferay-on-websphere.markdown
Edit for new section on configuring WebSphere to use HTTP cookies when DXP is also configured to use HTTP. Originally submitted by @justinchoi001 in https://github.com/sez11a/liferay-docs/pull/2121
> LRDOCS-3312 WebSphere HTTP cookies

- discover/deployment/articles/06-liferay-enterprise-search/02-configuring-elasticsearch.markdown
https://issues.liferay.com/browse/LRDOCS-3314, added a note about how discovery works in ES, with links to approrpiate docs, and mentioned an important setting used to declare the IP address of hosts that will act as gossip routers.
> Added ES Clustering Setting

- discover/deployment/articles-dxp/07-liferay-connected-services/01-lcs-preconfiguration.markdown
Hi Rich,
I've just see that  https://customer.liferay.com/documentation/7.0/deploy/-/official_documentation/deployment/lcs-preconfiguration misses some agent option so I've readded it from https://customer.liferay.com/documentation/6.1/admin/-/official_documentation/portal/patching-liferay
I've also added another system property `-Dfile.encoding=UTF8` in the agent opts as a customer faced an issue that was solved by this.
Please let me know if you have any questions.
Best,
Zoli
> Add back missing agent opts + UTF8 encoding recommendation to the LCS documentation

- develop/tutorials/articles/460-customizable-web-applications/01-providing-portlets-to-manage-requests.markdown
- guidelines/01-creating-docs-for-liferay.markdown
I also removed an old note related to setting the Portlet Provider model class name to *any class*. This is not available anymore ([3dbaf62](https://github.com/liferay/liferay-portal/commit/3dbaf6239539d740a3d84da16e18928bf7a6761e)).
> Update GitHub Links

- develop/tutorials/articles/120-service-builder/02-service-builder-persistence/02-running-service-builder-and-understanding-the-generated-code.markdown
We never mentioned how to run Service Builder from Maven. The Dev Tools team renamed the command, which will be usable this week. I've added the new command to our SB tutorials, and it's referenced from our Maven SB tutorial.
Please hold on publishing this until Friday. Thanks!
https://issues.liferay.com/browse/LRDOCS-3497
> LRDOCS-3497 Add in new Service Builder Maven command

- develop/tutorials/articles/03-jsf/02-writing-a-data-driven-jsf-application/03-creating-managed-beans-to-use-services.markdown
- develop/tutorials/articles/03-jsf/03-setting-permissions/02-adding-permissions-resources-to-the-service-layer.markdown
- develop/tutorials/articles/03-jsf/03-setting-permissions/04-updating-the-ui-with-extended-permissions-scheme.markdown
- develop/tutorials/articles/03-jsf/04-creating-entity-actions/04-adding-permissions-to-your-action-buttons.markdown
- develop/tutorials/articles/03-jsf/05-adding-a-portlet-to-the-control-panel/03-defining-portlet-actions-and-permissions.markdown
- develop/tutorials/articles/106-jsf-portlets-with-liferay-faces/11-communicating-between-jsf-portlets-using-ipc.markdown
- develop/tutorials/articles/106-jsf-portlets-with-liferay-faces/14-leveraging-the-portal-users-locale-with-liferay-faces-portal.markdown
- develop/tutorials/articles/106-jsf-portlets-with-liferay-faces/97-migrating-from-liferay-faces-31-to-liferay-faces-32-42.markdown
- develop/tutorials/articles/106-jsf-portlets-with-liferay-faces/99-building-liferay-faces-from-source.markdown
- develop/tutorials/articles/118-liferay-faces-alloy-ui-components/00-liferay-faces-alloy-ui-components-intro.markdown
- discover/deployment/articles/01-installation-and-setup/16-installing-liferay-on-oracle-weblogic-12c.markdown
Hey Rich; due to the Liferay Faces repo being reorganized, links we pointed to were outdated. I've updated these links to point to the new repositories. I also updated the *Building from Source* article to incorporate all active repos.
@stiemannkj1 Sorry for the delay; I was on vacation last week. There are still a couple links in the learning path I need to update that references the sample [guestbook-jsf-portlet](https://github.com/codyhoag/liferay-docs/tree/6.2.x/develop/tutorials/code/02-jsf/learning-sdk/portlets/guestbook-jsf-portlet). This will take a bit more time, but I've added it to my TO-DO list.
https://issues.liferay.com/browse/LRDOCS-3588
> LRDOCS-3588 JSF updates due to repo reorganization | 6.2.x

- develop/tutorials/articles/01-introduction-to-liferay-development/50-finding-extension-points/00-finding-extension-points-intro.markdown
- develop/tutorials/articles/02-from-liferay-6-to-liferay-7/08-optimizing-existing-plugins-for-liferay-7/06-modularizing-plugins/06-modularizing-an-existing-portlet.markdown
- develop/tutorials/articles/100-tooling/02-liferay-ide/04-creating-modules-with-liferay-ide.markdown
- develop/tutorials/articles/100-tooling/03-blade-cli/04-creating-modules-with-blade-cli.markdown
- develop/tutorials/articles/110-portlets/01-liferay-mvc-portlet/01-creating-an-mvc-portlet.markdown
- develop/tutorials/articles/110-portlets/04-jsf/02-creating-a-jsf-project-manually.markdown
- develop/tutorials/articles/110-portlets/04-jsf/04-services-in-jsf.markdown
- develop/tutorials/articles/120-service-builder/03-business-logic-with-service-builder/05-customizing-liferay-services.markdown
- develop/tutorials/articles/140-assets/00-asset-framework-intro.markdown
- develop/tutorials/articles/210-application-security/04-authentication-pipelines/02-authentication-pipelines.markdown
- develop/tutorials/articles/250-forms/03-form-navigator-extensions.markdown
- develop/tutorials/articles/260-themes-and-layout-templates/07-embedding-portlets-in-themes-and-layout-templates.markdown
- develop/tutorials/articles/300-osgi-basics/02-using-the-wab-generator.markdown
- develop/tutorials/articles/340-data-upgrades-and-verifiers/01-creating-an-upgrade-process-for-your-application.markdown
Broken links associated with the following changes:
- *Business Logic and Data Access* &rarr; *Service Builder*
- *Application Configuration* &rarr; *Configuration*
- *Project Templates* moved to `develop/reference`
> Update Broken Links

- discover/portal/articles/16-using-the-control-panel/04-server-administration.markdown
- discover/portal/articles/17-advanced-portal-operation/05-patching-liferay.markdown
- discover/portal/articles/19-configuring-for-high-availability/02-performance-tuning.markdown
Since LCS is no longer supported in 6.1, this removes links and mentions to LCS in other articles.
> LRDOCS-3656 removing 6.1 LCS links and mentions

- develop/reference/articles/05-theme-gulp-tasks.markdown
@sez11a removed the remote server information since that task will not work without the Server Manager Web App (which has not been modularized for Liferay 7.0) I'm following up on this for an alternative.
Thx!
> LRDOCS-3742 removed server manager info and added kickstart gulp task.

- develop/tutorials/articles/02-from-liferay-6-to-liferay-7/09-customization-with-ext-plugins/09-customization-with-ext-plugins-intro.markdown
QA is having new problems with app servers when testing Ext plugins. We now want to only show Tomcat as the supported app server until things are resolved. Can you publish this change at your earliest convenience? Thanks!
> Ext Plugins Temporary change

- develop/tutorials/articles-dxp/02-from-liferay-6-to-liferay-7/09-customization-with-ext-plugins/09-customization-with-ext-plugins-intro.markdown
This adds a last minute decision by Support to include the Tomcat workaround for developers that have not upgraded (or do not plan to upgrade) to SP4. Many customers upgrade via fix pack instead of service pack, so they wanted to include the workaround for them.
> LRDOCS-3333 Include workaround for Ext plugins (DXP)

- develop/tutorials/articles/02-from-liferay-6-to-liferay-7/07-upgrading-plugins-to-liferay-7/01-adapting-to-liferay-7s-api.markdown
Now that IDE 3.1 GA1 is officially released, I've removed the note we had for the Code Upgrade tool being unsupported.
> Remove pre-IDE 3.1 note

- develop/tutorials/articles/110-portlets/15-javascript/00-using-javascript-in-your-portlets-intro.markdown
- develop/tutorials/articles/110-portlets/15-javascript/02-es2015/00-es2015-intro.markdown
- develop/tutorials/articles/110-portlets/15-javascript/02-es2015/01-preparing-your-js-files-for-es2015.markdown
- develop/tutorials/articles/110-portlets/15-javascript/02-es2015/02-using-es2015-modules-in-your-portlets.markdown
- develop/tutorials/articles/110-portlets/15-javascript/04-npm/00-npm-portlets-intro.markdown
@sez11a this adds proper intros for the JavaScript portlets section and reorganizes them. This also reorganizes the ES2015 portlet tutorials into a their own sub-section. Please delete the old files so they are not duplicated. Thanks!
> LRDOCS-4006 wrote intros and reorganized es2015 tutorials

- develop/tutorials/articles/02-from-liferay-6-to-liferay-7/07-upgrading-plugins-to-liferay-7/02-resolving-a-plugins-dependencies.markdown
Added documentation that explains how Portal provides several third-party JARs and therefore excludes them from WABs. 
https://issues.liferay.com/browse/LRDOCS-4014
> LRDOCS-4014 Understanding excluded JARs

- discover/portal/articles/05-document-management/03-alternative-file-repository-options.markdown
Here's the same improvement for 6.2.
cc/ @ngaskill
https://issues.liferay.com/browse/LRDOCS-4031
> LRDOCS-4031 Describe DBStore's blob size limit; mention alternative

- develop/tutorials/articles/120-service-builder/02-service-builder-persistence/03-understanding-service-context.markdown
- develop/tutorials/articles/130-web-services/01-service-builder-web-services/05-invoking-json-web-services.markdown
- discover/portal/articles-dxp/04-business-productivity/03-using-workflow/02-kaleo-designer/00-intro.markdown
- discover/portal/articles-dxp/04-business-productivity/03-using-workflow/02-kaleo-designer/04-kaleo-designer-task-nodes.markdown
- discover/portal/articles/07-setting-up-liferay/04-scripting/01-invoking-liferay-services-from-scripts.markdown
- discover/portal/articles/07-setting-up-liferay/04-scripting/02-running-scripts-from-script-console.markdown
https://issues.liferay.com/browse/LRDOCS-4051 some scripting information was wrong: package names needed to be fixed, non-groovy scripting examples removed (modules never released on MP). Some other minor fixes were made.
> LRDOCS-4051, fixed package names, removed non-groovy stuff

- discover/portal/articles/07-setting-up-liferay/01-system-settings/02-configuration-files.markdown
https://issues.liferay.com/browse/LRDOCS-4065 spaces can't be used between multiple values, and should be escaped inside values.
> LRDOCS-4065 add info on spaces to config articles doc

- discover/deployment/articles/08-liferay-enterprise-search/05-solr.markdown
https://issues.liferay.com/browse/LRDOCS-4064, edited the note on deactivating the ES adapter bundle.The App Manager now uses the blacklist, so the deactivation persists even after an LPKG is replaced.
> LRDOCS-4064, ES Adapter Deactivation Note

- develop/tutorials/articles/03-developing-a-web-application/11-workflow/01-supporting-workflow-status/01-setting-guestbook-status.markdown
- develop/tutorials/articles/03-developing-a-web-application/11-workflow/01-supporting-workflow-status/02-setting-entry-status.markdown
- develop/tutorials/articles/150-workflow/00-workflow-framework-intro.markdown
- develop/tutorials/code/com-liferay-docs-guestbook/modules/guestbook/guestbook-service/service.xml
- develop/tutorials/code/com-liferay-docs-guestbook/modules/guestbook/guestbook-service/src/main/java/com/liferay/docs/guestbook/service/base/EntryLocalServiceBaseImpl.java
- develop/tutorials/code/com-liferay-docs-guestbook/modules/guestbook/guestbook-service/src/main/java/com/liferay/docs/guestbook/service/base/EntryServiceBaseImpl.java
- develop/tutorials/code/com-liferay-docs-guestbook/modules/guestbook/guestbook-service/src/main/java/com/liferay/docs/guestbook/service/base/GuestbookLocalServiceBaseImpl.java
- develop/tutorials/code/com-liferay-docs-guestbook/modules/guestbook/guestbook-service/src/main/java/com/liferay/docs/guestbook/service/base/GuestbookServiceBaseImpl.java
- develop/tutorials/code/com-liferay-docs-guestbook/modules/guestbook/guestbook-service/src/main/java/com/liferay/docs/guestbook/service/impl/EntryLocalServiceImpl.java
- develop/tutorials/code/com-liferay-docs-guestbook/modules/guestbook/guestbook-service/src/main/java/com/liferay/docs/guestbook/service/impl/GuestbookLocalServiceImpl.java
- develop/tutorials/code/com-liferay-docs-guestbook/modules/guestbook/guestbook-service/src/main/resources/service.properties
https://issues.liferay.com/browse/LRDOCS-4056 added necessary call to deleteWorkflowInstanceLinks, in workflow framework tutorial and in the Learning Path Workflow section.
> LRDOCS-4056 deleteWorkflowInstanceLinks in LP and Tutorial

- develop/tutorials/articles/111-customizing/03-overriding-liferays-default-aui-yui-modules.markdown
@sez11a Atom editor likes to throw two ' ' in every time I add one. Looks like one slipped through in the header...
> LRDOCS-3617 SF

- discover/deployment/articles/03-configuring-liferay/03-liferay-clustering.markdown
DB read-writer split requires ...
-    add a `jdbc.*.jndi.name properties`: One for the read data source and one for the read-write data source
-    add `dynamic-data-source-spring.xml` to `spring.infrastructure.configs` property.
https://issues.liferay.com/browse/LRDOCS-4077
> LRDOCS-4077 Fix Read-Writer Database Configuration instructions

- discover/portal/articles-dxp/08-targeting-content-to-your-audience/01-managing-user-segments.markdown
https://issues.liferay.com/browse/LRDOCS-4116
The "Managing User Segments" article leaves out the clarifying point that only users that visit the Site once a User Segment has been created will be tracked.
Without this important detail documented, the only place within Liferay itself that points this out in some form appears to be the error message in a "Segment Users" report when there are no segment users. This error message makes it somewhat clear, but it's a bit hidden out of the way; users are probably not likely to check "Reports" first to find out why the user segment does not have some users (and besides if it has any data, the message will not appear).
We have a customer who is confused about this functionality, and it's hard to blame them as it's not well explained. Thus we want …
> Add clarifying note to User Segment documentation

- discover/portal/articles/07-setting-up-liferay/01-system-settings/02-configuration-files.markdown
https://issues.liferay.com/browse/LRDOCS-4114, bug in system settings that causes impaired functionalit when an improperly named .config file is deployed, for an entry that supports factory configuration.
> LRDOCS-4114

- develop/reference/articles/07-screenlets-in-liferay-screens-for-android/00-intro.markdown
- develop/reference/articles/07-screenlets-in-liferay-screens-for-android/10-image-gallery-screenlet-for-android.markdown
- develop/reference/articles/08-screenlets-in-liferay-screens-for-ios/00-intro.markdown
- develop/reference/articles/08-screenlets-in-liferay-screens-for-ios/10-image-gallery-screenlet-for-ios.markdown
- develop/tutorials/articles/160-import-export-and-staging/02-understanding-staged-models.markdown
- distribute/publish/articles/01-publishing-your-app/02-preparing-your-app.markdown
This fixes the remainder of the broken relative links. All relative links are now correct in the `7.0.x` branch for the first time. This will give us a clean slate to work from for our upcoming migration to 7.1.
> Fix Remaining Links

- devGuide/en/chapters/02-liferays-developer-tools.markdown
- develop/tutorials/articles/103-maven/02-managing-liferay-maven-artifacts.markdown
- develop/tutorials/articles/103-maven/07-creating-liferay-maven-plugins-from-command-line.markdown
Received in codyhoag#137.
This PR fixes a Maven repository link we're using in our 6.2.x docs, which no longer exists.
This also fixes an article that isn't maintained anymore (i.e., `devGuide/en/chapters/...`). Should we delete the unused folders in our `6.2.x` branch so we prevent people who don't regularly work in `liferay-docs` from updating/referencing them?
> Fix links for Liferay Nexus repository

- discover/deployment/articles-dxp/04-maintaining-liferay/01-patching-liferay/02-patching-liferay.markdown
- discover/deployment/articles-dxp/09-liferay-connected-services/01-lcs-preconfiguration.markdown
- discover/deployment/articles/08-liferay-enterprise-search/05-solr.markdown
https://issues.liferay.com/browse/LRDOCS-4819, edited information on deleting osgi/state to clarify the repercussions and highlight that it shouldn't be necessary. CC @lipusz, @ngaskill
> LRDOCS-4819, don't reflexiveley delete osgi/state

- discover/portal/articles/12-using-workflow/02-creating-new-workflow-definitions.markdown
The erroneous inclusion of an execution-type element inside a task timer has apparently caused confusion and distress in a customer and support engineer. The sooner we remove it, the better.  cc @natocesarrego
> Remove execution-type element from task-timer snippet

- develop/reference/articles/01-development-reference.markdown
Hi Rich,
This fixes the links to the taglib docs.
cc/ @codyhoag - In case you had ported this doc to 7.1.
> 7.0 Develop > Reference - Fix taglib doc links and use tokens for all URLs

- discover/deployment/articles-dxp/03-configuring-liferay/03-liferay-clustering.markdown
discover > deployment > 7.0
https://issues.liferay.com/browse/LRDOCS-4830
Complete updating the DXP clustering docs and remove duplicate load testing information.
> LRDOCS-4830 7.0 Fix the DXP clustering docs

- develop/reference/articles/13-sample-projects/02-extensions/02-document-action.markdown
We have an old Liferaypedia entry for [Display Context](https://dev.liferay.com/participate/liferaypedia/-/wiki/Main/Display+Context)s. The Support team requested we make this entry available to DXP docs customers too (link was not working).
My first intention was to extract this info into a tutorial. We confirmed with Engineering, however, that we do not want to promote Display Context usage in our tutorials. So instead of extracting the Display Context info out of the Liferaypedia entry into a tutorial, we have been instructed to let the Liferaypedia entry die. 💀 
Since the Blade Sample still uses them, I've added some brief info on Display Contexts so readers know how they're being used. The links to the Liferaypedia entry have been removed.
> LRDOCS-5083 Resolve Display Context links issue

- develop/tutorials/articles-dxp/02-from-liferay-6-to-liferay-7/09-customization-with-ext-plugins/09-customization-with-ext-plugins-intro.markdown
- develop/tutorials/articles/02-from-liferay-6-to-liferay-7/00-from-liferay-6-to-liferay-7-intro.markdown
- develop/tutorials/articles/02-from-liferay-6-to-liferay-7/07-upgrading-plugins-to-liferay-7/05-upgrading-hook-plugins/09-converting-struts-action-wrappers-to-mvc-commands.markdown
- develop/tutorials/articles/02-from-liferay-6-to-liferay-7/07-upgrading-plugins-to-liferay-7/06-upgrading-themes/01-upgrading-liferay-6-themes.markdown
- develop/tutorials/articles/02-from-liferay-6-to-liferay-7/08-optimizing-existing-plugins-for-liferay-7/06-modularizing-plugins/00-modularizing-plugins-intro.markdown
- develop/tutorials/articles/02-from-liferay-6-to-liferay-7/09-customization-with-ext-plugins/09-customization-with-ext-plugins-intro.markdown
- develop/tutorials/articles/05-developing-an-ios-app/03-creating-entry-list-screenlet/03-creating-the-connector.markdown
- develop/tutorials/articles/05-developing-an-ios-app/03-creating-entry-list-screenlet/04-creating-the-interactor.markdown
- develop/tutorials/articles/110-portlets/02-liferay-soy-portlet/01-creating-a-soy-portlet.markdown
- develop/tutorials/articles/110-portlets/15-javascript/04-npm/03-configuring-liferay-npm-bundler.markdown
- develop/tutorials/articles/150-workflow/00-workflow-framework-intro.markdown
- develop/tutorials/articles/180-configuration/01-making-apps-configurable.markdown
- develop/tutorials/articles/200-search/02-customizing-liferay-search.markdown
- develop/tutorials/articles/210-application-security/06-service-access-policies.markdown
- develop/tutorials/articles/310-troubleshooting/00-troubleshooting-intro.markdown
- develop/tutorials/articles/310-troubleshooting/01-resolving-bundle-requirements.markdown
- develop/tutorials/articles/310-troubleshooting/06-adjusting-module-logging.markdown
- discover/deployment/articles-dxp/02-installing-liferay/07-installing-liferay-on-tcserver.markdown
- discover/deployment/articles-dxp/02-installing-liferay/08-installing-liferay-on-weblogic.markdown
- discover/deployment/articles-dxp/08-liferay-enterprise-search/06-backing-up-search/00-intro.markdown
- discover/deployment/articles/08-liferay-enterprise-search/06-backing-up-search/00-intro.markdown
- discover/portal/articles/100-web-experience-management/01-starting-site-development/07-creating-teams-for-advanced-site-membership-management.markdown
- discover/portal/articles/100-web-experience-management/02-creating-web-content/02-designing-uniform-content.markdown
- discover/portal/articles/100-web-experience-management/03-staging-content-for-publication/05-scheduling-web-content-publication.markdown
- discover/portal/articles/110-collaboration/01-managing-documents-and-media/03-liferay-repository-types.markdown
This removes that pesky special char apostrophe typically copied over from a Google doc.
> Remove all special char apostrophes in docs | 7.0.x

- develop/tutorials/articles/340-osgi-basics-for-liferay-development/10-semantic-versioning.markdown
The related ticket was already closed for the 7.0 article creation. This PR copies over the Semantic Versioning tutorial for 7.1 (no changes).
> LRDOCS-2527 Add SemVer tutorial for 7.1

- discover/deployment/articles/08-liferay-enterprise-search/05-solr.markdown
removed white spaces so the .config property value in the Solr article is copyable. cc @lipusz
> Remove whitepsaces from code block

- develop/tutorials/articles/360-osgi-basics-for-liferay-development/03-importing-packages.markdown
I updated the package import docs to mention 7.1 currently exports Java Portlet 2.0 API and that until 3.0 is supported, use 2.0.
https://issues.liferay.com/browse/LRDOCS-5567
> LRDOCS-5567 use Java Portlet 2.0 API for now

- develop/tutorials/articles/380-troubleshooting/00-troubleshooting-intro.markdown
- develop/tutorials/articles/380-troubleshooting/12-sort-order-changed-with-different-database.markdown
The Troubleshooting intro is now fleshed out with the dropdown text and links as we did in 7.0.
The DB sort order tutorial was one we added more recently for 7.0 that I'm porting to 7,1.
Thanks!
https://issues.liferay.com/browse/LRDOCS-4678  
https://issues.liferay.com/browse/LRDOCS-5626
> LRDOCS-4678  LRDOCS-5626 port the Troubleshooting intro and DB sort order tutorial

- develop/tutorials/articles/02-from-liferay-6-to-liferay-7/02-benefits-of-liferay-7-for-liferay-6-developers.markdown
- develop/tutorials/articles/110-portlets/07-using-javascript-in-your-portlets/03-using-npm-in-your-portlets/08-npmresolver-api/01-obtaining-osgi-bundle-npm-package-descriptors.markdown
- develop/tutorials/articles/260-import-export-and-staging/03-understanding-staged-models.markdown
One broken link came from a PR that was merged before the check-links target was integrated into the `check` task. The other two are easy token errors.
> Broken links

- develop/tutorials/articles/02-from-liferay-6-to-liferay-7/07-upgrading-plugins-to-liferay-7/06-upgrading-themes/00-upgrading-themes-intro.markdown
- develop/tutorials/articles/03-from-liferay-70-to-71/06-upgrading-themes/00-upgrading-themes-intro.markdown
@sez11a this moves the 7.0 theme upgrade link to the new 7.0-7.1 section and renames the original 
theme upgrade tutorial to upgrading-6.2-themes.
cc @jbalsas
> LRDOCS-5770 Move 7.0 theme upgrade docs to new section

- discover/portal/articles/100-web-experience-management/07-staging-content-for-publication/05-publishing-single-assets-from-staged-site/00-publishing-single-assets-from-staged-site-intro.markdown
Very weird; I had fixed this a couple months ago 79a0aa2bf1e66dc875c648aecc0d90fe3df50ad7. Not sure how this crept back in; maybe a corrupt merge elsewhere? Anyway, here's the fix.
> Fix image path

- develop/reference/articles/10-sample-projects/01-apps/03-npm-samples/00-intro.markdown
I ended up going with your *very generic* solution. A quick Google search presented many different blogs/forums/etc. for ways to tinker with a slew of different OS types and versions. It's probably better to keep it simple and let devs set their limits on their own.
https://issues.liferay.com/browse/LRDOCS-5773
> LRDOCS-5773 Open file limit (npm)

- develop/reference/articles/13-sample-projects/01-apps/01-greedy-policy-option-portlet.markdown
- develop/reference/articles/13-sample-projects/01-apps/02-kotlin-portlet.markdown
- develop/reference/articles/13-sample-projects/01-apps/03-npm-samples/01-angular-npm-portlet.markdown
- develop/reference/articles/13-sample-projects/01-apps/03-npm-samples/02-billboardjs-npm-portlet.markdown
- develop/reference/articles/13-sample-projects/01-apps/03-npm-samples/03-isomorphic-npm-portlet.markdown
- develop/reference/articles/13-sample-projects/01-apps/03-npm-samples/04-jquery-npm-portlet.markdown
- develop/reference/articles/13-sample-projects/01-apps/03-npm-samples/05-metaljs-npm-portlet.markdown
- develop/reference/articles/13-sample-projects/01-apps/03-npm-samples/06-react-npm-portlet.markdown
- develop/reference/articles/13-sample-projects/01-apps/03-npm-samples/07-simple-npm-portlet.markdown
- develop/reference/articles/13-sample-projects/01-apps/03-npm-samples/08-vuejs-npm-portlet.markdown
- develop/reference/articles/13-sample-projects/01-apps/04-service-builder-samples/04-service-builder-adq.markdown
- develop/reference/articles/13-sample-projects/01-apps/05-service-builder-samples/02-service-builder-jdbc.markdown
- develop/reference/articles/13-sample-projects/01-apps/05-service-builder-samples/03-service-builder-jndi.markdown
- develop/reference/articles/13-sample-projects/01-apps/06-shared-language-keys.markdown
- develop/reference/articles/13-sample-projects/01-apps/07-simulation-panel-app.markdown
- develop/reference/articles/13-sample-projects/01-apps/08-spring-mvc-portlet.markdown
- develop/reference/articles/13-sample-projects/02-extensions/01-control-menu-entry.markdown
- develop/reference/articles/13-sample-projects/02-extensions/02-document-action.markdown
- develop/reference/articles/13-sample-projects/02-extensions/03-gogo-shell-command.markdown
- develop/reference/articles/13-sample-projects/02-extensions/04-indexer-post-processor.markdown
- develop/reference/articles/13-sample-projects/02-extensions/05-model-listener.markdown
- develop/reference/articles/13-sample-projects/02-extensions/06-screen-name-validator.markdown
- develop/reference/articles/13-sample-projects/02-extensions/07-servlet.markdown
- develop/reference/articles/13-sample-projects/03-overrides/01-core-jsp-override.markdown
- develop/reference/articles/13-sample-projects/03-overrides/02-module-jsp-override.markdown
- develop/reference/articles/13-sample-projects/03-overrides/03-resource-bundle-override.markdown
- develop/reference/articles/13-sample-projects/04-themes/01-simple-theme.markdown
- develop/reference/articles/13-sample-projects/04-themes/02-template-context-contributor.markdown
- develop/reference/articles/13-sample-projects/04-themes/03-theme-contributor.markdown
This came as a suggestion from a community member. The repetitive intro text in our samples is causing unhelpful preview text in LDN's article tiles (e.g., see [here](https://dev.liferay.com/develop/reference/-/knowledge_base/7-0/npm-samples)).
https://issues.liferay.com/browse/LRDOCS-5806
> LRDOCS-5806 Remove repetitive intro text in samples | 7.0.x

- discover/portal/articles-dxp/110-collaboration/01-managing-documents-and-media/05-administering-liferay-sync.markdown
Bad line spacing caused a duplicate header ID, which was being rendered on customer.liferay.com. Note there are no changes to the content.
> LRDOCS-5502 fixing line spacing

- distribute/publish/articles/01-publishing-your-app/01-planning-your-apps-distribution/04-app-versioning-and-target-liferay-editions-and-versions.markdown
- distribute/publish/articles/01-publishing-your-app/02-preparing-your-app/00-preparing-your-app-intro.markdown
- distribute/publish/articles/01-publishing-your-app/02-preparing-your-app/02-packaging-your-marketplace-app.markdown
- distribute/publish/articles/01-publishing-your-app/03-submitting-your-app/01-your-apps-initial-details.markdown
PACL is only applicable for apps that have WAR-style plugins and are for 6.1 GA3 or 6.2 releases.
https://issues.liferay.com/browse/LRDOCS-4709
> LRDOCS-4709 de-emphasize PACL and clarify when to use it.

- discover/portal/articles/120-search/01-whats-new-in-search.markdown
make ech item a second level heading with header ids, and uncomment the solr 7 article link. cc @lipusz
> Tibor's enhancements to What's New in Search, 7.1.x

- develop/tutorials/articles/130-service-builder/02-service-builder-persistence/01-defining-an-object-relational-map-with-service-builder/04-defining-the-columns-attributes-for-each-service-entity.markdown
In my snippet, I used the wrong characters for sidebars--- used `+###` instead of `+$$$`, and same for closing sidebar chars.
https://issues.liferay.com/browse/LRDOCS-6294
> LRDOCS-6294 7.1: fix sidebar syntax

- develop/tutorials/articles/120-customizing/04-overriding-language-keys/02-overriding-a-modules-language-keys.markdown
- develop/tutorials/articles/300-internationalization/01-localizing-your-application.markdown
Resource bundle loaders are no longer needed for overriding language keys; OSGi manifest headers let you do everything. The articles on overriding language keys and using language keys are updated.
https://issues.liferay.com/browse/LRDOCS-6316
> LRDOCS-6316 7.1: Overriding and aggregating resource bundles using OSGi manifest headers

- develop/tutorials/articles/111-customizing/05-overriding-language-keys.markdown
- develop/tutorials/articles/220-internationalization/01-localizing-your-application.markdown
Resource bundle loaders are no longer needed for overriding language keys; OSGi manifest headers let you do everything. The articles on overriding language keys and using language keys are updated.
https://issues.liferay.com/browse/LRDOCS-6316
> LRDOCS-6316 7.0: Overriding and aggregating resource bundles using OSGi headers

- develop/tutorials/articles/230-wysiwyg-editors/02-modifying-an-editor-configuration.markdown
@sez11a  This include LRDOCS-6425 and LRDOCS-6487
cc@jbalsas I've spoken with the km-team member for blogs. For now, we will push the note through. We can plan to document Blogs and Blogs Admin configuration/framework separately after the release.
> LRDOCS-6487 note how to create global editor configuration

- develop/reference/articles/03-portlet-descriptors.markdown
- develop/tutorials/articles/110-portlets/01-liferay-mvc-portlet/00-liferay-mvc-portlet-intro.markdown
- develop/tutorials/articles/110-portlets/03-spring-mvc/00-spring-mvc-intro.markdown
https://issues.liferay.com/browse/LRDOCS-6498
> LRDOCS-6498 7.0: Explain how Liferay uses portlet name to create portletId

- develop/tutorials/articles/320-wysiwyg-editors/02-modifying-an-editors-configuration.markdown
@sez11a  This include LRDOCS-6425 and LRDOCS-6487
cc@jbalsas I've spoken with the km-team member for blogs. For now, we will push the note through. We can plan to document Blogs and Blogs Admin configuration/framework separately after the release.
> LRDOCS-6487 add note for global editor configuration

- guidelines/02-standards-and-customizations.markdown
Hey Rich; I've added our supported syntax highlighting aliases to our guidelines based on what you shared in Slack:
https://prismjs.com/download.html#themes=prism&languages=markup+css+clike+javascript+bash+docker+groovy+java+typescript+properties+sass+yaml&plugins=line-numbers+toolbar+copy-to-clipboard
Please update if you see any issues. Thanks!
> Supported syntax highlighting

- develop/reference/articles/07-gradle/gulp-gradle-plugin.markdown
- develop/reference/articles/07-gradle/javadoc-formatter-gradle-plugin.markdown
- develop/reference/articles/07-gradle/js-module-config-generator-gradle-plugin.markdown
- develop/reference/articles/07-gradle/js-transpiler-gradle-plugin.markdown
- develop/reference/articles/07-gradle/jsdoc-gradle-plugin.markdown
- develop/reference/articles/07-gradle/node-gradle-plugin.markdown
- develop/reference/articles/07-gradle/rest-builder-gradle-plugin.markdown
- develop/reference/articles/07-gradle/service-builder-gradle-plugin.markdown
- develop/reference/articles/07-gradle/source-formatter-gradle-plugin.markdown
- develop/reference/articles/07-gradle/target-platform-gradle-plugin.markdown
- develop/reference/articles/08-maven/javadoc-formatter-plugin.markdown
- develop/reference/articles/08-maven/rest-builder-plugin.markdown
- develop/reference/articles/08-maven/service-builder-plugin.markdown
- develop/reference/articles/08-maven/source-formatter-plugin.markdown
This includes the backported REST Builder plugin docs (sent for master in sez11a#4112). Peter informed me those plugins were applicable for 7.1 and 7.2.
> Gradle/Maven Plugin version updates | 7.1.x

- deployment/articles/04-securing-liferay/07-openid-connect-authentication.markdown
- developer/customization/articles/02-fundamentals/01-fundamentals-intro.markdown
- developer/customization/articles/02-fundamentals/02-configuring-dependencies/01-configuring-dependencies-intro.markdown
- developer/customization/articles/02-fundamentals/02-configuring-dependencies/03-specifying-dependencies.markdown
This is the second part of the former [Configuring Dependencies](https://dev.liferay.com/develop/tutorials/-/knowledge_base/7-1/configuring-dependencies#configuring-dependencies) article. I added a step on specifying compile-only if the dependency's packages are exported by Portal already.
https://issues.liferay.com/browse/LRDOCS-6649
>  LRDOCS-6649 7.2: Specifying dependencies

- develop/tutorials/articles/150-web-services/05-service-builder-web-services/05-invoking-json-web-services.markdown
because it's been come up multiple time in questions and escalations (a recent [example](https://issues.liferay.com/browse/PTR-893)).
Thanks,
Tibor
> PTR-893 Add examples for "inner parameters" to the Invoking JSON WebServices article

- user/articles/110-collaboration/02-managing-documents-and-media/02-publishing-files/02-adding-files.markdown
- user/articles/110-collaboration/02-managing-documents-and-media/02-publishing-files/03-creating-folders.markdown
- user/articles/110-collaboration/02-managing-documents-and-media/02-publishing-files/04-dm-management-bar.markdown
- user/articles/110-collaboration/02-managing-documents-and-media/02-publishing-files/05-file-previews.markdown
- user/articles/110-collaboration/02-managing-documents-and-media/02-publishing-files/07-publishing-files.markdown
- user/articles/110-collaboration/02-managing-documents-and-media/02-publishing-files/08-checkout-edit-files.markdown
- user/articles/110-collaboration/02-managing-documents-and-media/02-publishing-files/10-configuring-sharing.markdown
- user/articles/110-collaboration/02-managing-documents-and-media/04-document-types.markdown
- user/articles/110-collaboration/03-sync/02-administering-sync/02-prerequisites.markdown
- user/articles/110-collaboration/03-sync/03-sync-desktop/03-using-sync-desktop.markdown
- user/articles/110-collaboration/03-sync/04-sync-mobile/01-intro.markdown
- user/articles/110-collaboration/04-adaptive-media/02-installing-adaptive-media.markdown
- user/articles/110-collaboration/04-adaptive-media/03-adding-image-resolutions.markdown
- user/articles/110-collaboration/04-adaptive-media/05-creating-content-adapted-images.markdown
- user/articles/110-collaboration/04-adaptive-media/06-migrating-dm-thumbnails.markdown
- user/articles/110-collaboration/05-collaborating/02-blogs/02-adding-blog-entries.markdown
- user/articles/110-collaboration/05-collaborating/02-blogs/03-blog-entry-editor.markdown
- user/articles/110-collaboration/05-collaborating/02-blogs/04-managing-blog-entries.markdown
- user/articles/110-collaboration/05-collaborating/02-blogs/06-displaying-blogs.markdown
- user/articles/110-collaboration/05-collaborating/03-message-boards/03-configuring-message-boards.markdown
- user/articles/110-collaboration/05-collaborating/03-message-boards/04-message-board-permissions.markdown
- user/articles/110-collaboration/05-collaborating/03-message-boards/05-message-board-categories.markdown
- user/articles/110-collaboration/05-collaborating/03-message-boards/07-using-message-boards.markdown
- user/articles/110-collaboration/05-collaborating/03-message-boards/08-managing-message-boards.markdown
- user/articles/110-collaboration/05-collaborating/05-wiki/01-intro.markdown
- user/articles/110-collaboration/05-collaborating/05-wiki/02-getting-started-wiki.markdown
- user/articles/110-collaboration/05-collaborating/05-wiki/03-add-edit-wiki.markdown
- user/articles/110-collaboration/05-collaborating/05-wiki/04-using-wiki-site-pages.markdown
- user/articles/110-collaboration/05-collaborating/06-alerts-announcements.markdown
- user/articles/110-collaboration/05-collaborating/11-invite-members.markdown
Ran ant convert-links on existing (already merged) collab user docs. No content was changed.
> Converting collab user links to new format

- developer/appdev/articles/01-web-front-ends/01-web-front-ends-intro.markdown
- developer/appdev/articles/01-web-front-ends/02-angular-widget/01-developing-an-angular-application-intro.markdown
- developer/appdev/articles/01-web-front-ends/03-react-widget/01-developing-react-application-intro.markdown
- developer/appdev/articles/01-web-front-ends/04-vue-widget/01-developing-a-vue-application-intro.markdown
This applies the rename for the Liferay Bundle Generator to the Liferay JS Generator and removes the process serially steps since this setting was replaced with a new setting that avoids these EMFILE errors on Windows
cc @jhinkey
> LRDOCS-6299 rename generator and remove process serially info

- user/articles/120-search/09-search-configuration.markdown
Just a quick addition for a setting I noticed was missing from our omni-configuration article.
> Added a definition to search config article

- deployment/articles/03-installing-a-search-engine/02-elasticsearch/08-upgrading-to-elasticsearch_65.markdown
https://issues.liferay.com/browse/LRDOCS-5911, cover the scenario in which customers upgrade to 7.2 before upgrading their elasticsearch servers to 6.5. cc @lipusz
> 7.2 New | Upgrade to Elasticsearch 6.5 | LRDOCS-5911

- discover/deployment/articles/03-configuring-liferay/02-document-repository.markdown
- discover/deployment/articles/06-upgrading-liferay/02-preparing-for-upgrade.markdown
https://issues.liferay.com/browse/LRDOCS-6905
Deprecate it and arrange CMIS Store and JCR Store last in the articles. Format to highlight syntax.
> LRDOCS-6905 7.0: deprecate CMIS Store as of 7.0 FP14 (SP3)

- developer/frameworks/articles/configuration/02-creating-a-configuration-interface.markdown
https://issues.liferay.com/browse/LRDOCS-7102, Basically, Ray found a typo, and I noticed that the information around it seemed incorrect. We've moved it closer to the truth, though there may be another edit when Greg gets back to us about whether the Bundle Support plugin really applies the metatype instruction to the bundle metadata. cc @pei-jung, @codyhoag
> 7.2 Developer | USM, Correcting some Metatype Information | LRDOCS-7102

- developer/reference/articles/02-project-templates/service-builder-template.markdown
https://issues.liferay.com/browse/LRDOCS-7081
> LRDOCS-7081 Setting DI for Service Builder project template

- developer/frameworks/articles/configuration/02-creating-a-configuration-interface.markdown
https://issues.liferay.com/browse/LRDOCS-7298, the Meta.OCD annotation's ID property must be the FQCN of the confiugration class. cc @drewbrokke
> USM 7.2 Developer, Configuration | LRDOCS-7298

- build-common.xml
The *Edit on Github* buttons on our site are now broken because I didn't insert the language dir in the metadata path. If you merge this and republish, the buttons will be fixed. Thanks!
> Fix Github URL in metadata

- en/user/articles/05-setting-up/01-system-settings/03-server-administration/02-server-admin-external-services.markdown
https://issues.liferay.com/browse/LRDOCS-7484 Add note that OpenOffice is now configured via ConfigurationAdmin, not portal properties
> LRDOCS-7484 Add note that OpenOffice is now configured via ConfigurationAdmin, not portal properties

- en/deployment/articles/04-securing-liferay/08-openam-authentication.markdown
- en/developer/frameworks/articles/service-context/01-understanding-service-context-intro.markdown
- en/developer/frameworks/articles/web-services/02-headless-apis/02-discover-api.markdown
- en/developer/frameworks/articles/web-services/02-headless-apis/03-invoke-service.markdown
- en/developer/frameworks/articles/web-services/02-headless-apis/04-authenticated-requests.markdown
- en/developer/frameworks/articles/web-services/02-headless-apis/05-collections/02-getting-collections.markdown
- en/developer/frameworks/articles/web-services/02-headless-apis/05-collections/03-pagination.markdown
- en/developer/frameworks/articles/web-services/02-headless-apis/05-collections/04-collection-to-elements.markdown
- en/developer/frameworks/articles/web-services/02-headless-apis/06-api-formats.markdown
- en/developer/frameworks/articles/web-services/02-headless-apis/08-filter-and-sort.markdown
- en/developer/frameworks/articles/web-services/02-headless-apis/09-restrict-properties.markdown
- en/developer/frameworks/articles/web-services/02-headless-apis/10-multipart.markdown
- en/developer/reference/articles/02-front-end/05-liferay-js-apis/05-invoking-liferay-services.markdown
- en/user/articles/05-setting-up/02-instance-settings/02-configuring-virtual-instance-settings/02-email-instance-settings.markdown
- en/user/articles/05-setting-up/03-script-console/04-script-examples.markdown
- en/user/articles/110-collaboration/05-collaborating/03-message-boards/03-configuring-message-boards.markdown
- en/user/articles/130-forms/16-form-notifications.markdown
https://issues.liferay.com/browse/LRDOCS-7401
These updates are from @jorgediaz-lr, who's described the changes...
> After [LPS-84320](https://issues.liferay.com/browse/LPS-84320) and [LRDOCS-7395](https://issues.liferay.com/browse/LRDOCS-7395) changes, we should remove all references to "test@liferay.com" email.
> 
> I have done following changes:
> 
> - **First commit https://github.com/jhinkey/liferay-docs/commit/0b781a5ad56b0ce35667d6b4a0f24c68c1e0bb8d -** I have updated groovy script to avoid hardcoding "test@liferay.com"
> - **Second https://github.com/jhinkey/liferay-docs/commit/2212362cdaf4b1be34bceca736478346cc9a39f9 and third commit https://github.com/jhinkey/liferay-docs/commit/52542fdc4a8b1bf88af5dc64370e793c715ecf98** I have replaced "test@liferay.com" with …
> LRDOCS-7401 Remove references to "test@liferay.com" email

- en/deployment/articles/02-configuring-liferay/04-liferay-portal-clustering/05-enabling-cluster-link.markdown
https://issues.liferay.com/browse/LRDOCS-7500 Improve JGroups Unicast TCPPing instructions.
https://issues.liferay.com/browse/LRDOCS-7518 Explain localhost value and real addresses at the start. Note using initial hosts in a JVM arg.
> LRDOCS-7500 LRDOCS-7518 7.2: Fix and improve Cluster Link instructions

- en/deployment/articles/05-upgrading-to-liferay-7-2/98-deprecated-apps-in-7-2-what-to-do.markdown
The Liferay Connector to OAuth 1.0a should be in Maintenance mode and not deprecated. Added it to the maintenance mode page in https://github.com/sez11a/liferay-docs/pull/4752.
> LRDOCS-7541 Move OAuth 1.0a to Maintenance

- en/deployment/articles/01-deploying-liferay/03-preparing-for-install.markdown
https://issues.liferay.com/browse/LRDOCS-7655
DXP doesn't require the database itself does not need to be set to GMT timezone.
> LRDOCS-7655 DXP doesn't require the database to be set to GMT

- en/deployment/articles/01-deploying-liferay/06-installing-liferay-portal-on-wildfly.markdown
default-bindings#datasource attrib uses the same jndi-name …value as the datasource#jndi-name attrib.
cc/ @justinchoi001
> LPS-75089 set Wildfly's<default-bindings datasource=.../> to same JDNI name as <datasource/> element

- en/developer/frameworks/articles/search/02-aggregations/02-base-search-aggregations-code.markdown
- en/developer/frameworks/articles/search/02-aggregations/03-statistical-aggregations.markdown
- en/developer/frameworks/articles/search/03-queries-and-filters/02-building-search-queries-and-filters.markdown
https://issues.liferay.com/browse/LRDOCS-7943, cc @lipusz. Changed 3 incorrect instances that were calling a now non-existent method to instantiate the SearchRequestBuilder.
> Search 7.2 Developer | LRDOCS-7943 | SearchRequestBuilder must be instantiated with its factory's `builder` method

- en/discover/deployment/articles-dxp/01-deploying-liferay/06-installing-liferay-portal-on-jboss-eap.markdown
- en/discover/deployment/articles-dxp/01-deploying-liferay/07-installing-liferay-on-tc-server.markdown
- en/discover/deployment/articles-dxp/01-deploying-liferay/08-installing-liferay-on-weblogic.markdown
- en/discover/deployment/articles-dxp/01-deploying-liferay/09-installing-liferay-on-websphere.markdown
- en/discover/deployment/articles/01-deploying-liferay/04-installing-liferay-portal-on-tomcat.markdown
- en/discover/deployment/articles/01-deploying-liferay/05-installing-liferay-portal-on-wildfly.markdown
https://issues.liferay.com/browse/LRDOCS-7603
1. Removed `war` folder from `osgi` subfolder list. In fact, I just removed the explicit subfolder listing. 
2. Simplify or remove dependency installation section checkpoints.
3. Replaced installing mysql.jar with generic instructions.
Thanks.
> 7.1 .x - LRDOCS-7603 Remove war from the osgi folder list

- en/discover/deployment/articles/03-configuring-liferay/03-liferay-portal-clustering/04-enabling-cluster-link.markdown
https://issues.liferay.com/browse/LRDOCS-7914
- Used the [improved instructions from Liferay Learn](https://learn.liferay.com/dxp/7.x/en/installation-and-upgrades/setting-up-liferay-dxp/clustering-for-high-availability/configuring-cluster-link.html#id1) to update the the bind address reference to include using host name.
- Updated the Unicast instructions with option to use hostname.
> LRDOCS-7914 7.1.x JGroups bind address can be IP address or host name

- discover/deployment/articles-dxp/03-configuring-liferay/03-liferay-clustering.markdown
https://issues.liferay.com/browse/LRDOCS-7914
- Used the [improved instructions from Liferay Learn](https://learn.liferay.com/dxp/7.x/en/installation-and-upgrades/setting-up-liferay-dxp/clustering-for-high-availability/configuring-cluster-link.html#id1) to update the the bind address reference to include using host name.
- Updated the Unicast instructions with option to use hostname.
> LRDOCS-7914 7.0.x JGroups bind address can be IP address or host name

- bin/migrate.py
- en/distribute/publish/articles/01-publishing-your-app/04-understanding-the-app-review-process/00-understanding-the-app-review-process-intro.markdown
Here's the much improved script!
Example:
`$ python ~/git/liferay-docs/bin/migrate.py 01-importing-packages-intro.markdown`
Features:
- "Unwraps" (removes hard returns) from paragraphs. Yaye!
- Copies images to `[article destination]/images/` and updates the article links to that folder. (If you don't specify a destination, the article .md and and images/ folder are created locally--you can copy them manually to liferay-learn)
- Removes legacy metadata: `header-id` and `[TOC ...]`
- Converts legacy sidebars ` | **Note:** ...` to 
```
```note::
Text here ... `Caption text <url>`_ and ``inline code``
```
\`\`\`
- Converts ordered list items from `2.    Text...` to `1. Text...` (notice single space after number).
- Converts unordered list items from `-     Text...` to `* Text...`
> Script: migrate.py

- discover/deployment/articles/05-configuring-for-high-availability/01-liferay-clustering.markdown
https://issues.liferay.com/browse/LRDOCS-8186
The ehcache documentation link was missing the prefix `http://`
> 6.2.x: Fix ehcache doc link

- en/discover/deployment/articles-dxp/01-deploying-liferay/06-installing-liferay-portal-on-jboss-eap.markdown
- en/discover/deployment/articles/01-deploying-liferay/05-installing-liferay-portal-on-wildfly.markdown
https://issues.liferay.com/browse/LRDOCS-8724
https://issues.liferay.com/browse/LRDOCS-8725
> LRDOCS-8724-5 7.1.x Fix: Wildfly uses jsp-config element. For JBoss & Wildfly, add a resources-root element for each dependencies JAR. 

- .gitignore
- en/developer/frameworks/articles/web-experience-management/02-page-fragments/06-creating-contributed-fragment-collection.markdown
Includes information at the beginning of the Liferay Help Center article liking to the updated version in Liferay Learn.
Article updated:
[Creating a Contributed Fragment Collection (doc repo)](https://help.liferay.com/hc/en-us/articles/360028726872-Creating-a-Contributed-Fragment-Collection?flash_digest=cdd6073268e611831855ec6d4926b05865c52e9b)
Article linked to:
[Creating a Contributed Fragment Collection (learn repo)](https://learn.liferay.com/dxp/7.x/en/site-building/developer-guide/developing-page-fragments/creating-a-contributed-fragment-collection.html)
> LRDOCS-7854 Adding information about superseded article.

- en/user/articles/100-web-experience-management/06-publishing-content-dynamically/03-using-the-asset-publisher/04-configuring-display-settings.markdown
[LRDOCS-7930](https://issues.liferay.com/browse/LRDOCS-7930) [Subtask for 7.2](https://issues.liferay.com/browse/LRDOCS-8851)
- Adding information about the [updated article in liferay-learn](https://learn.liferay.com/dxp/7.x/en/site-building/displaying-content/using-the-asset-publisher-widget/configuring-display-settings.html).
- Removing incorrect Tip.
> LRDOCS-7930 [7.2 update] Incorrect information in Small Image Links.

- en/discover/portal/articles-dxp/110-collaboration/01-managing-documents-and-media/05-sharepoint/01-creating-a-sharepoint-application.markdown
This PR capitalizes the `Scope` attribute in the Creating a Sharepoint Application article, per [LRDOCS-8913](https://issues.liferay.com/browse/LRDOCS-8913).
> LRDOCS-8913 corrects Creating a Sharepoint Application article

- en/develop/tutorials/articles/210-front-end-taglibs/04-clay-taglibs/00-using-clay-taglibs-intro.markdown
From JIRA ticket [LRDOCS-9640](https://issues.liferay.com/browse/LRDOCS-9640).
The first link in the 'Using the Clay Taglib in Your portlets' is invalid and should be removed.
This change affects the 7.1 branch in the liferay-docs repository.
> LRDOCS 9640 Update incorrect and risky link [7.1]

- en/developer/reference/articles/02-front-end/03-front-end-taglibs/07-clay-taglibs/01-using-clay-taglibs-intro.markdown
From JIRA ticket [LRDOCS-9642](https://issues.liferay.com/browse/LRDOCS-9642).
The first link in the 'Using the Clay Taglib in Your portlets' is invalid and should be removed.
This change affects the 7.2 branch in the liferay-docs repository.
> LRDOCS-9642 Update incorrect and risky link [7.2]

- bin/migrate.py
Updates to admonitions
- Use Markdown links instead of angle bracket RST style links.
- Use single back-tics for code instead of double back-tics.
- Removed pipes
> Update migrate.py for MyST style admonitions

- en/user/articles/170-content-publication-management/02-staging/04-using-the-staging-environment/03-advanced-publication-with-staging.markdown
Per [LRDOCS-9989](https://issues.liferay.com/browse/LRDOCS-9989), this PR fixes a broken link in Staging documentation.
> LRDOCS-9989 fixes broken link

- en/developer/frameworks/articles/web-experience-management/02-page-fragments/06-creating-contributed-fragment-collection.markdown
See: https://issues.liferay.com/browse/LRDOCS-10363
This is a simple link fix, to an article that was renamed. (Note that a redirect was not added for this article when it was renamed; however, given it's already been a year since it was, I'm not sure it's worth adding one now)
The complaint originally comes from content on an HC article (which is of course no longer maintained), which we have ported but then reorganized the relevant parts to handle them totally differently (no longer using such a specific example that has the issue). I was originally thinking about re-adding the way it was documented in the HC article, but after talking with James and seeing the way we are doing it now (without using such arbitrary examples), I don't think that would really add any extra value, and would …
> LRDOCS-10363 Fix link to similar article on learn.liferay.com

- en/develop/tutorials/articles/300-internationalization/01-localizing-your-application.markdown
Related issue: [LRDOCS-10244](https://liferay.atlassian.net/browse/LRDOCS-10244)
Under What Locales are Available by Default, Language_es.properties is spelled Langauge_es.properties.
What was changed:
- Corrected typo
Article in question - [Localizing Your Application 7.1](https://help.liferay.com/hc/en-us/articles/360018168251-Localizing-Your-Application)
> LRDOCS-10244 Fix Typo

- en/develop/tutorials/articles/100-tooling/04-liferay-workspace/10-updating-default-plugins-provided-by-workspace.markdown
Related issue: [LRDOCS-7371](https://liferay.atlassian.net/browse/LRDOCS-7371)
The tutorial tells readers to add a property to build.gradle, gradle properties should go in a gradle.properties file.
What was changed:
- Corrected the file where properties are written
Article in question - [Updating Default Plugins Provided by Liferay Workspace 7.1](https://help.liferay.com/hc/en-us/articles/360018164831)
> LRDOCS-7371 Wrong File

- en/developer/frameworks/articles/portlets/07-using-javascript-in-your-portlets/09-spa/03-disabling-spa.markdown
Jira Ticket: https://liferay.atlassian.net/browse/LRDOCS-8732
Related article: https://help.liferay.com/hc/en-us/articles/360030752391-Disabling-SPA#disabling-spa-for-a-portlet
The code snippet shown in the article is supposed to be put in the liferay-portlet.xml file, since it processes Liferay-specific configs.
Changes made: 
- Change portlet.xml to liferay-portlet.xml
Reviewed [here](https://github.com/abhnerramos/liferay-docs/pull/2).
> LRDOCS-8732 Single page application support is toggled in liferay-portlet.xml, not portlet.xml

- en/developer/reference/articles/02-tooling/theme-generator/01-theme-generator-intro.markdown
Jira Ticket: https://liferay.atlassian.net/browse/LRDOCS-9454
Related article: https://help.liferay.com/hc/en-us/articles/360029147711
The command to install the 9.x.x version of generator-liferay-theme for 7.2 DXP was incomplete.
Changes made:
- Fix incomplete command for 7.2 Theme Generator
Thank you, @abhnerramos, for [reviewing](https://github.com/abhnerramos/liferay-docs/pull/3) this.
> LRDOCS-9454 Incomplete Command for 7.2 Theme Generator

- en/developer/frameworks/articles/front-end-development/02-themes/03-developing-themes/10-creating-a-thumbnail-preview-for-your-theme.markdown
Related issue: [LRDOCS-8718](https://liferay.atlassian.net/browse/LRDOCS-8718)
The article says images have to be 480px high and 270px wide, but it's actually the other way around.
What was changed:
- Fixed dimensions
Article in question - [Creating a Thumbnail Preview for Your Theme](https://help.liferay.com/hc/en-us/articles/360029046131-Creating-a-Thumbnail-Preview-for-Your-Theme)
> LRDOCS-8718 Fix dimensions

- develop/tutorials/articles/210-application-security/01-resources-roles-and-permissions.markdown
Jira Ticket: https://liferay.atlassian.net/browse/LRDOCS-8898
Related article: https://help.liferay.com/hc/en-us/articles/360018161671
The steps to add permissions to a custom portlet were supposed to have their respective tutorials. However, only the first step has an existing article. The other steps had a "(not yet written)" note.
Changes made: 
- Remove "(not yet written)" note from the DRAC steps
- Minor wordsmithing
Thanks, @abhnerramos, for [reviewing](https://github.com/abhnerramos/liferay-docs/pull/1) this.
> LRDOCS-8898 Not yet written links on 7.0 Adding Permissions to Resources

- en/discover/portal/articles-dxp/160-targeting-content-to-your-audience/08-audience-targeting-system-settings.markdown
Related issue: [LRDOCS-7377](https://liferay.atlassian.net/browse/LRDOCS-7377)
The HC article says Web Experience, but in 7.1 it's called Audience Targeting
- Corrected the name
Article in question - [Audience Targeting System Settings](https://help.liferay.com/hc/en-us/articles/360017895092-Audience-Targeting-System-Settings-)
> LRDOCS-7377 Section is called Audience Targeting

- discover/deployment/articles/06-upgrading-liferay/05-upgrading-social-office.markdown
Related issue: [LRDOCS-2768](https://liferay.atlassian.net/browse/LRDOCS-2768)
The old dev.liferay page on upgrading to Liferay 7.0 had a couple of links that didn't work. I looked through Help Center to see if they did too and found one link that wasn't working. @mhartel said to remove it.
- Removed broken link
Article in question - [Upgrading Social Office](https://help.liferay.com/hc/en-us/articles/360018175591-Upgrading-Social-Office-)
> LRDOCS-2768 Remove old link

- en/user/articles/100-web-experience-management/06-publishing-content-dynamically/04-publishing-rss-feeds/03-rss-publisher-widget.markdown
Related issue: [LRDOCS-7763](https://liferay.atlassian.net/browse/LRDOCS-7763)
The page has markup elements that weren't properly rendered and are visible.
- Removed markup entirely to make page match with it's 7.1 version
Article in question - [The RSS Publisher Widget](https://help.liferay.com/hc/en-us/articles/360028820672)
> LRDOCS-7763 Remove Visible Markup Elements

- en/develop/reference/articles/01-development-reference/01-intro.markdown
Jira ticket: https://liferay.atlassian.net/browse/LRDOCS-8372
Related article: https://help.liferay.com/hc/es/articles/360017901252-Development-Reference
The information in the Liferay DXP App Java APIs table and its links redirected the user to the wrong Portal app version.  
Changes made:
- Updated links to the correct app version; and
- Refactor HTML tables;
- Wordsmithing
Thank you, @rbohl and @Alec-Shay, for helping with this one!
> LRDOCS-8372 Links go to 7.0 for 7.1 Development Reference

- develop/reference/articles/12-project-templates/34-theme-contributor-template.markdown
Jira Ticket: https://liferay.atlassian.net/browse/LRDOCS-7925
Related article: https://help.liferay.com/hc/en-us/articles/360017891592-Theme-Contributor-Template
The Blade CLI command used in the article is wrong and will receive an error because of a typo in one of the parameters (contributorType).
Changes made:
- Fix Blade command typo
- Update generated files' structure
___
Thanks, @abhnerramos, for [reviewing](https://github.com/abhnerramos/liferay-docs/pull/6) this PR.
> LRDOCS-7925 Incorrect Blade Command for Theme Contributors

- en/developer/frameworks/articles/content-publication-management/02-export-import/02-developing-staged-models/02-generating-staged-models-using-service-builder.markdown
Related issue: [LRDOCS-9799](https://liferay.atlassian.net/browse/LRDOCS-9799)
The page has a broken link.
- Removed link
- Added alert that this page is no longer maintained
Article in question - [Generating Staged Models Using Service Builder](https://help.liferay.com/hc/en-us/articles/360029045791-Generating-Staged-Models-Using-Service-Builder)
> LRDOCS-9799 Remove link to zip 7.2

- en/developer/frameworks/articles/web-services/05-rest-builder/01-intro.markdown
Related issue: [LRDOCS-10121](https://liferay.atlassian.net/browse/LRDOCS-10121)
The link to JAX-RS was wrong. I found that the other link in this page was also outdated.
- Fixed both links
Article in question - [REST Builder](https://help.liferay.com/hc/es/articles/360036343312-REST-Builder)
> LRDOCS-10121 Fix Links on REST Builder

- develop/reference/articles/12-project-templates/19-npm-vuejs-portlet-template.markdown
Jira ticket: https://liferay.atlassian.net/browse/LRDOCS-7566
Related article: https://help.liferay.com/hc/en-us/articles/360017891312
The npm Vue.js Portlet was only implemented after DXP 7.0 Fix Pack 44+ or Portal CE GA7+. This information is important, since the reader needs to know the version in order for the portlet deployment work.
Changes made: 
- Add important admonition for the portlet's compatible version; and
- Fix outdated information.
___
Thank you, @abhnerramos, for [reviewing](https://github.com/abhnerramos/liferay-docs/pull/8) this PR!
> LRDOCS-7566 Note needed for npm Vue.js Portlet Template

- en/develop/tutorials/articles/290-configuration/01-making-apps-configurable/00-intro.markdown
Jira ticket: https://liferay.atlassian.net/browse/LRDOCS-7644
Related article: https://help.liferay.com/hc/en-us/articles/360018168111
In one of the notes in the article, the path that leads to the Blade sample configuration is incorrect. 
Changes made:
- Update wrong information; and
___
Thanks, @abhnerramos, for [reviewing](https://github.com/abhnerramos/liferay-docs/pull/10) this PR!
> LRDOCS-7644 Blade Sample Configuration changed for Making Applications Configurable

- en/develop/tutorials/articles/04-developing-a-web-application/07-permissions/03-assigning-permissions-to-resources.markdown
Related issue: [LRDOCS-6976](https://liferay.atlassian.net/browse/LRDOCS-6976)
The page has the user create an internal package and then export it. This isn't best practice.
- Removed .internal from package name
Article in question - [Assigning Permissions to Resources](https://help.liferay.com/hc/en-us/articles/360017884972-Assigning-Permissions-to-Resources)
> LRDOCS-6976 Do not reference internal packages or export them

- en/developer/appdev/articles/04-rest-builder/02-generating-apis-rest-builder.markdown
Related issue: [LRDOCS-9691](https://liferay.atlassian.net/browse/LRDOCS-9691)
Step 6 is incorrect
- Removed false information
Article in question - [Generating APIs with REST Builder](https://help.liferay.com/hc/en-us/articles/360028748872)
> LRDOCS-9691 buildREST can't be run from root module folder

- develop/tutorials/articles/310-troubleshooting/10-js-css-changes.markdown
Related issue: [LRDOCS-10127](https://liferay.atlassian.net/browse/LRDOCS-10127)
Example uses com.liferay.portlet.header-portlet-js when it should use com.liferay.portlet.header-portlet-javascript
- Changed js to javascript
Article in question - [Why Aren't My Module's JavaScript and CSS Changes Showing?](https://help.liferay.com/hc/en-us/articles/360018162731-Why-Aren-t-my-Module-s-JavaScript-and-CSS-Changes-Showing-?source=search)
> LRDOCS-10127 Fix attribute name

- discover/portal/articles/100-web-experience-management/03-staging-content-for-publication/03-using-the-staging-environment.markdown
Jira ticket: https://liferay.atlassian.net/browse/LRDOCS-7293
Related article: https://help.liferay.com/hc/en-us/articles/360018172331-Advanced-Publication-with-Staging
When using the Staging function in Liferay Portal, some types of content (in this case, Custom Fields) aren't supported for staging and will only be added in the Live server. That means that it will not be deleted by using Staging after being added to the Live enviroment, except by doing it directly.
This PR adds this information in the 7.0.x version of the article.
Changes made: 
- Add note about unsupported content for staging; and
___
Thanks, @abhnerramos, for [reviewing](https://github.com/abhnerramos/liferay-docs/pull/12) this PR.
> LRDOCS-7293 Custom Fields aren't deleted on the Live env after publishing (7.0.x)

- en/discover/portal/articles/100-web-experience-management/07-staging-content-for-publication/03-using-the-staging-environment/02-advanced-publication-with-staging.markdown
Jira ticket: https://liferay.atlassian.net/browse/LRDOCS-7293
Related article: https://help.liferay.com/hc/en-us/articles/360018172331-Advanced-Publication-with-Staging
When using the Staging function in Liferay Portal, some types of content (in this case, Custom Fields) aren't supported for staging and will only be added in the Live server. That means that it will not be deleted by using Staging after being added to the Live enviroment, except by doing it directly.
This PR adds this information in the 7.1 version of the article.
Changes made: 
- Modify note to include Custom Fields; and
___
Thanks, @abhnerramos, for [reviewing](https://github.com/abhnerramos/liferay-docs/pull/11) this PR.
> LRDOCS-7293 Custom Fields aren't deleted on the Live env after publishing (7.1.x) 

- develop/tutorials/articles/101-plugins-sdk/02-using-the-liferay-plugins-sdk.markdown
Jira Ticket: https://liferay.atlassian.net/browse/LRDOCS-4035
Related article: https://help.liferay.com/hc/en-us/articles/360018178271-Using-the-Plugins-SDK
This ticket describes a compilation error that can happen while using 6.2 Plugins SDK and JDK 8. In order to fix that problem, you need to insert two java build version properties in the `build.[username].properties` file. This PR adds that information as an admonition note in the article.
Changes made:
- Add admonition about java compiler error fix;
- Add links in commented placeholders; and
___
Thanks, @abhnerramos and @jrao, for [reviewing](https://github.com/abhnerramos/liferay-docs/pull/9) this PR!
> LRDOCS-4035 Java Compiler Compliance Issue
