develop/learning-paths/mvc/articles/01-beginning-liferay-development/02-developing-apps-with-liferay-ide.markdown

https://issues.liferay.com/browse/LRDOCS-1521

Specify Java Installation Type

---

develop/tutorials/articles/osgi/developing-osgi-plugins-for-liferay-intro.markdown

This fix was sent by Dave Nebinger, and is necessary for the link to work properly.

OSGI Link Fix

---

README.markdown
develop/learning-paths/mvc/articles/02-writing-a-data-driven-application/01-using-service-builder.markdown

This fix was submitted by @juergenu.

GitHub URL Fix

---

README.markdown
develop/tutorials/articles/maven/managing-liferay-maven-artifacts.markdown

This fix was sent by @kgolebiowski.

Maven URL Fix

---

develop/tutorials/articles/customizing-liferay-portal/overriding-language-props-hook.markdown
develop/tutorials/articles/customizing-liferay-portal/overriding-web-resources.markdown
develop/tutorials/articles/localization/generating-language-props-and-translations.markdown
develop/tutorials/articles/localization/localizing-site-administration-portlets.markdown
develop/tutorials/articles/localization/sharing-language-keys.markdown
develop/tutorials/articles/localization/using-language-keys.markdown

https://issues.liferay.com/browse/LRDOCS-1523

Add custom lang props files manually

---

discover/deployment/articles/04-managing-liferay-with-liferay-cloud-services/01-setting-up-your-lcs-account.markdown

This minor update was submitted by Juan Fernandez.

LCS Update

---

devGuide/en/chapters/11-apis.markdown

https://issues.liferay.com/browse/LRDOCS-1564

Bug - 6.1 Device Detection

---

discover/portal/articles/09-collaboration-suite/03-discuss-ask-and-answer-using-message-boards.markdown
userGuide/en/chapters/09-collaboration-suite.markdown

Clarifying Recent Posts setting for Message Boards portlet, per LRDOCS-1461.

fix - Minor user guide and discover/portal fix for Message Boards - LRDOCS-1461

---

develop/tutorials/articles/localization/using-language-keys.markdown

This fix was sent by @rmorrise.

More detail for portal-impl.jar path

---

discover/deployment/articles/01-installation-and-setup/16-installing-liferay-on-oracle-weblogic-12c.markdown
userGuide/en/chapters/16-installation-and-setup.markdown

Summary of changes:
-  Use WL_HOME instead of WEBLOGIC_HOME as name of variable, since it's used in the scripts.
-  Include Oracle_Home/ folder in path examples.
-  Recommend using Liferay to manage database and mail. LRDOCS-337
-  Recommend deploying Liferay on a managed server.
Tickets:
http://issues.liferay.com/browse/LRDOCS-337
http://issues.liferay.com/browse/LRDOCS-1584

Weblogic installation/setup improvements

---

devGuide/en/chapters/12-customizing-with-hooks.markdown
develop/tutorials/articles/customizing-liferay-portal/performing-a-custom-action-using-a-hook.markdown

https://issues.liferay.com/browse/LRDOCS-1567
Added workaround for Struts Action bug.

Struts action bug workaround

---

devGuide/en/chapters/07-hooks.markdown
devGuide/en/chapters/14-plugin-security.markdown
develop/tutorials/articles/07-hooks/02-overriding-web-resources.markdown
discover/portal/articles/20-errata/01-errata-for-using-liferay-portal-6-1.markdown

This should do the trick. :)
https://issues.liferay.com/browse/LRDOCS-1581

Fix - Xuggler 6.1.x

---

develop/tutorials/articles/liferay-mvc-portlet/configurable-portlet-preferences.markdown

https://issues.liferay.com/browse/LRDOCS-1586

Fix - link to sample view.jsp in tutorial

---

discover/portal/articles/03-advanced-web-content-management/10-displaying-site-pages-to-mobile-devices.markdown
userGuide/en/chapters/03-advanced-web-content-management.markdown

https://issues.liferay.com/browse/LRDOCS-1588

Fix - Device Recognition Provider app is EE-only

---

devGuide/en/chapters/07-hooks.markdown
develop/tutorials/articles/07-hooks/02-overriding-web-resources.markdown
discover/portal/articles/20-errata/01-errata-for-using-liferay-portal-6-1.markdown

Updated the errata.
https://issues.liferay.com/browse/LRDOCS-1588

Fix - (6.1.x) Device Recognition Provider app is EE-only

---

develop/tutorials/articles/resources-importer/importing-resources-with-your-themes.markdown

https://issues.liferay.com/browse/LRDOCS-1589

Specifying ADT for sitemap.json

---

develop/learning-paths/mvc/articles/01-beginning-liferay-development/03-writing-your-first-liferay-application.markdown

https://issues.liferay.com/browse/LRDOCS-1591

Fix - Add search container props to Writing Your First Liferay Application

---

discover/deployment/articles/01-installation-and-setup/17-installing-liferay-on-websphere-8.5.markdown
discover/portal/articles/07-targeting-content-to-your-audience/01-installation-and-uninstallation.markdown

https://issues.liferay.com/browse/LRDOCS-1592

Fix - WebSphere Installation Correction

---

discover/portal/articles/03-advanced-web-content-management/05-localization.markdown

https://issues.liferay.com/browse/LRDOCS-1578

Warning for Localizable Entities

---

discover/portal/articles/16-user-management/03-roles-and-permissions.markdown

https://issues.liferay.com/browse/LRDOCS-1609, I replaced the mention of chapter 3 with a link to the Site teams section of LDN.

Replace reference to chapter with link to article

---

develop/learning-paths/mvc/articles/08-using-alloyui-in-your-application/01-alloyui-form-validation.markdown

Removed extra space from code example in AlloyUI learning path form validation section.

LRDOCS-1618 Removed extra space from code example.

---

discover/portal/articles/05-document-management/08-liferay-sync-beta.markdown

Also a minor edit for a missing word.

Adding links to Sync downloads page.

---

develop/tutorials/articles/liferay-faces-alloy-ui-components/00-liferay-faces-alloy-ui-components-intro.markdown
develop/tutorials/articles/liferay-faces-bridge-ui-components/00-liferay-faces-bridge-ui-components-intro.markdown
develop/tutorials/articles/liferay-faces-bridge-ui-components/01-using-the-bridge-inputfile-ui-component.markdown
develop/tutorials/articles/liferay-faces-bridge-ui-components/02-using-the-portlet-actionurl-ui-component.markdown
develop/tutorials/articles/liferay-faces-bridge-ui-components/03-using-the-portlet-namespace-ui-component.markdown
develop/tutorials/articles/liferay-faces-bridge-ui-components/04-using-the-portlet-param-ui-component.markdown
develop/tutorials/articles/liferay-faces-bridge-ui-components/05-using-the-portlet-renderurl-ui-component.markdown
develop/tutorials/articles/liferay-faces-bridge-ui-components/06-using-the-portlet-resourceurl-ui-component.markdown

Here are the UI component tutorials based on the content from the dev guide.
All of the Jira tickets are in https://issues.liferay.com/browse/STRUC-1108 and https://issues.liferay.com/browse/STRUC-1109.

Conversion - Liferay Faces UI component tutorials

---

build.properties

https://issues.liferay.com/browse/LRDOCS-1651

Update repo.branch property to 6.2.x

---

discover/portal/articles/16-user-management/01-the-users-section-of-the-control-panel.markdown

https://issues.liferay.com/browse/LRDOCS-1640, fixed descirption of Organization Owner and Administrator, since the creator of an organization is no longer automatically assigned as a member of the organiation or the Organization Owner Role. Also added links to LDN articles in place of chapter references throughout article.

Default Organization Owner Descirption

---

discover/deployment/articles/04-managing-liferay-with-liferay-connected-services/04-configuring-the-lcs-client.markdown

Per the LCS team, added instructions for setting LCS client connection properties, and clarified property definitions.

LRDOCS-1644 LCS properties

---

discover/portal/articles/03-advanced-web-content-management/08-staging-page-publication.markdown

https://issues.liferay.com/browse/LRDOCS-1599

Date Range feature - Staging

---

develop/tutorials/articles/ddl/placeholder.txt
develop/tutorials/articles/ddm/placeholder.txt
develop/tutorials/code/ddl/placeholder.txt
develop/tutorials/code/ddm/placeholder.txt
develop/tutorials/code/recycle/placeholder.txt

Remove empty tutorial article folders and code folders.

---

develop/tutorials/articles/audience-targeting/creating-new-audience-targeting-rule-types.markdown
discover/portal/articles/03-advanced-web-content-management/10-displaying-site-pages-to-mobile-devices.markdown
discover/portal/articles/07-targeting-content-to-your-audience/06-audience-targeting-rules-reference.markdown

https://issues.liferay.com/browse/LRDOCS-1625
https://issues.liferay.com/browse/LRDOCS-1626

Minor Additions for Audience Targeting

---

develop/tutorials/articles/opensocial-gadgets/01-sending-pubsub-messages-between-gadgets-and-portlets.markdown
develop/tutorials/articles/opensocial-gadgets/02-using-the-gadget-editor.markdown

Added Related Topics section and links to OpenSocial tutorials.
@jhinkey

OpenSocial tutorials Related Topics.

---

develop/tutorials/articles/audience-targeting/accessing-the-content-targeting-api.markdown

Hey Rich; I also sent you an email related to this PR. In the email, I attached a sample portlet that demonstrates using the Content Targeting API. I've already created a dummy link for it in the text. Once this tutorial is merged, could you upload the portlet to LDN's doc library and provide the link to it? Thanks!
https://issues.liferay.com/browse/LRDOCS-1702

Accessing Audience Targeting API - tutorial

---

develop/tutorials/articles/themes-and-layout-templates/03-using-developer-mode-with-themes.markdown

Originally submitted by James Falkner.

Additional Info for Developer Mode

---

develop/learning-paths/mvc/articles/03-writing-a-data-driven-application/04-implementing-a-ui-with-taglibs.markdown

Fix - JSP code snippet typo

---

develop/learning-paths/mvc/articles/04-setting-permissions/01-configuring-your-permissions-scheme.markdown

Fix - XML Snippet Typo

---

develop/tutorials/articles/02-plugins-sdk/02-structure-of-the-sdk.markdown

Fix - SDK section typo - 6.1.x

---

develop/tutorials/articles/04-maven/01-setting-up-maven.markdown

Fix - Nexus URL Updates

---

discover/portal/articles/03-advanced-web-content-management/01-advanced-content-with-structures-and-templates.markdown

https://issues.liferay.com/browse/LRDOCS-1706

Web Content Preview Validity

---

discover/portal/articles/08-personalization-and-customization/03-using-application-display-templates.markdown

https://issues.liferay.com/browse/LRDOCS-1727

Warn to not embed portlets in ADTs

---

discover/portal/articles/07-targeting-content-to-your-audience/01-installation-and-uninstallation.markdown

https://issues.liferay.com/browse/LRDOCS-1785

Audience Targeting - required WebSphere version update

---

develop/learning-paths/mvc/articles/03-writing-a-data-driven-application/01-using-service-builder.markdown
develop/learning-paths/mvc/articles/03-writing-a-data-driven-application/02-integrating-persistence-framework.markdown
develop/learning-paths/mvc/articles/03-writing-a-data-driven-application/03-updating-your-controller.markdown

Fixed broken links to Liferaypedia pages. https://issues.liferay.com/browse/LRDOCS-1783

Fixed broken links to Liferaypedia entries

---

discover/portal/articles/19-configuring-for-high-availability/01-managing-liferay-with-lcs.markdown

Added step for LCS patching tool setup to include auto-discovery.

LRDOCS-1782 update to LCS patching tool instructions - 6.1.x

---

discover/deployment/articles/04-managing-liferay-with-liferay-connected-services/03-configuring-the-patching-tool.markdown

Added step on auto-discovery to patching tool setup for LCS.

LRDOCS-1781 update to LCS patching tool instructions - 6.2.x

---

discover/portal/articles/02-web-content-management/04-features-of-liferays-wcm.markdown

https://issues.liferay.com/browse/LRDOCS-1512

Fix - Localizable checkbox no longer exists

---

develop/tutorials/articles/customizing-liferay-portal-with-hooks/01-creating-a-hook-project-in-the-plugins-sdk.markdown

https://issues.liferay.com/browse/LRDOCS-1541

Link to 6.2 Portal Compat Hook

---

distribute/publish/articles/01-publishing-your-app/01-planning-your-apps-distribution.markdown
distribute/publish/articles/01-publishing-your-app/02-preparing-your-app.markdown
distribute/publish/articles/01-publishing-your-app/03-submitting-your-app.markdown
distribute/publish/articles/01-publishing-your-app/04-understanding-the-app-review-process.markdown

Thanks
https://issues.liferay.com/browse/LRDOCS-1767

Fix broken links in MP App Publishing docs.

---

develop/tutorials/articles/search-and-indexing/02-faceted-search-and-customized-search-filtering.markdown

Clarify definition of 'term result list' in search and indexing tutorial

Search term clarification

---

develop/tutorials/articles/customizing-liferay-portal-with-hooks/12-creating-plugins-to-extend-plugins.markdown

https://issues.liferay.com/browse/LRDOCS-1745

Creating Plugins to Extend Plugins - tutorial

---

discover/portal/articles/03-advanced-web-content-management/08-staging-page-publication.markdown

https://issues.liferay.com/browse/LRDOCS-1601

Publishing Embedded WC images

---

develop/tutorials/articles/service-builder/09-understanding-liferays-service-security-model.markdown

https://issues.liferay.com/browse/LRDOCS-1779 Clarify documentation on authentication for remote service calls

LRDOCS-1779 Clarify documentation on authentication for remote service calls

---

discover/portal/articles/03-advanced-web-content-management/08-staging-page-publication.markdown

https://issues.liferay.com/browse/LRDOCS-1600

Staging Updates for Content Boxes

---

develop/tutorials/articles/07-jsf-portlets-with-liferay-faces/05-understanding-the-liferay-faces-version-scheme.markdown
develop/tutorials/articles/07-jsf-portlets-with-liferay-faces/97-migrating-from-liferay-faces-31-to-liferay-faces-32-42.markdown
develop/tutorials/articles/07-jsf-portlets-with-liferay-faces/98-migrating-from-portletfaces-to-liferay-faces.markdown
develop/tutorials/articles/liferay-faces-alloy-ui-components/00-liferay-faces-alloy-ui-components-intro.markdown
develop/tutorials/articles/liferay-faces-bridge-ui-components/00-liferay-faces-bridge-ui-components-intro.markdown

JSF Version Updates

---

develop/reference/articles/02-screenlets-in-liferay-screens-for-android/01-login-screenlet-for-android.markdown
develop/reference/articles/02-screenlets-in-liferay-screens-for-android/02-sign-up-screenlet-for-android.markdown
develop/reference/articles/02-screenlets-in-liferay-screens-for-android/03-forgot-password-screenlet-for-android.markdown
develop/reference/articles/02-screenlets-in-liferay-screens-for-android/04-user-portrait-screenlet-for-android.markdown
develop/reference/articles/02-screenlets-in-liferay-screens-for-android/05-ddl-form-screenlet-for-android.markdown
develop/reference/articles/02-screenlets-in-liferay-screens-for-android/06-ddl-list-screenlet-for-android.markdown
develop/reference/articles/02-screenlets-in-liferay-screens-for-android/07-asset-list-screenlet-for-android.markdown
develop/reference/articles/02-screenlets-in-liferay-screens-for-android/08-web-content-display-screenlet-for-android.markdown
develop/reference/articles/03-screenlets-in-liferay-screens-for-ios/03-forgot-password-screenlet-for-ios.markdown
develop/reference/articles/03-screenlets-in-liferay-screens-for-ios/05-ddl-form-screenlet-for-ios.markdown
develop/reference/articles/03-screenlets-in-liferay-screens-for-ios/06-ddl-list-screenlet-for-ios.markdown
develop/reference/articles/03-screenlets-in-liferay-screens-for-ios/07-asset-list-screenlet-for-ios.markdown
develop/tutorials/articles/mobile-apps-with-liferay-screens/01-preparing-android-projects-for-liferay-screens.markdown
develop/tutorials/articles/mobile-apps-with-liferay-screens/03-using-views-in-android-screenlets.markdown
develop/tutorials/articles/mobile-apps-with-liferay-screens/04-architecture-of-liferay-screens-for-android.markdown
develop/tutorials/articles/mobile-apps-with-liferay-screens/05-creating-android-screenlets.markdown
develop/tutorials/articles/mobile-apps-with-liferay-screens/06-creating-android-views.markdown
develop/tutorials/articles/mobile-apps-with-liferay-screens/07-packaging-android-screenlets.markdown
develop/tutorials/articles/mobile-apps-with-liferay-screens/08-using-liferay-push-in-android-apps.markdown
develop/tutorials/articles/mobile-apps-with-liferay-screens/09-preparing-ios-projects-for-liferay-screens.markdown
develop/tutorials/articles/mobile-apps-with-liferay-screens/10-using-screenlets-in-ios-apps.markdown
develop/tutorials/articles/mobile-apps-with-liferay-screens/11-architecture-of-liferay-screens-for-ios.markdown
develop/tutorials/articles/mobile-apps-with-liferay-screens/12-creating-ios-screenlets.markdown
develop/tutorials/articles/mobile-apps-with-liferay-screens/13-creating-ios-themes.markdown

Updates to Android SDK version, Android Screens version, Compatibility Plugin links, and GitHub links.

LRDOCS-1810 Screens 1.1 minor updates

---

discover/deployment/articles/02-advanced-portal-operation/06-upgrading-liferay.markdown

https://issues.liferay.com/browse/LRDOCS-1824 Replace references to chapter 14 (the old installing Liferay chapter) with references to the Deployment documentation

LRDOCS-1824 Replace references to chapter 14 (the old installing Liferay chapter) with references to the Deployment documentation

---

develop/learning-paths/mvc/articles/11-approving-content-with-workflow/03-displaying-approved-workflow-items.markdown

Account for workflow status in the view_search.jsp: https://issues.liferay.com/browse/LRDOCS-1826

Account for Workflow in view_search.jsp

---

develop/tutorials/articles/customizing-portal/providing-portlets-to-manage-requests.markdown
develop/tutorials/articles/themes-and-layout-templates/embedding-portlets-in-a-theme.markdown
develop/tutorials/articles/themes-and-layout-templates/embedding-portlets-in-themes-and-layout-templates.markdown

@juliocamarero
https://issues.liferay.com/browse/LRDOCS-1778
https://issues.liferay.com/browse/LRDOCS-1797

Portlet Providers - tutorials

---

develop/tutorials/articles/localization/02-generating-language-properties-files-and-automated-translations.markdown

I just had to set this up to review Cody's language key improvements and found that it would be more helpful to add these links and adjust the instructions.

6.2 - Improvements for setting up to use Microsoft Translator

---

develop/tutorials/articles/search-and-indexing/02-faceted-search-and-customized-search-filtering.markdown

LDN user feedback pointed to these inconsistencies.

Tutorial formatting

---

develop/tutorials/articles/04-service-builder/09-writing-remote-service-classes.markdown

This change was recommended by Jorge in the LDN *Suggestions*.

Provide JSON link for SB tutorial

---

discover/portal/articles/01-what-is-liferay/00-what-is-liferay-intro.markdown

https://dev.liferay.com/discover/portal  Discover-->Portal landing page article, WHAT IS LIFERAY?, has messed up formatting. I added a line break, and it is now beautiful.

A Line break was missing from What is Liferay?

---

discover/deployment/articles/02-advanced-portal-operation/05-patching-liferay.markdown
discover/deployment/articles/05-configuring-for-high-availability/02-performance-tuning.markdown
discover/deployment/articles/05-configuring-for-high-availability/04-configuring-for-high-availability-summary.markdown
discover/portal/articles/17-using-the-control-panel/05-server-administration.markdown

Added links to LCS in sidebars. Fixed summary mention of Liferay Cloud Services, per PR:
https://github.com/liferay/liferay-docs/pull/146/files
@juanferrub

LRDOCS-1875 LCS links

---

discover/portal/articles/16-using-the-control-panel/04-server-administration.markdown
discover/portal/articles/17-advanced-portal-operation/05-patching-liferay.markdown
discover/portal/articles/19-configuring-for-high-availability/03-performance-tuning.markdown
discover/portal/articles/19-configuring-for-high-availability/04-configuring-for-high-availability-summary.markdown

Linked to LCS docs in relevant sections. Fixed Cloud Services mention in summary, per following PR:
https://github.com/liferay/liferay-docs/pull/147
@juanferrub

LRDOCS-1877 Link to LCS in relevant docs - 6.1.x

---

develop/tutorials/articles/editor-configurations/adding-new-behavior-to-an-editor.markdown
develop/tutorials/articles/editor-configurations/modifying-an-editors-configuration.markdown

https://issues.liferay.com/browse/LRDOCS-1758
https://issues.liferay.com/browse/LRDOCS-1788

Extending Editors - 7.0 tutorials

---

develop/tutorials/articles/dynamic-applications/embedding-portlets-in-themes-and-layout-templates.markdown

https://issues.liferay.com/browse/LRDOCS-1856

Update LanguageEntry classes

---

discover/deployment/articles/04-managing-liferay-with-liferay-connected-services/00-managing-liferay-with-liferay-connected-services-intro.markdown

Edits to LCS contribution from @juanferrub

Edits to LCS contribution

---

develop/tutorials/articles/01-getting-started-plugins-sdk/02-creating-a-simple-bundle.markdown
develop/tutorials/articles/01-getting-started-plugins-sdk/03-creating-a-portlet-application.markdown

Fix typo in simple bundle tutorial and number the steps of creating a portlet application tutorial

Typo fix and number tutorial steps

---

develop/tutorials/articles/user-interfaces-with-alloyui/using-select-lists-to-present-options.markdown

Added information to Using Select Lists to Present Options tutorial, explaining the benefits of writing your JavaScript in main.js vs. inside of aui:script tags.

LRDOCS-1880 Explained benefits of JavaScript placement in main.js and aui:script tag

---

develop/tutorials/articles/02-blade-development/02-blade-tools-bundle-creation.markdown

Added note about specifying fully qualified class anme for service and servicewrapper projects, and added updated help output.https://issues.liferay.com/browse/LRDOCS-1883

Added etail to Blade Tools tutorial

---

develop/reference/articles/02-screenlets-in-liferay-screens-for-android/05-ddl-form-screenlet-for-android.markdown
develop/reference/articles/02-screenlets-in-liferay-screens-for-android/08-web-content-display-screenlet-for-android.markdown
develop/reference/articles/03-screenlets-in-liferay-screens-for-ios/01-login-screenlet-for-ios.markdown
develop/reference/articles/03-screenlets-in-liferay-screens-for-ios/02-sign-up-screenlet-for-ios.markdown
develop/reference/articles/03-screenlets-in-liferay-screens-for-ios/03-forgot-password-screenlet-for-ios.markdown
develop/reference/articles/03-screenlets-in-liferay-screens-for-ios/04-user-portrait-screenlet-for-ios.markdown
develop/reference/articles/03-screenlets-in-liferay-screens-for-ios/05-ddl-form-screenlet-for-ios.markdown
develop/reference/articles/03-screenlets-in-liferay-screens-for-ios/06-ddl-list-screenlet-for-ios.markdown
develop/reference/articles/03-screenlets-in-liferay-screens-for-ios/07-asset-list-screenlet-for-ios.markdown
develop/reference/articles/03-screenlets-in-liferay-screens-for-ios/08-web-content-display-screenlet-for-ios.markdown
develop/tutorials/articles/android-apps-with-liferay-screens/01-preparing-android-projects-for-liferay-screens.markdown
develop/tutorials/articles/ios-apps-with-liferay-screens/01-preparing-ios-projects-for-liferay-screens.markdown

No text changes. Incremented version numbers of requirements and dependencies. Also added Compatibility Plugin link to some Screenlet reference docs.
@juanferrub
@nhpatt
@jmnavarro

LRDOCS-1920 Incrementing version numbers for Screens 1.2 release.

---

discover/portal/articles/06-displaying-content-dynamically/02-searching-for-content-in-liferay.markdown

https://issues.liferay.com/browse/LRDOCS-842 Specify the rules regarding searching for localized web content in Liferay

LRDOCS-842 Specify the rules regarding searching for localized web content in Liferay

---

discover/portal/articles/17-using-the-control-panel/02-integrating-existing-users-into-liferay.markdown

https://issues.liferay.com/browse/LRDOCS-1917
Add explanation of the logic that applies to configuring the metadata URL and metadata file fields for the SAML plugin

LRDOCS-1917 Add explanation of the logic that applies to configuring the metadata URL and metadata file fields for the SAML plugin

---

discover/deployment/articles/04-managing-liferay-with-liferay-connected-services/05-using-lcs.markdown

Edited submission from @igorbeslic that adds a note to the LCS docs section on using environment tokens.

LRDOCS-2032 LCS auto-scaling note

---

develop/reference/articles/02-migrated-services/calling-migrated-services-from-legacy-plugins-intro.markdown

@gamerson 
I had Eduardo fill out the remaining services in the Google Doc. I've provided these services in a table, with a brief explanation. Let me know if there is something else that needs to be added to this reference doc. Thanks!
https://issues.liferay.com/browse/LRDOCS-1888

Exhaustive list of APIs migrated from core to modules

---

develop/reference/articles/03-breaking-changes/breaking-changes-intro.markdown

Hey Rich; as you suggested, I read through the breaking changes to see if any were for internal-use only. I was not able to find any entries that did not affect developers outside Liferay. I coordinated with @jhinkey on a few of the entries, and we decided that the ones I had selected as questionable did indeed affect outside developers. Therefore, I copied over all the contents of the document from `liferay-portal` and removed the guidelines for contributing. Thanks!

Breaking Changes Document

---

develop/tutorials/articles/export-import-and-staging/00-intro.markdown
develop/tutorials/articles/export-import-and-staging/initiating-new-processes-with-exportimportconfiguration-objects.markdown
develop/tutorials/articles/export-import-and-staging/using-the-export-import-lifecycle-listener-framework.markdown

I added more use cases and tried to make these features seem more interesting/useful for developers. Let me know if you have any further suggestions. Thanks!

Staging Intro refactoring

---

discover/portal/articles/17-using-the-control-panel/02-integrating-existing-users-into-liferay.markdown

https://issues.liferay.com/browse/LRDOCS-2058 Update SAML plugin documentation

https://issues.liferay.com/browse/LRDOCS-2058 Update SAML plugin documentation

---

develop/tutorials/articles/arquillian-extension-liferay/00-intro.markdown
develop/tutorials/articles/arquillian-extension-liferay/01-arquillian-extension-liferay.markdown

https://issues.liferay.com/browse/LRDOCS-1854 Update Arquillian extension for liferay docs; add section on Jacoco; mention that either Gradle or Maven can be used. (Gradle example to be added later)

Update Arquillian docs

---

discover/portal/articles/04-configuring-liferay-applications/02-export-import.markdown

Hey Rich; this staging security documentation should be published to LDN when Liferay 6.2 CE GA5 is released. From the last release email I received, this should happen tomorrow (Nov 25). I'll comment on this ticket if anything changes with this plan. Thanks!
https://issues.liferay.com/browse/LRDOCS-2046

Staging security prop 6.2.x

---

discover/portal/articles/07-collaboration-suite/01-understand-common-config-options.markdown

See sez11a#1438 for comment on publishing.
https://issues.liferay.com/browse/LRDOCS-2046

Staging security prop 6.1.x

---

discover/deployment/articles/04-managing-liferay-with-liferay-connected-services/04-using-lcs.markdown

Added table of contents to Using LCS article, for 6.2.x.

LRDOCS-2095 Add TOC to Using LCS article.

---

discover/portal/articles/19-configuring-for-high-availability/01-managing-liferay-with-lcs.markdown

Added table of contents to Using LCS section, and created links for section listing in intro.

LRDOCS-2096 Add TOC to Using LCS section

---

discover/portal/articles/15-liferay-marketplace/05-creating-and-uploading-apps.markdown

6.2.x Fix - Marketplace dev guide link

---

develop/reference/articles/03-breaking-changes/breaking-changes-intro.markdown

Breaking Changes for:
- LPS-60705
- LPS-60843
- LPS-60995
- LPS-60810

New Breaking Changes

---

discover/deployment/articles/03-maintaining-liferay/00-intro.markdown
discover/deployment/articles/03-maintaining-liferay/01-backing-up-liferay.markdown
discover/deployment/articles/03-maintaining-liferay/03-upgrading-liferay.markdown

https://issues.liferay.com/browse/LRDOCS-1974 Add documentation on maintaining liferay

LRDOCS-1974 Add documentation on maintaining liferay

---

discover/portal/articles/05-managing-users/00-user-management-intro.markdown

users intro file

---

discover/portal/articles/05-document-management/03-alternative-file-repository-options.markdown

https://issues.liferay.com/browse/LRDOCS-2121

Fix (6.2) Mention file system based document store limitation

---

develop/tutorials/articles/user-interfaces-with-alloyui/using-alloyui-validator.markdown

Thank you @peterborkuti!
cc/ @mwilliams2014

6.2.x aui:validator parameter description contribution

---

discover/portal/articles/04-business-productivity/03-using-workflow/00-intro.markdown
discover/portal/articles/04-business-productivity/03-using-workflow/01-enabling-workflow.markdown

Created enabling workflow article and workflow intro article.

LRDOCS-2000, Enabling Workflow

---

discover/portal/articles/04-business-productivity/03-using-workflow/01-enabling-workflow.markdown

https://issues.liferay.com/lrdocs-2000

manually renumbered figure

---

discover/deployment/articles/02-securing-liferay/09-openid-authentication.markdown

https://issues.liferay.com/browse/LRDOCS-2106 Fix link to Open ID for Java

LRDOCS-2106 Fix link to Open ID for Java

---

develop/tutorials/articles/configurable-component/01-making-apps-configurable-intro.markdown

Update Making Your Apps Configurable tutorial with new information from Jorge

Update Making Your Apps Configurable tutorial

---

develop/tutorials/articles/07-jsf-portlets-with-liferay-faces/05-understanding-the-liferay-faces-version-scheme.markdown

Update JSF Version Scheme

---

discover/deployment/articles/01-installing-liferay-portal/00-intro.markdown

Remove placeholder article that duplicated real article

Remove placeholder article that duplicated real article

---

develop/tutorials/articles/android-apps-with-liferay-screens/07-creating-android-screenlets.markdown

In Android Screenlet creation tutorial, added new BaseViewModel methods to View class for Screens 1.3.

LRDOCS-2187 Minor Screens 1.3 update

---

develop/reference/articles/05-osgi-properties/osgi-properties.markdown

Add OSGi properties reference
(from https://github.com/sez11a/liferay-docs/pull/1209)

Add OSGi properties reference

---

discover/deployment/articles/03-maintaining-liferay/03-upgrading-liferay.markdown

Clarify order of upgrade process steps

Clarify order of upgrade process steps

---

develop/tutorials/articles/themes-and-layout-templates/06-specifying-color-schemes.markdown

@sez11a Partner requested docs update for 6.2 color schemes.

LRDOCS-2196 Updated 6.2 color schemes tutorial to specify default color scheme

---

discover/portal/articles/04-business-productivity/03-using-workflow/00-intro.markdown
discover/portal/articles/04-business-productivity/03-using-workflow/01-enabling-workflow.markdown

You know, just formatting stuff, and things like that.

Boring stuff

---

discover/deployment/articles/01-installing-liferay/01-liferay-installation-overview.markdown

Comment out Editions of Liferay section

Comment out Editions of Liferay section

---

discover/deployment/articles/01-installing-liferay/05-installing-liferay-on-wildfly.markdown

https://issues.liferay.com/browse/LRDOCS-1955

Wildfly 10 Installation Guide

---

discover/deployment/articles/03-maintaining-liferay/03-upgrading-liferay.markdown

Update Upgrade doc's LIFERAY_CLASSSPATH variable

Update Upgrade doc's LIFERAY_CLASSSPATH variable

---

discover/portal/articles/08-personalization-and-customization/02-page-customizations.markdown

https://issues.liferay.com/browse/LRDOCS-2220

Page Customizations are for Public/Private Pages

---

discover/portal/articles/02-web-experience-management/04-publishing-content-dynamically/01-organizing-content-with-tags-and-categories.markdown
discover/portal/articles/02-web-experience-management/04-publishing-content-dynamically/03-searching-for-content.markdown
discover/portal/articles/02-web-experience-management/04-publishing-content-dynamically/04-publishing-assets.markdown

Web Content Instance rename

---

develop/tutorials/articles/mobile-sdk/11-building-mobile-sdks.markdown

Minor update to Mobile SDK Builder instructions.
@brunofarache

Mobile SDK Builder Update

---

develop/tutorials/articles/search/01-introduction-to-search-concepts.markdown
develop/tutorials/articles/search/02-customizing-liferay-search.markdown

Add two new search tutorial based on drafts from engineering

Search tutorials

---

develop/tutorials/articles/friendly-urls.markdown

Tutorial draft. Steps were confirmed by Ray, opportunity was provided for a technical review.

LRDOCS-2298, Friendly URLs Tutorial

---

develop/tutorials/articles/migrating-a-legacy-application/03-modularizing-legacy-plugins.markdown

Originally sent in sez11a#1563

ServiceBuilder template has changed

---

develop/tutorials/articles/mobile-sdk/00-intro.markdown
develop/tutorials/articles/mobile-sdk/03-invoking-liferay-services-in-your-android-app.markdown
develop/tutorials/articles/mobile-sdk/04-invoking-services-asynchronously-from-your-android-app.markdown
develop/tutorials/articles/mobile-sdk/05-sending-your-android-apps-requests-using-batch-processing.markdown
develop/tutorials/articles/mobile-sdk/06-creating-ios-apps-that-use-liferay.markdown
develop/tutorials/articles/mobile-sdk/07-making-liferay-services-available-ios.markdown
develop/tutorials/articles/mobile-sdk/08-invoking-liferay-services-in-your-ios-app.markdown
develop/tutorials/articles/mobile-sdk/09-invoking-services-asynchronously-from-your-ios-app.markdown
develop/tutorials/articles/mobile-sdk/10-sending-your-ios-apps-requests-using-batch-processing.markdown
develop/tutorials/articles/mobile-sdk/11-building-mobile-sdks.markdown

This fixes several broken links to the 6.2.x Mobile SDK docs.

Fixing Mobile SDK docs links - 6.2.x

---

develop/tutorials/articles/07-jsf-portlets-with-liferay-faces/05-understanding-the-liferay-faces-version-scheme.markdown

cc/ @ngriffin7a
https://issues.liferay.com/browse/LRDOCS-2309

Update Faces Bridge Ext 4.0.x versions

---

develop/tutorials/articles/08-customizable-web-applications/providing-portlets-to-manage-requests.markdown
develop/tutorials/articles/28-themes-and-layout-templates/embedding-portlets-in-themes-and-layout-templates.markdown

New Portlet Provider Action

---

discover/deployment/articles/02-advanced-portal-operation/06-upgrading-liferay.markdown

Hey @sez11a,
This is a small change for a common issue during upgrades.
I will send you the changes for upgrading to Liferay 7 once the new tool is included in the liferay-portal repository. I hope it can be next week at most.
Thanks.

LRDOCS-2318 Check image permissions after upgrading your portal

---

develop/learning-paths/mvc/articles/03-writing-a-data-driven-application/01-using-service-builder.markdown

cc/ @pandaboi
https://issues.liferay.com/browse/LRDOCS-2319

Make sure Uuid attribute is set to "true" in service.xml

---

discover/portal/articles/06-displaying-content-dynamically/03-using-the-asset-publisher.markdown

Asset Publisher Ordering Note

---

develop/tutorials/articles/04-business-logic-and-data-access/02-customizing-liferay-services.markdown

https://issues.liferay.com/browse/LRDOCS-2332, fixed service wrapper tutorial blade cli creation command

LRDOCS-2332

---

develop/tutorials/articles/25-frontend-customizations/03-mvc-command-override.markdown

https://issues.liferay.com/browse/LRDOCS-2483

MVC Command Overrides, LRDOCS-2483

---

discover/portal/articles/14-installation-and-setup/11-installing-liferay-jboss-5-1.markdown

https://issues.liferay.com/browse/LRDOCS-997

Edit JBoss 5.1 deploy folder instructions

---

develop/reference/articles/01-intro/00-development-reference-intro.markdown

https://issues.liferay.com/browse/LRDOCS-2581

Fix: Remove large gaps in dev reference intro

---

discover/deployment/articles-dxp/01-installing-liferay/installing-liferay-on-jboss-eap.markdown
discover/deployment/articles/01-installing-liferay/01-liferay-installation-overview.markdown
discover/deployment/articles/01-installing-liferay/02-installing-liferay-bundle.markdown
discover/deployment/articles/01-installing-liferay/understanding-liferays-releases.markdown

https://issues.liferay.com/browse/LRDOCS-2101

JBoss EAP 6.4

---

develop/tutorials/articles/06-web-applications/05-jsf/01-packaging-a-jsf-application.markdown

JSF tutorial typo

---

discover/deployment/articles/01-installation-and-setup/14-installing-liferay-on-jboss-7.1.markdown

https://issues.liferay.com/browse/LRDOCS-932

Note known limitations with JBoss 7.1.1

---

develop/tutorials/articles/04-business-logic-and-data-access/03-business-logic-with-service-builder/04-customizing-liferay-services.markdown

Service Wrapper Template tutorial.

LRDOCS-2584 Replaced Blade create instructions with a link to the

---

develop/reference/articles/04-breaking-changes/breaking-changes-intro.markdown
develop/tutorials/articles/02-tooling/02-liferay-workspace/01-creating-a-liferay-workspace.markdown
develop/tutorials/articles/31-migrating-a-legacy-application/01-migrating-existing-code-to-liferay-7.markdown
develop/tutorials/articles/31-migrating-a-legacy-application/03-modularizing-legacy-plugins.markdown
discover/deployment/articles/03-maintaining-liferay/03-upgrading-liferay.markdown

… to both DXP and CE versions.

LRDOCS-2549 Mentioned functionality covered in these articles applies

---

discover/portal/articles/10-social-networking/03-exporting-portal-applications-widgets-opensocial-gadgets.markdown

@dejuknow on github deleted 6.2.x branch. Updated correct URL

Updated twitter widget URL

---

develop/reference/articles/01-intro/00-development-reference-intro.markdown
develop/reference/articles/02-liferay-api-modules/00-liferay-api-modules-intro.markdown
develop/tutorials/articles/04-business-logic-and-data-access/03-business-logic-with-service-builder/03-finding-and-invoking-liferay-services.markdown
develop/tutorials/articles/29-product-navigation/03-extending-the-simulation-menu.markdown

... as the repository used is now https://repository.liferay.com/nexus/content/repositories/liferay-public-releases

Fix artifact repository links

---

discover/deployment/articles/03-maintaining-liferay/03-upgrading-liferay.markdown
discover/portal/articles/03-collaboration/01-managing-documents-and-media/03-repository-types.markdown

Hi @sez11a,
The upgrade documentation is ready to be published. But, please:
- Review my english syntax before publishing it.
- I have included a section using +$$$ and I don't know if this is still valid:
https://github.com/sez11a/liferay-docs/commit/6b3c58e189b943bfb8a73c986944bcbaaff756bd
Thanks!
cc: @vicnate5

Upgrade to Liferay 7 Documentation

---

develop/tutorials/articles/28-themes-and-layout-templates/xx-creating-forms-with-liferays-taglibs.markdown

LRDOCS-2558 Wrote creating forms with taglibs tutorial

---

develop/tutorials/articles/11-apis/09-device-detection.markdown
discover/portal/articles/03-advanced-web-content-management/10-displaying-site-pages-mobile.markdown

See 6.2.x PR (sez11a#1663) for details.

Remove Device Recognition Provider content - 6.1.x

---

develop/tutorials/articles/03-portlets/xx-applying-lexicon-styles-to-your-application.markdown

LRDOCS-2470 Correcting syntax in code example.

---

develop/tutorials/articles/03-portlets/packaging-a-jsf-application.markdown

cc/ @vsingleton @ngriffin7a
https://issues.liferay.com/browse/LRDOCS-2619

Emphasize WAB Generator

---

develop/tutorials/articles/28-themes-and-layout-templates/01-application-decorators/01-adding-application-decorators-to-a-theme.markdown

Wordsmithing for Application Decorators tutorial

---

discover/portal/articles/02-web-experience-management/03-staging-content-for-publication/01-enabling-staging.markdown

cc/ @matethurzo 
https://issues.liferay.com/browse/LRDOCS-2599

Remote Staging environment patch levels should be consistent

---

discover/deployment/articles-dxp/03-maintaining-liferay/02-patching-liferay.markdown

https://issues.liferay.com/browse/LRDOCS-1973

LRDOCS-1973

---

discover/portal/articles-dxp/targeting-content-to-your-audience/02-managing-campaigns.markdown
discover/portal/articles-dxp/targeting-content-to-your-audience/06-audience-targeting-metrics-reference.markdown

cc/ @epgarcia
This should be added to this week's sprint. This is for DXP only. Thanks!
https://issues.liferay.com/browse/LRDOCS-2641

Audience Targeting Metrics

---

discover/portal/articles-dxp/targeting-content-to-your-audience/01-managing-user-segments.markdown
discover/portal/articles-dxp/targeting-content-to-your-audience/02-managing-campaigns.markdown
discover/portal/articles-dxp/targeting-content-to-your-audience/03-using-the-audience-targeting-applications.markdown

Audience Targeting Updates

---

discover/deployment/articles/02-advanced-portal-operation/05-patching-liferay.markdown

https://issues.liferay.com/browse/LRDOCS-2642

LRDOCS-2642

---

develop/tutorials/articles/250-frontend-customizations/01-overriding-module-jsps.markdown
discover/portal/articles/04-business-productivity/01-forms/02-advanced-forms.markdown

I renamed to something slightly different than Jorge suggested in the ticket, let me know if I should change it: https://issues.liferay.com/browse/LRDOCS-2643

LRDOCS-2643, article rename

---

discover/portal/articles-dxp/03-collaboration/01-managing-documents-and-media/03-using-a-sharepoint-repository.markdown

https://issues.liferay.com/browse/LRDOCS-1044

DXP SharePoint Connector correction

---

discover/portal/articles-dxp/targeting-content-to-your-audience/01-managing-user-segments.markdown
discover/portal/articles-dxp/targeting-content-to-your-audience/05-audience-targeting-rules-reference.markdown
discover/portal/articles-dxp/targeting-content-to-your-audience/06-audience-targeting-metrics-reference.markdown

Here are changes in the branch that Cody commented is ready for the Audience Targeting release.

Audience targeting release branch updates

---

discover/portal/articles/17-advanced-portal-operation/05-patching-liferay.markdown

Hi @sez11a ,
With this pull request I'd like to update the documentation for 6.1 as it is the same as we have on 6.2.x. Plus I've added the WebXML section from https://github.com/sez11a/liferay-docs/pull/1729 .
Please let me know if you have any questions.
Thank you,
Zoltán

Sync Patching Tool documentation from 6.2.x + WebXML updates

---

develop/tutorials/articles/106-jsf-portlets-with-liferay-faces/05-understanding-the-liferay-faces-version-scheme.markdown

cc @ngriffin7a
https://issues.liferay.com/browse/LRDOCS-2835

Update JSF Version Scheme 6.2

---

develop/tutorials/articles/mobile/01-android-apps-with-liferay-screens/08-creating-android-list-screenlets.markdown

Ready for review and publication.

Edits and fixes to Android list Screenlet tutorial.

---

develop/tutorials/articles/121-android-apps-with-liferay-screens/08-creating-android-list-screenlets.markdown

Ready for review and publication.

Edits and fixes to Android list Screenlet creation tutorial.

---

develop/reference/articles/03-portlet-descriptors/00-portlet-descriptors-intro.markdown

Fix mapping of portlet-name to javax.portlet.name. Add mapping of mime-type to javax.portlet.mime-type.

Correct and add OSGi property names

---

discover/deployment/articles/02-configuring-liferay/02-securing-liferay/13-antisamy.markdown

Change the category "Platform" to "Foundation" in System Settings.

Update 13-antisamy.markdown to change the category in System Settings

---

discover/deployment/articles-dxp/05-monitoring-liferay/02-liferay-connected-services/02-activating-dxp/01-preconfiguring-lcs-client.markdown

Update to LCS proxy configuration steps.

LCS Proxy Settings

---

discover/deployment/articles/04-managing-liferay-with-liferay-connected-services/02-configuring-the-lcs-client.markdown

Update to LCS proxy configuration steps for 6.2.x

LCS Proxy Settings - 6.2.x

---

discover/deployment/articles/01-installing-liferay/01-preparing-for-install.markdown

https://issues.liferay.com/browse/LRDOCS-2924

Replace "Liferay Portal" with tokens

---

discover/deployment/articles-dxp/05-monitoring-liferay/02-liferay-connected-services/02-activating-dxp/01-preconfiguring-lcs-client.markdown

Added http properties for LCS proxy configuration.

Additional LCS proxy configuration properties.

---

develop/tutorials/articles/260-themes-and-layout-templates/04-themelets.markdown

Fix Themelets typo

---

distribute/publish/articles/01-publishing-your-app/03-submitting-your-app.markdown

LRDOCS-2928 Marketplace

---

discover/deployment/articles-dxp/01-installing-liferay/08-installing-liferay-on-weblogic.markdown

Removing redundant security manager property from WebLogic setup doc.

Minor WebLogic fix

---

develop/reference/articles/09-liferay-faces/02-understanding-liferay-faces-bridge.markdown
develop/reference/articles/09-liferay-faces/03-understanding-liferay-faces-alloy.markdown
develop/reference/articles/09-liferay-faces/04-understanding-liferay-faces-portal.markdown
develop/tutorials/articles/110-portlets/packaging-a-jsf-application.markdown

JSF Reference article links

---

develop/tutorials/articles/107-service-builder/19-customizing-model-entities-with-model-hints.markdown

Improve default-value model hint description

LRDOCS-2936 6.2.x tutorial improvement

---

develop/tutorials/articles/120-business-logic-and-data-access/02-service-builder-persistence/04-customizing-model-entities-with-model-hints.markdown

Improve default-value model hint description

LRDOCS-2936 7.0 Tutorial improvement

---

develop/tutorials/articles/230-wysiwyg-editors/03-editor-configurations/modifying-an-editors-configuration.markdown

LRDOCS-1758 Fixes a bad link and replacse GitHub URLs with Javadoc URLs

LRDOCS-1758 Tutorial - minor fix and improvement

---

discover/deployment/articles-dxp/05-monitoring-liferay/02-liferay-connected-services/01-configuring-the-patching-tool.markdown

In LCS docs, fixing links to patching tool download and patching tool installation instructions.

LRDOCS-2938 LCS link fixes in patching tool article.

---

develop/tutorials/articles/100-tooling/03-blade-cli/04-activator-template.markdown
develop/tutorials/articles/100-tooling/03-blade-cli/05-fragment-template.markdown
develop/tutorials/articles/100-tooling/03-blade-cli/06-mvc-portlet-template.markdown
develop/tutorials/articles/100-tooling/03-blade-cli/07-portlet-template.markdown
develop/tutorials/articles/100-tooling/03-blade-cli/08-service-builder-template.markdown
develop/tutorials/articles/100-tooling/03-blade-cli/09-service-template.markdown
develop/tutorials/articles/100-tooling/03-blade-cli/10-service-wrapper-template.markdown

https://issues.liferay.com/browse/LRDOCS-2761
https://issues.liferay.com/browse/LRDOCS-2879
Also addressed PRs from liferay#193, liferay#205, and liferay#206

LRDOCS-2879 Blade CLI Template Edits

---

develop/tutorials/articles/120-business-logic-and-data-access/03-business-logic-with-service-builder/05-customizing-liferay-services.markdown

Add kernel in package

---

discover/deployment/articles/02-advanced-portal-operation/04-liferays-logging-system.markdown

6.2 Deployment Guide correction
https://issues.liferay.com/browse/LRDOCS-2941

LRDOCS-2941 Correct logging class name to LogFactoryUtil

---

discover/portal/articles/02-web-content-management/04-features-of-liferays-wcm.markdown

WCM Corrections 6.2.x

---

develop/tutorials/articles/260-themes-and-layout-templates/05-layout-templates-with-the-themes-generator.markdown

LRDOCS-2493 Added build note to ltpl sub generator tutorial.

---

discover/portal/articles-dxp/05-managing-users/07-auditing-users.markdown

lrdocs-2954

---

develop/tutorials/articles/106-jsf-portlets-with-liferay-faces/05-understanding-the-liferay-faces-version-scheme.markdown

/cc @ngriffin7a
https://issues.liferay.com/browse/LRDOCS-2955

LRDOCS-2955 Fix JSF Version Scheme Typo 6.2.x

---

discover/deployment/articles/04-managing-liferay-with-liferay-connected-services/02-configuring-the-lcs-client.markdown

Updated steps to configure the LCS client app to connect through a proxy - 6.2.x

New LCS proxy steps - 6.2.x

---

discover/portal/articles/07-targeting-content-to-your-audience/06-audience-targeting-rules-reference.markdown

https://issues.liferay.com/browse/LRDOCS-2958

LRDOCS-2958 Some Facebook rules require extra permissions 6.2.x

---

develop/reference/articles/xx-theme-file-reference/00-theme-reference-intro.markdown

@sez11a can you push these changes?
cc:@jhinkey
supersedes  https://github.com/sez11a/liferay-docs/pull/1837

LRDOCS-2974 fixed broken links in theme reference doc.

---

develop/tutorials/articles/100-tooling/03-blade-cli/05-fragment-template.markdown

https://issues.liferay.com/browse/LRDOCS-2971

LRDOCS-2971 Refer to Fragment Module Docs

---

develop/tutorials/articles/240-frontend-building-blocks/03-context-contributors.markdown

Hey Rich,
I've attempted to clarify the ***context*** of a template in the Context Contributors tutorial. Let me know if you still think it's unclear.
Thanks!
/cc @juliocamarero

LRDOCS-2291 Context Contributors tutorial

---

develop/tutorials/articles/260-themes-and-layout-templates/embedding-portlets-in-themes-and-layout-templates.markdown

Github links are broken for following files:
- RolesSelectorEditPortletProvider.java
- SiteNavigationLanguageViewPortletProvider.java

LRDOCS-2995 Broken links in "Embedding Portlets in Themes and Layout Templates" page

---

develop/tutorials/articles/04-themes/01-setting-up-the-theme/02-setting-up-the-theme-directory-structure.markdown

@sez11a This is a fix for a broken link sent in by a user. Can you please merge this and close this pr from the user: https://github.com/liferay/liferay-docs/pull/180

LRDOCS-3008

---

develop/tutorials/articles/260-themes-and-layout-templates/02-themes-generator.markdown

@sez11a this is a submitted fix by a user. Can you please close this pr: https://github.com/liferay/liferay-docs/pull/217
thx!

LRDOCS-3009 Update property name in package.json for themes generator

---

develop/tutorials/articles/01-introduction-to-liferay-development/00-intro.markdown
develop/tutorials/articles/01-introduction-to-liferay-development/01-fundamentals.markdown
develop/tutorials/articles/01-introduction-to-liferay-development/02-liferay-as-a-development-platform.markdown
develop/tutorials/articles/02-from-liferay-6-to-liferay-7/03-osgi-and-modularity-for-liferay-6-developers/00-osgi-and-modularity-for-liferay-6-developers-intro.markdown
develop/tutorials/articles/100-tooling/02-liferay-ide/03-creating-modules-with-liferay-ide.markdown
develop/tutorials/articles/260-themes-and-layout-templates/06-layout-templates-with-the-plugins-sdk.markdown
discover/deployment/articles/03-maintaining-liferay/02-liferay-enterprise-search/00-intro.markdown
discover/deployment/articles/03-maintaining-liferay/02-liferay-enterprise-search/04-solr.markdown
discover/portal/articles/03-collaboration/01-managing-documents-and-media/03-repository-types.markdown
discover/reference/articles/02-solr-settings.markdown
discover/reference/articles/03-elasticsearch-settings.markdown

Also snuck in a small typo fix. 😃 Thanks!

Number headers in all liferay-docs sections

---

discover/deployment/articles-dxp/05-monitoring-liferay/02-liferay-connected-services/02-activating-dxp/00-intro.markdown
discover/deployment/articles-dxp/05-monitoring-liferay/02-liferay-connected-services/03-using-lcs.markdown

New paragraph on floating licenses in LCS, and a note advising users to always install the latest client.

LRDOCS-3019 LCS floating licenses update

---

discover/deployment/articles/04-managing-liferay-with-liferay-connected-services/02-configuring-the-lcs-client.markdown
discover/deployment/articles/04-managing-liferay-with-liferay-connected-services/03-using-lcs.markdown

New paragraph on floating licenses in LCS, and a note advising users to always install the latest client.

LRDOCS-3020 LCS floating licenses update - 6.2.x

---

develop/tutorials/articles/130-importing-resources/03-importing-resources-with-your-themes.markdown

@sez11a Here is the update for our 6.2 docs. I'll send the 7.0 fix in a separate pr next week.

LRDOCS-3042 added notes to clarify the requirements for importing public and private page sets.

---

develop/tutorials/articles/260-themes-and-layout-templates/xx-importing-resources-with-a-theme.markdown

@sez11a here is the 7.0.x tutorial update mentioned in https://github.com/sez11a/liferay-docs/pull/1887

LRDOCS-3042 Clarified requirements for importing public and private page sets in the resources importer.

---

develop/tutorials/articles/100-tooling/03-blade-cli/02-creating-a-liferay-workspace-with-blade-cli.markdown
develop/tutorials/articles/100-tooling/04-liferay-workspace/00-liferay-workspace-intro.markdown

LRDOCS-2366 Update Workspace link and use new token

---

develop/reference/articles/01-development-reference.markdown
develop/tutorials/articles/100-tooling/03-blade-cli/02-creating-a-liferay-workspace-with-blade-cli.markdown

https://issues.liferay.com/browse/LRDOCS-3083

LRDOCS-3083 Update developer reference with missing HTML links

---

develop/tutorials/articles/100-tooling/05-maven/00-intro.markdown

Now that all the Maven topics are merged, I've updated the Maven intro to include everything, instead of just the first batch of tutorials.
/cc @jhinkey

LRDOCS-2367 Uncomment Maven topics in Intro

---

discover/deployment/articles/01-installing-liferay/12-liferay-enterprise-search/01-configuring-elasticsearch.markdown
discover/deployment/articles/01-installing-liferay/12-liferay-enterprise-search/04-solr.markdown

Fixed all kinds of bad links (mostly missing the leading /, and added link to Solr Settings ref article.

Link fixes

---

discover/portal/articles/02-web-experience-management/03-staging-content-for-publication/01-enabling-staging.markdown

These changes were submitted by Support to add/correct a few things.
https://issues.liferay.com/browse/LRDOCS-3117

Staging User Guide Updates

---

discover/portal/articles/02-web-experience-management/04-publishing-content-dynamically/01-organizing-content-with-tags-and-categories.markdown

https://issues.liferay.com/browse/LRDOCS-3107

LRDOCS-3107 Tags can only be lowercase chars

---

develop/tutorials/articles/100-tooling/05-maven/08-compiling-sass-files-in-a-maven-project.markdown

Originally submitted in liferay#226
https://issues.liferay.com/browse/LRDOCS-3103

LRDOCS-3103 Using Bourbon when using CSS Builder (Maven)

---

discover/deployment/articles-dxp/05-monitoring-liferay/02-liferay-connected-services/02-activating-dxp/01-preconfiguring-lcs-client.markdown
discover/deployment/articles-dxp/05-monitoring-liferay/02-liferay-connected-services/03-using-lcs.markdown

Various minor updates to LCS docs.

LRDOCS-3113 LCS docs update

---

discover/deployment/articles/04-managing-liferay-with-liferay-connected-services/02-configuring-the-lcs-client.markdown
discover/deployment/articles/04-managing-liferay-with-liferay-connected-services/03-using-lcs.markdown

Various minor updates to LCS docs - 6.2

LRDOCS-3118 LCS docs update - 6.2

---

discover/portal/articles/02-web-experience-management/04-publishing-content-dynamically/05-publishing-assets.markdown

https://issues.liferay.com/browse/LRDOCS-3128

LRDOCS-3128 Asset Publishers on page templates have fewer scope options

---

develop/reference/articles/100-felix-gogo-shell.markdown

This prevents users from shutting down the server accidentally.

Use Blade CLI for Gogo shell commands

---

build-site-common.xml
develop/reference/articles/01-development-reference.markdown
develop/tutorials/articles-dxp/450-audience-targeting/02-creating-new-audience-targeting-rule-types.markdown
develop/tutorials/articles-dxp/450-audience-targeting/04-tracking-user-actions-with-audience-targeting.markdown
release-site.properties

Updates the main developer reference with links to the newly aggregated CE/DE and app reference docs and it uses the tokens Cody introduced.
https://issues.liferay.com/browse/LRDOCS-3119
Requires re-importing *Develop > Reference*
Thanks

LRDOCS-3119 Update Developer Reference intro article.

---

develop/reference/articles/200-breaking-changes.markdown
develop/tutorials/articles/02-from-liferay-6-to-liferay-7/07-upgrading-plugins-to-liferay-7/05-upgrading-themes.markdown
develop/tutorials/articles/260-themes-and-layout-templates/xx-importing-resources-with-a-theme.markdown
discover/deployment/articles/02-configuring-liferay/02-document-repository.markdown
discover/portal/articles-dxp/targeting-content-to-your-audience/01-managing-user-segments.markdown
discover/portal/articles-dxp/targeting-content-to-your-audience/02-managing-campaigns.markdown
discover/portal/articles/03-collaboration/01-managing-documents-and-media/01-publishing-files.markdown
distribute/publish/articles/01-publishing-your-app/02-preparing-your-app.markdown

https://issues.liferay.com/browse/LRDOCS-3129 Changed OSGI to OSGi where applicable. @rotty3000

LRDOCS-3129, Fixed incorrect OSGi syntax

---

develop/tutorials/articles/100-tooling/05-maven/09-building-themes-in-a-maven-project.markdown

Reviewed by @david-truong
https://issues.liferay.com/browse/LRDOCS-3106

LRDOCS-3106 Theme Builder - Maven

---

develop/reference/articles/200-breaking-changes.markdown

Based on brianchandotcom/liferay-portal#44978

Update Breaking Change

---

develop/tutorials/articles/260-themes-and-layout-templates/02-themes-generator.markdown

LRDOCS-3145 Added note about image caching issues for themes

---

develop/tutorials/articles/100-tooling/04-liferay-workspace/00-liferay-workspace-intro.markdown

Originally sent in liferay#196
https://issues.liferay.com/browse/LRDOCS-2944

LRDOCS-2944 Skipping bundle download in Workspace

---

develop/tutorials/articles/01-introduction-to-liferay-development/20-frontend-development-in-liferay/00-frontend-development-in-liferay-intro.markdown
develop/tutorials/articles/110-portlets/12-automatic-single-page-application.markdown
develop/tutorials/articles/244-liferay-js-api/01-theme-display.markdown
develop/tutorials/articles/244-liferay-js-api/02-working-with-urls-in-javascript.markdown
develop/tutorials/articles/244-liferay-js-api/03-javascript-utilities.markdown
develop/tutorials/articles/260-themes-and-layout-templates/11-importing-lexicon-css-in-a-theme.markdown

LRDOCS-3188 fixes

---

develop/tutorials/articles/100-tooling/03-blade-cli/01-installing-blade-cli.markdown
develop/tutorials/articles/100-tooling/03-blade-cli/03-creating-modules-with-blade-cli.markdown

Hey Rich,
I decided to reorganize the current sections we had in Blade CLI's installation tutorial instead of creating a new one. I converted the "Verifying..." section into an "Updating..." section to highlight the update process, and reorganized the verification content as a part of installing. I don't think verification requires its own section.
I also made a couple other minor edits. Thanks!
https://issues.liferay.com/browse/LRDOCS-3190

LRDOCS-3190 Blade CLI Update edits

---

discover/deployment/articles/04-upgrading-liferay/00-upgrading-liferay-intro.markdown
discover/deployment/articles/04-upgrading-liferay/01-upgrading-sharding.markdown

LRDOCS-3108 Add tutorial for upgrade sharding

---

discover/portal/articles/02-web-experience-management/02-creating-web-content/01-publishing-basic-web-content.markdown

https://issues.liferay.com/browse/LRDOCS-3201

LRDOCS-3201 Fix link referencing Xuggler

---

discover/portal/articles/17-using-the-control-panel/05-server-administration.markdown

https://issues.liferay.com/browse/LRDOCS-3201

LRDOCS-3201 Fix link with missing leading slash

---

develop/tutorials/articles/110-portlets/12-automatic-single-page-application.markdown

@sez11a can you push this through please. The system setting description was wrong in the draft and needs updated. thx!

LRDOCS-2485 fix to SPA system setting description.

---

discover/deployment/articles-dxp/00-introduction/00-intro.markdown
discover/deployment/articles-dxp/01-installing-liferay/06-installing-liferay-on-jboss-eap.markdown
discover/deployment/articles-dxp/01-installing-liferay/07-installing-liferay-on-tcserver.markdown
discover/deployment/articles-dxp/01-installing-liferay/08-installing-liferay-on-weblogic.markdown
discover/deployment/articles-dxp/01-installing-liferay/09-installing-liferay-on-websphere.markdown
discover/deployment/articles-dxp/01-installing-liferay/10-trial-plugin-installation.markdown
discover/deployment/articles-dxp/01-installing-liferay/12-liferay-enterprise-search/00-intro.markdown
discover/deployment/articles-dxp/01-installing-liferay/12-liferay-enterprise-search/02-shield.markdown
discover/deployment/articles-dxp/01-installing-liferay/12-liferay-enterprise-search/03-marvel.markdown
discover/deployment/articles-dxp/02-configuring-liferay/03-liferay-clustering.markdown
discover/deployment/articles-dxp/02-configuring-liferay/04-securing-liferay/01-saml/00-intro.markdown
discover/deployment/articles-dxp/02-configuring-liferay/04-securing-liferay/01-saml/01-setting-up-saml.markdown
discover/deployment/articles-dxp/02-configuring-liferay/04-securing-liferay/12-oauth.markdown
discover/deployment/articles-dxp/03-maintaining-liferay/00-intro.markdown
discover/deployment/articles-dxp/03-maintaining-liferay/01-patching-liferay/00-intro.markdown
discover/deployment/articles-dxp/03-maintaining-liferay/01-patching-liferay/01-patching-basics.markdown
discover/deployment/articles-dxp/03-maintaining-liferay/01-patching-liferay/01-patching-tool-configuration/01-configuration-basic.markdown
discover/deployment/articles-dxp/03-maintaining-liferay/01-patching-liferay/01-patching-tool-configuration/02-configuration-advanced.markdown
discover/deployment/articles-dxp/03-maintaining-liferay/01-patching-liferay/01-patching-tool-configuration/03-installing-patches-on-the-liferay-de-war.markdown
discover/deployment/articles-dxp/03-maintaining-liferay/01-patching-liferay/02-patching-liferay.markdown
discover/deployment/articles-dxp/05-monitoring-liferay/02-liferay-connected-services/00-intro.markdown
discover/deployment/articles-dxp/05-monitoring-liferay/02-liferay-connected-services/01-configuring-the-patching-tool.markdown
discover/deployment/articles-dxp/05-monitoring-liferay/02-liferay-connected-services/02-activating-dxp/00-intro.markdown
discover/deployment/articles-dxp/05-monitoring-liferay/02-liferay-connected-services/02-activating-dxp/01-preconfiguring-lcs-client.markdown
discover/deployment/articles-dxp/05-monitoring-liferay/02-liferay-connected-services/02-activating-dxp/02-activating-your-dxp-server-with-lcs.markdown
discover/deployment/articles-dxp/05-monitoring-liferay/02-liferay-connected-services/03-using-lcs.markdown

Hi Rich,
This is my first PR about liferay-docs\discover\deployment folder.
I will continue with the other folders inside this folder later.
Could you please prioritize this and email me (gabor.kovacs@liferay.com) whether my changes are correct?
I will be on PTO from the 17th of Dec till the end of the year and it is a high priority project.
Thanks a lot!

Changes of liferay-docs\discover\deployment\articles-dxp folder

---

develop/tutorials/articles/01-introduction-to-liferay-development/30-starting-module-development/00-starting-module-development-intro.markdown

Remove square brackets from parameters

---

develop/tutorials/articles/340-data-upgrades-and-verifiers/01-creating-an-upgrade-process-for-your-application.markdown

https://issues.liferay.com/browse/LRDOCS-3210

Update links to Foundation app suite reference docs.

---

discover/portal/articles/02-web-experience-management/01-starting-site-development/01-creating-sites.markdown
discover/portal/articles/02-web-experience-management/01-starting-site-development/02-creating-and-managing-pages.markdown
discover/portal/articles/02-web-experience-management/01-starting-site-development/04-building-sites-from-templates.markdown
discover/portal/articles/02-web-experience-management/02-creating-web-content/01-publishing-basic-web-content.markdown
discover/portal/articles/02-web-experience-management/06-styling-apps-with-application-display-templates.markdown
discover/portal/articles/03-collaboration/02-collaborating/02-creating-forums-with-message-boards.markdown

https://issues.liferay.com/browse/LRDOCS-3214

LRDOCS-3214 Site Requests and Site Selector

---

develop/tutorials/articles/01-introduction/00-intro.markdown

Plugins SDK URL fix | 6.2.x

---

develop/tutorials/articles/180-application-configuration/01-making-apps-configurable.markdown

ExtendedObjectClassDefinition Package Edit

---

develop/reference/articles/100-felix-gogo-shell.markdown

More Gogo commands

---

discover/deployment/articles-dxp/02-configuring-liferay/04-securing-liferay/01-saml/01-setting-up-saml.markdown

https://issues.liferay.com/browse/LRDOCS-3202

LRDOCS-3202 Third party IdP must use signed messages, SAML

---

discover/portal/articles/05-managing-users/05-roles-and-permissions.markdown

https://issues.liferay.com/browse/LRDOCS-3220 @chrislui

Add details on assigning users to a role

---

discover/portal/articles/03-collaboration/02-collaborating/01-publishing-blogs.markdown

@sez11a There was a miscommunication. This feature is only available on master. Can you please merge this in soon. thx!
This reverts commit c1a29c1d7eeed4c6e81a79a46762d168fb80769e.

Revert "LRDOCS-3203 Added note about friendly URLs for blogs."

---

discover/deployment/articles/01-installing-liferay/04-installing-liferay-on-tomcat.markdown

https://issues.liferay.com/browse/LRDOCS-3231

LRDOCS-3231 Update Mojarra and Faces Versions

---

discover/deployment/articles/01-installation-and-setup/14-installing-liferay-on-jboss-7.1.markdown
discover/deployment/articles/01-installation-and-setup/15-installing-liferay-on-tomcat-7.markdown

https://issues.liferay.com/browse/LRDOCS-3231

LRDOCS-3231 Update Mojarra and Faces Versions | 6.2.x

---

discover/deployment/articles/01-installing-liferay/12-liferay-enterprise-search/01-configuring-elasticsearch.markdown

https://issues.liferay.com/browse/LRDOCS-3199
Author: @rbohl
Reviewers: @lipusz

LRDOCS-3199 Added "configuring remote hosts" section to Elasticsearch

---

develop/tutorials/articles/100-tooling/03-blade-cli/03-creating-modules-with-blade-cli.markdown

https://issues.liferay.com/browse/LRDOCS-3232

LRDOCS-3232 External Repo URL in Modules

---

develop/tutorials/articles-dxp/450-audience-targeting/02-creating-new-audience-targeting-rule-types.markdown
develop/tutorials/articles-dxp/450-audience-targeting/04-tracking-user-actions-with-audience-targeting.markdown
develop/tutorials/articles/02-from-liferay-6-to-liferay-7/02-benefits-of-liferay-7-for-liferay-6-developers/00-benefits-of-liferay-7-for-liferay-6-developers-intro.markdown
develop/tutorials/articles/160-import-export-and-staging/using-the-export-import-lifecycle-listener-framework.markdown
develop/tutorials/articles/230-wysiwyg-editors/02-modifying-an-editor-configuration.markdown
develop/tutorials/articles/230-wysiwyg-editors/03-adding-new-behavior-to-an-editor.markdown
develop/tutorials/articles/260-themes-and-layout-templates/07-embedding-portlets-in-themes-and-layout-templates.markdown
develop/tutorials/articles/270-product-navigation/03-extending-the-simulation-menu.markdown
develop/tutorials/articles/460-customizable-web-applications/01-providing-portlets-to-manage-requests.markdown

LRDOCS-3242 linked to creating modules tutorial.

---

develop/tutorials/articles/110-portlets/12-automatic-single-page-application.markdown

LRDOCS-3246 added additional info on disabling SPA.

---

develop/reference/articles/07-screenlets-in-liferay-screens-for-android/05-ddl-form-screenlet-for-android.markdown
develop/tutorials/articles/115-mobile/01-android-apps-with-liferay-screens/15-android-best-practices.markdown
develop/tutorials/articles/115-mobile/01-android-apps-with-liferay-screens/16-screens-android-troubleshooting-faq.markdown

Adding references in the Android best practices and troubleshooting tutorials to the new Android Breaking Changes doc.

Android Breaking Changes Links

---

develop/tutorials/articles/100-tooling/03-blade-cli/01-installing-blade-cli.markdown
develop/tutorials/articles/100-tooling/03-blade-cli/02-creating-a-liferay-workspace-with-blade-cli.markdown
develop/tutorials/articles/100-tooling/03-blade-cli/03-creating-modules-with-blade-cli.markdown
develop/tutorials/articles/100-tooling/04-liferay-workspace/01-configuring-a-liferay-workspace.markdown
develop/tutorials/articles/100-tooling/04-liferay-workspace/02-development-lifecycle-for-liferay-workspaces.markdown

https://issues.liferay.com/browse/LRDOCS-3206
https://issues.liferay.com/browse/LRDOCS-3251

LRDOCS-3251 Workspace Fixes/Updates

---

develop/tutorials/articles/120-business-logic-and-data-access/02-service-builder-persistence/02-running-service-builder-and-understanding-the-generated-code.markdown

just fixing the table name 'service_' to 'release_'. The BBDD script that is shown as an example is ok, just fixing the previous text

LRDOCS-3195 Just fixing the table name 'service_' to 'release_'

---

develop/tutorials/articles/280-testing/03-liferay-slim-runtime.markdown

https://issues.liferay.com/browse/LRDOCS-3131

LRDOCS-3131 Slim Runtime Conversion

---

develop/tutorials/articles/100-tooling/02-liferay-ide/04-deploying-modules-with-liferay-ide.markdown
develop/tutorials/articles/100-tooling/05-maven/02-generating-new-projects-using-archetypes.markdown
develop/tutorials/articles/100-tooling/05-maven/04-deploying-a-module-built-with-maven-to-liferay.markdown

https://issues.liferay.com/browse/LRDOCS-3258

LRDOCS-3258 Maven Clarifications

---

develop/tutorials/articles/110-portlets/02-liferay-soy-portlet/01-creating-a-soy-portlet.markdown

see https://github.com/liferay/liferay-docs/pull/246

LRDOCS-3278 pull 246

---

distribute/publish/articles/01-publishing-your-app/02-preparing-your-app.markdown

Import to *Distribute > Publish*
https://issues.liferay.com/browse/LRDOCS-3329

Fix link to API adaptation tutorial

---

develop/tutorials/articles/100-tooling/03-blade-cli/03-creating-modules-with-blade-cli.markdown

Blade Template Correction

---

discover/deployment/articles-dxp/07-liferay-connected-services/02-activating-dxp/02-activating-your-dxp-server-with-lcs.markdown

Edit of LCS note from @justinchoi001 in https://github.com/sez11a/liferay-docs/pull/2118

LRDOCS-3308 LCS note - master

---

discover/deployment/articles/04-managing-liferay-with-liferay-connected-services/02-configuring-the-lcs-client.markdown

Edit of LCS note from @justinchoi001 in https://github.com/sez11a/liferay-docs/pull/2119

LRDOCS-3308 LCS note - 6.2.x

---

develop/tutorials/articles/02-from-liferay-6-to-liferay-7/03-osgi-and-modularity-for-liferay-6-developers/00-osgi-and-modularity-for-liferay-6-developers-intro.markdown

[LRDOCS-3322](https://issues.liferay.com/browse/LRDOCS-3322)
cc/ @chrislui

Fix Gogo Shell component command descriptions

---

develop/tutorials/articles/220-internationalization/02-automatic-translation.markdown

https://issues.liferay.com/browse/LRDOCS-3324

LRDOCS-3324 Fix Grade build code for generating language keys

---

discover/deployment/articles-dxp/01-installing-liferay/09-installing-liferay-on-websphere.markdown

Updating WebSphere fix pack requirement, and adding a small section on setting the correct JDK version for compiling JSPs.

LRDOCS-3328 edits to WebSphere installation guide

---

discover/portal/articles/04-business-productivity/00-intro.markdown
discover/portal/articles/04-business-productivity/03-using-workflow/01-enabling-workflow.markdown

https://issues.liferay.com/browse/LRDOCS-3355, changed all instances of *Business Productivity* to *Forms and Workflow*. @marcellustavares

Product Name Change

---

develop/tutorials/articles/240-javascript-module-loaders/03-using-external-libraries.markdown

LRDOCS-3359 JS loader required version fix

---

discover/portal/articles/07-setting-up-liferay/04-scripting/03-leveraging-the-script-engine-in-workflow.markdown

https://issues.liferay.com/browse/LRDOCS-3215, added note about the bug (pre fp-11) that stops script users from resolving dependencies on non-core classes.

Workflow Scripting Bug Note

---

develop/tutorials/articles/02-from-liferay-6-to-liferay-7/08-optimizing-existing-plugins-for-liferay-7/00-modularizing-an-existing-portlet-intro.markdown

Service Builder Blade Correction

---

develop/tutorials/articles/260-themes-and-layout-templates/13-freemarker-macros.markdown

@sez11a Should be good to go now. The converter is no longer getting hung up, and the render looks correct after using the convert script.

LRDOCS-3358 freemarker table fix

---

develop/tutorials/articles/260-themes-and-layout-templates/08-theme-contributors.markdown

LRDOCS-3487 pr 110

---

develop/reference/articles/12-sample-modules/00-intro.markdown
develop/reference/articles/12-sample-modules/01-control-menu-entry.markdown
develop/reference/articles/12-sample-modules/02-core-jsp-hook.markdown
develop/reference/articles/12-sample-modules/03-screen-name-validator.markdown
develop/reference/articles/12-sample-modules/04-theme-contributor.markdown
develop/reference/articles/12-sample-modules/05-theme.markdown
develop/tutorials/articles/100-tooling/07-liferay-sample-modules/00-liferay-sample-modules-intro.markdown

https://issues.liferay.com/browse/LRDOCS-3502

LRDOCS-3502 BNDTools and Gradle sample modules have been removed

---

develop/tutorials/articles/115-mobile/01-android-apps-with-liferay-screens/07-creating-android-screenlets.markdown
develop/tutorials/articles/115-mobile/01-android-apps-with-liferay-screens/08-creating-android-list-screenlets.markdown
develop/tutorials/articles/160-import-export-and-staging/03-understanding-data-handlers.markdown
develop/tutorials/articles/160-import-export-and-staging/04-developing-data-handlers.markdown

Adding detail from Learning Path to Screens for Android Screenlet creation tutorials

LRDOCS-3509 Android Detail

---

discover/deployment/articles/01-installing-liferay/01-preparing-for-install.markdown
discover/deployment/articles/05-upgrading-liferay/00-upgrading-liferay-intro.markdown
discover/deployment/articles/06-liferay-enterprise-search/02-configuring-elasticsearch.markdown
discover/deployment/articles/06-liferay-enterprise-search/05-solr.markdown
discover/portal/articles/07-setting-up-liferay/04-scripting/02-running-scripts-from-script-console.markdown
discover/portal/articles/07-setting-up-liferay/04-scripting/03-leveraging-the-script-engine-in-workflow.markdown

liferay#267
liferay#269
liferay#271

Liferay PRs and link fixing

---

develop/tutorials/articles/11-apis/00-intro.markdown

Typo | 6.1.x

---

develop/tutorials/articles/01-introduction-to-liferay-development/30-starting-module-development/00-starting-module-development-intro.markdown
develop/tutorials/articles/110-portlets/01-liferay-mvc-portlet/01-creating-an-mvc-portlet.markdown

We no longer provide BndTools samples.
Thanks.

Fix: Remove mention of BndTools samples

---

develop/tutorials/articles/180-configuration/transitioning-from-portlet-preferences-to-the-configuration-api.markdown

Fixed the list formatting in the Transitioning...Configuration API article.

Formatting Fix

---

discover/portal/articles/07-setting-up-liferay/system-settings/system-settings.markdown

This is a User Guide fix.
Thanks

Fix caption for a configuration's actions

---

develop/tutorials/articles/110-portlets/08-friendly-urls/00-making-urls-friendlier-intro.markdown

Indent routes.xml file content so that it shows. Untabify.

Fix code formatting in friendly URL mapping tutorial

---

develop/reference/articles/07-screenlets-in-liferay-screens-for-android/01-login-screenlet-for-android.markdown
develop/reference/articles/08-screenlets-in-liferay-screens-for-ios/01-login-screenlet-for-ios.markdown

New attribute for Login Screenlet reference docs. Also did some wordsmithing and other general improvements.

LRDOCS-3538 new Login Screenlet attribute

---

develop/tutorials/articles/121-android-apps-with-liferay-screens/07-creating-android-screenlets.markdown
develop/tutorials/articles/121-android-apps-with-liferay-screens/08-creating-android-list-screenlets.markdown

Note that this content has already been reviewed and merged into master.

LRDOCS-3540 Porting recent Screens edits from master to 6.2

---

discover/portal/articles/03-advanced-web-content-management/11-liferay-monitoring-using-google-analytics.markdown

https://issues.liferay.com/browse/LRDOCS-3533
6.2.x Changes. 7.0 changes in a separate PR.

LRDOCS-3533 Added custom analytics

---

discover/deployment/articles/01-installing-liferay/10-configuring-search.markdown

https://issues.liferay.com/browse/LRDOCS-3330 fixed instructions on accessing the embedded ES. Thanks @chrislui!

LRDOCS-3330, Accessing Embedded ES

---

develop/tutorials/articles/195-forms/00-intro.markdown

There was a typo and a grammatical error I fixed.

Fixes to Liferay Forms Intro

---

discover/deployment/articles/02-configuring-liferay/02-document-repository.markdown
discover/portal/articles/03-collaboration/01-managing-documents-and-media/03-liferay-repository-types.markdown
discover/portal/articles/03-collaboration/01-managing-documents-and-media/04-using-external-repositories.markdown

LRDOCS-3553 CMIS Store deprecation and doc fixes

---

discover/deployment/articles-dxp/01-installing-liferay/10-trial-plugin-installation.markdown

Small edit on #5; dropped the parenthetical clause and reworded the limitations on Customer Portal.

LRDOCS-3558

---

discover/portal/articles/04-business-productivity/03-using-workflow/01-enabling-workflow.markdown

Fixed a couple typos in the Enabling Workflow article. Thanks @natocesarrego !

Typos in article

---

develop/tutorials/articles/195-forms/01-form-field-types/00-intro.markdown

removed note that form field settings article was coming soon

minor fix to form field types

---

develop/tutorials/articles/300-osgi-basics/01-adding-third-party-libraries-to-a-module.markdown

https://issues.liferay.com/browse/LRDOCS-3362

Critical: Improvements for using 3rd party libs

---

develop/tutorials/articles/01-introduction-to-liferay-development/30-starting-module-development/00-starting-module-development-intro.markdown

https://issues.liferay.com/browse/LRDOCS-3582

Fix: Sample project is created in the current folder

---

develop/tutorials/articles/02-from-liferay-6-to-liferay-7/07-upgrading-plugins-to-liferay-7/06-upgrading-liferay-6-themes.markdown

@sez11a This fixes a rendering issue with one of the notes. Please merge as soon as you can. thx!

LRDOCS-3500 fixed note syntax issue.

---

discover/portal/articles-dxp/04-business-productivity/03-using-workflow/02-kaleo-designer/04-kaleo-designer-task-nodes.markdown

https://issues.liferay.com/browse/LRDOCS-3360

LRDOCS-3360 fixed image path, resending

---

develop/tutorials/articles/106-jsf-portlets-with-liferay-faces/11-communicating-between-jsf-portlets-using-ipc.markdown
develop/tutorials/articles/120-liferay-faces-bridge-ui-components/01-using-the-bridge-inputfile-ui-component.markdown

JSF2 instances renamed to "JSF"

---

discover/deployment/articles/02-installing-liferay/10-configuring-search.markdown
discover/deployment/articles/08-liferay-enterprise-search/02-configuring-elasticsearch.markdown
discover/deployment/articles/08-liferay-enterprise-search/05-solr.markdown

https://issues.liferay.com/browse/LRDOCS-3602, Removed basic installation steps from the Configuring... article, and added relevant information to the steps in the Installing... article. @arboliveira

LRDOCS-3602 ES installation guide reconciliation

---

develop/tutorials/articles/100-tooling/03-blade-cli/01-installing-blade-cli.markdown

This was temporarily commented out since it was broken. It is now fixed in the latest version of Blade CLI and should be an option again.

Readd Blade Update command

---

develop/tutorials/articles/100-tooling/04-liferay-workspace/01-configuring-a-liferay-workspace.markdown

https://issues.liferay.com/browse/LRDOCS-3548

LRDOCS-3548 Configuring user-specific properties in Liferay Workspace

---

develop/tutorials/articles/100-tooling/05-maven/04-deploying-a-module-built-with-maven-to-liferay.markdown

https://issues.liferay.com/browse/LRDOCS-3556

LRDOCS-3556 Update Maven Deployment

---

develop/tutorials/articles/110-portlets/01-liferay-mvc-portlet/05-mvc-command-override.markdown

https://issues.liferay.com/browse/LRDOCS-3611

LRDOCS-3611 Reference MVC command implementations via component name

---

develop/tutorials/articles/02-from-liferay-6-to-liferay-7/07-upgrading-plugins-to-liferay-7/01-adapting-to-liferay-7s-api.markdown
develop/tutorials/articles/260-themes-and-layout-templates/02-themes-generator.markdown

https://issues.liferay.com/browse/LRDOCS-3620

LRDOCS-3620 Wordsmith Warning Notes

---

develop/tutorials/articles/02-from-liferay-6-to-liferay-7/07-upgrading-plugins-to-liferay-7/02-resolving-a-plugins-dependencies.markdown

https://issues.liferay.com/browse/LRDOCS-3632

LRDOCS-3632 Fix system package Bnd file location

---

develop/tutorials/articles-dxp/100-tooling/08-deployment-helper/00-deployment-helper-intro.markdown

https://issues.liferay.com/browse/LRDOCS-3589

LRDOCS-3589 Deployment Helper

---

develop/tutorials/articles/120-service-builder/02-service-builder-persistence/05-developing-custom-sql-queries.markdown
develop/tutorials/articles/120-service-builder/02-service-builder-persistence/06-leveraging-hibernates-criteria-api.markdown

/cc @migue
https://issues.liferay.com/browse/LRDOCS-3623

LRDOCS-3623 SB Finder Changes

---

develop/tutorials/articles/180-configuration/02-implementing-configuration-actions.markdown
develop/tutorials/articles/460-customizable-web-applications/01-providing-portlets-to-manage-requests.markdown
discover/deployment/articles/06-upgrading-liferay/00-upgrading-liferay-intro.markdown

liferay#244
liferay#273
liferay#280
Can you also please close liferay#258? Russ fixed this a while back.
Thanks!

Typo Fixes

---

develop/tutorials/articles/114-workflow/designing-workflow-definitions.markdown
develop/tutorials/articles/131-modularization-with-osgi-plugins/00-developing-osgi-plugins-for-liferay-intro.markdown

Fix Typos | 6.2.x

---

develop/tutorials/articles/11-apis/06-json-web-services.markdown

Fix Typos | 6.1.x

---

develop/tutorials/articles/130-web-services/01-service-builder-web-services/01-creating-remote-services.markdown

Fix: refer to app that matches the example code

---

discover/portal/articles/03-collaboration/02-collaborating/01-publishing-blogs.markdown

@sez11a feature was released as part of FP13 and will be available in the upcoming CE GA4 release. I've added a note to specify that. This update is ready to be published. thx!

LRDOCS-3203 blogs friendly urls

---

develop/reference/articles/10-gradle/15-node-gradle-plugin.markdown

liferay#296
Reviewed in Ithildir/liferay-portal#689
https://issues.liferay.com/browse/LRDOCS-3663

LRDOCS-3663 Node Gradle Update

---

develop/tutorials/articles/110-portlets/00-portlets-intro.markdown
develop/tutorials/articles/110-portlets/01-liferay-mvc-portlet/01-creating-an-mvc-portlet.markdown
develop/tutorials/articles/110-portlets/01-liferay-mvc-portlet/02-mvc-action-command.markdown
develop/tutorials/articles/110-portlets/01-liferay-mvc-portlet/03-mvc-render-command.markdown
develop/tutorials/articles/110-portlets/01-liferay-mvc-portlet/04-mvc-resource-command.markdown
develop/tutorials/articles/110-portlets/02-liferay-soy-portlet/01-creating-a-soy-portlet.markdown
develop/tutorials/articles/110-portlets/03-spring-mvc/00-spring-mvc-intro.markdown
develop/tutorials/articles/110-portlets/08-friendly-urls/00-making-urls-friendlier-intro.markdown
develop/tutorials/articles/110-portlets/12-automatic-single-page-application.markdown

https://issues.liferay.com/browse/LRDOCS-3668

LRDOCS-3668 add/update links to Javadoc and code

---

discover/portal/articles/07-setting-up-liferay/07-configuring-form-navigator-forms.markdown

LRDOCS-3671 added use case to User Guide doc

---

develop/reference/articles/100-felix-gogo-shell.markdown

Recommended by suggestion on LDN
https://issues.liferay.com/browse/LRDOCS-3680

LRDOCS-3680 Add 'scr:info' command to Felix Gogo article

---

develop/tutorials/articles/180-configuration/01-making-apps-configurable.markdown

https://issues.liferay.com/browse/LRDOCS-3679

LRDOCS-3679 Update reference to the module and remove pre-release text

---

develop/reference/articles/09-liferay-faces/03-understanding-liferay-faces-alloy.markdown
develop/reference/articles/09-liferay-faces/04-understanding-liferay-faces-portal.markdown
develop/tutorials/articles/100-tooling/02-liferay-ide/02-creating-a-liferay-workspace-with-liferay-ide.markdown
develop/tutorials/articles/110-portlets/04-jsf/01-generating-a-jsf-application.markdown
develop/tutorials/articles/110-portlets/04-jsf/02-creating-a-jsf-project-manually.markdown
develop/tutorials/articles/300-osgi-basics/02-using-the-wab-generator.markdown

https://issues.liferay.com/browse/LRDOCS-3677

LRDOCS-3677 JSF Portlet Links

---

develop/tutorials/articles/180-configuration/01-making-apps-configurable.markdown

https://issues.liferay.com/browse/LRDOCS-3687 cc: @JorgeFerrer

LRDOCS-3687, use ConfigurableUtil to create configurations

---

develop/reference/articles/11-maven/service-builder-with-maven.markdown
develop/reference/articles/12-project-templates/18-service-builder-template.markdown
develop/tutorials/articles/100-tooling/05-maven/07-using-service-builder-in-a-maven-project.markdown
develop/tutorials/articles/120-service-builder/02-service-builder-persistence/02-running-service-builder-and-understanding-the-generated-code.markdown

https://issues.liferay.com/browse/LRDOCS-3676
https://issues.liferay.com/browse/LRDOCS-3697

LRDOCS-3697 SB/Maven documentation Updates

---

develop/tutorials/articles/180-configuration/01-making-apps-configurable.markdown
develop/tutorials/articles/180-configuration/02-implementing-configuration-actions.markdown

Additional ConfigurableUtil Updates

---

develop/tutorials/articles/123-mobile-sdk/11-building-mobile-sdks.markdown

Updates to Mobile SDK tutorial for 6.2

LRDOCS-3645 Mobile SDK Builder 6.2

---

discover/portal/articles/02-web-experience-management/03-staging-content-for-publication/01-enabling-staging.markdown

liferay#303
https://issues.liferay.com/browse/LRDOCS-3750
Reviewed by @matethurzo

LRDOCS-3750 Remote staging Updates

---

develop/tutorials/articles/111-customizing/01-overriding-core-jsps.markdown

https://issues.liferay.com/browse/LRDOCS-3777

LRDOCS-3777 Note core JSPs that are now inlined and how to use them

---

develop/reference/articles/200-breaking-changes.markdown

liferay#301
Confirmed with Julio and also sent to BChan: brianchandotcom/liferay-portal#49840

Breaking Change Update

---

develop/tutorials/articles/100-tooling/03-blade-cli/01-installing-blade-cli.markdown
develop/tutorials/articles/100-tooling/03-blade-cli/07-updating-blade-cli.markdown

https://issues.liferay.com/browse/LRDOCS-3762

LRDOCS-3762 Split Blade CLI install and update tutorials

---

distribute/publish/articles/01-publishing-your-app/04-understanding-the-app-review-process.markdown

Update 04-understanding-the-app-review-process.markdown
Thanks @lionah  !

Minor update to Marketplace app review article

---

develop/tutorials/articles/02-from-liferay-6-to-liferay-7/08-optimizing-existing-plugins-for-liferay-7/00-optimizing-plugins-for-liferay-7-intro.markdown

@sez11a note that I am still refactoring the existing Lexicon tutorial, so it will still say Lexicon for the moment.

LRDOCS-2963 linked to Clay tutorial in optimizing plugins intro.

---

develop/tutorials/articles/02-from-liferay-6-to-liferay-7/07-upgrading-plugins-to-liferay-7/05-upgrading-hook-plugins/00-upgrading-hook-plugins-intro.markdown
develop/tutorials/articles/02-from-liferay-6-to-liferay-7/07-upgrading-plugins-to-liferay-7/05-upgrading-hook-plugins/01-upgrading-core-jsp-hooks.markdown
develop/tutorials/articles/02-from-liferay-6-to-liferay-7/07-upgrading-plugins-to-liferay-7/05-upgrading-hook-plugins/02-upgrading-app-jsp-hooks.markdown
develop/tutorials/articles/02-from-liferay-6-to-liferay-7/07-upgrading-plugins-to-liferay-7/05-upgrading-hook-plugins/03-upgrading-service-wrappers.markdown
develop/tutorials/articles/02-from-liferay-6-to-liferay-7/07-upgrading-plugins-to-liferay-7/05-upgrading-hook-plugins/06-upgrading-model-listener-hooks.markdown
develop/tutorials/articles/02-from-liferay-6-to-liferay-7/07-upgrading-plugins-to-liferay-7/05-upgrading-hook-plugins/07-upgrading-servlet-filter-hooks.markdown
develop/tutorials/articles/02-from-liferay-6-to-liferay-7/07-upgrading-plugins-to-liferay-7/05-upgrading-hook-plugins/08-upgrading-portal-property-and-event-action-hooks.markdown

I messed up the IDE token. So it's _@liferay-ide@_ instead of _Liferay IDE_, or _Liferay Developer Studio_. sorry.
Can you merge and re-import?

Correct token from @liferay-ide@ to "Liferay @ide@"

---

develop/tutorials/articles/160-import-export-and-staging/04-creating-staged-models-manually.markdown

https://issues.liferay.com/browse/LRDOCS-3761

LRDOCS-3761 Clarify Staging example

---

discover/portal/articles/02-web-experience-management/04-publishing-content-dynamically/04-searching-for-content.markdown

https://issues.liferay.com/browse/LRDOCS-3753

LRDOCS-3753, note on unavailability of Lucene syntax

---

develop/reference/articles/10-gradle/00-intro.markdown
develop/tutorials/articles/100-tooling/04-liferay-workspace/04-development-lifecycle-for-liferay-workspaces.markdown

https://issues.liferay.com/browse/LRDOCS-3802

LRDOCS-3802 Gradle plugins are automatically applied to Workspace

---

discover/portal/articles/02-web-experience-management/02-creating-web-content/02-designing-uniform-content.markdown

New Localizable field

---

develop/reference/articles/12-project-templates/13-portlet-configuration-icon-template.markdown
develop/reference/articles/12-project-templates/15-portlet-toolbar-contributor-template.markdown
develop/reference/articles/12-project-templates/20-simulation-panel-entry-template.markdown
develop/reference/articles/12-project-templates/22-template-context-contributor-template.markdown
develop/reference/articles/13-sample-modules/01-control-menu-entry.markdown
develop/reference/articles/13-sample-modules/02-core-jsp-hook.markdown
develop/reference/articles/13-sample-modules/03-document-action.markdown
develop/reference/articles/13-sample-modules/04-language.markdown
develop/reference/articles/13-sample-modules/05-language-web.markdown
develop/reference/articles/13-sample-modules/06-screen-name-validator.markdown
develop/reference/articles/13-sample-modules/07-spring-mvc-portlet.markdown
develop/reference/articles/13-sample-modules/08-template-context-contributor.markdown
develop/reference/articles/13-sample-modules/09-theme-contributor.markdown
develop/reference/articles/13-sample-modules/10-theme.markdown
develop/tutorials/articles/02-from-liferay-6-to-liferay-7/07-upgrading-plugins-to-liferay-7/05-upgrading-hook-plugins/04-upgrading-core-language-key-override-hooks.markdown
develop/tutorials/articles/02-from-liferay-6-to-liferay-7/07-upgrading-plugins-to-liferay-7/05-upgrading-hook-plugins/05-upgrading-portlet-language-key-hooks.markdown
develop/tutorials/articles/100-tooling/03-blade-cli/04-creating-modules-with-blade-cli.markdown
develop/tutorials/articles/111-customizing/01-overriding-core-jsps.markdown
develop/tutorials/articles/111-customizing/02-overriding-app-jsps.markdown
develop/tutorials/articles/120-service-builder/01-introduction-to-service-builder/01-introduction-to-service-builder-intro.markdown

Please publish at your earliest convenience. Thanks!
/cc @gamerson
https://issues.liferay.com/browse/LRDOCS-3781

LRDOCS-3781 Adapt Blade Sample docs to new "self documenting" structure

---

discover/portal/articles-dxp/04-business-productivity/03-using-workflow/03-kaleo-forms.markdown

misuse of the @product@ token. cc @natocesarrego

minor fix to recently merged kaleo forms note

---

discover/portal/articles/02-web-experience-management/03-staging-content-for-publication/01-enabling-staging.markdown

This PR supercedes sez11a#2395.

LRDOCS-3803 Remote Staging Improvements

---

develop/tutorials/articles/270-product-navigation/01-customizing-the-product-menu.markdown

https://issues.liferay.com/browse/LRDOCS-3826

LRDOCS-3826 Fix Javadoc links

---

discover/portal/articles/03-collaboration/02-collaborating/04-working-together-with-the-wiki.markdown

@sez11a app was released. Please publish as soon as you are able. thx!

LRDOCS-2876 added JSPWiki info back to note.

---

develop/tutorials/articles/100-tooling/05-maven/10-maven-workspace.markdown

https://issues.liferay.com/browse/LRDOCS-3823

LRDOCS-3823 Remove unused Maven Workspace package option

---

develop/tutorials/articles/02-from-liferay-6-to-liferay-7/07-upgrading-plugins-to-liferay-7/03-upgrading-the-liferay-maven-build.markdown
develop/tutorials/articles/100-tooling/05-maven/08-compiling-sass-files-in-a-maven-project.markdown
develop/tutorials/articles/100-tooling/05-maven/09-building-themes-in-a-maven-project.markdown

https://issues.liferay.com/browse/LRDOCS-3619

LRDOCS-3619 Rename Maven goals for building CSS/themes

---

develop/tutorials/articles/100-tooling/04-liferay-workspace/02-configuring-a-liferay-workspace.markdown

https://issues.liferay.com/browse/LRDOCS-3834

LRDOCS-3834 Gradle Local Properties file configured automatically

---

develop/tutorials/articles/270-product-navigation/01-customizing-the-product-menu.markdown
develop/tutorials/articles/270-product-navigation/02-customizing-the-control-menu.markdown
develop/tutorials/articles/270-product-navigation/03-extending-the-simulation-menu.markdown
develop/tutorials/articles/270-product-navigation/04-providing-the-user-personal-bar.markdown

https://issues.liferay.com/browse/LRDOCS-3833

LRDOCS-3833 Clarify steps for Product Navigation tutorials

---

develop/tutorials/articles-dxp/100-tooling/02-liferay-ide/01-installing-liferay-ide.markdown
develop/tutorials/articles/100-tooling/04-liferay-workspace/01-installing-liferay-workspace.markdown

https://issues.liferay.com/browse/LRDOCS-3836

LRDOCS-3836 IDE/Workspace Installer Token (and workaround)

---

develop/tutorials/articles/02-from-liferay-6-to-liferay-7/07-upgrading-plugins-to-liferay-7/04-upgrading-portlet-plugins/03-upgrading-a-liferay-mvcportlet.markdown

Fix sidebar so that the text following the intended sidebar is not included in the sidebar.

LRDOCS-2303 Fix sidebar formatting

---

discover/portal/articles/03-collaboration/03-social-networking/04-integrating-with-facebook-and-more.markdown

@sez11a This app is about to release. Can you please publish the docs as soon as possible. Thx!

LRDOCS-3222 added Twitter section back to social network integration guide

---

develop/tutorials/articles/01-introduction-to-liferay-development/30-starting-module-development/00-starting-module-development-intro.markdown
develop/tutorials/articles/100-tooling/03-blade-cli/05-deploying-modules-with-blade-cli.markdown

https://issues.liferay.com/browse/LRDOCS-3864

LRDOCS-3864 Blade deploy -p option temporarily removed

---

discover/portal/articles/05-managing-users/05-roles-and-permissions.markdown

https://issues.liferay.com/browse/LRDOCS-3869, Fixed link to point to 7.0 article.

LRDOCS-3869

---

develop/reference/articles/11-maven/service-builder-plugin.markdown
develop/reference/articles/11-maven/source-formatter-plugin.markdown
develop/tutorials/articles/100-tooling/05-maven/07-using-service-builder-in-a-maven-project.markdown
develop/tutorials/articles/100-tooling/05-maven/08-compiling-sass-files-in-a-maven-project.markdown
develop/tutorials/articles/100-tooling/05-maven/09-building-themes-in-a-maven-project.markdown

https://issues.liferay.com/browse/LRDOCS-3809
https://issues.liferay.com/browse/LRDOCS-3899

LRDOCS-3809 Maven reference docs (SF and SB plugins)

---

develop/tutorials/articles-dxp/100-tooling/02-liferay-ide/01-installing-liferay-ide.markdown
develop/tutorials/articles/100-tooling/04-liferay-workspace/01-installing-liferay-workspace.markdown

https://issues.liferay.com/browse/LRDOCS-3903

LRDOCS-3903 Installer now creates ~/.liferay folder automatically

---

develop/reference/articles/12-project-templates/06-control-menu-entry-template.markdown
develop/reference/articles/12-project-templates/23-spring-mvc-portlet-template.markdown
develop/reference/articles/12-project-templates/25-theme-template.markdown

Thanks to @mwilliams2014 for spotting the theme template typos!

Project template doc updates

---

develop/reference/articles/11-maven/theme-builder-plugin.markdown

https://issues.liferay.com/browse/LRDOCS-3907

LRDOCS-3907 Theme Builder Maven ref doc

---

develop/tutorials/articles/110-portlets/02-liferay-soy-portlet/01-creating-a-soy-portlet.markdown

LRDOCS-3913 soy portlet fix

---

develop/tutorials/articles/03-developing-a-web-application/06-displaying-messages-errors/00-intro.markdown
develop/tutorials/articles/03-developing-a-web-application/06-displaying-messages-errors/01-creating-language-keys.markdown
develop/tutorials/articles/03-developing-a-web-application/06-displaying-messages-errors/02-adding-error-messages.markdown
develop/tutorials/articles/03-developing-a-web-application/06-displaying-messages-errors/03-adding-messages-jsp.markdown
develop/tutorials/articles/03-developing-a-web-application/06-permissions/00-permissions-intro.markdown
develop/tutorials/articles/03-developing-a-web-application/06-permissions/01-configuring-resources.markdown
develop/tutorials/articles/03-developing-a-web-application/06-permissions/02-permissions-service-layer.markdown
develop/tutorials/articles/03-developing-a-web-application/06-permissions/03-creating-permissions-helper-classes.markdown
develop/tutorials/articles/03-developing-a-web-application/06-permissions/04-permissions-jsps.markdown

@sez11a here are the styles for the latest sections.

LRDOCS-3842 added markup for MVC Learning Path Permissions and Messages and Errors sections

---

develop/tutorials/articles/111-customizing/08-overriding-mvc-commands.markdown

https://issues.liferay.com/browse/LRDOCS-3916

LRDOCS-3916 fix example for overriding mvcactioncommands

---

develop/tutorials/articles/110-portlets/02-liferay-soy-portlet/01-creating-a-soy-portlet.markdown

@sez11a this fixes the SF issues introduced by the Atom editor.

LRDOCS-3913 soy portlet SF fix

---

discover/deployment/articles-dxp/02-installing-liferay/10-trial-plugin-installation.markdown

https://issues.liferay.com/browse/LRDOCS-3932 fixed trailing spaces issue in trial plugin article.

LRDOCS-3932

---

develop/tutorials/articles/260-themes-and-layout-templates/02-themes-generator.markdown

LRDOCS-3933 added note and updated version

---

discover/deployment/articles/06-upgrading-liferay/03-running-the-upgrade-process.markdown

https://issues.liferay.com/browse/LRDOCS-3937

LRDOCS-3937 On Windows, execute the upgrade command in the JAR's folder

---

develop/tutorials/articles/03-developing-a-web-application/07-search-and-indexing/00-intro.markdown
develop/tutorials/articles/03-developing-a-web-application/07-search-and-indexing/01-enabling-search-and-indexing-for-guestbooks/00-intro.markdown
develop/tutorials/articles/03-developing-a-web-application/07-search-and-indexing/01-enabling-search-and-indexing-for-guestbooks/01-understanding-search-and-indexing.markdown
develop/tutorials/articles/03-developing-a-web-application/07-search-and-indexing/01-enabling-search-and-indexing-for-guestbooks/02-creating-a-guestbook-indexer.markdown
develop/tutorials/articles/03-developing-a-web-application/07-search-and-indexing/01-enabling-search-and-indexing-for-guestbooks/03-handling-indexing-in-the-guestbook-service-layer.markdown
develop/tutorials/articles/03-developing-a-web-application/07-search-and-indexing/02-enabling-search-and-indexing-for-guestbook-entries/00-intro.markdown
develop/tutorials/articles/03-developing-a-web-application/07-search-and-indexing/02-enabling-search-and-indexing-for-guestbook-entries/01-creating-an-entry-indexer.markdown
develop/tutorials/articles/03-developing-a-web-application/07-search-and-indexing/02-enabling-search-and-indexing-for-guestbook-entries/02-handling-indexing-in-the-entry-service-layer.markdown
develop/tutorials/articles/03-developing-a-web-application/07-search-and-indexing/03-updating-your-user-interface-for-search/00-intro.markdown
develop/tutorials/articles/03-developing-a-web-application/07-search-and-indexing/03-updating-your-user-interface-for-search/01-adding-a-search-bar-to-the-guestbook-portlet.markdown
develop/tutorials/articles/03-developing-a-web-application/07-search-and-indexing/03-updating-your-user-interface-for-search/02-creating-a-search-results-jsp-for-the-guestbook-portlet.markdown

@sez11a I've merged in Nick's wordsmithing and added my changes on top to avoid merge conflicts.
I added the "Let's Go!" button to each section's intro. Please let me know if you want to make the sub-intros all steps instead. Thx!

LRDOCS-3842 learn path styles applied

---

discover/portal/articles/02-web-experience-management/01-starting-site-development/02-creating-and-managing-pages.markdown

@sez11a these changes are for the Liferay Layout Templates app, which hasn't been released yet. Please review and return for holding. Thx!

LRDOCS-3930 added note about Layout Templates app and updated links

---

develop/tutorials/articles/260-themes-and-layout-templates/04-creating-layout-templates-manually.markdown

LRDOCS-3678 layout template look and feel

---

develop/tutorials/articles/100-tooling/05-maven/08-compiling-sass-files-in-a-maven-project.markdown

https://issues.liferay.com/browse/LRDOCS-3955

LRDOCS-3955 Fix CSS Builder's Sass compiler tag

---

develop/reference/articles/10-gradle/05-css-builder-gradle-plugin.markdown

https://issues.liferay.com/browse/LRDOCS-3956

LRDOCS-3956 Be specific about how to change compiler for CSS Builder

---

develop/tutorials/articles/190-social/03-ratings/00-ratings-intro.markdown
develop/tutorials/articles/190-social/03-ratings/01-ratings-assets.markdown

@sez11a this fixes broken URLs for comments tutorial and fixes product token typo.

LRDOCS-2420 fix broken URLs and token typo

---

develop/reference/articles/10-gradle/05-css-builder-gradle-plugin.markdown

https://issues.liferay.com/browse/LRDOCS-3981

LRDOCS-3981 Compiling Sass using Ruby (Gradle)

---

develop/reference/articles/13-sample-modules/extensions/01-control-menu-entry.markdown
develop/tutorials/articles/270-product-navigation/02-customizing-the-control-menu.markdown

https://issues.liferay.com/browse/LRDOCS-3954

LRDOCS-3954 Control Menu Entry Updates

---

develop/tutorials/articles/100-tooling/05-maven/10-maven-workspace.markdown

https://issues.liferay.com/browse/LRDOCS-3991

LRDOCS-3991 Use latest Bundle Support version to specify custom bundle URL

---

develop/tutorials/articles/03-developing-a-web-application/02-creating-working-prototype/00-creating-a-working-prototype-intro.markdown
develop/tutorials/articles/260-themes-and-layout-templates/04-lexicon/00-lexicon-and-themes-intro.markdown
develop/tutorials/articles/260-themes-and-layout-templates/04-lexicon/01-importing-lexicon-css-in-a-theme.markdown

LRDOCS-3987 marcos Lexicon CSS Updates

---

discover/portal/articles/07-targeting-content-to-your-audience/01-installation-and-uninstallation.markdown

liferay#294
Reviewed by Eduardo

AT Community Submission

---

develop/tutorials/articles/02-from-liferay-6-to-liferay-7/07-upgrading-plugins-to-liferay-7/06-upgrading-themes/00-upgrading-themes-intro.markdown
develop/tutorials/articles/02-from-liferay-6-to-liferay-7/07-upgrading-plugins-to-liferay-7/06-upgrading-themes/01-upgrading-liferay-6-themes.markdown
develop/tutorials/articles/02-from-liferay-6-to-liferay-7/07-upgrading-plugins-to-liferay-7/06-upgrading-themes/02-upgrading-themes.markdown

@sez11a this reorganizes the upgrading themes tutorials into their own section. Please remove the existing upgrading themes tutorials so they're not duplicated. thx!

LRDOCS-3598 upgrading themes reorg 7.0.x

---

develop/tutorials/articles/100-tooling/03-blade-cli/05-deploying-modules-with-blade-cli.markdown

https://issues.liferay.com/browse/LRDOCS-4020

LRDOCS-4020 "blade deploy" only for JARs

---

develop/tutorials/articles-dxp/02-from-liferay-6-to-liferay-7/09-customization-with-ext-plugins/09-customization-with-ext-plugins-intro.markdown
develop/tutorials/articles-dxp/310-troubleshooting/14-patching-and-debugging-portal-source-code.markdown
develop/tutorials/articles/310-troubleshooting/13-config-files.markdown
discover/reference/.METADATA

https://issues.liferay.com/browse/LRDOCS-4030

LRDOCS-4030 Incorrect licensing info removed from DXP doc

---

develop/tutorials/articles/03-developing-a-web-application/11-workflow/00-intro.markdown
develop/tutorials/articles/03-developing-a-web-application/11-workflow/01-supporting-workflow-status/00-enabling-workflow-service-layer-intro.markdown
develop/tutorials/articles/03-developing-a-web-application/11-workflow/01-supporting-workflow-status/01-setting-guestbook-status.markdown
develop/tutorials/articles/03-developing-a-web-application/11-workflow/01-supporting-workflow-status/02-setting-entry-status.markdown
develop/tutorials/articles/03-developing-a-web-application/11-workflow/01-supporting-workflow-status/03-finding-entities-by-status.markdown
develop/tutorials/articles/03-developing-a-web-application/11-workflow/02-workflow-handlers/00-implementing-workflow-handlers-intro.markdown
develop/tutorials/articles/03-developing-a-web-application/11-workflow/02-workflow-handlers/01-guestbook-workflow-handlers.markdown
develop/tutorials/articles/03-developing-a-web-application/11-workflow/02-workflow-handlers/02-entry-workflow-handlers.markdown
develop/tutorials/articles/03-developing-a-web-application/11-workflow/03-displaying-approved-items/00-displaying-approved-workflow-items-intro.markdown
develop/tutorials/articles/03-developing-a-web-application/11-workflow/03-displaying-approved-items/01-displaying-status-guestbook-admin.markdown
develop/tutorials/articles/03-developing-a-web-application/11-workflow/03-displaying-approved-items/02-displaying-approved-entries.markdown

@sez11a here is the Learning Path markup for the Workflow section

LRDOCS-3482 added markup to workflow section

---

develop/tutorials/articles-dxp/310-troubleshooting/14-patching-and-debugging-portal-source-code.markdown
develop/tutorials/articles/230-wysiwyg-editors/02-modifying-an-editor-configuration.markdown
develop/tutorials/articles/310-troubleshooting/13-config-files.markdown
discover/reference/.METADATA

Verified by Chema.
https://issues.liferay.com/browse/LRDOCS-4026

LRDOCS-4026 WYSIWYG toolbar config only applicable to AlloyEditor

---

discover/portal/articles/03-collaboration/01-managing-documents-and-media/03-liferay-repository-types.markdown

Core Infra Support requested this limitation and suggested alternative be documented.
cc/ @ngaskill
https://issues.liferay.com/browse/LRDOCS-4031

LRDOCS-4031 Describe DBStore's file size limitation and alternative

---

discover/deployment/articles/08-liferay-enterprise-search/02-configuring-elasticsearch.markdown

https://issues.liferay.com/browse/LRDOCS-4034

LRDOCS-4034, fix link

---

discover/portal/articles/02-web-experience-management/03-staging-content-for-publication/99-whats-expected-from-staging.markdown

This is only a fraction of the testing results that I plan on documenting for Staging. Therefore, please leave the ticket open. I wanted to send a preliminary PR to you for one area (Web Content) and see if you agree with the way I've set this up before finishing the rest.
I'll plan to break this task into multiple parts (PRs). Please publish if you approve this. Thanks!
https://issues.liferay.com/browse/LRDOCS-3996

LRDOCS-3996 Staging Triage Reference Doc

---

develop/tutorials/articles/270-product-navigation/04-providing-the-user-personal-bar.markdown

https://issues.liferay.com/browse/LRDOCS-4041
liferay#339

LRDOCS-4041 User personal bar updates

---

develop/tutorials/articles/106-jsf-portlets-with-liferay-faces/05-understanding-the-liferay-faces-version-scheme.markdown

https://issues.liferay.com/browse/LRDOCS-4042
https://issues.liferay.com/browse/LRDOCS-4043

LRDOCS-4042 Update Faces version scheme | 6.2.x

---

develop/reference/articles/09-liferay-faces/01-liferay-faces-version-scheme.markdown

https://issues.liferay.com/browse/LRDOCS-4042
https://issues.liferay.com/browse/LRDOCS-4043

LRDOCS-4042 Update Faces version scheme | 7.0.x

---

discover/deployment/articles/04-managing-liferay-with-liferay-connected-services/03-using-lcs.markdown

Porting change from below PR to 6.2
https://github.com/sez11a/liferay-docs/pull/2634

LRDOCS-4057 adding note about token credentials to LCS docs

---

develop/tutorials/articles/112-application-display-templates/01-implementing-application-display-templates.markdown

https://issues.liferay.com/browse/LRDOCS-4019

LRDOCS-4019 added missing step for ADT dev

---

develop/tutorials/articles/310-troubleshooting/15-server-startup-with-no-database-connection.markdown

New troubleshooting article
https://issues.liferay.com/browse/LRDOCS-3948

LRDOCS-3948 Portal init failed; database not ready

---

develop/reference/articles/13-sample-projects/apps/05-spring-mvc-portlet.markdown

https://issues.liferay.com/browse/LRDOCS-4055

LRDOCS-4055 Building Maven samples that depend on other samples

---

develop/tutorials/articles/240-javascript-module-loaders/10-liferay-amd-module-loader.markdown

https://github.com/liferay/liferay-docs/pull/344
the module that the user requests doesn't match the trigger in line no. 62

Module Name Mismatch Fix

---

discover/portal/articles/07-setting-up-liferay/01-system-settings/03-environment-variables.markdown

https://issues.liferay.com/browse/LRDOCS-3947

Using environment variables to override portal properties

---

develop/tutorials/articles/120-service-builder/02-service-builder-persistence/08-connecting-service-builder-to-external-data-sources.markdown

Only one data source can be used with Service Builder in a module.

Note one data soruce per Service Builder module

---

develop/reference/articles/13-sample-projects/01-apps/02-npm-samples/01-angular-npm-portlet.markdown
develop/reference/articles/13-sample-projects/01-apps/02-npm-samples/02-billboardjs-npm-portlet.markdown
develop/reference/articles/13-sample-projects/01-apps/02-npm-samples/03-isomorphic-npm-portlet.markdown
develop/reference/articles/13-sample-projects/01-apps/02-npm-samples/04-jquery-npm-portlet.markdown
develop/reference/articles/13-sample-projects/01-apps/02-npm-samples/05-metaljs-npm-portlet.markdown
develop/reference/articles/13-sample-projects/01-apps/02-npm-samples/06-react-npm-portlet.markdown
develop/reference/articles/13-sample-projects/01-apps/02-npm-samples/07-simple-npm-portlet.markdown
develop/reference/articles/13-sample-projects/01-apps/02-npm-samples/08-vuejs-npm-portlet.markdown
develop/tutorials/articles/110-portlets/15-javascript/04-npm/00-npm-portlets-intro.markdown

LRDOCS-4006 intro URL edit

---

develop/reference/articles/10-gradle/05-css-builder-gradle-plugin.markdown

https://issues.liferay.com/browse/LRDOCS-4073

LRDOCS-4073 CSS Builder note when using Ruby compiler

---

discover/portal/articles/17-using-the-control-panel/05-server-administration.markdown

https://issues.liferay.com/browse/LRDOCS-3600

LRDOCS-3600 expanded the instructions and clarified paths and requirements

---

develop/reference/articles/13-sample-projects/01-apps/05-spring-mvc-portlet.markdown
develop/tutorials/articles/120-service-builder/01-introduction-to-service-builder/01-introduction-to-service-builder-intro.markdown
develop/tutorials/articles/120-service-builder/02-service-builder-persistence/06-leveraging-hibernates-criteria-api.markdown

https://issues.liferay.com/browse/LRDOCS-4076

LRDOCS-4076 Update Blade SB sample names/URLs

---

develop/tutorials/articles/140-assets/05-rendering-an-asset.markdown

I think this more clearly delineates the specific requirements (a noninstanceable portlet) from the recommendation of what to add if you don't have one.

Lrdocs 3792 asset limitations

---

develop/tutorials/articles/310-troubleshooting/12-unresolved-osgi-components.markdown

Added section headers and cross references
https://issues.liferay.com/browse/LRDOCS-4081

LRDOCS-4081 Make component detection features more prominent

---

develop/tutorials/articles/03-jsf/02-writing-a-data-driven-jsf-application/02-integrating-your-persistence-framework.markdown

LRDOCS-4086 JSF Clarification

---

develop/tutorials/articles/180-configuration/01-making-apps-configurable.markdown

This PR addresses liferay#346.
The following PRs can be closed since they've already been resolved:
- liferay#265
- liferay#336
Thanks!

Liferay PRs

---

discover/deployment/articles/06-upgrading-liferay/05-upgrading-social-office.markdown

Adding link to Chat CE app in Social Office upgrade doc

LRDOCS-4088 small change to social office upgrade doc

---

develop/tutorials/articles-dxp/100-tooling/02-liferay-ide/01-installing-liferay-ide.markdown

https://issues.liferay.com/browse/LRDOCS-4087

LRDOCS-4087 Workspace token generation has been improved

---

discover/portal/articles/02-web-experience-management/02-creating-web-content/01-publishing-basic-web-content.markdown

https://issues.liferay.com/browse/LRDOCS-1870

LRDOCS-1870 Web Content Permission check

---

discover/portal/articles/02-web-content-management/04-features-of-liferays-wcm.markdown

https://issues.liferay.com/browse/LRDOCS-1870

LRDOCS-1870 6.2.x update added instructions

---

develop/reference/articles/11-maven/db-support-plugin.markdown
develop/tutorials/articles/120-service-builder/02-service-builder-persistence/02-running-service-builder-and-understanding-the-generated-code.markdown

https://issues.liferay.com/browse/LRDOCS-4098

DB Support Maven Plugin

---

develop/tutorials/articles/300-osgi-basics/05-using-the-wab-generator.markdown

https://issues.liferay.com/browse/LRDOCS-4096

LRDOCS-4096 Clarify package detection for generating WABs. Mention LPS ticket

---

discover/deployment/articles-dxp/03-configuring-liferay/06-securing-liferay/01-saml/01-setting-up-identity-provider.markdown
discover/deployment/articles-dxp/03-configuring-liferay/06-securing-liferay/01-saml/02-setting-up-service-provider.markdown
discover/deployment/articles-dxp/03-configuring-liferay/06-securing-liferay/01-saml/03-configuring-saml.markdown

Hi Rich. Please see below for my SME review rebased on top of Daniel's changes.
/cc @topolik @csierra

SME review of SAML Provider 3.1 documentation

---

develop/reference/articles/200-breaking-changes.markdown

Updated and confirmed in brianchandotcom/liferay-portal#53507

New breaking change

---

develop/tutorials/articles/260-themes-and-layout-templates/01-themes/01-themes-generator.markdown

https://issues.liferay.com/browse/LRDOCS-4113

LRDOCS-4113 Don't extend theme implementations such as the Classic theme

---

.gitignore

Add .directory to .gitignore, like I did for master.

Add .directory to .gitignore

---

develop/tutorials/articles/01-introduction-to-liferay-development/30-starting-module-development/00-starting-module-development-intro.markdown
develop/tutorials/articles/100-tooling/03-blade-cli/05-deploying-modules-with-blade-cli.markdown

https://issues.liferay.com/browse/LRDOCS-4105
/cc @rbohl In case you were still interested in this.

LRDOCS-4105 Blade deploy

---

discover/portal/articles-dxp/08-targeting-content-to-your-audience/03-using-the-audience-targeting-applications.markdown

https://issues.liferay.com/browse/LRDOCS-2317

LRDOCS-2317 Asset Publisher with Audience Targeting

---

develop/tutorials/articles/300-osgi-basics/03-adding-third-party-libraries-to-a-module.markdown

https://issues.liferay.com/browse/LRDOCS-4110

LRDOCS-4110 Use compileInclude to embed "optional" dependencies

---

guidelines/05-javadoc-submission-process.markdown

Lrdocs 4100 javadocc submission process

---

develop/tutorials/articles/11-apis/09-device-detection.markdown
discover/portal/articles/05-asset-framework/04-using-the-asset-publisher.markdown

https://issues.liferay.com/browse/LRDOCS-4128
cc/ @mhan810

LRDOCS-4128 6.1 Device recognition update

---

develop/tutorials/articles/260-themes-and-layout-templates/01-themes/05-theme-contributors.markdown

see: https://github.com/mwilliams2014/liferay-docs/pull/129

LRDOCS-4122- pr-129 minor wordsmithing

---

develop/tutorials/articles/250-forms/03-form-navigator-extensions.markdown
develop/tutorials/articles/260-themes-and-layout-templates/03-portlets/03-embedding-portlets-in-themes-and-layout-templates.markdown

URL fixes reported by community

---

guidelines/06-taglibdoc-guidelines.markdown

LRDOCS-4108 taglibdoc guidelines migration

---

develop/tutorials/articles/260-themes-and-layout-templates/01-themes/01-themes-generator.markdown
develop/tutorials/articles/290-modularity-and-osgi/01-the-benefits-of-modularity.markdown

cc @jbalsas cc@robert-frampton

LRDOCS-4132 theme gen theme deps note

---

guidelines/06-javadoc-guidelines.markdown
guidelines/07-advanced-javadoc-guidelines.markdown

https://issues.liferay.com/browse/LRDOCS-4101

LRDOCS-4101 Javadoc Guidelines Markdown Conversion

---

develop/tutorials/articles/02-from-liferay-6-to-liferay-7/09-customization-with-ext-plugins/09-customization-with-ext-plugins-intro.markdown
develop/tutorials/articles/310-troubleshooting/06-adjusting-module-logging.markdown

https://issues.liferay.com/browse/LRDOCS-4115
https://issues.liferay.com/browse/LRDOCS-3628

Logging configuration improvements for modules and portal

---

develop/tutorials/articles/128-customizing-liferay-portal-with-hooks/13-overriding-portal-properties.markdown

https://issues.liferay.com/browse/LRDOCS-3523

LRDOCS-3523 6.2 Tutorial: Overriding Portal Properties

---

develop/tutorials/articles/128-customizing-liferay-portal-with-hooks/02-overriding-web-resources.markdown
develop/tutorials/articles/128-customizing-liferay-portal-with-hooks/03-customizing-jsps-by-extending-the-original.markdown

https://issues.liferay.com/browse/LRDOCS-2089

LRDOCS-2089 Fix 6.2 tutorials: Clear the content cache to invalidate the current JSP

---

develop/tutorials/articles/07-hooks/02-overriding-web-resources.markdown
develop/tutorials/articles/07-hooks/03-customizing-jsps-by-extending-the-original.markdown

https://issues.liferay.com/browse/LRDOCS-2089

LRDOCS-2089 Fix 6.1 tutorials: Clear the content cache to invalidate the current JSP

---

develop/tutorials/articles/110-portlets/02-liferay-soy-portlet/02-soy-portlet-state/03-configuring-state-properties-on-the-client-side.markdown

@sez11a Hopefully this fixes the numbering issue in the tutorial. The formatting seemed correct. The only thing I found was an extra space between steps, so I removed it...

LRDOCS-4084 SF

---

develop/tutorials/articles/200-search/00-intro.markdown

https://issues.liferay.com/browse/LRDOCS-4144

LRDOCS-4144, clarify spell checking behavior

---

discover/deployment/articles-dxp/09-liferay-connected-services/01-lcs-preconfiguration.markdown
discover/deployment/articles-dxp/09-liferay-connected-services/02-activating-your-dxp-server-with-lcs.markdown
discover/deployment/articles-dxp/09-liferay-connected-services/03-using-lcs.markdown

Includes changes for:
- LRDOCS-4137
- LRDOCS-4136
- LRDOCS-4126

Misc changes to LCS docs

---

develop/tutorials/articles/310-troubleshooting/00-troubleshooting-intro.markdown

Tested on dev-uat.
cc @jhinkey

LRDOCS-4166 updated FAQ article to use new toggler script

---

discover/portal/articles/100-web-experience-management/03-staging-content-for-publication/99-whats-expected-from-staging.markdown

The *What's Expected from Staging* article was inadvertently deleted. I've re-added it. Thanks!
/cc @jhinkey

Re-add Staging article that was inadvertently deleted

---

develop/reference/articles/10-gradle/05-css-builder-gradle-plugin.markdown
develop/reference/articles/10-gradle/06-db-support-gradle-plugin.markdown
develop/reference/articles/10-gradle/09-gulp-gradle-plugin.markdown
develop/reference/articles/10-gradle/12-js-module-config-generator-gradle-plugin.markdown
develop/reference/articles/10-gradle/13-js-transpiler-gradle-plugin.markdown
develop/reference/articles/10-gradle/14-jsdoc-gradle-plugin.markdown
develop/reference/articles/10-gradle/15-lang-builder-gradle-plugin.markdown
develop/reference/articles/10-gradle/17-node-gradle-plugin.markdown
develop/reference/articles/10-gradle/18-service-builder-gradle-plugin.markdown
develop/reference/articles/10-gradle/19-source-formatter-gradle-plugin.markdown
develop/reference/articles/10-gradle/24-whip-gradle-plugin.markdown
develop/reference/articles/10-gradle/25-wsdd-builder-gradle-plugin.markdown
develop/reference/articles/10-gradle/26-wsdl-builder-gradle-plugin.markdown
develop/reference/articles/10-gradle/28-xsd-builder-gradle-plugin.markdown
develop/reference/articles/11-maven/service-builder-plugin.markdown
develop/reference/articles/11-maven/source-formatter-plugin.markdown

https://issues.liferay.com/browse/LRDOCS-4503

LRDOCS-4503 Reference plugin updates

---

discover/deployment/articles/02-installing-liferay/00-installing-intro.markdown
discover/deployment/articles/02-installing-liferay/01-preparing-for-install.markdown
discover/deployment/articles/02-installing-liferay/02-installing-liferay-bundle.markdown

Here are the first three installation articles, including the installation intro.
https://issues.liferay.com/browse/LRDOCS-4726
https://issues.liferay.com/browse/LRDOCS-4727
https://issues.liferay.com/browse/LRDOCS-4728
cc/ @rbohl

Deploying Liferay Portal Tier 1 - Core

---

develop/tutorials/articles/15-javascript-module-loaders/00-javascript-module-loaders-intro.markdown
develop/tutorials/articles/15-javascript-module-loaders/03-using-external-libraries.markdown
develop/tutorials/articles/15-javascript-module-loaders/04-loading-modules-with-aui-script-tag.markdown

@sez11a this includes all the tier 1 docs for the JavaScript Module Loader's section:
LRDOCS-4411
LRDOCS-4414
LRDOCS-4415
cc @jbalsas

LRDOCS-4411 JavaScript Module Loaders Tier 1 Docs

---

develop/reference/articles/200-breaking-changes.markdown

Breaking Changes: Links to LPS tickets

---

develop/tutorials/articles/260-themes-and-layout-templates/01-themes/01-themes-generator.markdown

LRDOCS-4725 Remove NODE_PATH variable configuration

---

develop/tutorials/articles/14-themes-and-layout-templates/04-clay-and-themes/00-clay-and-themes-intro.markdown
develop/tutorials/articles/14-themes-and-layout-templates/04-clay-and-themes/01-importing-clay-css-in-a-theme.markdown

@sez11a this includes tickets LRDOCS-4410 and LRDOCS-4723
cc @robert-frampton
cc @jbalsas

LRDOCS-4410 Clay CSS and themes

---

develop/tutorials/articles/02-from-liferay-6-to-liferay-7/07-upgrading-plugins-to-liferay-7/03-upgrading-the-liferay-maven-build.markdown

https://issues.liferay.com/browse/LRDOCS-4246

LRDOCS-4246 Upgrading the Liferay Maven Build

---

develop/tutorials/articles/14-themes-and-layout-templates/01-themes/06-context-contributors.markdown

LRDOCS-4389 Context Contributors

---

develop/reference/articles/10-gradle/05-css-builder-gradle-plugin.markdown
develop/reference/articles/10-gradle/06-db-support-gradle-plugin.markdown
develop/reference/articles/10-gradle/09-gulp-gradle-plugin.markdown
develop/reference/articles/10-gradle/12-js-module-config-generator-gradle-plugin.markdown
develop/reference/articles/10-gradle/13-js-transpiler-gradle-plugin.markdown
develop/reference/articles/10-gradle/14-jsdoc-gradle-plugin.markdown
develop/reference/articles/10-gradle/15-lang-builder-gradle-plugin.markdown
develop/reference/articles/10-gradle/17-node-gradle-plugin.markdown
develop/reference/articles/10-gradle/18-service-builder-gradle-plugin.markdown
develop/reference/articles/10-gradle/19-source-formatter-gradle-plugin.markdown
develop/reference/articles/10-gradle/24-whip-gradle-plugin.markdown
develop/reference/articles/10-gradle/25-wsdd-builder-gradle-plugin.markdown
develop/reference/articles/10-gradle/26-wsdl-builder-gradle-plugin.markdown
develop/reference/articles/10-gradle/28-xsd-builder-gradle-plugin.markdown
develop/reference/articles/11-maven/service-builder-plugin.markdown
develop/reference/articles/11-maven/source-formatter-plugin.markdown
develop/reference/articles/14-third-party-packages-portal-exports.markdown
develop/tutorials/articles/01-introduction-to-liferay-development/40-confinguring-dependencies/00-configuring-dependencies-intro.markdown
develop/tutorials/articles/02-from-liferay-6-to-liferay-7/07-upgrading-plugins-to-liferay-7/02-resolving-a-plugins-dependencies.markdown
develop/tutorials/articles/244-liferay-js-api/01-theme-display.markdown
develop/tutorials/articles/310-troubleshooting/06-adjusting-module-logging.markdown
discover/deployment/articles-dxp/01-introduction/00-intro.markdown
discover/deployment/articles-dxp/03-configuring-liferay/06-securing-liferay/01-saml/00-intro.markdown
discover/deployment/articles-dxp/03-configuring-liferay/06-securing-liferay/01-saml/03-configuring-saml.markdown
discover/deployment/articles-dxp/04-maintaining-liferay/01-patching-liferay/02-patching-liferay.markdown
discover/deployment/articles-dxp/07-monitoring-liferay/00-monitoring-intro.markdown
discover/deployment/articles-dxp/09-liferay-connected-services/01-lcs-preconfiguration.markdown
discover/deployment/articles-dxp/09-liferay-connected-services/03-using-lcs.markdown
discover/portal/articles/100-web-experience-management/03-staging-content-for-publication/99-whats-expected-from-staging.markdown
discover/portal/articles/150-setting-up-liferay/01-system-settings/03-server-admin.markdown

Wordsmithed.
https://issues.liferay.com/browse/LRDOCS-4163

Lrdocs 4163 3rd party packages portal exports

---

develop/reference/articles/200-breaking-changes.markdown

From brianchandotcom/liferay-portal#54878

LPS-63635 New Breaking Change

---

develop/tutorials/articles/14-themes-and-layout-templates/01-themes/15-adding-new-behavior-to-an-editor.markdown

LRDOCS-4398 Adding New Behavior to an Editor

---

develop/tutorials/articles/100-tooling/07-liferay-sample-projects/00-liferay-sample-projects-intro.markdown
develop/tutorials/articles/310-troubleshooting/06-adjusting-module-logging.markdown

https://issues.liferay.com/browse/LRDOCS-4792

LRDOCS-4792 Blade Sample Logging

---

develop/tutorials/articles/07-customizing/00-customizing-intro.markdown
develop/tutorials/articles/07-customizing/06-overriding-liferays-default-yui-and-aui-modules.markdown

@sez11a this includes a port of the intro as well. @jhinkey will most likely update later on.
cc @jbalsas

LRDOCS-4328 Overriding Liferay's Default AUI and YUI Modules

---

develop/tutorials/articles/03-developing-a-web-application/02-creating-working-prototype/08-displaying-guestbook-entries.markdown
develop/tutorials/articles/03-developing-a-web-application/03-generating-the-backend/02-generating-layers.markdown
develop/tutorials/articles/03-developing-a-web-application/04-refactoring-the-prototype/01-folder-structure.markdown
develop/tutorials/articles/03-developing-a-web-application/05-writing-admin-portlet/04-updating-your-service-layer.markdown
develop/tutorials/articles/03-developing-a-web-application/07-displaying-messages-errors/02-adding-error-messages.markdown
develop/tutorials/articles/03-developing-a-web-application/08-search-and-indexing/01-enabling-search-and-indexing-for-guestbooks/02-creating-a-guestbook-indexer.markdown
develop/tutorials/articles/03-developing-a-web-application/08-search-and-indexing/02-enabling-search-and-indexing-for-guestbook-entries/01-creating-an-entry-indexer.markdown
develop/tutorials/articles/03-developing-a-web-application/09-assets/01-enabling-assets-at-the-service-layer/00-intro.markdown
develop/tutorials/articles/03-developing-a-web-application/09-assets/01-enabling-assets-at-the-service-layer/02-handling-assets-at-the-entry-service-layer.markdown
develop/tutorials/articles/03-developing-a-web-application/09-assets/03-adding-asset-features-to-your-user-interface/04-enabling-comments-and-ratings-for-entries.markdown
develop/tutorials/articles/03-developing-a-web-application/10-web-services/01-creating-remote-services.markdown
develop/tutorials/articles/03-developing-a-web-application/11-workflow/00-intro.markdown
develop/tutorials/articles/03-developing-a-web-application/11-workflow/01-supporting-workflow-status/01-setting-guestbook-status.markdown
develop/tutorials/articles/03-developing-a-web-application/11-workflow/01-supporting-workflow-status/03-finding-entities-by-status.markdown

https://issues.liferay.com/browse/LRDOCS-4504
Fixed textual issues that constituted a bug or could cause confusion
Added sidebar offering guidance on import choices
Fixed 1 critical issue described where necessary imports needed to be added to build.gradle earlier

LRDOCS-4504 - Issues with the Guestbook Tutorial

---

develop/tutorials/articles/01-introduction-to-liferay-development/40-confinguring-dependencies/00-configuring-dependencies-intro.markdown
develop/tutorials/articles/02-from-liferay-6-to-liferay-7/07-upgrading-plugins-to-liferay-7/02-resolving-a-plugins-dependencies.markdown
develop/tutorials/articles/300-osgi-basics/06-importing-packages.markdown
develop/tutorials/articles/300-osgi-basics/07-exporting-packages.markdown

Lrdocs 3526 importing and exporting packages

---

discover/deployment/articles/02-installing-liferay/04-installing-liferay-on-tomcat.markdown

Fix Tomcat common.loader property (7.0.x)

---

develop/tutorials/articles/250-forms/01-forms-and-validation.markdown

see https://github.com/liferay/liferay-docs/pull/370

LRDOCS-4821 The fieldName should be namespaced

---

develop/reference/articles/11-maven/bundle-support-plugin.markdown

This will also directly apply to `master` once we're ready to convert developer reference docs for 7.1.
https://issues.liferay.com/browse/LRDOCS-4798

LRDOCS-4798 Bundle Support Maven plugin

---

develop/reference/articles/11-maven/css-builder-plugin.markdown
develop/reference/articles/11-maven/db-support-plugin.markdown
develop/reference/articles/11-maven/deployment-helper-plugin.markdown
develop/reference/articles/11-maven/javadoc-formatter-plugin.markdown
develop/reference/articles/11-maven/lang-builder-plugin.markdown
develop/reference/articles/11-maven/service-builder-plugin.markdown
develop/reference/articles/11-maven/source-formatter-plugin.markdown
develop/reference/articles/11-maven/theme-builder-plugin.markdown
develop/reference/articles/11-maven/tld-formatter-plugin.markdown
develop/reference/articles/11-maven/wsdd-builder-plugin.markdown
develop/reference/articles/11-maven/xml-formatter-plugin.markdown

These will also port to `master` once our reference doc tickets are available. Thanks!
**Lang Builder** - https://issues.liferay.com/browse/LRDOCS-4799
**CSS Builder** - https://issues.liferay.com/browse/LRDOCS-4800
**Deployment Helper** - https://issues.liferay.com/browse/LRDOCS-4802
**Javadoc Formatter** - https://issues.liferay.com/browse/LRDOCS-4807
**TLD Formatter** - https://issues.liferay.com/browse/LRDOCS-4808
**WSDD Builder** - https://issues.liferay.com/browse/LRDOCS-4809
**XML Formatter** - https://issues.liferay.com/browse/LRDOCS-4810

New Maven Plugin Documentation

---

develop/tutorials/articles/14-themes-and-layout-templates/01-themes/01-theme-generator/03-overwriting-gulp-theme-tasks.markdown

Lrdocs 4149 overwriting liferay theme tasks

---

develop/tutorials/articles/120-service-builder/03-business-logic-with-service-builder/04-service-trackers.markdown

https://issues.liferay.com/browse/LRDOCS-4832

LRDOCS-4832 Service Tracker dependency must be "provided"

---

develop/tutorials/articles/02-from-liferay-6-to-liferay-7/07-upgrading-plugins-to-liferay-7/05-upgrading-hook-plugins/01-upgrading-core-jsp-hooks.markdown
develop/tutorials/articles/02-from-liferay-6-to-liferay-7/07-upgrading-plugins-to-liferay-7/05-upgrading-hook-plugins/02-upgrading-app-jsp-hooks.markdown
develop/tutorials/articles/111-customizing/01-overriding-jsps/00-overriding-jsps-intro.markdown
develop/tutorials/articles/111-customizing/01-overriding-jsps/04-jsp-overrides-using-fragments.markdown
develop/tutorials/articles/111-customizing/01-overriding-jsps/05-core-jsp-overrides-using-customjspbag.markdown
develop/tutorials/articles/111-customizing/03-overriding-liferays-default-aui-yui-modules.markdown
develop/tutorials/articles/310-troubleshooting/11-jsp-fragments.markdown

https://issues.liferay.com/browse/LRDOCS-4835

LRDOCS-4835 Deprecate overriding JSPs w/fragments and custom JSP bags (7.0)

---

develop/tutorials/articles/120-customizing/03-overriding-language-keys/01-overriding-liferays-language-keys.markdown
develop/tutorials/articles/120-customizing/03-overriding-language-keys/02-overriding-a-modules-language-keys.markdown

https://issues.liferay.com/browse/LRDOCS-4844
https://issues.liferay.com/browse/LRDOCS-4903

LRDOCS-4844 Creating global language key override modules for multiple locales (7.1)

---

develop/tutorials/articles/111-customizing/05-overriding-language-keys.markdown

Includes these fixes:
- https://issues.liferay.com/browse/LRDOCS-4844 Creating global language key override modules for multiple locales
- https://issues.liferay.com/browse/LRDOCS-4903 Update to ResourceBundleLoader changes
Thanks

LRDOCS-4844 Fix global language key overrides for multiple locales (7.0)

---

develop/tutorials/articles/110-portlets/07-using-javascript-in-your-portlets/00-using-javascript-in-your-portlets-intro.markdown
develop/tutorials/articles/110-portlets/07-using-javascript-in-your-portlets/01-preparing-your-js-files-for-esplus.markdown
develop/tutorials/articles/110-portlets/07-using-javascript-in-your-portlets/02-using-esplus-modules-in-your-portlets.markdown
develop/tutorials/articles/110-portlets/07-using-javascript-in-your-portlets/03-using-npm-in-your-portlets/00-npm-intro.markdown
develop/tutorials/articles/110-portlets/07-using-javascript-in-your-portlets/03-using-npm-in-your-portlets/01-liferay-npm-bundler.markdown
develop/tutorials/articles/110-portlets/07-using-javascript-in-your-portlets/03-using-npm-in-your-portlets/02-configuring-liferay-npm-bundler.markdown
develop/tutorials/articles/110-portlets/07-using-javascript-in-your-portlets/03-using-npm-in-your-portlets/03-adding-liferay-npm-bundler-to-your-portlet.markdown
develop/tutorials/articles/110-portlets/07-using-javascript-in-your-portlets/03-using-npm-in-your-portlets/04-the-structure-of-osgi-bundles-npm.markdown
develop/tutorials/articles/110-portlets/07-using-javascript-in-your-portlets/03-using-npm-in-your-portlets/05-how-the-bundler-formats-js-modules.markdown
develop/tutorials/articles/110-portlets/07-using-javascript-in-your-portlets/03-using-npm-in-your-portlets/06-how-portal-publishes-npm-packages.markdown
develop/tutorials/articles/110-portlets/07-using-javascript-in-your-portlets/03-using-npm-in-your-portlets/07-how-liferay-amd-loader-configuration-is-exported.markdown
develop/tutorials/articles/110-portlets/07-using-javascript-in-your-portlets/03-using-npm-in-your-portlets/08-npmresolver-api/00-using-npmresolver-api-intro.markdown
develop/tutorials/articles/110-portlets/07-using-javascript-in-your-portlets/03-using-npm-in-your-portlets/08-npmresolver-api/01-obtaining-osgi-bundle-npm-package-descriptors.markdown
develop/tutorials/articles/110-portlets/07-using-javascript-in-your-portlets/03-using-npm-in-your-portlets/08-npmresolver-api/02-obtaining-dependency-npm-package-descriptors.markdown

@sez11a  this includes tickets for:
LRDOCS-4300
LRDOCS-4301
LRDOCS-4302
LRDOCS-4303
LRDOCS-4304
LRDOCS-4305
LRDOCS-4306
LRDOCS-4307
LRDOCS-4308
LRDOCS-4895
cc @jbalsas

LRDOCS-4301 Ported using JavaScript in your Portlets docs

---

develop/tutorials/articles/110-portlets/02-soy-portlets/00-liferay-soy-portlet-intro.markdown
develop/tutorials/articles/110-portlets/02-soy-portlets/01-creating-a-soy-portlet.markdown

@sez11a this includes tickets:
LRDOCS-4286
LRDOCS-4287
cc @jbalsas

LRDOCS-4286 ported soy portlet docs to 7.1

---

develop/tutorials/articles/180-themes-and-layout-templates/01-themes/01-theme-generator/00-themes-generator-intro.markdown
develop/tutorials/articles/180-themes-and-layout-templates/01-themes/01-theme-generator/01-installing-the-generator.markdown
develop/tutorials/articles/180-themes-and-layout-templates/01-themes/01-theme-generator/02-creating-a-theme-with-the-generator.markdown

LRDOCS-4919 Note that 7.1 themes are currently unsupported

---

discover/deployment/articles-dxp/03-configuring-liferay/03-liferay-clustering.markdown
discover/deployment/articles/03-configuring-liferay/03-liferay-clustering.markdown

https://issues.liferay.com/browse/LRDOCS-4830 cluster cache replication
https://issues.liferay.com/browse/LRDOCS-4077 copy read-writer updates to DXP article

LRDOCS-4830 Fix 7.0 cache replication docs

---

discover/deployment/articles/05-configuring-for-high-availability/01-liferay-clustering.markdown

https://issues.liferay.com/browse/LRDOCS-4830

LRDOCS-4830 Fix 6.2 cache replication docs

---

userGuide/en/chapters/19-configuring-for-high-availability.markdown

https://issues.liferay.com/browse/LRDOCS-4830

LRDOCS-4830 Fix 6.1 cache replication docs

---

develop/tutorials/articles/100-tooling/02-liferay-ide/10-using-gradle-in-liferay-ide.markdown

https://issues.liferay.com/browse/LRDOCS-4912

LRDOCS-4912 Gradle auto-sync | 7.0.x

---

develop/tutorials/articles/100-tooling/02-liferay-ide/13-using-gradle-in-liferay-ide.markdown

https://issues.liferay.com/browse/LRDOCS-4912

LRDOCS-4912 Gradle auto-sync | master

---

develop/reference/articles/11-maven/db-support-plugin.markdown

liferay#376
https://issues.liferay.com/browse/LRDOCS-4914

LRDOCS-4914 DB Support plugin fix

---

develop/tutorials/articles/180-themes-and-layout-templates/04-clay-and-themes/00-clay-and-themes-intro.markdown
develop/tutorials/articles/180-themes-and-layout-templates/04-clay-and-themes/01-importing-clay-css-in-a-theme.markdown
develop/tutorials/articles/180-themes-and-layout-templates/04-clay-and-themes/02-integrating-third-party-themes-with-clay.markdown

LRDOCS-4641 wrote third party themes tutorial

---

discover/portal/articles/150-setting-up-liferay/01-system-settings/01-system-settings.markdown

https://issues.liferay.com/browse/LRDOCS-4917

LRDOCS-4917, deploy to osgi/configs, not osgi/modules

---

develop/tutorials/articles/300-osgi-basics/03-adding-third-party-libraries-to-a-module.markdown

https://issues.liferay.com/browse/LRDOCS-5024

LRDOCS-5024 (7.0) mention ServiceMix Bundles project and artifact location

---

develop/reference/articles/200-breaking-changes.markdown

From:
brianchandotcom/liferay-portal#55858
brianchandotcom/liferay-portal#56050

LPS-77183 Add new breaking changes

---

develop/reference/articles/02-screenlets-in-liferay-screens-for-android/01-login-screenlet-for-android.markdown
develop/reference/articles/03-screenlets-in-liferay-screens-for-ios/01-login-screenlet-for-ios.markdown
develop/tutorials/articles/122-ios-apps-with-liferay-screens/01-preparing-ios-projects-for-liferay-screens.markdown

6.2.x port of changes from https://github.com/sez11a/liferay-docs/pull/2893

LRDOCS-5039 updates for Screens minor release - 6.2

---

develop/reference/articles/200-breaking-changes.markdown

Breaking Change Typo

---

develop/reference/articles/gradle/00-intro.markdown
develop/reference/articles/gradle/21-target-platform-gradle-plugin.markdown

https://issues.liferay.com/browse/LRDOCS-5042

LRDOCS-5042 Target Platform Ref Doc

---

develop/tutorials/articles/111-customizing/01-overriding-jsps/00-overriding-jsps-intro.markdown
develop/tutorials/articles/111-customizing/01-overriding-jsps/01-jsp-overrides-using-dynamic-includes.markdown

7.0 Fix wording on customizing JSPs and that dynamic includes insert content

---

develop/reference/articles/13-sample-projects/01-apps/03-npm-samples/03-isomorphic-npm-portlet.markdown

https://issues.liferay.com/browse/LRDOCS-5052
/cc @izaera

LRDOCS-5052 Isomorphic Sample Portlet Clarifications

---

discover/deployment/articles/03-configuring-liferay/06-securing-liferay/03-service-access-policies.markdown
discover/deployment/articles/03-configuring-liferay/06-securing-liferay/05-ldap.markdown

Liferay 7.0.x PRs

---

develop/tutorials/articles/110-portlets/07-using-javascript-in-your-portlets/03-using-npm-in-your-portlets/02-configuring-liferay-npm-bundler.markdown

@sez11a back-porting these updates to 7.0 as well. I'll send a separate PR with those changes.
cc @jbalsas

LRDOCS-5056 liferay-npm-bundler updates

---

develop/tutorials/articles/110-portlets/15-javascript/04-npm/03-configuring-liferay-npm-bundler.markdown

@sez11a backporting latest changes from 7.1 docs to 7.0 docs.
cc @jbalsas

LRDOCS-5056 add latest updates to liferay-npm-bundler

---

develop/tutorials/articles/260-themes-and-layout-templates/01-themes/01-themes-generator.markdown

LRDOCS-5067 Note to use Theme Generator 7.x.x version

---

discover/deployment/articles/02-installing-liferay/04-installing-liferay-on-tomcat.markdown

These changes are based on this commit 582a33d51f468025ea8a15cfc1caa5b055c1f8da from @olafk

Use CATALINA_BASE and CATALINA_HOME instead of TOMCAT_HOME

---

develop/tutorials/articles/02-from-liferay-6-to-liferay-7/07-upgrading-plugins-to-liferay-7/05-upgrading-hook-plugins/06-upgrading-model-listener-hooks.markdown

Straight conversion. Thanks.
https://issues.liferay.com/browse/LRDOCS-4202

LRDOCS-4202 7.1 port Upgrading Model Listener Hooks

---

develop/tutorials/articles/02-from-liferay-6-to-liferay-7/07-upgrading-plugins-to-liferay-7/05-upgrading-hook-plugins/07-upgrading-servlet-filter-hooks.markdown

Straight conversion. Thanks.
https://issues.liferay.com/browse/LRDOCS-4203

LRDOCS-4203 7.1 port Upgrading Servlet Filter Hooks

---

develop/tutorials/articles/02-from-liferay-6-to-liferay-7/07-upgrading-plugins-to-liferay-7/05-upgrading-hook-plugins/08-upgrading-portal-property-and-event-action-hooks.markdown

Straight conversion.
https://issues.liferay.com/browse/LRDOCS-4204

LRDOCS-4204 7.1. port Upgrading Portal Property and Event Action Hooks

---

develop/tutorials/articles/02-from-liferay-6-to-liferay-7/07-upgrading-plugins-to-liferay-7/05-upgrading-hook-plugins/09-converting-struts-action-wrappers-to-mvc-commands.markdown

https://issues.liferay.com/browse/LRDOCS-4205

LRDOCS-4205 7.1 Converting StrutsAction Wrappers to MVCCommands

---

develop/tutorials/articles/02-from-liferay-6-to-liferay-7/08-optimizing-plugins-for-liferay-portal-7/00-optimizing-plugins-for-liferay-7-intro.markdown
develop/tutorials/articles/02-from-liferay-6-to-liferay-7/08-optimizing-plugins-for-liferay-portal-7/02-modularizing-plugins/00-modularizing-plugins-intro.markdown

https://issues.liferay.com/browse/LRDOCS-4208

LRDOCS-4208 7.1 Modularizing Plugins

---

develop/tutorials/articles/130-service-builder/00-service-builder-intro.markdown

https://issues.liferay.com/browse/LRDOCS-4332

LRDOCS-4332 7.1 service builder intro

---

develop/tutorials/articles/02-from-liferay-6-to-liferay-7/02-benefits-of-liferay-7-for-liferay-6-developers.markdown

https://issues.liferay.com/browse/LRDOCS-4179

LRDOCS-4179 Benefits of 7.1 for liferay portal 6 developers

---

develop/tutorials/articles/330-modularity-and-osgi/03-leveraging-dependencies.markdown

https://issues.liferay.com/browse/LRDOCS-5086
This tutorial is from content extracted from Learning Path "From Liferay 6 to 7"

LRDOCS-5086 7.1 Leveraging Dependencies

---

develop/tutorials/articles/140-application-security/06-service-access-policies.markdown
develop/tutorials/articles/160-import-export-and-staging/08-developing-staged-model-data-handlers.markdown

I like checking in the *ant check* changes. Makes a cleaner output when I run ant check on my own articles.

Ran ant check in msater

---

develop/tutorials/articles/02-from-liferay-6-to-liferay-7/02-benefits-of-liferay-7-for-liferay-6-developers.markdown
develop/tutorials/articles/330-modularity-and-osgi/04-osgi-services-and-dependency-injection.markdown

https://issues.liferay.com/browse/LRDOCS-2525
This content was extracted from *From Liferay 6 to 7...*.

LRDOCS-2525 7.1 osgi services and dependency injection

---

develop/tutorials/articles/330-modularity-and-osgi/99-learning-more-about-osgi.markdown

https://issues.liferay.com/browse/LRDOCS-5089
This tutorial is from content extracted from Learning Path "From Liferay 6 to 7"

LRDOCS-5089 7.1 learning more about osgi

---

develop/reference/articles/200-breaking-changes.markdown

From brianchandotcom/liferay-portal#56628

LPS-79214 Add new breaking change

---

develop/reference/articles/10-gradle/18-service-builder-gradle-plugin.markdown

https://issues.liferay.com/browse/LRDOCS-5050

LRDOCS-5050 Overriding default SB Gradle plugin in Workspace

---

discover/portal/articles/140-managing-apps/05-blacklisting-osgi-modules.markdown

- Explain how to find bundle symbolic names for each type.
- Include each type of module in the example blacklist
- Add headings to distinguish blacklist steps from un-blacklist steps.
https://issues.liferay.com/browse/LRDOCS-5094

LRDOCS-5094 7.0 Improve blacklisting instructions

---

bin/convert.bat
bin/convert.sh

https://issues.liferay.com/browse/LRDOCS-5105

LRDOCS-5105 convert scripts should use new class name

---

develop/tutorials/articles/120-customizing/10-dynamic-includes/00-dynamic-include-extension-points-intro.markdown
develop/tutorials/articles/120-customizing/10-dynamic-includes/01-wysiwyg-editor-dynamic-includes.markdown
develop/tutorials/articles/120-customizing/10-dynamic-includes/02-top-head-jsp-dynamic-include.markdown
develop/tutorials/articles/120-customizing/10-dynamic-includes/03-top-js-dynamic-include.markdown
develop/tutorials/articles/120-customizing/10-dynamic-includes/04-bottom-jsp-dynamic-include.markdown

@sez11a this fixes the links in the Dynamic Include articles.

LRDOCS-5037 SF fix links

---

develop/reference/articles/00-development-reference.markdown

With this landing page for `develop/reference`, we should be able to start publishing articles for that section for 7.1.
https://issues.liferay.com/browse/LRDOCS-5021

LRDOCS-5021 Dev Reference Intro

---

discover/deployment/articles-dxp/08-liferay-enterprise-search/07-upgrading-to-elasticsearch-6.markdown
discover/deployment/articles-dxp/08-liferay-enterprise-search/08-xpack-security.markdown
discover/deployment/articles-dxp/08-liferay-enterprise-search/09-xpack-monitoring.markdown
discover/deployment/articles/02-installing-liferay/10-configuring-search.markdown
discover/deployment/articles/08-liferay-enterprise-search/02-configuring-elasticsearch.markdown

https://issues.liferay.com/browse/LRDOCS-5103, incorporated feedback on the new ES 6 docs (bad link, better links, fixed subscriptions information, technical note on proxying the Kibana UI). cc @lipusz

LRDOCS-5103 improvements to X-Pack/ES 6

---

develop/tutorials/articles/120-service-builder/02-service-builder-persistence/05-developing-custom-sql-queries.markdown

develop > tutorials > 7.0
https://issues.liferay.com/browse/LRDOCS-2956
Thanks!

LRDOCS-2956 7.0 Fix call to CustomSQLUtil.get

---

discover/deployment/articles/05-upgrading-to-liferay-7-1/01-pre-upgrade-speed-up-the-process.markdown

discover > deployment > 7.1
https://issues.liferay.com/browse/LRDOCS-5107

LRDOCS-5107 7.1 fix anchor link

---

discover/deployment/articles-dxp/08-liferay-enterprise-search/08-xpack-security.markdown
discover/deployment/articles-dxp/08-liferay-enterprise-search/09-xpack-monitoring.markdown

https://issues.liferay.com/browse/LRDOCS-5114. cc @lipusz

LRDOCS-514, ES 6 7.0 bug fixes

---

develop/tutorials/articles/340-osgi-basics-for-liferay-development/06-waiting-on-lifecycle-events.markdown

https://issues.liferay.com/browse/LRDOCS-4841

LRDOCS-4841 7.1 waiting on lifecycle events

---

develop/tutorials/articles/290-internationalization/01-localizing-your-application.markdown

https://issues.liferay.com/browse/LRDOCS-5085

LRDOCS-5085 7.1 port improvements to localizing your application

---

develop/tutorials/articles/160-import-export-and-staging/07-developing-portlet-data-handlers.markdown

https://issues.liferay.com/browse/LRDOCS-5053

LRDOCS-5053 Schema Version docs

---

develop/tutorials/articles/130-service-builder/02-service-builder-persistence/04-customizing-model-entities-with-model-hints.markdown

Hey Rich,
I noted that aui is not related to AlloyUI and that you can use a mix of Clay and aui tags.
https://issues.liferay.com/browse/LRDOCS-4338

LRDOCS-4338 7.1 customizing model entities (aui is not AlloyUI)

---

develop/tutorials/articles/02-from-liferay-6-to-liferay-7/07-upgrading-plugins-to-liferay-7/04-upgrading-portlet-plugins/07-upgrading-a-spring-mvc-portlet.markdown
develop/tutorials/articles/02-from-liferay-6-to-liferay-7/08-optimizing-existing-plugins-for-liferay-7/01-migrating-traditional-plugins-to-workspace-web-applications.markdown

https://issues.liferay.com/browse/LRDOCS-5202

LRDOCS-5202 7.0 facilitate upgrading spring mvc portlet by converting it to a workspace war

---

develop/tutorials/articles/110-portlets/04-spring-mvc-portlet.markdown
develop/tutorials/articles/110-portlets/04-spring-mvc/00-spring-mvc-intro.markdown
develop/tutorials/articles/110-portlets/04-spring-mvc/01-configuring-a-spring-mvc-portlet.markdown
develop/tutorials/articles/110-portlets/04-spring-mvc/02-deploying-a-spring-mvc-portlet.markdown

Update the Spring MVC content and split it into separate tutorials.
https://issues.liferay.com/browse/LRDOCS-4293

LRDOCS-4293 spring mvc

---

develop/tutorials/articles/111-customizing/01-overriding-jsps/01-jsp-overrides-using-dynamic-includes.markdown

https://issues.liferay.com/browse/LRDOCS-5207

LRDOCS-5207 7.0 Clarify creating a module for the dynamic include

---

develop/tutorials/articles/120-customizing/01-customizing-jsps/01-customizing-jsps-with-dynamic-includes.markdown

https://issues.liferay.com/browse/LRDOCS-5207

LRDOCS-5207 7.1 Clarify creating a module for the dynamic include

---

develop/tutorials/articles/130-service-builder/02-service-builder-persistence/08-configuring-service-properties.markdown

https://issues.liferay.com/browse/LRDOCS-4341
Also applied update from https://issues.liferay.com/browse/LRDOCS-3801

LRDOCS-4341 configuring service.properties

---

develop/tutorials/articles/01-introduction-to-liferay-development/01-fundamentals.markdown

Fix JSR links

---

discover/portal/articles/140-managing-apps/05-blacklisting-osgi-modules.markdown

https://issues.liferay.com/browse/LRDOCS-5224

LRDOCS-5224 7.0 blacklisting components

---

release-site.properties

https://issues.liferay.com/browse/LRDOCS-5228

LRDOCS-5228 Update Enterprise product token update

---

develop/reference/articles/maven/00-intro.markdown
develop/reference/articles/maven/bundle-support-plugin.markdown
develop/reference/articles/maven/css-builder-plugin.markdown
develop/reference/articles/maven/db-support-plugin.markdown
develop/reference/articles/maven/deployment-helper-plugin.markdown
develop/reference/articles/maven/javadoc-formatter-plugin.markdown
develop/reference/articles/maven/lang-builder-plugin.markdown
develop/reference/articles/maven/service-builder-plugin.markdown
develop/reference/articles/maven/source-formatter-plugin.markdown
develop/reference/articles/maven/theme-builder-plugin.markdown
develop/reference/articles/maven/tld-formatter-plugin.markdown
develop/reference/articles/maven/wsdd-builder-plugin.markdown
develop/reference/articles/maven/xml-formatter-plugin.markdown

https://issues.liferay.com/browse/LRDOCS-5119
https://issues.liferay.com/browse/LRDOCS-5149
https://issues.liferay.com/browse/LRDOCS-5150
https://issues.liferay.com/browse/LRDOCS-5151
https://issues.liferay.com/browse/LRDOCS-5152
https://issues.liferay.com/browse/LRDOCS-5153
https://issues.liferay.com/browse/LRDOCS-5154
https://issues.liferay.com/browse/LRDOCS-5155
https://issues.liferay.com/browse/LRDOCS-5156
https://issues.liferay.com/browse/LRDOCS-5157
https://issues.liferay.com/browse/LRDOCS-5158
https://issues.liferay.com/browse/LRDOCS-5159
https://issues.liferay.com/browse/LRDOCS-5160

LRDOCS-5119 Maven Plugins 7.1

---

develop/reference/articles/100-felix-gogo-shell.markdown

https://issues.liferay.com/browse/LRDOCS-5200

LRDOCS-5200 Felix Gogo shell

---

develop/tutorials/articles-dxp/100-tooling/02-liferay-ide/01-installing-liferay-ide.markdown
develop/tutorials/articles/100-tooling/02-liferay-ide/01-installing-liferay-ide.markdown

https://issues.liferay.com/browse/LRDOCS-5251

LRDOCS-5251 Add steps to upgrade to Oxygen

---

develop/tutorials/articles/130-service-builder/02-service-builder-persistence/01-defining-an-object-relational-map-with-service-builder/04-defining-the-columns-attributes-for-each-service-entity.markdown
develop/tutorials/articles/130-service-builder/02-service-builder-persistence/01-defining-an-object-relational-map-with-service-builder/07-defining-service-entity-finder-methods.markdown

https://issues.liferay.com/browse/LRDOCS-5027

LRDOCS-5027 7.1 do not create finders that use entity primary key columns

---

develop/tutorials/articles/120-service-builder/02-service-builder-persistence/01-defining-an-object-relational-map-with-service-builder.markdown

https://issues.liferay.com/browse/LRDOCS-5027

LRDOCS-5027 7.0 do not create finders for entity primary key columns

---

develop/tutorials/articles/100-tooling/02-liferay-ide/02-creating-a-liferay-workspace-with-liferay-ide.markdown

https://issues.liferay.com/browse/LRDOCS-5263

LRDOCS-5263 IDE/Buildship Note | 7.0.x

---

develop/tutorials/articles/130-service-builder/03-business-logic-with-service-builder/01-creating-local-services/03-implementing-an-update-method.markdown

https://issues.liferay.com/browse/LRDOCS-4344

LRDOCS-4344 Implementing update and delete methods

---

develop/tutorials/articles/300-osgi-basics/08-semantic-versioning.markdown

https://issues.liferay.com/browse/LRDOCS-2527
I'll convert this to our 7.1 docs once it has passed your review.

LRDOCS-2527 Semantic Versioning tutorial

---

develop/tutorials/articles/130-service-builder/03-business-logic-with-service-builder/01-creating-local-services/04-implementing-methods-to-get-and-count-entities.markdown

https://issues.liferay.com/browse/LRDOCS-4344

LRDOCS-4344 Service Buidler - implementing getter and get count methods

---

develop/tutorials/articles/130-service-builder/03-business-logic-with-service-builder/01-creating-local-services/05-implementing-any-other-business-logic.markdown

https://issues.liferay.com/browse/LRDOCS-4344

LRDOCS-4344 Service Builder: Implementing any other business logic

---

discover/deployment/articles/03-configuring-liferay/00-intro.markdown

https://issues.liferay.com/browse/LRDOCS-4749

LRDOCS-4749 Configuring Liferay Portal

---

discover/deployment/articles/02-installing-liferay/01-preparing-for-install.markdown

https://issues.liferay.com/browse/LRDOCS-5275

LRDOCS-5275 7.0 Deployment - Warning about data truncation on retrieval of CLOB data

---

discover/deployment/articles/00-deploying-liferay/01-preparing-for-install.markdown

https://issues.liferay.com/browse/LRDOCS-5275

LRDOCS-5275 7.1 Deployment: warn about data truncations reading from CLOB columns

---

discover/deployment/articles/00-deploying-liferay/10-configuring-search.markdown
discover/deployment/articles/00-deploying-liferay/10-installing-elasticsearch.markdown

https://issues.liferay.com/browse/LRDOCS-4736 installing elasticsearch article for 7.1. cc @lipusz

LRDOCS-4736 installing elasticsearch

---

develop/reference/articles/200-breaking-changes.markdown

Originally sent brianchandotcom/liferay-portal#58261

LRDOCS-5284 New Breaking Change

---

discover/reference/articles/05-whats-expected-from-staging.markdown
discover/reference/articles/placeholder.txt

https://issues.liferay.com/browse/LRDOCS-4575

LRDOCS-4575 Add Staging User reference article

---

develop/tutorials/articles/110-portlets/07-using-javascript-in-your-portlets/03-using-npm-in-your-portlets/02-configuring-liferay-npm-bundler.markdown
develop/tutorials/articles/110-portlets/07-using-javascript-in-your-portlets/03-using-npm-in-your-portlets/05-how-the-bundler-formats-js-modules.markdown

LRDOCS-5292 fix links

---

develop/tutorials/articles/130-service-builder/02-service-builder-persistence/07-actionable-dynamic-query.markdown

https://issues.liferay.com/browse/LRDOCS-5106

LRDOCS-5106 Actionable Dynamic Query

---

discover/deployment/articles/00-deploying-liferay/13-setting-up-marketplace-and-portal-security.markdown

https://issues.liferay.com/browse/LRDOCS-4739

LRDOCS-4739 Setting up Marketplace

---

discover/analytics-cloud/build.xml

@rbohl - Lets put our articles and images in `articles` and ` images` of this folder.

LRDOCS-5113 folder for Analytics Cloud documentation.

---

develop/tutorials/articles/03-developing-a-web-application/06-permissions/01-configuring-resources.markdown
develop/tutorials/articles/112-application-display-templates/01-implementing-application-display-templates.markdown
discover/deployment/articles/03-configuring-liferay/02-document-repository.markdown

https://github.com/liferay/liferay-docs/pull/397
https://github.com/liferay/liferay-docs/pull/400
https://github.com/liferay/liferay-docs/pull/401
https://github.com/liferay/liferay-docs/pull/402
Please also close:
liferay#396 (similar issue resolved in liferay#395)
liferay#398 (This issue was resolved in the Forums [here](https://web.liferay.com/community/forums/-/message_boards/view_message/108598385))

Liferay PRs | 7.0.x

---

develop/tutorials/articles/190-javascript-module-loaders/00-javascript-module-loaders-intro.markdown
develop/tutorials/articles/190-javascript-module-loaders/02-loading-amd-modules-in-liferay.markdown
develop/tutorials/articles/190-javascript-module-loaders/04-loading-modules-with-aui-script-tag.markdown

LRDOCS-4413 AMD Module Loader 

---

develop/tutorials/articles/101-plugins-sdk/01-setting-up-the-plugins-sdk.markdown

https://issues.liferay.com/browse/LRDOCS-5298

LRDOCS-5298 Compiling 6.2 plugins using Java 8

---

develop/tutorials/articles/240-javascript-module-loaders/03-using-external-libraries.markdown

LRDOCS-5286 Add note and clarify required versions for steps

---

develop/tutorials/articles/190-javascript-module-loaders/03-using-external-libraries.markdown

LRDOCS-5286 remove browser globals section and update steps

---

discover/portal/articles/190-managing-users/00-intro.markdown
discover/portal/articles/190-managing-users/02-roles-and-permissions/00-intro.markdown

fixed some bad bulleted list formatting and added the new articles to the section intro, with links.

LRDOCS-4999 formatting fix

---

discover/portal/articles/100-web-experience-management/07-staging-content-for-publication/01-enabling-staging/02-enabling-remote-live-staging.markdown
discover/portal/articles/100-web-experience-management/07-staging-content-for-publication/01-enabling-staging/03-configuring-servers-for-remote-live-staging.markdown

https://issues.liferay.com/browse/LRDOCS-5351

LRDOCS-5351 Tunnel Auth Verifiers update

---

develop/tutorials/articles/02-from-liferay-6-to-liferay-7/08-optimizing-existing-plugins-for-liferay-7/06-modularizing-plugins/06-modularizing-an-existing-portlet.markdown

7.0 fix blade command sequence

---

discover/deployment/articles-dxp/09-liferay-connected-services/04-troubleshooting-lcs-connection.markdown

Updating info about LCS grace period in LCS troubleshooting article

LRDOCS-5337 LCS grace period update

---

develop/reference/articles/200-breaking-changes.markdown

Merged in brianchandotcom/liferay-portal#59857
https://issues.liferay.com/browse/LRDOCS-5284

LRDOCS-5284 Breaking change update

---

discover/deployment/articles/00-deploying-liferay/01-preparing-for-install.markdown

https://issues.liferay.com/browse/LRDOCS-4727

LRDOCS-4727 Preparing for install (SME reviewed)

---

discover/deployment/articles/00-deploying-liferay/03-installing-liferay-manually.markdown

https://issues.liferay.com/browse/LRDOCS-4729

LRDOCS-4729 Installing Liferay Portal Manually

---

develop/reference/articles/200-breaking-changes.markdown

Merged by BChan: brianchandotcom/liferay-portal#60098

LRDOCS-5374 New breaking changes

---

discover/portal/articles/100-web-experience-management/02-building-a-site/04-building-sites-with-templates/00-building-sites-from-templates-intro.markdown
discover/portal/articles/100-web-experience-management/02-building-a-site/04-building-sites-with-templates/01-creating-a-site-template.markdown
discover/portal/articles/100-web-experience-management/02-building-a-site/04-building-sites-with-templates/02-managing-site-templates.markdown
discover/portal/articles/100-web-experience-management/02-building-a-site/04-building-sites-with-templates/03-propagating-changes-from-site-templates.markdown
discover/portal/articles/100-web-experience-management/02-building-a-site/04-building-sites-with-templates/04-sharing-site-templates.markdown

https://issues.liferay.com/browse/LRDOCS-4553
Minor reorganization of files based on WEM team feedback and updated screenshots with minor instruction updates.

LRDOCS-4553 Site Templates

---

discover/portal/articles/100-web-experience-management/00-intro.markdown
discover/portal/articles/100-web-experience-management/01-authoring-content.markdown
discover/portal/articles/100-web-experience-management/02-building-a-site/00-building-a-site-intro.markdown
discover/portal/articles/100-web-experience-management/02-building-a-site/01-site-management/00-site-management-intro.markdown
discover/portal/articles/100-web-experience-management/02-building-a-site/01-site-management/01-understanding-site-management.markdown
discover/portal/articles/100-web-experience-management/02-building-a-site/01-site-management/02-adding-sites.markdown

https://issues.liferay.com/browse/LRDOCS-4542
https://issues.liferay.com/browse/LRDOCS-4551

Broke out first section into a separate PR

---

develop/reference/articles/22-what-changed-between-liferay-npm-bundler-1.x-and-2.x.markdown
develop/tutorials/articles/110-portlets/15-javascript/04-npm/00-npm-portlets-intro.markdown
develop/tutorials/articles/110-portlets/15-javascript/04-npm/01-liferay-npm-bundler.markdown
develop/tutorials/articles/110-portlets/15-javascript/04-npm/02-adding-liferay-npm-bundler-to-your-portlet.markdown
develop/tutorials/articles/110-portlets/15-javascript/04-npm/03-configuring-liferay-npm-bundler.markdown
develop/tutorials/articles/110-portlets/15-javascript/04-npm/04-structure-of-osgi-bundles-npm.markdown
develop/tutorials/articles/110-portlets/15-javascript/04-npm/05-how-the-bundler-formats-js-modules.markdown
develop/tutorials/articles/110-portlets/15-javascript/04-npm/06-how-portal-publishes-npm-packages.markdown
develop/tutorials/articles/110-portlets/15-javascript/04-npm/07-how-lifery-amd-loader-configuration-is-exported.markdown

LRDOCS-5375 update 7.0 bundler docs to version 2.x

---

discover/deployment/articles-dxp/09-liferay-connected-services/04-troubleshooting-lcs-connection.markdown

Removing incorrect port number for LCS troubleshooting doc

Minor fix for LCS 7.0 doc

---

develop/tutorials/articles/130-web-services/01-service-builder-web-services/09-soap-web-services.markdown

Fix note about using SSL in production environments

Fix note about using SSL in production environments

---

discover/portal/articles/100-web-experience-management/07-staging-content-for-publication/05-publishing-single-assets-from-staged-site.markdown

https://issues.liferay.com/browse/LRDOCS-5369

LRDOCS-5369 Add permissions info for single asset publishing

---

develop/tutorials/articles/150-web-services/00-intro.markdown

LRDOCS-4359 Web services intro

LRDOCS-4359 Web services intro

---

discover/deployment/articles/00-deploying-liferay/04-installing-liferay-portal-on-tomcat.markdown

The Tomcat install is SME reviewed and ready for your review. :-)
https://issues.liferay.com/browse/LRDOCS-4730

LRDOCS-4730 installing on tomcat

---

develop/tutorials/articles/150-web-services/00-intro.markdown
develop/tutorials/articles/150-web-services/01-service-builder-web-services/01-creating-remote-services.markdown

LRDOCS-4362 Add creating remote web services article

LRDOCS-4362 Add creating remote web services article

---

discover/deployment/articles-dxp/00-deploying-liferay/07-installing-liferay-on-tc-server.markdown

@sez11a SME reviewed and ready to go
cc @jhinkey

LRDOCS-4732 tc server dxp

---

develop/tutorials/articles/150-web-services/00-intro.markdown
develop/tutorials/articles/150-web-services/03-service-security-layers.markdown

LRDOCS-4364 Update service security layers article

LRDOCS-4364 Update service security layers article

---

discover/deployment/articles-dxp/03-configuring-liferay/07-dxp-configuration-and-tuning/00-dxp-configuration-and-tuning-intro.markdown
discover/deployment/articles-dxp/03-configuring-liferay/07-dxp-configuration-and-tuning/01-application-server-tuning.markdown
discover/deployment/articles-dxp/03-configuring-liferay/07-dxp-configuration-and-tuning/02-jvm-tuning.markdown

https://issues.liferay.com/browse/LRDOCS-5409

LRDOCS-5409 dxp config and tuning guidelines

---

develop/tutorials/articles/150-web-services/00-intro.markdown
develop/tutorials/articles/150-web-services/04-registering-json-web-services.markdown

LRDOCS-4365 Update registering JSON web services article

LRDOCS-4365 Update registering JSON web services article

---

discover/new-articles/08-installing-liferay-on-weblogic.markdown

I took parts of Jim's draft: https://github.com/jhinkey/liferay-docs/blob/71-weblogic-install/discover/deployment/articles-dxp/00-deploying-liferay/08-installing-liferay-dxp-on-weblogic.markdown

LRDOCS-4734

---

discover/deployment/articles/00-deploying-liferay/05-installing-liferay-portal-on-wildfly.markdown
discover/deployment/articles/03-configuring-liferay/02-document-repository-configuration/00-document-repository-configuration-intro.markdown

https://issues.liferay.com/browse/LRDOCS-4731

LRDOCS-4731 Wildfly App Server

---

discover/deployment/articles-dxp/04-maintaining-liferay/01-patching-liferay-dxp/00-patching-liferay-dxp-intro.markdown
discover/deployment/articles-dxp/04-maintaining-liferay/01-patching-liferay-dxp/04-keeping-up-with-fix-packs.markdown

This is part 4 of 4 Patching DXP articles. 
https://issues.liferay.com/browse/LRDOCS-4771
https://issues.liferay.com/browse/LRDOCS-5396

LRDOCS-5396 Patching DXP: Keeping up with fix packs and service packs

---

discover/deployment/articles/06-upgrading-to-liferay-7-1/03-running-the-upgrade-process/02-gogo-shell-commands-for-module-upgrades.markdown

https://issues.liferay.com/browse/LRDOCS-5413
cc/ @codyhoag

LRDOCS-5413 Use the Gogo Shell portlet to upgrade modules.

---

develop/reference/articles/maven/bundle-support-plugin.markdown
develop/tutorials/articles/140-application-security/04-authentication-pipelines/02-authentication-pipelines.markdown
develop/tutorials/articles/150-web-services/01-service-builder-web-services/01-creating-remote-services.markdown
develop/tutorials/articles/300-internationalization/02-automatically-generating-language-files.markdown
develop/tutorials/articles/360-osgi-basics-for-liferay-development/05-resolving-third-party-package-dependencies.markdown

https://issues.liferay.com/browse/LRDOCS-5420

LRDOCS-5420 CDN URL Updates

---

develop/learning-paths/mvc/code/guestbook-ui-complete/guestbook/build.gradle
develop/learning-paths/mvc/code/guestbook-ui-complete/guestbook/settings.gradle
develop/reference/articles/11-maven/bundle-support-plugin.markdown
develop/tutorials/articles/130-web-services/01-service-builder-web-services/01-creating-remote-services.markdown
develop/tutorials/articles/195-forms/01-form-field-types/01-creating-form-field-types.markdown
develop/tutorials/articles/210-application-security/04-authentication-pipelines/02-authentication-pipelines.markdown
develop/tutorials/articles/220-internationalization/02-automatic-translation.markdown
develop/tutorials/articles/300-osgi-basics/03-adding-third-party-libraries-to-a-module.markdown
develop/tutorials/code/com-liferay-docs-guestbook/gradle.properties
develop/tutorials/code/com-liferay-docs-guestbook/settings.gradle
develop/tutorials/code/com.liferay.docs.emailAddressAuthenticator/build.gradle
develop/tutorials/code/com.liferay.docs.emailAddressValidator/build.gradle
develop/tutorials/code/dynamic-data-mapping-time/build.gradle
develop/tutorials/code/my-blogs-editor-config-contributor/build.gradle
develop/tutorials/code/osgi/modules/console-logger-portlet/build.gradle
develop/tutorials/code/osgi/modules/js-logger/build.gradle

The remaining CDN updates for `7.0.x` are changed in this PR: #3225 
https://issues.liferay.com/browse/LRDOCS-5420

LRDOCS-5420 CDN URL Updates | 7.0.x

---

develop/tutorials/articles/180-themes-and-layout-templates/01-themes/01-creating-themes/00-creating-themes-intro.markdown

@sez11a this removes the unsupported note, as the theme generator will be supported moving forward for 7.1 in the next couple weeks.
cc @jbalsas

LRDOCS-5424 remove support note

---

discover/portal/articles/100-web-experience-management/07-staging-content-for-publication/05-publishing-single-assets-from-staged-site.markdown

https://issues.liferay.com/browse/LRDOCS-5423

LRDOCS-5423 Cannot publish page-scoped single assets

---

develop/tutorials/articles/170-assets/02-entering-and-displaying-tags-and-categories.markdown
develop/tutorials/articles/170-assets/03-relating-assets.markdown
develop/tutorials/articles/170-assets/04-implementing-asset-priority.markdown
develop/tutorials/articles/170-assets/05-rendering-an-asset/00-rendering-an-asset-intro.markdown
develop/tutorials/articles/180-themes-and-layout-templates/01-themes/02-developing-themes/15-injecting-additional-context-variables-and-functionality-into-your-templates.markdown
develop/tutorials/articles/180-themes-and-layout-templates/01-themes/03-managing-theme-resources/02-creating-a-sitemap/03-defining-portlets-in-a-sitemap.markdown
develop/tutorials/articles/230-web-experience-management/01-developing-fragments/01-creating-a-fragment.markdown
develop/tutorials/articles/250-collaboration/05-social-api/02-adding-comments-to-your-app.markdown
develop/tutorials/articles/360-osgi-basics-for-liferay-development/07-using-the-wab-generator.markdown

Fixed links for changed headers and commented out links with incoming tutorials

Wem link fix

---

discover/deployment/articles-dxp/04-maintaining-liferay/01-patching-liferay-dxp/01-patching-basics.markdown

https://issues.liferay.com/browse/LRDOCS-5393

LRDOCS-5393 Patching basics

---

discover/deployment/articles-dxp/04-securing-liferay/01-saml/00-intro.markdown
discover/deployment/articles-dxp/04-securing-liferay/01-saml/01-setting-up-identity-provider.markdown

Fixed paths of images that exist, commented out 2 images that don't exist. cc @jrao

SAML Image Problems

---

discover/deployment/articles-dxp/02-installing-liferay/11-activating-liferay-dxp.markdown
discover/deployment/articles-dxp/09-liferay-connected-services/00-intro.markdown
discover/deployment/articles-dxp/09-liferay-connected-services/01-lcs-preconfiguration.markdown
discover/deployment/articles-dxp/09-liferay-connected-services/02-activating-your-dxp-server-with-lcs.markdown
discover/deployment/articles-dxp/09-liferay-connected-services/03-using-lcs.markdown
discover/deployment/articles-dxp/09-liferay-connected-services/04-troubleshooting-lcs-connection.markdown

Porting updated activation info from below PR to 7.0.x
https://github.com/sez11a/liferay-docs/pull/3303

LRDOCS-5435 LCS 7.0 activation update

---

develop/tutorials/articles/01-introduction-to-liferay-development/01-fundamentals.markdown
develop/tutorials/articles/120-customizing/02-overriding-liferay-services.markdown
develop/tutorials/articles/230-web-experience-management/01-developing-fragments/02-fragment-specific-tags.markdown
discover/deployment/articles/06-upgrading-to-liferay-7-1/03-running-the-upgrade-process/01-running-the-upgrade-tool.markdown
discover/portal/articles/120-search/02-configuring-a-search-page.markdown

liferay#406
liferay#408
liferay#410
liferay#418
liferay#419
https://issues.liferay.com/browse/LRDOCS-5437
Also please close
liferay#396 (similar issue resolved in liferay#395)
liferay#398 (This issue was resolved in the Forums [here](https://web.liferay.com/community/forums/-/message_boards/view_message/108598385))

LRDOCS-5437 Liferay PRs

---

discover/deployment/articles-dxp/08-liferay-enterprise-search/04-marvel.markdown

https://issues.liferay.com/browse/LRDOCS-5443 cc @lipusz

LRDOCS-5443, Marvel Licesne clarification

---

develop/tutorials/articles/128-customizing-liferay-portal-with-hooks/99-advanced-customization-with-ext-plugins.markdown
discover/deployment/articles/01-installation-and-setup/13-installing-liferay-on-glassfish-4.markdown

Liferay PRs | 6.2.x

---

develop/reference/articles/200-breaking-changes.markdown

https://issues.liferay.com/browse/LRDOCS-5450

LRDOCS-5450 Staging breaking change

---

discover/portal/articles/120-search/01-whats-new-in-search.markdown
discover/portal/articles/120-search/03-searching-for-assets.markdown
discover/portal/articles/120-search/04-facets/00-facets-intro.markdown
discover/portal/articles/120-search/04-facets/01-site-facet.markdown
discover/portal/articles/120-search/05-search-results/02-results-behavior.markdown

LPS-83193 changed how Search Widget Configuration works and some more SME review comments came in. cc @lipusz

Search Article Fixes

---

develop/tutorials/articles/100-tooling/04-liferay-workspace/05-managing-the-target-platform-for-liferay-workspace.markdown
develop/tutorials/articles/100-tooling/04-liferay-workspace/06-validating-modules-against-the-target-platform/01-resolving-your-modules.markdown
develop/tutorials/articles/100-tooling/04-liferay-workspace/06-validating-modules-against-the-target-platform/02-modifying-the-target-platforms-capabilities.markdown
develop/tutorials/articles/100-tooling/04-liferay-workspace/06-validating-modules-against-the-target-platform/99-validating-modules-outside-of-workspace.markdown

https://issues.liferay.com/browse/LRDOCS-5451

LRDOCS-5451 Target Platform DXP Versioning

---

discover/portal/articles/140-workflow/00-intro.markdown

Added links to the available workflow docs and make it clear what the section will cover. One of the bullet points was just old cruft that overlaps with my existing Activating Workflow article.

Linked to the available workflow docs and make it clear what'

---

discover/portal/articles/120-search/00-intro.markdown
discover/portal/articles/120-search/01-whats-new-in-search.markdown
discover/portal/articles/120-search/03-searching-for-assets.markdown
discover/portal/articles/120-search/05-search-results/00-intro.markdown
discover/portal/articles/120-search/05-search-results/01-display-settings.markdown
discover/portal/articles/120-search/05-search-results/02-results-behavior.markdown
discover/portal/articles/130-forms/00-intro.markdown
discover/portal/articles/130-forms/04-form-rules/00-intro.markdown
discover/portal/articles/130-forms/04-form-rules/01-show-hide-rules.markdown
discover/portal/articles/190-managing-users/00-intro.markdown
discover/portal/articles/190-managing-users/01-users-and-organizations/01-managing-users.markdown
discover/portal/articles/190-managing-users/01-users-and-organizations/03-organizations.markdown
discover/portal/articles/190-managing-users/02-roles-and-permissions/00-intro.markdown
discover/portal/articles/190-managing-users/03-managing-user-data/00-intro.markdown
discover/portal/articles/190-managing-users/03-user-groups/03-user-group-sites.markdown
discover/portal/articles/210-setting-up/01-system-settings/00-intro.markdown
discover/portal/articles/210-setting-up/01-system-settings/02-config-files/00-intro.markdown
discover/portal/articles/210-setting-up/01-system-settings/02-config-files/02-factory-configurations.markdown
discover/portal/articles/210-setting-up/01-system-settings/03-server-administration/00-intro.markdown
discover/portal/articles/210-setting-up/02-instance-settings/04-authentication.markdown

fixing links in discover/portal

fixed some links

---

develop/tutorials/articles-dxp/100-tooling/05-maven/01-installing-liferay-maven-artifacts.markdown
discover/deployment/articles-dxp/00-deploying-liferay/06-installing-liferay-portal-on-jboss-eap.markdown
discover/deployment/articles-dxp/00-deploying-liferay/07-installing-liferay-on-tc-server.markdown
discover/deployment/articles-dxp/00-deploying-liferay/08-installing-liferay-on-weblogic.markdown
discover/deployment/articles-dxp/00-deploying-liferay/09-installing-liferay-on-websphere.markdown
discover/deployment/articles-dxp/05-maintaining-liferay/01-patching-liferay-dxp/02-using-the-patching-tool/00-using-the-patching-tool-intro.markdown
discover/deployment/articles-dxp/05-maintaining-liferay/01-patching-liferay-dxp/02-using-the-patching-tool/01-installing-patches.markdown
discover/deployment/articles-dxp/05-maintaining-liferay/01-patching-liferay-dxp/03-configuring-the-patching-tool/00-configuring-the-patching-tool-intro.markdown
discover/deployment/articles-dxp/05-maintaining-liferay/01-patching-liferay-dxp/03-configuring-the-patching-tool/03-installing-patches-on-the-liferay-war.markdown
discover/deployment/articles-dxp/05-maintaining-liferay/01-patching-liferay-dxp/04-keeping-up-with-fix-packs.markdown
discover/deployment/articles-dxp/08-lcs/01-lcs-preconfiguration.markdown
discover/deployment/articles/00-deploying-liferay/04-installing-liferay-portal-on-tomcat.markdown
discover/deployment/articles/00-deploying-liferay/05-installing-liferay-portal-on-wildfly.markdown

https://issues.liferay.com/browse/LRDOCS-5453

LRDOCS-5453 Update DXP downloads URL

---

discover/analytics-cloud/articles/04-analyzing-touchpoints/01-page-analytics.markdown
discover/analytics-cloud/articles/04-analyzing-touchpoints/05-blogs-analytics.markdown
discover/analytics-cloud/articles/04-analyzing-touchpoints/07-web-content-analytics.markdown

- Refer to the correct image in Web Content Analytics
- Fix formatting.
- Remove sidebar syntax for now.
cc @rbohl
https://issues.liferay.com/browse/LRDOCS-5313

LRDOCS-5313 Analytics Cloud: Fix touchpoint articles

---

discover/analytics-cloud/articles/01-what-is-liferay-analytics-cloud/00-generating-new-business-using-analytics-intro.markdown
discover/analytics-cloud/articles/02-getting-started/01-managing-data-sources.markdown
discover/analytics-cloud/articles/02-getting-started/02-adding-a-liferay-dxp-data-source.markdown

Jon Lee requested and reviewed these changes. Thanks!
https://issues.liferay.com/browse/LRDOCS-5311

LRDOCS-5311 AC: DXP 7.0 is the only supported DXP version.

---

discover/portal/articles-dxp/110-collaboration/02-sync/01-administering-sync/01-prerequisites.markdown

Adding note to DXP Sync doc

---

develop/tutorials/articles/150-web-services/00-intro.markdown
develop/tutorials/articles/150-web-services/06-json-web-services-invoker.markdown

LRDOCS-4367 Update JSON web services invoker article

LRDOCS-4367 Update JSON web services invoker article

---

develop/tutorials/articles/150-web-services/00-intro.markdown
develop/tutorials/articles/150-web-services/08-configuring-json-web-services.markdown

LRDOCS-4369 Update configuring JSON web services article to 7.1

LRDOCS-4369 Update configuring JSON web services article to 7.1

---

develop/tutorials/articles/01-introduction-to-liferay-development/04-configuring-dependencies.markdown
develop/tutorials/articles/120-customizing/03-overriding-language-keys/02-overriding-a-modules-language-keys.markdown

https://issues.liferay.com/browse/LRDOCS-5414

LRDOCS-5414 Fix overriding module language keys

---

develop/reference/articles/03-portlet-descriptors.markdown

https://issues.liferay.com/browse/LRDOCS-5097
https://issues.liferay.com/browse/LRDOCS-5252

 LRDOCS-5097, 5252 - 70 OSGi property fixes

---

develop/tutorials/articles/100-tooling/02-liferay-ide/00-liferay-ide-intro.markdown
develop/tutorials/articles/100-tooling/02-liferay-ide/08-managing-projects-with-liferay-ide.markdown
develop/tutorials/articles/100-tooling/02-liferay-ide/12-searching-liferay-portal-source-in-liferay-ide.markdown
develop/tutorials/articles/100-tooling/02-liferay-ide/13-debugging-liferay-portal-source-in-liferay-ide.markdown

https://issues.liferay.com/browse/LRDOCS-5492

LRDOCS-5492 Remove most "CE" references for Dev Studio

---

develop/tutorials/articles/110-portlets/00-portlets-intro.markdown
develop/tutorials/articles/360-osgi-basics-for-liferay-development/03-importing-packages.markdown

https://issues.liferay.com/browse/LRDOCS-5500
cc @rotty3000

LRDOCS-5500 Importing Packages: using portable java contracts

---

develop/reference/articles/200-breaking-changes.markdown
discover/analytics-cloud/articles/01-what-is-liferay-analytics-cloud/00-generating-new-business-using-analytics-intro.markdown
discover/analytics-cloud/articles/02-getting-started/02-adding-a-liferay-dxp-data-source.markdown

Sent brianchandotcom/liferay-portal#61509

LPS-83185 New Breaking Change

---

discover/portal/articles/190-managing-users/03-user-groups/00-intro.markdown

https://issues.liferay.com/browse/LRDOCS-5433

change example for user groups

---

develop/tutorials/articles/110-portlets/15-javascript/02-es2015/01-preparing-your-js-files-for-es2015.markdown
develop/tutorials/articles/110-portlets/15-javascript/02-es2015/02-using-es2015-modules-in-your-portlets.markdown
develop/tutorials/articles/240-javascript-module-loaders/10-liferay-amd-module-loader.markdown

@sez11a this includes PRS:
https://github.com/liferay/liferay-docs/pull/424
https://github.com/liferay/liferay-docs/pull/425

Community theme doc fixes

---

develop/tutorials/articles/02-from-liferay-6-to-liferay-7/01-what-hasnt-changed-and-what-has.markdown
develop/tutorials/articles/02-from-liferay-6-to-liferay-7/02-benefits-of-liferay-7-for-liferay-6-developers.markdown
develop/tutorials/articles/02-from-liferay-6-to-liferay-7/04-improved-developer-tooling/01-from-the-plugins-sdk-to-workspace.markdown
develop/tutorials/articles/02-from-liferay-6-to-liferay-7/06-planning-plugin-upgrades-and-optimizations/00-planning-plugin-upgrades-and-optimizations-intro.markdown
develop/tutorials/articles/02-from-liferay-6-to-liferay-7/07-upgrading-plugins-to-liferay-7/02-resolving-a-plugins-dependencies.markdown
develop/tutorials/articles/02-from-liferay-6-to-liferay-7/07-upgrading-plugins-to-liferay-7/04-upgrading-portlet-plugins/05-upgrading-a-servlet-based-portlet.markdown
develop/tutorials/articles/02-from-liferay-6-to-liferay-7/08-optimizing-plugins-for-liferay-portal-7/01-migrating-traditional-plugins-to-workspace-web-applications.markdown
develop/tutorials/articles/100-tooling/02-liferay-ide/16-using-front-end-development-code-assist-features-in-ide.markdown
develop/tutorials/articles/100-tooling/03-blade-cli/00-intro.markdown
develop/tutorials/articles/100-tooling/03-blade-cli/03-creating-a-liferay-workspace-with-blade-cli.markdown
develop/tutorials/articles/100-tooling/04-liferay-workspace/00-liferay-workspace-intro.markdown
develop/tutorials/articles/180-themes-and-layout-templates/02-layout-templates/04-including-layout-templates-with-a-theme.markdown

https://issues.liferay.com/browse/LRDOCS-5493

LRDOCS-5493 Update docs to reflect removal of Plugins SDK

---

discover/deployment/articles/06-upgrading-to-liferay-7-1/02-preparing-for-upgrade-to-liferay-7-1.markdown

https://issues.liferay.com/browse/LRDOCS-5487

LRDOCS-5487 Add staging publication as a pre-upgrade step

---

discover/deployment/articles/06-upgrading-liferay/02-preparing-for-upgrade.markdown

https://issues.liferay.com/browse/LRDOCS-5487

LRDOCS-5487 Add staging publication as a pre-upgrade step | 7.0.x

---

develop/reference/articles/03-back-end/00-back-end-intro.markdown
develop/reference/articles/03-back-end/03-portlet-descriptor-to-osgi-service-property-map.markdown

This is the first installment of the Back-end references.  Neil's contributed a lot of important mappings.
Import to Develop > Reference.
Thanks!
https://issues.liferay.com/browse/LRDOCS-5481
https://issues.liferay.com/browse/LRDOCS-5484
https://issues.liferay.com/browse/LRDOCS-5097
https://issues.liferay.com/browse/LRDOCS-5208
https://issues.liferay.com/browse/LRDOCS-5252
https://issues.liferay.com/browse/LRDOCS-5255
https://issues.liferay.com/browse/LRDOCS-5269
https://issues.liferay.com/browse/LRDOCS-5270
https://issues.liferay.com/browse/LRDOCS-5271
https://issues.liferay.com/browse/LRDOCS-5278
https://issues.liferay.com/browse/LRDOCS-5326
https://issues.liferay.com/browse/LRDOCS-5357
https://issues.liferay.com/browse/LRDOCS-5358
https://issues.liferay.com/browse/LRDOCS-5352

LRDOCS-5481 LRDOCS-5484 Back-end refs intro and descriptor map article

---

discover/portal/articles/190-managing-users/00-intro.markdown

https://issues.liferay.com/browse/LRDOCS-5306, add anonymous user note

LRDOCS-5306, anonymous user

---

build-common.xml

https://issues.liferay.com/browse/LRDOCS-5508

LRDOCS-5508 Dist targets should number images outside of Zip too

---

discover/deployment/articles-dxp/08-liferay-enterprise-search/09-xpack-monitoring.markdown

htttps://issues.liferay.com/browse/LRDOCS-5499, based on a contributed solution from @JosemariaMunoz. Thanks!

LRDOCS-5499, clarifiactions to 7.0 X-Pack Monitoring

---

develop/reference/articles/03-back-end/00-back-end-intro.markdown
develop/reference/articles/03-back-end/02-third-party-packages-portal-exports.markdown

Import to Develop > Reference.
Thanks!
https://issues.liferay.com/browse/LRDOCS-5483

Developer Reference: Third party packages portal exports

---

discover/portal/articles/140-managing-apps/05-blacklisting-osgi-modules.markdown

https://issues.liferay.com/browse/LRDOCS-5542

LRDOCS-5542 7.0 fix blacklist BSN for LPKGs

---

develop/reference/articles-dxp/03-back-end/00-back-end-intro.markdown
develop/reference/articles-dxp/03-back-end/04-classes-moved-from-portal-service-jar.markdown
develop/reference/articles/03-back-end/00-back-end-intro.markdown
develop/reference/articles/03-back-end/04-classes-moved-from-portal-service-jar.markdown
develop/tutorials/articles/01-introduction-to-liferay-development/04-configuring-dependencies.markdown
develop/tutorials/articles/02-from-liferay-6-to-liferay-7/07-upgrading-plugins-to-liferay-7/01-adapting-to-liferay-7s-api.markdown
develop/tutorials/articles/02-from-liferay-6-to-liferay-7/07-upgrading-plugins-to-liferay-7/02-resolving-a-plugins-dependencies.markdown

https://issues.liferay.com/browse/LRDOCS-5485

LRDOCS-5485 Generated table ref docs on classes moved from portal-service.jar

---

develop/tutorials/articles-dxp/380-troubleshooting/17-patching-dxp-source-code.markdown
develop/tutorials/articles/380-troubleshooting/00-troubleshooting-intro.markdown

Got this PR from @jhinkey, looks good to me!

LRDOCS-4694 7.1 troubleshooting - patching dxp

---

discover/portal/articles/100-web-experience-management/03-creating-web-content/02-designing-uniform-content/02-designing-web-content-with-templates/04-template-permissions.markdown

https://issues.liferay.com/browse/LRDOCS-5533

LRDOCS-5533 added more detail to warning

---

discover/analytics-cloud/articles/04-analyzing-touchpoints/01-page-analytics.markdown

https://issues.liferay.com/browse/LRDOCS-5559, added definitions to the timer period filters in Analytics Cloud, Page Analytics article. cc @jhinkey

LRDOCS-5559, define AC time periods

---

discover/deployment/articles/01-installation-and-setup/14-installing-liferay-on-jboss-7.1.markdown

https://issues.liferay.com/browse/LRDOCS-5563

LRDOCS-5563 JBoss configuration update | 6.2.x

---

discover/deployment/articles-dxp/05-maintaining-liferay/01-patching-liferay-dxp/03-configuring-the-patching-tool/02-patching-tool-advanced-configuration.markdown

Hey, this is a "bugfix" for the Patching Tool documentation for DXP.
Please see https://issues.liferay.com/browse/LRSUPPORT-24954

LRDOCS-5566

---

discover/deployment/articles-dxp/05-maintaining-liferay/01-patching-liferay-dxp/02-using-the-patching-tool/01-installing-patches.markdown

https://issues.liferay.com/browse/LRDOCS-5564

LRDOCS-5564 keep patch zipped up

---

develop/tutorials/articles/150-web-services/09-soap-web-services.markdown

This is causing our Ant build to fail.

Fix malformed image path

---

develop/tutorials/articles/110-portlets/12-automatic-single-page-application.markdown

LRDOCS-5515 add `data-senna-track` attribute info

---

develop/tutorials/articles/180-themes-and-layout-templates/01-themes/05-upgrading-7.0-themes-7.1/05-bootstrap-lexicon-compatibility-layer.markdown

Supersedes https://github.com/sez11a/liferay-docs/pull/3393

LRDOCS-5530 fix merge conflict

---

develop/tutorials/articles/101-plugins-sdk/01-setting-up-the-plugins-sdk.markdown

https://issues.liferay.com/browse/LRDOCS-5539

LRDOCS-5539 Update Plugins SDK Download Instructions | 6.2.x

---

develop/tutorials/articles/380-troubleshooting/06-adjusting-module-logging.markdown
develop/tutorials/articles/380-troubleshooting/07-implementing-logging.markdown

These troubleshooting articles explain how to configure and implement logging. Thanks!
https://issues.liferay.com/browse/LRDOCS-4684
https://issues.liferay.com/browse/LRDOCS-4685

LRDOCS-4684-5 troubleshooting logging

---

develop/tutorials/articles/380-troubleshooting/15-database-not-ready.markdown

https://issues.liferay.com/browse/LRDOCS-4692

LRDOCS-4692 troubleshooting that the database is not ready

---

develop/tutorials/articles/130-service-builder/02-service-builder-persistence/06-custom-sql.markdown

https://issues.liferay.com/browse/LRDOCS-5511

LRDOCS-5511 Fix using CustomSQL

---

develop/tutorials/articles/180-themes-and-layout-templates/01-themes/03-managing-theme-resources/02-creating-a-sitemap/00-creating-a-sitemap-intro.markdown
develop/tutorials/articles/180-themes-and-layout-templates/04-clay-and-themes/01-importing-clay-css-in-a-theme.markdown
develop/tutorials/articles/180-themes-and-layout-templates/04-clay-and-themes/02-integrating-third-party-themes-with-clay.markdown
develop/tutorials/articles/190-javascript-module-loaders/03-using-external-libraries.markdown
develop/tutorials/articles/320-wysiwyg-editors/03-adding-new-behavior-to-an-editor.markdown

@sez11a this includes PRs:
https://github.com/liferay/liferay-docs/pull/432
https://github.com/liferay/liferay-docs/pull/433
https://github.com/liferay/liferay-docs/pull/434 (7.1 changes)
https://github.com/liferay/liferay-docs/pull/435

Community contributions

---

develop/tutorials/articles/260-themes-and-layout-templates/01-themes/03-importing-resources-with-a-theme.markdown

submission https://github.com/liferay/liferay-docs/pull/434 (7.0 changes)

Community contribution pr 434

---

develop/tutorials/articles/180-themes-and-layout-templates/01-themes/01-creating-themes/00-creating-themes-intro.markdown

LRDOCS-5536 Add Ruby Sass configuration information

---

discover/commerce/articles/020-catalog-management/02-products/03-skus.markdown
discover/commerce/articles/030-user-segmentation.markdown
discover/commerce/articles/040-pricing/01-discounts.markdown
discover/commerce/articles/040-pricing/02-price-lists.markdown
discover/commerce/articles/050-warehouses.markdown
discover/commerce/articles/060-payment-methods/00-payment-methods-intro.markdown
discover/commerce/articles/070-shipping-methods/01-flat-rate-shipping.markdown
discover/commerce/articles/080-taxes.markdown

https://issues.liferay.com/browse/LRDOCS-5603

LRDOCS-5603-commerce-updates

---

discover/deployment/articles/06-upgrading-to-liferay-7-1/02-preparing-for-upgrade-to-liferay-7-1.markdown
discover/deployment/articles/06-upgrading-to-liferay-7-1/04-post-upgrade-tasks.markdown

Import to: Discover > Deployment > 7.1
https://issues.liferay.com/browse/LRDOCS-5569
Thanks!

LRDOCS-5569 re-enable search indexes after upgrade

---

discover/deployment/articles/06-upgrading-liferay/02-preparing-for-upgrade.markdown
discover/deployment/articles/06-upgrading-liferay/03-running-the-upgrade-process.markdown

Import to: Discover > Deployment > 7.0
https://issues.liferay.com/browse/LRDOCS-5569
Thanks!

LRDOCS-5569 7.0 re-enable search indexes after upgrade

---

discover/deployment/articles-dxp/02-installing-liferay/08-installing-liferay-on-weblogic.markdown

https://issues.liferay.com/browse/LRDOCS-5575

LRDOCS-5575 7.0 set utf8 file encoding in setDomainEnv.sh

---

discover/deployment/articles-dxp/00-deploying-liferay/08-installing-liferay-on-weblogic.markdown

https://issues.liferay.com/browse/LRDOCS-5575

LRDOCS-5575 set utf8 file encoding in setDomainEnv.sh

---

develop/reference/articles/07-screenlets-in-liferay-screens-for-android/07-asset-list-screenlet-for-android.markdown
develop/reference/articles/08-screenlets-in-liferay-screens-for-ios/07-asset-list-screenlet-for-ios.markdown

Updating supported asset types for Asset List Screenlet in both Android and iOS. 
cc @dgarciasarai

LRDOCS-5604 Asset List Screenlet update

---

discover/deployment/articles-dxp/08-liferay-enterprise-search/08-xpack-security.markdown

https://issues.liferay.com/browse/LRDOCS-5577, cc @lipusz

LRDOCS-5577, add note that ES and DXP must share keys and certs for SSL

---

develop/tutorials/articles/270-product-navigation/00-intro.markdown

https://issues.liferay.com/browse/LRDOCS-5608

LRDOCS-5608 Change Peronsal to Personal

---

discover/analytics-cloud/articles/04-analyzing-touchpoints/04-forms-analytics.markdown

https://issues.liferay.com/browse/LRDOCS-5607 cc @jhinkey

LRDOCS-5607 ac typo

---

develop/reference/articles/06-themes/00-themes-intro.markdown

rename duplicate header

---

discover/portal/articles/130-forms/10-success-pages.markdown
discover/portal/articles/130-forms/14-validation.markdown
discover/portal/articles/130-forms/18-form-permissions.markdown
discover/portal/articles/130-forms/19-styling-forms.markdown

https://issues.liferay.com/browse/LRDOCS-5546. cc @natocesarrego

LRDOCS-5546, advanced forms SME review

---

develop/tutorials/articles/100-tooling/04-liferay-workspace/09-updating-default-plugins-provided-by-workspace.markdown

https://issues.liferay.com/browse/LRDOCS-5386

LRDOCS-5386 Updating Tools in Workspace

---

discover/commerce/articles-dxp/090-site-initializers/02-customer-portal/01-accounts-management.markdown
discover/commerce/articles/020-catalog-management/01-product-categories.markdown
discover/commerce/articles/020-catalog-management/02-products/00-products-intro.markdown
discover/commerce/articles/020-catalog-management/02-products/01-images.markdown
discover/commerce/articles/020-catalog-management/02-products/02-adding-options-to-products.markdown
discover/commerce/articles/020-catalog-management/02-products/03-skus.markdown
discover/commerce/articles/020-catalog-management/02-products/04-attachments.markdown
discover/commerce/articles/020-catalog-management/02-products/05-product-relations.markdown
discover/commerce/articles/020-catalog-management/02-products/06-configuration.markdown
discover/commerce/articles/020-catalog-management/03-options.markdown
discover/commerce/articles/020-catalog-management/05-catalog-rules.markdown
discover/commerce/articles/040-pricing/00-pricing-intro.markdown
discover/commerce/articles/040-pricing/01-discounts.markdown
discover/commerce/articles/040-pricing/02-price-lists.markdown
discover/commerce/articles/050-warehouses.markdown
discover/commerce/articles/060-payment-methods/00-payment-methods-intro.markdown
discover/commerce/articles/070-shipping-methods/01-flat-rate-shipping.markdown
discover/commerce/articles/070-shipping-methods/05-measurement-units.markdown
discover/commerce/articles/080-taxes.markdown
discover/commerce/articles/100-storefront/00-setting-up-a-storefront-intro.markdown
discover/commerce/articles/100-storefront/02-category-detail-page.markdown
discover/commerce/articles/110-settings/00-settings-intro.markdown
discover/commerce/articles/110-settings/01-availability-estimates.markdown
discover/commerce/articles/110-settings/03-currencies.markdown
discover/commerce/articles/110-settings/04-notifications.markdown

https://issues.liferay.com/browse/LRDOCS-5622

LRDOCS-5622 links

---

develop/tutorials/articles/02-from-liferay-6-to-liferay-7/07-upgrading-plugins-to-liferay-7/06-upgrading-themes/00-upgrading-themes-intro.markdown
develop/tutorials/articles/180-themes-and-layout-templates/01-themes/04-upgrading-6.2-themes-7.1/00-upgrading-6.2-themes-to-7.1-intro.markdown
develop/tutorials/articles/180-themes-and-layout-templates/01-themes/04-upgrading-6.2-themes-7.1/02-updating-6.2-project-metadata.markdown
develop/tutorials/articles/180-themes-and-layout-templates/01-themes/04-upgrading-6.2-themes-7.1/03-updating-6.2-css-code/01-updating-6.2-css-file-names.markdown
develop/tutorials/articles/180-themes-and-layout-templates/01-themes/04-upgrading-6.2-themes-7.1/03-updating-6.2-css-code/02-updating-6.2-css-rules-and-imports.markdown
develop/tutorials/articles/180-themes-and-layout-templates/01-themes/04-upgrading-6.2-themes-7.1/03-updating-6.2-css-code/03-updating-6.2-responsiveness.markdown
develop/tutorials/articles/180-themes-and-layout-templates/01-themes/04-upgrading-6.2-themes-7.1/04-updating-6.2-theme-templates.markdown
develop/tutorials/articles/180-themes-and-layout-templates/01-themes/04-upgrading-6.2-themes-7.1/05-updating-the-resources-importer.markdown
develop/tutorials/articles/270-product-navigation/01-customizing-the-product-menu/00-customizing-the-product-menu-intro.markdown
develop/tutorials/articles/320-wysiwyg-editors/04-alloy-editor/01-adding-buttons-to-the-alloyeditor/02-adding-buttons-to-the-alloyeditor-add-toolbar.markdown

@sez11a supersedes https://github.com/sez11a/liferay-docs/pull/3485

LRDOCS-5624 fix Front-End broken links

---

discover/portal/articles/100-web-experience-management/02-building-a-site/07-managing-site-members/00-managing-membership-intro.markdown
discover/portal/articles/100-web-experience-management/02-building-a-site/07-managing-site-members/01-adding-members-to-sites.markdown
discover/portal/articles/100-web-experience-management/02-building-a-site/07-managing-site-members/02-managing-site-user-settings.markdown
discover/portal/articles/100-web-experience-management/02-building-a-site/07-managing-site-members/03-creating-teams-to-empower-site-members.markdown

https://issues.liferay.com/browse/LRDOCS-4556

LRDOCS-4556 Added missing section

---

discover/deployment/articles/06-upgrading-to-liferay-7-1/99-deprecated-apps.markdown

Search Portlet added and DDL Form removed, per @rbohl

Minor additions to deprecation doc

---

discover/portal/articles/220-polls.markdown

https://issues.liferay.com/browse/LRDOCS-5548 polls cc @natocesarrego

LRDOCS-5548 polls sme review editing

---

discover/deployment/articles/01-installing-search-engine/04-preparing-to-install.markdown

https://issues.liferay.com/browse/LRDOCS-4742 cc @BryanEngler

LRDOCS-4742 preparing to install es

---

discover/deployment/articles/01-installing-search-engine/05-tuning.markdown

https://issues.liferay.com/browse/LRDOCS-4744 cc @arboliveira

LRDOCS-4744 tuning es

---

develop/tutorials/articles/290-configuration/01-making-apps-configurable/04-reading-configurations-portlet.markdown

LDN feedback on Reading Config Values in a MVC Portlet--small change, no ticket. Change approved by @drewbrokke.

fix Class parameter in example method call--LDN feedback

---

develop/tutorials/articles/310-troubleshooting/00-troubleshooting-intro.markdown

https://issues.liferay.com/browse/LRDOCS-4678
Fixed formatting for one of the FAQ questions that wasn't using the expand/collapse HTML.

7.0 fix troubleshooting intro
