sez11a/liferay-docs

develop/tutorials/articles/320-wysiwyg-editors/03-adding-new-behavior-to-an-editor.markdown

LRDOCS-5642 add CKEditor add remove empty note

---

develop/tutorials/articles/230-wysiwyg-editors/03-adding-new-behavior-to-an-editor.markdown

LRDOCS-5642 7.0.x add empty note

---

discover/deployment/articles-dxp/05-maintaining-liferay/01-patching-liferay-dxp/02-using-the-patching-tool/02-working-with-patches.markdown

https://issues.liferay.com/browse/LRDOCS-5614

LRDOCS-5614 Provide more info in support tickets

---

develop/tutorials/articles/180-themes-and-layout-templates/01-themes/05-upgrading-7.0-themes-7.1/05-bootstrap-lexicon-compatibility-layer.markdown

LRDOCS-5652 BS3 compatibility layer update

---

develop/tutorials/articles/120-service-builder/02-service-builder-persistence/05-developing-custom-sql-queries.markdown

The 7.1 instructions are backported for 7.0 for using the CustomSQL class.
https://issues.liferay.com/browse/LRDOCS-5659

LRDOCS-5659 7.0 update the instructions to use CustomSQL class

---

develop/reference/articles/03-back-end/01-portal-startup-phases.markdown
develop/tutorials/articles/360-osgi-basics-for-liferay-development/06-waiting-on-lifecycle-events.markdown

https://issues.liferay.com/browse/LRDOCS-5527

LRDOCS-5527 Liferay startup phases

---

develop/tutorials/articles/180-themes-and-layout-templates/01-themes/02-developing-themes/16-packaging-independent-ui-resources-for-your-site.markdown

LRDOCS-5664 link to Maven Central artifact for now

---

develop/tutorials/articles/280-workflow/01-creating-workflow-definitions/02-tasks.markdown

https://issues.liferay.com/browse/LRDOCS-5044, cc @natocesarrego

LRDOCS-5044 scripts inside task timers

---

discover/deployment/articles-dxp/08-lcs/01-lcs-preconfiguration.markdown

Adding section to LCS preconfiguration article on WebSphere config steps

LRDOCS-5672 LCS WebSphere instructions

---

discover/deployment/articles-dxp/09-liferay-connected-services/01-lcs-preconfiguration.markdown

Applying changes from https://github.com/sez11a/liferay-docs/pull/3539 to 7.0.x

LRDOCS-5679 LCS WebSphere config - 7.0.x

---

discover/deployment/articles/06-upgrading-to-liferay-7-1/02-preparing-for-upgrade-to-liferay-7-1.markdown

https://issues.liferay.com/browse/LRDOCS-5628

LRDOCS-5628 install latest fix pack before data upgrade

---

discover/deployment/articles/06-upgrading-liferay/02-preparing-for-upgrade.markdown

https://issues.liferay.com/browse/LRDOCS-5628

LRDOCS-5628 7.0 install the latest fix pack before data upgrade

---

discover/portal/articles/20-errata/01-errata-for-using-liferay-portal-6-1.markdown

Still more to come for this ticket.

LRDOCS-5662 Replace full URLs with relative ones | 6.1.x

---

develop/tutorials/articles/380-troubleshooting/00-troubleshooting-intro.markdown

https://issues.liferay.com/browse/LRDOCS-4678

LRDOCS-4678 Update the FAQ with questions and answers.

---

guidelines/01-creating-docs-for-liferay.markdown

@sez11a My previous fix apparently had an error...remove `\` typo from URLS. Tested. Everything runs smoothly now :-)

LRDOCS-5677 SF

---

discover/portal/articles/230-calendar/00-calendar-intro.markdown
discover/portal/articles/230-calendar/02-calendar-resources-and-porting.markdown

https://issues.liferay.com/browse/LRDOCS-5561, cc @natocesarrego

LRDOCS-5561, calendar review

---

discover/analytics-cloud/articles/04-analyzing-touchpoints/00-analytics-intro.markdown

https://issues.liferay.com/browse/LRDOCS-5695, cc @rafaelfe

LRDOCS-5695, remove Touchpoint terminology

---

develop/tutorials/articles/180-themes-and-layout-templates/01-themes/04-upgrading-6.2-themes-7.1/01-running-the-theme-upgrade-task-for-6.2-themes.markdown
develop/tutorials/articles/180-themes-and-layout-templates/01-themes/05-upgrading-7.0-themes-7.1/01-running-the-theme-upgrade-task.markdown

@jbalsas here are the upgrade docs updates. Please let me know if anything else needs added/removed before sending this forward. Thanks!

LRDOCS-5668 themes sdk update

---

develop/reference/articles/18-ckeditor-plugin-reference.markdown

Lrdocs 5696 ckeditor inline note

---

develop/tutorials/articles/200-integrating-with-front-end-frameworks/00-front-end-frameworks-intro.markdown
develop/tutorials/articles/200-integrating-with-front-end-frameworks/01-integrating-with-react.markdown
develop/tutorials/articles/200-integrating-with-front-end-frameworks/02-integrating-with-vue-js.markdown
develop/tutorials/articles/200-integrating-with-front-end-frameworks/03-integrating-with-angular-js.markdown

@sez11a this includes tickets:
https://issues.liferay.com/browse/LRDOCS-5568
https://issues.liferay.com/browse/LRDOCS-5644
https://issues.liferay.com/browse/LRDOCS-5645
https://issues.liferay.com/browse/LRDOCS-5646
cc @jbalsas

LRDOCS-5568 Integrating with Front-End frameworks

---

develop/tutorials/articles/280-workflow/01-creating-workflow-definitions/02-tasks.markdown
develop/tutorials/articles/280-workflow/01-creating-workflow-definitions/03-notifications.markdown

https://issues.liferay.com/browse/LRDOCS-2225, cc @natocesarrego

LRDOCS-2225 cc/bcc workflow notification emails

---

develop/tutorials/articles/110-portlets/02-soy-portlets/01-creating-a-soy-portlet.markdown

LRDOCS-5683 add note about unique template namespaces

---

develop/tutorials/articles/260-themes-and-layout-templates/01-themes/01-themes-generator.markdown

LRDOCS-5688 placed note in sidebar

---

develop/tutorials/articles/180-themes-and-layout-templates/01-themes/02-developing-themes/04-changing-the-base-theme.markdown

LRDOCS-5688 add note about classic theme

---

develop/tutorials/articles/110-portlets/08-friendly-urls/00-making-urls-friendlier-intro.markdown

https://issues.liferay.com/browse/LRDOCS-3613

LRDOCS-3613 7.0 Show pattern for instanceable portlet. Don't end in slash.

---

develop/tutorials/articles/110-portlets/06-making-urls-friendlier.markdown

https://issues.liferay.com/browse/LRDOCS-3613

LRDOCS-3613 7.1 Show pattern for instanceable portlet. Don't end in slash.

---

discover/deployment/articles-dxp/05-maintaining-liferay/01-patching-liferay-dxp/02-using-the-patching-tool/02-working-with-patches.markdown
discover/deployment/articles-dxp/05-maintaining-liferay/01-patching-liferay-dxp/03-configuring-the-patching-tool/01-patching-tool-basic-configuration.markdown
discover/deployment/articles-dxp/05-maintaining-liferay/01-patching-liferay-dxp/03-configuring-the-patching-tool/02-patching-tool-advanced-configuration.markdown
discover/deployment/articles-dxp/05-maintaining-liferay/01-patching-liferay-dxp/03-configuring-the-patching-tool/03-installing-patches-on-the-liferay-war.markdown

https://issues.liferay.com/browse/LRDOCS-5687

LRDOCS-5687 Update DXP patching tool examples to 7.1

---

develop/reference/articles/04-front-end/02-ckeditor-plugin-reference-guide.markdown

Sent 7.0 changes in https://github.com/sez11a/liferay-docs/pull/3558 
cc @jbalsas

LRDOCS-5696 port CKEditor note to 7.1

---

develop/tutorials/articles/360-other-backend-frameworks/01-device-recognition-api.markdown

https://issues.liferay.com/browse/LRDOCS-5701

LRDOCS-5701 JVM requirements for LMDD Enterprise

---

develop/tutorials/articles/340-testing/00-testing-intro.markdown
develop/tutorials/articles/340-testing/02-injecting-service-components-into-tests.markdown

Ported tutorials to 7.1
https://issues.liferay.com/browse/LRDOCS-4653
https://issues.liferay.com/browse/LRDOCS-4656

LRDOCS-4653, LRDOCS-4656  Injecting service components into tests

---

develop/tutorials/articles/02-from-liferay-6-to-liferay-7/07-upgrading-plugins-to-liferay-7/01-adapting-to-liferay-7s-api.markdown

https://issues.liferay.com/browse/LRDOCS-5700

LRDOCS-5700 Note IDE versioning information for Code Upgrade Tool | 7.0.x

---

discover/deployment/articles-dxp/00-deploying-liferay/06-installing-liferay-portal-on-jboss-eap.markdown
discover/deployment/articles-dxp/00-deploying-liferay/07-installing-liferay-on-tc-server.markdown
discover/deployment/articles-dxp/00-deploying-liferay/08-installing-liferay-on-weblogic.markdown
discover/deployment/articles-dxp/00-deploying-liferay/09-installing-liferay-on-websphere.markdown
discover/deployment/articles/00-deploying-liferay/03-installing-liferay-manually.markdown
discover/deployment/articles/00-deploying-liferay/04-installing-liferay-portal-on-tomcat.markdown
discover/deployment/articles/00-deploying-liferay/05-installing-liferay-portal-on-wildfly.markdown

https://issues.liferay.com/browse/LRDOCS-5415

LRDOCS-5415 Add note on adjusting logging for excessive messages. 

---

develop/tutorials/articles/100-tooling/04-liferay-workspace/05-managing-the-target-platform-for-liferay-workspace.markdown
develop/tutorials/articles/100-tooling/04-liferay-workspace/07-validating-modules-against-the-target-platform/00-intro.markdown

BChan has requested a large reorganization of the code for Target Platform. This has made BOM generation slow and the feature unstable. I've added notes to warn that this feature is provisional until the reorg is finished.
https://issues.liferay.com/browse/LRDOCS-5720

LRDOCS-5720 Note that Target Platform is not officially supported

---

develop/reference/articles/09-liferay-faces/01-liferay-faces-version-scheme.markdown

https://issues.liferay.com/browse/LRDOCS-5719

LRDOCS-5719 Update Faces version scheme

---

discover/deployment/articles-dxp/03-configuring-liferay/03-liferay-clustering.markdown

https://issues.liferay.com/browse/LRDOCS-5746

7.0 LRDOCS-5746 Set cluster.link.enabled=true whether cluster link multicast or unicast

---

discover/deployment/articles-dxp/03-configuring-liferay/03-liferay-portal-clustering/04-enabling-cluster-link.markdown

https://issues.liferay.com/browse/LRDOCS-5746

7.1 LRDOCS-5746 Set cluster.link.enabled=true whether cluster link multicast or unicast

---

develop/tutorials/articles/02-from-liferay-70-to-71/00-from-liferay-70-to-71-intro.markdown
develop/tutorials/articles/02-from-liferay-70-to-71/01-upgrading-plugins-from-liferay-70-to-71/00-upgrading-plugins-from-liferay-70-to-71.markdown

The first is a quick intro to upgrading plugins to 7.1 and the other gives the steps for upgrading a plugin. Thanks!  
https://issues.liferay.com/browse/LRDOCS-5656 From Liferay 7.0 to 7.1 (intro)
https://issues.liferay.com/browse/LRDOCS-5665 Upgrading plugins from Liferay 7.0 to 7.1

LRDOCS-5656 LRDOCS-5665 From Liferay 7.0 to 7.1

---

develop/tutorials/articles/180-themes-and-layout-templates/01-themes/02-developing-themes/10-creating-a-thumbnail-preview-for-your-theme.markdown
develop/tutorials/articles/180-themes-and-layout-templates/01-themes/02-developing-themes/11-creating-color-schemes-for-your-theme.markdown
develop/tutorials/articles/180-themes-and-layout-templates/01-themes/02-developing-themes/12-making-themes-configurable-with-theme-settings.markdown

@sez11a this also include LRDOCS-5756
cc @jbalsas

LRDOCS-5755 color scheme doc fix

---

discover/portal/articles-dxp/160-targeting-content-to-your-audience/01-managing-user-segments.markdown

https://issues.liferay.com/browse/LRDOCS-5673

replaced "develop" with "discover" to fix broken link

---

discover/deployment/articles/01-installing-search-engine/00-intro.markdown

Use token, add link

---

discover/portal/articles/100-web-experience-management/02-creating-web-content/01-publishing-basic-web-content.markdown

https://issues.liferay.com/browse/LRDOCS-5754

remove erroneous statement about autosave

---

develop/tutorials/articles/385-troubleshooting-front-end-dev/00-troubleshooting-front-end-dev-intro.markdown

@sez11a this includes:
LRDOCS-5654
LRDOCS-5693
LRDOCS-5698
cc @jhinkey
cc @jbalsas

LRDOCS-5654 Front-End FAQ

---

develop/reference/articles/04-front-end/01-liferay-npm-bundler/08-changes-between-bundler-1.x-and-2.x.markdown
develop/tutorials/articles/110-portlets/07-using-javascript-in-your-portlets/03-using-npm-in-your-portlets/02-migrating-liferay-npm-bundler-projects-from-1x-to-2x.markdown

LRDOCS-5741 integrated Ivan's bundler migration wiki info

---

develop/reference/articles/03-back-end/03-portlet-descriptor-to-osgi-service-property-map.markdown

https://issues.liferay.com/browse/LRDOCS-5739
https://issues.liferay.com/browse/LRDOCS-5740
https://issues.liferay.com/browse/LRDOCS-5742

LRDOCS-5739 LRDOCS-5740 LRDOCS-5742 descriptor mapping updates

---

discover/portal/articles/190-managing-users/01-users-and-organizations/01-managing-users.markdown

https://issues.liferay.com/browse/LRDOCS-5366

LRDOCS-5366 screen names and email addresses

---

discover/deployment/articles-dxp/05-maintaining-liferay/01-patching-liferay-dxp/02-using-the-patching-tool/00-using-the-patching-tool-intro.markdown

https://issues.liferay.com/browse/LRDOCS-5753

LRDOCS-5753 Fix patching tool link

---

develop/reference/articles/10-gradle/21-theme-builder-gradle-plugin.markdown

https://issues.liferay.com/browse/LRDOCS-5752

LRDOCS-5752 Finding compatible theme dependencies (Theme Builder) | 7.0.x

---

develop/tutorials/articles/280-workflow/01-creating-workflow-definitions/00-creating-workflow-definitions-intro.markdown

https://issues.liferay.com/browse/LRDOCS-5685 add info on how the workflow name, if specified, serves as a unique ID for the workflow. cc @jeyvison

LRDOCS-5685, workflow name serves as ID

---

develop/tutorials/articles/210-front-end-taglibs/05-chart-taglibs/01-bar-charts.markdown
develop/tutorials/articles/210-front-end-taglibs/05-chart-taglibs/02-line-charts.markdown
develop/tutorials/articles/210-front-end-taglibs/05-chart-taglibs/03-scatter-charts.markdown
develop/tutorials/articles/210-front-end-taglibs/05-chart-taglibs/04-spline-charts.markdown
develop/tutorials/articles/210-front-end-taglibs/05-chart-taglibs/05-step-charts.markdown
develop/tutorials/articles/210-front-end-taglibs/05-chart-taglibs/06-combination-charts.markdown
develop/tutorials/articles/210-front-end-taglibs/05-chart-taglibs/07-donut-charts.markdown
develop/tutorials/articles/210-front-end-taglibs/05-chart-taglibs/08-gauge-charts.markdown
develop/tutorials/articles/210-front-end-taglibs/05-chart-taglibs/09-pie-charts.markdown
develop/tutorials/articles/210-front-end-taglibs/05-chart-taglibs/10-geomap-charts.markdown
develop/tutorials/articles/210-front-end-taglibs/05-chart-taglibs/11-predictive-charts.markdown
develop/tutorials/articles/210-front-end-taglibs/05-chart-taglibs/12-refreshing-charts-to-reflect-real-time-data.markdown

LRDOCS-5743 charts update

---

discover/portal/articles/100-web-experience-management/06-configuring-widgets/01-look-and-feel-configuration.markdown

https://issues.liferay.com/browse/LRDOCS-5749

LRDOCS-5749 removed feature and added note about deprecation

---

develop/tutorials/articles/180-themes-and-layout-templates/01-themes/02-developing-themes/09-creating-reusable-pieces-of-code-for-your-themes.markdown

LRDOCS-5761 themelet updates

---

develop/tutorials/articles/260-themes-and-layout-templates/01-themes/02-themelets.markdown

LRDOCS-5761 port 7.1 changes to 7.0 themelet docs

---

develop/tutorials/articles/180-themes-and-layout-templates/01-themes/02-developing-themes/13-overwriting-and-extending-theme-tasks.markdown

LRDOCS-5767 improve example and update links

---

discover/deployment/articles/06-upgrading-to-liferay-7-1/04-post-upgrade-tasks.markdown

Discover > Deployment
https://issues.liferay.com/browse/LRDOCS-5768

LRDOCS-5768 address web content view permissions

---

discover/commerce/articles-dxp/010-getting-started/00-getting-started-intro.markdown
discover/commerce/articles-dxp/090-site-initializers/02-customer-portal/01-accounts-management.markdown
discover/commerce/articles/010-getting-started/00-getting-started-intro.markdown
discover/commerce/articles/020-catalog-management/02-products/00-products-intro.markdown
discover/commerce/articles/090-site-initializers/00-site-initializers-intro.markdown
discover/commerce/articles/090-site-initializers/01-breccia.markdown
discover/commerce/articles/100-storefront/00-setting-up-a-storefront-intro.markdown

https://issues.liferay.com/browse/LRDOCS-5759?filter=-1

LRDOCS-5759 accelerators

---

develop/tutorials/articles/03-from-liferay-70-to-71/00-from-liferay-70-to-71-intro.markdown
develop/tutorials/articles/03-from-liferay-70-to-71/01-upgrading-plugins-from-liferay-70-to-71/00-upgrading-plugins-from-liferay-70-to-71-intro.markdown

LRDOCS-5656 add product token to the 7.0 to 7.1 titles

---

develop/tutorials/articles/100-tooling/03-blade-cli/01-installing-blade-cli.markdown
develop/tutorials/articles/100-tooling/04-liferay-workspace/01-installing-liferay-workspace.markdown

https://issues.liferay.com/browse/LRDOCS-5785

LRDOCS-5785 Update Project SDK installer link and related text

---

develop/tutorials/articles/100-tooling/03-blade-cli/01-installing-blade-cli.markdown
develop/tutorials/articles/100-tooling/04-liferay-workspace/01-installing-liferay-workspace.markdown

https://issues.liferay.com/browse/LRDOCS-5785

LRDOCS-5785 Update installer reference for Blade/Workspace | 7.0.x

---

develop/tutorials/articles/130-service-builder/02-service-builder-persistence/01-defining-an-object-relational-map-with-service-builder/02-defining-global-service-information.markdown
develop/tutorials/articles/130-service-builder/03-business-logic-with-service-builder/02-invoking-local-services.markdown
develop/tutorials/articles/130-service-builder/03-business-logic-with-service-builder/03-invoking-services-from-service-builder-code.markdown

https://issues.liferay.com/browse/LRDOCS-5738

LRDOCS-5738 enable mvcc and explain how to update entities

---

develop/tutorials/articles/180-themes-and-layout-templates/01-themes/02-developing-themes/10-creating-a-thumbnail-preview-for-your-theme.markdown

LRDOCS-5779 add note for Theme Builder Gradle plugin to 7.1 docs

---

develop/tutorials/articles/260-themes-and-layout-templates/01-themes/09-creating-a-theme-thumbnail.markdown

LRDOCS-5779 add theme builder thumbnail note to 7.0 docs

---

develop/tutorials/articles/380-troubleshooting/17-troubleshooting-front-end-dev.markdown

LRDOCS-5784 Front-End FAQ updates

---

develop/tutorials/articles/130-service-builder/02-service-builder-persistence/00-service-builder-persistence-intro.markdown

https://issues.liferay.com/browse/LRDOCS-5817

LRDOCS-5817 fix links

---

discover/deployment/articles/06-upgrading-to-liferay-7-1/03-running-the-upgrade-process/01-running-the-upgrade-tool.markdown

https://issues.liferay.com/browse/LRDOCS-5819

LRDOCS-5819 update the upgrade tool download instructions

---

discover/deployment/articles/06-upgrading-liferay/03-running-the-upgrade-process.markdown

https://issues.liferay.com/browse/LRDOCS-5819

LRDOCS-5819 7.0 update the upgrade tool download instructions

---

develop/tutorials/articles/100-tooling/03-blade-cli/01-installing-blade-cli.markdown

https://issues.liferay.com/browse/LRDOCS-5820

LRDOCS-5820 Clean up installer error note to be macOS AND Linux compatible

---

develop/tutorials/articles/100-tooling/03-blade-cli/01-installing-blade-cli.markdown

https://issues.liferay.com/browse/LRDOCS-5820

LRDOCS-5820 Clean up installer error note to be mac AND Linux compatible | 7.0.x

---

develop/reference/articles/200-breaking-changes.markdown

See brianchandotcom/liferay-portal#64343

LPS-85998 Add new breaking change

---

discover/deployment/articles-dxp/01-installing-search-engine/02-enterprise-search/02-xpack-monitoring.markdown
discover/portal/articles/100-web-experience-management/02-building-a-site/02-adding-pages-to-sites/02-page-types-and-templates/03-using-widget-pages/01-creating-widget-pages.markdown
discover/portal/articles/100-web-experience-management/02-building-a-site/06-configuring-pages/02-configuring-individual-pages/02-personalizing-pages.markdown
discover/portal/articles/100-web-experience-management/05-publishing-content-dynamically/01-defining-content-relationships.markdown
discover/portal/articles/110-collaboration/04-collaborating/01-blogs/07-recent-bloggers.markdown

https://issues.liferay.com/browse/LRDOCS-5821

LRDOCS-5821 application-->widget

---

distribute/publish/articles/01-publishing-your-app/00-publishing-your-app-intro.markdown
distribute/publish/articles/placeholder.txt
distribute/publish/images/placeholder.txt

https://issues.liferay.com/browse/LRDOCS-4709

 LRDOCS-4709 publishing your app (intro)

---

discover/portal/articles/210-setting-up/03-script-console/02-running-scripts-from-script-console.markdown

https://issues.liferay.com/browse/LRDOCS-5823?filter=-1

LRDOCS-5823 script engine edit

---

develop/tutorials/articles/110-portlets/05-jsf-portlets-with-liferay-faces/04-services-in-jsf.markdown

https://issues.liferay.com/browse/LRDOCS-5816

LRDOCS-5816 Add clarifications for JSF services tutorial

---

develop/tutorials/articles/110-portlets/04-jsf/04-services-in-jsf.markdown

https://issues.liferay.com/browse/LRDOCS-5816

LRDOCS-5816 Add clarifications for JSF services tutorial | 7.0.x

---

develop/tutorials/articles/180-themes-and-layout-templates/01-themes/03-managing-theme-resources/02-creating-a-sitemap/04-retrieving-portlet-ids-with-gogo-shell.markdown

LRDOCS-5827 document Gogo Shell method to retrieve portlet IDs

---

discover/portal/articles/210-setting-up/01-system-settings/01-system-settings.markdown
discover/portal/articles/210-setting-up/01-system-settings/02-config-files/00-intro.markdown
discover/portal/articles/210-setting-up/01-system-settings/03-server-administration/01-server-admin-resources.markdown

https://issues.liferay.com/browse/LRDOCS-5655
cc @rbohl

LRDOCS-5655 7.1 caching and config files

---

discover/portal/articles/150-setting-up-liferay/01-system-settings/01-system-settings.markdown
discover/portal/articles/150-setting-up-liferay/01-system-settings/02-configuration-files.markdown
discover/portal/articles/150-setting-up-liferay/01-system-settings/03-server-admin.markdown

https://issues.liferay.com/browse/LRDOCS-5655
cc @rbohl

LRDOCS-5655 7.0 caching and config files

---

discover/portal/articles/200-managing-apps/02-liferay-marketplace.markdown
discover/portal/images-dxp/placeholder.txt
discover/portal/images/placeholder.txt

https://issues.liferay.com/browse/LRDOCS-5830

LRDOCS-5830 renewing a purchased app

---

discover/portal/articles/140-managing-apps/02-using-the-liferay-marketplace.markdown

https://issues.liferay.com/browse/LRDOCS-5830

LRDOCS-5830 7.0 renewing a purchased app

---

discover/deployment/articles/03-configuring-liferay/04-updating-a-cluster/00-updating-a-cluster-intro.markdown
discover/deployment/articles/03-configuring-liferay/04-updating-a-cluster/01-using-rolling-restarts.markdown
discover/deployment/articles/03-configuring-liferay/04-updating-a-cluster/02-other-cluster-update-techniques.markdown

https://issues.liferay.com/browse/LRDOCS-5417

LRDOCS-5417 blue-green deployment and cluster update tutorial intro updates

---

discover/deployment/articles/06-upgrading-to-liferay-7-1/03-running-the-upgrade-process/01-running-the-upgrade-tool.markdown

https://issues.liferay.com/browse/LRDOCS-5810

LRDOCS-5810 clarify app-server.properties requirements

---

discover/deployment/articles/06-upgrading-liferay/03-running-the-upgrade-process.markdown

https://issues.liferay.com/browse/LRDOCS-5810

LRDOCS-5810 7.0 clarify app-server.properties requirements

---

develop/tutorials/articles/100-tooling/04-liferay-workspace/05-managing-the-target-platform-for-liferay-workspace.markdown

https://issues.liferay.com/browse/LRDOCS-5783

 LRDOCS-5783 Add info on how to override BOM artifact versions

---

develop/tutorials/articles/100-tooling/04-liferay-workspace/05-managing-the-target-platform-for-liferay-workspace.markdown

https://issues.liferay.com/browse/LRDOCS-5783

 LRDOCS-5783 Add info on how to override BOM artifact versions | 7.0.x

---

develop/reference/articles/08-maven/bundle-support-plugin.markdown
develop/tutorials/articles/100-tooling/03-blade-cli/03-creating-a-liferay-workspace-with-blade-cli.markdown
develop/tutorials/articles/100-tooling/03-blade-cli/04-creating-projects-with-blade-cli.markdown
develop/tutorials/articles/100-tooling/04-liferay-workspace/02-configuring-a-liferay-workspace.markdown
develop/tutorials/articles/100-tooling/04-liferay-workspace/04-development-lifecycle-for-liferay-workspaces.markdown
develop/tutorials/articles/100-tooling/04-liferay-workspace/07-validating-modules-against-the-target-platform/02-modifying-the-target-platforms-capabilities.markdown
develop/tutorials/articles/100-tooling/05-maven/10-maven-workspace.markdown

https://issues.liferay.com/browse/LRDOCS-5834
https://issues.liferay.com/browse/LRDOCS-5844
https://issues.liferay.com/browse/LRDOCS-5846

LRDOCS-5844 Blade updates

---

develop/reference/articles/11-maven/bundle-support-plugin.markdown
develop/tutorials/articles/100-tooling/03-blade-cli/03-creating-a-liferay-workspace-with-blade-cli.markdown
develop/tutorials/articles/100-tooling/04-liferay-workspace/02-configuring-a-liferay-workspace.markdown
develop/tutorials/articles/100-tooling/04-liferay-workspace/04-development-lifecycle-for-liferay-workspaces.markdown
develop/tutorials/articles/100-tooling/04-liferay-workspace/06-validating-modules-against-the-target-platform/02-modifying-the-target-platforms-capabilities.markdown
develop/tutorials/articles/100-tooling/05-maven/10-maven-workspace.markdown

https://issues.liferay.com/browse/LRDOCS-5834
https://issues.liferay.com/browse/LRDOCS-5844
https://issues.liferay.com/browse/LRDOCS-5846

LRDOCS-5844 Blade updates | 7.0.x

---

develop/tutorials/articles/03-developing-a-web-application/12-staging-and-exportimport/00-intro.markdown
develop/tutorials/articles/03-developing-a-web-application/12-staging-and-exportimport/01-creating-staged-models.markdown
develop/tutorials/articles/03-developing-a-web-application/12-staging-and-exportimport/02-creating-the-entry-staged-model-data-handler.markdown
develop/tutorials/articles/03-developing-a-web-application/12-staging-and-exportimport/03-creating-the-guestbook-staged-model-data-handler.markdown
develop/tutorials/articles/03-developing-a-web-application/12-staging-and-exportimport/04-updating-permissions-to-support-staging.markdown
develop/tutorials/articles/03-developing-a-web-application/12-staging-and-exportimport/05-configuring-xstream.markdown
develop/tutorials/articles/03-developing-a-web-application/12-staging-and-exportimport/07-creating-the-portlet-data-handler.markdown
develop/tutorials/articles/03-developing-a-web-application/12-staging-and-exportimport/08-adapting-to-staged-site-management.markdown

Addressed your suggestions and made a few more updates to clarify some potential confusion.
https://issues.liferay.com/browse/LRDOCS-3820
https://issues.liferay.com/browse/LRDOCS-5629
https://issues.liferay.com/browse/LRDOCS-5630
https://issues.liferay.com/browse/LRDOCS-5631
https://issues.liferay.com/browse/LRDOCS-5632
https://issues.liferay.com/browse/LRDOCS-5633
https://issues.liferay.com/browse/LRDOCS-5634
https://issues.liferay.com/browse/LRDOCS-5635
https://issues.liferay.com/browse/LRDOCS-5636

LRDOCS-3820 Guestbook Staging | 7.0.x

---

discover/commerce/articles/010-getting-started/00-getting-started-intro.markdown

https://issues.liferay.com/browse/LRDOCS-5856?filter=-1

LRDOCS-5856 LPKG instructions

---

discover/deployment/articles-dxp/05-maintaining-liferay/01-patching-liferay-dxp/02-using-the-patching-tool/00-using-the-patching-tool-intro.markdown

https://issues.liferay.com/browse/LRDOCS-5753

LRDOCS-5753 use general link for navigating to patching tool download

---

develop/tutorials/articles/130-service-builder/02-service-builder-persistence/06-custom-sql.markdown

https://issues.liferay.com/browse/LRDOCS-5876

LRDOCS-5876 FIX wrap custom SQL in CDATA tag

---

develop/tutorials/articles/120-service-builder/02-service-builder-persistence/05-developing-custom-sql-queries.markdown

https://issues.liferay.com/browse/LRDOCS-5876

LRDOCS-5876 FIX 7.0 wrap custom sql in CDATA

---

discover/deployment/articles/00-deploying-liferay/01-preparing-for-install.markdown
discover/deployment/articles/00-deploying-liferay/02-installing-liferay.markdown

https://issues.liferay.com/browse/LRDOCS-5877

LRDOCS-5877 bundles are packaged in .7z and .tar.gz files

---

develop/tutorials/articles/260-themes-and-layout-templates/01-themes/01-themes-generator.markdown

LRDOCS-5886 Marcos theme gen updates 7.0

---

develop/tutorials/articles/180-themes-and-layout-templates/01-themes/01-creating-themes/00-creating-themes-intro.markdown

LRDOCS-5886 port 7.0 schema version info to 7.1

---

develop/tutorials/articles/260-import-export-and-staging/00-intro.markdown
develop/tutorials/articles/260-import-export-and-staging/07-developing-portlet-data-handlers.markdown
develop/tutorials/articles/260-import-export-and-staging/08-developing-staged-model-data-handlers.markdown

https://issues.liferay.com/browse/LRDOCS-5892

LRDOCS-5892 Add Staging data handler clarifications 

---

discover/portal/articles/100-web-experience-management/07-staging-content-for-publication/06-organizing-pages-for-staging/01-using-multi-and-single-page-variations.markdown

https://issues.liferay.com/browse/LRDOCS-5859

LRDOCS-5859 Clarifications for page templates and Staging

---

develop/tutorials/articles/230-web-experience-management/01-developing-fragments/02-fragment-specific-tags.markdown

https://issues.liferay.com/browse/LRDOCS-5936
@JorgeFerrer

removed note that rich-text could contain HTML

---

discover/portal/articles/100-web-experience-management/02-creating-web-content/01-publishing-basic-web-content.markdown

https://issues.liferay.com/browse/LRDOCS-5923

clarified function of searchable selection

---

discover/deployment/articles/01-installing-search-engine/03-installing-solr/00-installing-solr-intro.markdown
discover/deployment/articles/01-installing-search-engine/03-installing-solr/01-installing-solr-basic.markdown

Some small fixes for the Solr 7 docs. Added MP links, fixed the supported version (7.x-->7.5.x). cc @lipusz

Post publication Solr fixes

---

develop/tutorials/articles/230-web-experience-management/01-developing-fragments/02-fragment-specific-tags.markdown
develop/tutorials/articles/330-servlets/00-servlets-intro.markdown
develop/tutorials/articles/330-servlets/02-servlet-filters.markdown

https://issues.liferay.com/browse/LRDOCS-4648 servlets intro
https://issues.liferay.com/browse/LRDOCS-4652 servlet filter tutorial

LRDOCS-4652 Servlet filters tutorial

---

develop/tutorials/articles/180-themes-and-layout-templates/01-themes/02-developing-themes/00-developing-themes-intro.markdown
develop/tutorials/articles/180-themes-and-layout-templates/01-themes/02-developing-themes/17-using-macros-in-your-theme-templates.markdown

LRDOCS-4390 macros

---

develop/tutorials/articles/01-introduction-to-liferay-development/06-frontend-development-in-liferay/00-frontend-development-in-liferay-intro.markdown
develop/tutorials/articles/185-liferay-js-apis/00-liferay-js-apis-intro.markdown
develop/tutorials/articles/185-liferay-js-apis/01-theme-display.markdown
develop/tutorials/articles/185-liferay-js-apis/02-working-with-urls-in-js.markdown
develop/tutorials/articles/185-liferay-js-apis/03-javascript-utilities.markdown
develop/tutorials/articles/185-liferay-js-apis/04-invoking-liferay-services.markdown

LRDOCS-4416 Liferay JS APIs

---

discover/commerce/articles-dxp/010-getting-started/00-getting-started-intro.markdown
discover/commerce/articles-dxp/090-site-initializers/02-customer-portal/01-accounts-management.markdown

https://issues.liferay.com/browse/LRDOCS-5855

LRDOCS-5855 correcting dxp links

---

develop/reference/articles/200-breaking-changes.markdown

https://issues.liferay.com/browse/LRDOCS-5953
Updated for portal as well: brianchandotcom/liferay-portal-ee#22638
/cc @ngriffin7a

LRDOCS-5953 Update Portlet 3.0 breaking change

---

develop/tutorials/articles/220-mobile/01-android-apps-with-liferay-screens/01-preparing-android-projects-for-liferay-screens.markdown
develop/tutorials/articles/220-mobile/01-android-apps-with-liferay-screens/03-using-views-in-android-screenlets.markdown
develop/tutorials/articles/220-mobile/01-android-apps-with-liferay-screens/07-creating-android-screenlets/06-packaging-android-screenlets.markdown
develop/tutorials/articles/220-mobile/01-android-apps-with-liferay-screens/11-using-liferay-push-in-android-apps.markdown

Changed Gradle 'compile' statements to 'implementation'

LRDOCS-5964 fixing Gradle statements in Android Screens docs - 7.1.x

---

develop/tutorials/articles/115-mobile/01-android-apps-with-liferay-screens/01-preparing-android-projects-for-liferay-screens.markdown
develop/tutorials/articles/115-mobile/01-android-apps-with-liferay-screens/03-using-views-in-android-screenlets.markdown
develop/tutorials/articles/115-mobile/01-android-apps-with-liferay-screens/10-packaging-android-screenlets.markdown
develop/tutorials/articles/115-mobile/01-android-apps-with-liferay-screens/11-using-liferay-push-in-android-apps.markdown

Changed Gradle 'compile' statements to 'implementation'

LRDOCS-5964 fixing Gradle statements in Android Screens docs - 7.0.x

---

discover/analytics-cloud/articles/02-getting-started/00-your-new-home-for-analytics-intro.markdown

https://issues.liferay.com/browse/LRDOCS-5945

LRDOCS-5945 Analytics Cloud: add link to analytics.liferay.com page

---

develop/tutorials/articles/100-tooling/02-liferay-ide/07-deploying-projects-with-liferay-ide.markdown
develop/tutorials/articles/100-tooling/03-blade-cli/05-deploying-projects-with-blade-cli.markdown
develop/tutorials/articles/100-tooling/03-blade-cli/07-updating-blade-cli.markdown
develop/tutorials/articles/100-tooling/04-liferay-workspace/02-configuring-a-liferay-workspace.markdown
develop/tutorials/articles/100-tooling/04-liferay-workspace/05-managing-the-target-platform-for-liferay-workspace.markdown
develop/tutorials/articles/100-tooling/04-liferay-workspace/07-validating-modules-against-the-target-platform/01-resolving-your-modules.markdown
develop/tutorials/articles/100-tooling/04-liferay-workspace/07-validating-modules-against-the-target-platform/02-modifying-the-target-platforms-capabilities.markdown
develop/tutorials/articles/100-tooling/04-liferay-workspace/07-validating-modules-against-the-target-platform/99-validating-modules-outside-of-workspace.markdown
develop/tutorials/articles/100-tooling/05-maven/10-maven-workspace.markdown
develop/tutorials/articles/100-tooling/06-intellij/05-deploying-projects-with-intellij-idea.markdown

https://issues.liferay.com/browse/LRDOCS-5678
https://issues.liferay.com/browse/LRDOCS-5943

LRDOCS-5678 Blade watch (and other misc updates)

---

develop/reference/articles/13-sample-projects/02-extensions/04-indexer-post-processor.markdown

fix link in indexer post processor sample ref guide

---

develop/tutorials/articles/330-servlets/02-servlet-filters.markdown

https://issues.liferay.com/browse/LRDOCS-5945

LRDOCS-5945 servlet filter use cases

---

develop/tutorials/articles/130-service-builder/02-service-builder-persistence/06-dynamic-query/02-implementing-your-custom-finder-method-using-dynamic-query.markdown

This is already merged into upstream 7.1.x
https://issues.liferay.com/browse/LRDOCS-5922

LRDOCS-5922 7.1 - use classloader in calls to DynamicQueryFactoryUtil.forClass(...)

---

develop/tutorials/articles/120-service-builder/02-service-builder-persistence/06-leveraging-hibernates-criteria-api.markdown

This is already merged into upstream 7.0.x.
https://issues.liferay.com/browse/LRDOCS-5922

LRDOCS-5922 7.0 - use classloader in calls to DynamicQueryFactoryUtil.forClass(...)

---

develop/tutorials/articles/130-service-builder/03-business-logic-with-service-builder/02-invoking-local-services.markdown
develop/tutorials/articles/350-modularity-and-osgi/04-osgi-services-and-dependency-injection.markdown
develop/tutorials/articles/360-osgi-basics-for-liferay-development/08-service-trackers.markdown

https://issues.liferay.com/browse/LRDOCS-5863

LRDOCS-5863 @Reference can only be used in a class that has @Component

---

develop/tutorials/articles/180-themes-and-layout-templates/01-themes/03-managing-theme-resources/01-preparing-and-organizing-resources-for-the-importer.markdown

cc @stephenkostas 
No changes were required to the 7.0 docs. The information was already correct.

LRDOCS-5970 fix incorrect information

---

develop/tutorials/articles/100-tooling/03-blade-cli/05-deploying-projects-with-blade-cli.markdown

https://issues.liferay.com/browse/LRDOCS-5891
https://issues.liferay.com/browse/LRDOCS-5896

LRDOCS-5891 Update blade deploy to account for new functionality

---

develop/tutorials/articles/100-tooling/03-blade-cli/05-deploying-modules-with-blade-cli.markdown

https://issues.liferay.com/browse/LRDOCS-5891
https://issues.liferay.com/browse/LRDOCS-5896

LRDOCS-5891 Update blade deploy to account for new functionality | 7.0.x

---

develop/reference/articles/04-front-end/02-ckeditor-plugin-reference-guide.markdown
develop/tutorials/articles/320-wysiwyg-editors/01-adding-a-wysiwyg-editor-to-a-portlet.markdown
develop/tutorials/articles/320-wysiwyg-editors/02-modifying-an-editors-configuration.markdown
develop/tutorials/articles/320-wysiwyg-editors/04-alloy-editor/01-adding-buttons-to-the-alloyeditor/00-adding-buttons-to-the-alloy-editor-intro.markdown
develop/tutorials/articles/320-wysiwyg-editors/04-alloy-editor/01-adding-buttons-to-the-alloyeditor/01-preparing-and-configuring-your-module.markdown

@sez11a this includes LRDOCS-5531 and LRDOCS-6023
cc @jbalsas

LRDOCS-5531 modifying an editor configuration

---

develop/tutorials/articles/160-search/03-indexers.markdown

https://issues.liferay.com/browse/LRDOCS-4374, cc @lipusz

LRDOCS-4374, 7.1 Indexing tutorial

---

bin/convert.sh

I ran into some issues with the convert script when I set up git worktrees, so I tried tocome up with a more robust way to define the classpath. I am not sure if this new way will work on mac. Let me know what you think.

Convert Script Changes

---

develop/reference/articles/11-liferay-faces/04-understanding-liferay-faces-portal.markdown

https://issues.liferay.com/browse/LRDOCS-6021
https://issues.liferay.com/browse/LRDOCS-6022

LRDOCS-6021 Liferay Faces Portal edits | 7.1.x

---

develop/tutorials/articles/100-tooling/04-liferay-workspace/05-managing-the-target-platform-for-liferay-workspace.markdown
develop/tutorials/articles/100-tooling/04-liferay-workspace/06-validating-modules-against-the-target-platform/01-resolving-your-modules.markdown

https://issues.liferay.com/browse/LRDOCS-6128

LRDOCS-6128 DXP BOM Updates | 7.0.x

---

develop/tutorials/articles/02-from-liferay-6-to-liferay-7/07-upgrading-plugins-to-liferay-7/06-upgrading-themes/01-upgrading-liferay-6-themes.markdown
develop/tutorials/articles/02-from-liferay-6-to-liferay-7/07-upgrading-plugins-to-liferay-7/06-upgrading-themes/02-upgrading-themes.markdown
develop/tutorials/articles/110-portlets/15-javascript/04-npm/01-liferay-npm-bundler.markdown
develop/tutorials/articles/260-themes-and-layout-templates/01-themes/01-themes-generator.markdown
develop/tutorials/articles/260-themes-and-layout-templates/01-themes/02-themelets.markdown

LRDOCS-5939 themes sdk rename 7.0.x

---

develop/tutorials/articles/180-themes-and-layout-templates/01-themes/02-developing-themes/05-copying-an-existing-themes-files.markdown

LRDOCS-5764 add info to gulp kickstart doc for globally installing a theme

---

develop/tutorials/articles/240-javascript-module-loaders/20-loading-modules-with-aui-script-tag.markdown

7.1.x changes sent in https://github.com/sez11a/liferay-docs/pull/3855
cc @jbalsas

LRDOCS-6137 port multiple module use case to 7.0 docs

---

develop/tutorials/articles/190-javascript-module-loaders/04-loading-modules-with-aui-script-tag.markdown

7.0.x changes sent in https://github.com/sez11a/liferay-docs/pull/3854 
cc @jbalsas

LRDOCS-6137 AUI script use case update

---

develop/tutorials/articles/244-liferay-js-api/01-theme-display.markdown

Liferay Community PR review

---

develop/reference/articles/06-themes/03-understanding-the-page-layout.markdown
develop/tutorials/articles/180-themes-and-layout-templates/01-themes/02-developing-themes/17-using-macros-in-your-theme-templates.markdown
develop/tutorials/articles/180-themes-and-layout-templates/03-portlets-and-themes/02-portlet-decorators/02-applying-portlet-decorators-to-embedded-portlets.markdown
develop/tutorials/articles/180-themes-and-layout-templates/03-portlets-and-themes/03-embedding-portlets-in-themes-and-layout-templates.markdown
develop/tutorials/articles/320-wysiwyg-editors/03-adding-new-behavior-to-an-editor.markdown
develop/tutorials/articles/400-back-end-frameworks/02-portlet-providers/00-portlet-providers-intro.markdown

7.0.x changes sent https://github.com/sez11a/liferay-docs/pull/3857 
cc @jbalsas

LRDOCS-6152 remove embedding portlets in layout templates info 7.1.x

---

develop/tutorials/articles/230-wysiwyg-editors/02-modifying-an-editor-configuration.markdown
develop/tutorials/articles/230-wysiwyg-editors/03-adding-new-behavior-to-an-editor.markdown
develop/tutorials/articles/260-themes-and-layout-templates/03-portlets/01-portlet-decorators/02-applying-portlet-decorators-to-embedded-portlets.markdown
develop/tutorials/articles/260-themes-and-layout-templates/03-portlets/03-embedding-portlets-in-themes-and-layout-templates.markdown
develop/tutorials/articles/460-customizable-web-applications/01-providing-portlets-to-manage-requests.markdown

7.1.x updates sent https://github.com/sez11a/liferay-docs/pull/3856 
cc @jbalsas

LRDOCS-6152 remove embedding portlets in layout templates info 7.0.x

---

discover/deployment/articles-dxp/05-maintaining-liferay/01-patching-liferay-dxp/01-patching-basics/00-patching-basics-intro.markdown

https://issues.liferay.com/browse/LRDOCS-6239

LRDOCS-6239 7.1.x explain fix pack and service pack relationships

---

discover/portal/articles/100-web-experience-management/02-creating-web-content/02-designing-uniform-content.markdown

https://issues.liferay.com/browse/LRDOCS-6215

added more detail for structure default values - 7.0.x

---

discover/portal/articles/110-collaboration/02-sync/02-sync-desktop/01-install-configure-sync-desktop.markdown

Adding network drives note to Sync desktop article (7.1.x)

LRDOCS-6262 Sync network drives - 7.1.x

---

discover/portal/articles/110-collaboration/01-managing-documents-and-media/06-using-liferay-sync-desktop.markdown

Adding network drives note to Sync desktop article (7.0.x)

LRDOCS-6262 Sync network drives - 7.0.x

---

discover/portal/articles/05-document-management/08-using-liferay-sync-desktop.markdown

Adding network drives note to Sync desktop article (6.2.x)

LRDOCS-6262 Sync network drives - 6.2.x

---

develop/reference/articles/04-front-end/01-liferay-npm-bundler/00-liferay-npm-bundler-intro.markdown
develop/tutorials/articles/200-integrating-with-front-end-frameworks/04-creating-and-bundling-javascript-portlets-with-front-end-tools.markdown

LRDOCS-6270 add note to link to project's wiki

---

develop/tutorials/articles/130-service-builder/02-service-builder-persistence/09-connecting-service-builder-to-external-data-sources.markdown

This is an important update for Spring extender (you use this when using Service Builder with an external data source). It was introduced in FP3/SP1 and CE GA2.
https://issues.liferay.com/browse/LRDOCS-6267

 LRDOCS-6267 Important 7.1 Spring extender update

---

develop/tutorials/articles/350-modularity-and-osgi/99-learning-more-about-osgi.markdown

https://issues.liferay.com/browse/LRDOCS-6280

LRDOCS-6280 7.1 Fix: refactor the external OSGi resource links

---

develop/tutorials/articles/02-from-liferay-6-to-liferay-7/03-osgi-and-modularity-for-liferay-6-developers/00-osgi-and-modularity-for-liferay-6-developers-intro.markdown

https://issues.liferay.com/browse/LRDOCS-6280

LRDOCS-6280 7.0 Fix: Rerfactor OSGi links

---

develop/tutorials/articles/100-tooling/04-liferay-workspace/09-updating-liferay-workspace.markdown

https://issues.liferay.com/browse/LRDOCS-6281

LRDOCS-6281 Update Gradle wrapper in Workspace | 7.1.x

---

discover/portal/articles/100-web-experience-management/02-building-a-site/02-adding-pages-to-sites/02-page-types-and-templates/02-using-content-pages/02-building-content-pages-and-templates.markdown

https://issues.liferay.com/browse/LRDOCS-6146

added explanation of editable field propagation

---

develop/tutorials/articles/120-customizing/04-overriding-language-keys/02-overriding-a-modules-language-keys.markdown

https://issues.liferay.com/browse/LRDOCS-6284

LRDOCS-6284 Ignoring aggregated resource bundles

---

discover/deployment/articles/02-installing-search-engine/01-elasticsearch/02-configuring-the-connector.markdown
discover/deployment/articles/02-installing-search-engine/01-elasticsearch/06-installing-elasticsearch-6.1/01-configuring-elasticsearch-6_1.markdown
discover/portal/articles/120-search/03-searching-for-assets.markdown
discover/portal/articles/120-search/04-facets/07-custom-facet.markdown
discover/portal/articles/120-search/06-search-configuration.markdown
discover/reference/articles/06-elasticsearch-settings.markdown

https://issues.liferay.com/browse/LRDOCS-6227, I simply had to excape the dashes in the markdown tables. Also ran ant check for good measure. cc @lipusz

LRDOCS-6227, resent with formatting fixes

---

develop/tutorials/articles/120-service-builder/02-service-builder-persistence/01-defining-an-object-relational-map-with-service-builder.markdown
develop/tutorials/articles/120-service-builder/03-business-logic-with-service-builder/01-creating-local-services.markdown

https://issues.liferay.com/browse/LRDOCS-6294

LRDOCS-6294 7.0: reference docs on generating primary key values

---

develop/tutorials/articles/130-service-builder/02-service-builder-persistence/01-defining-an-object-relational-map-with-service-builder/04-defining-the-columns-attributes-for-each-service-entity.markdown
develop/tutorials/articles/130-service-builder/03-business-logic-with-service-builder/01-creating-local-services/02-implementing-an-add-method.markdown

https://issues.liferay.com/browse/LRDOCS-6294

LRDOCS-6294 7.1: reference info on generating entity primary keys

---

develop/tutorials/articles/100-tooling/04-liferay-workspace/05-managing-the-target-platform-for-liferay-workspace.markdown

https://issues.liferay.com/browse/LRDOCS-6307

LRDOCS-6307 Update Liferay CDN URL | 7.1.x

---

develop/tutorials/articles/180-themes-and-layout-templates/01-themes/01-creating-themes/00-creating-themes-intro.markdown

LRDOCS-6138 remove ruby-sass info

---

discover/analytics-cloud/articles/02-getting-started/02-adding-a-liferay-dxp-data-source.markdown
discover/analytics-cloud/articles/06-troubleshooting/00-troubleshooting-data-sources-intro.markdown

https://issues.liferay.com/browse/LRDOCS-6263

LRDOCS-6263 AC: DXP data source setup and troubleshooting

---

discover/deployment/articles-dxp/02-installing-liferay/06-installing-liferay-on-jboss-eap.markdown

https://issues.liferay.com/browse/LRDOCS-6297

LRDOCS-6301 7.0: JBoss container stability timeout

---

develop/tutorials/articles/330-servlets/02-servlet-filters.markdown
develop/tutorials/code/wars/sample-servlet-filter-hook/README.markdown
develop/tutorials/code/wars/sample-servlet-filter-hook/build.gradle
develop/tutorials/code/wars/sample-servlet-filter-hook/src/main/java/com/liferay/sampleservletfilter/hook/filter/SampleFilter.java
develop/tutorials/code/wars/sample-servlet-filter-hook/src/main/webapp/WEB-INF/liferay-hook.xml
develop/tutorials/code/wars/sample-servlet-filter-hook/src/main/webapp/WEB-INF/liferay-plugin-package.properties

https://issues.liferay.com/browse/LRDOCS-4652
cc/ @jrao

LRDOCS-4652 7.1: example servlet filter project

---

develop/tutorials/articles/100-tooling/04-liferay-workspace/05-managing-the-target-platform-for-liferay-workspace.markdown
develop/tutorials/articles/111-customizing/05-overriding-language-keys.markdown

liferay#481
liferay#482
And...
https://issues.liferay.com/browse/LRDOCS-6307

LRDOCS-6307 7.0 FP BOMs AND Liferay PRs | 7.0.x

---

discover/deployment/articles-dxp/05-maintaining-liferay/01-patching-liferay-dxp/03-configuring-the-patching-tool/01-patching-tool-basic-configuration.markdown
discover/deployment/articles-dxp/05-maintaining-liferay/01-patching-liferay-dxp/04-keeping-up-with-fix-packs/00-keeping-up-with-fix-packs-intro.markdown

https://issues.liferay.com/browse/LRDOCS-6311

LRDOCS-6311 7.1 Fix: update keeping up with fix packs and service packs

---

discover/deployment/articles-dxp/04-maintaining-liferay/01-patching-liferay/03-keeping-up-with-fix-packs/00-keeping-up-with-fix-packs-intro.markdown

https://issues.liferay.com/browse/LRDOCS-6311

LRDOCS-6311 7.0 Fix: update keeping up with fix packs

---

discover/deployment/articles/01-deploying-liferay/10-installing-elasticsearch.markdown
discover/deployment/articles/02-installing-search-engine/00-intro.markdown
discover/deployment/articles/02-installing-search-engine/01-elasticsearch/02-configuring-the-connector.markdown
discover/deployment/articles/02-installing-search-engine/01-elasticsearch/07-installing-elasticsearch-6.1/00-installing-elasticsearch-6_1-intro.markdown
discover/deployment/articles/02-installing-search-engine/01-elasticsearch/07-installing-elasticsearch-6.1/01-configuring-elasticsearch-6_1.markdown
discover/deployment/articles/02-installing-search-engine/03-installing-solr/01-installing-solr-basic.markdown

https://issues.liferay.com/browse/LRDOCS-5905 (jdk version), https://issues.liferay.com/browse/LRDOCS-6304 (example cluster IP:host), https://issues.liferay.com/browse/LRDOCS-6312 (reindex in new search admin). cc @lipusz

Various 7.1 search fixes

---

develop/tutorials/articles/106-jsf-portlets-with-liferay-faces/10-localizing-jsf-portlets.markdown

https://issues.liferay.com/browse/LRDOCS-6328

LRDOCS-6328 JSF localization updates | 6.2.x

---

discover/deployment/articles/03-configuring-liferay/05-remote-staging-in-a-cluster/00-configuring-remote-staging-in-clustered-environment-intro.markdown
discover/portal/articles/100-web-experience-management/07-staging-content-for-publication/01-enabling-staging/02-enabling-remote-live-staging.markdown
discover/portal/articles/100-web-experience-management/07-staging-content-for-publication/01-enabling-staging/03-configuring-servers-for-remote-live-staging.markdown

https://issues.liferay.com/browse/LRDOCS-6314
https://issues.liferay.com/browse/LRDOCS-6315

LRDOCS-6314 Remote Staging Configuration improvements | 7.1.x

---

discover/deployment/articles/03-configuring-liferay/05-configuring-remote-staging-in-clustered-environment.markdown
discover/portal/articles/100-web-experience-management/03-staging-content-for-publication/01-enabling-staging/02-enabling-remote-live-staging.markdown

https://issues.liferay.com/browse/LRDOCS-6314
https://issues.liferay.com/browse/LRDOCS-6315

LRDOCS-6314 Remote Staging Configuration improvements | 7.0.x

---

develop/tutorials/articles/100-tooling/03-blade-cli/06-managing-your-liferay-server-with-blade-cli.markdown

https://issues.liferay.com/browse/LRDOCS-5941
https://issues.liferay.com/browse/LRDOCS-6296

LRDOCS-6296 Blade server updates | 7.1.x

---

discover/deployment/articles-dxp/01-deploying-liferay/06-installing-liferay-portal-on-jboss-eap.markdown
discover/deployment/articles-dxp/01-deploying-liferay/07-installing-liferay-on-tc-server.markdown
discover/deployment/articles-dxp/01-deploying-liferay/08-installing-liferay-on-weblogic.markdown
discover/deployment/articles-dxp/01-deploying-liferay/09-installing-liferay-on-websphere.markdown
discover/deployment/articles-dxp/08-lcs/02-lcs-preconfiguration.markdown
discover/deployment/articles/01-deploying-liferay/04-installing-liferay-portal-on-tomcat.markdown
discover/deployment/articles/01-deploying-liferay/05-installing-liferay-portal-on-wildfly.markdown
discover/deployment/articles/06-upgrading-to-liferay-7-1/03-running-the-upgrade-process/01-running-the-upgrade-tool.markdown

https://issues.liferay.com/browse/LRDOCS-6387

LRDOCS-6387 7.1: Liferay requires GMT and UTF-8 JVM args

---

discover/deployment/articles-dxp/02-installing-liferay/06-installing-liferay-on-jboss-eap.markdown
discover/deployment/articles-dxp/02-installing-liferay/07-installing-liferay-on-tcserver.markdown
discover/deployment/articles-dxp/02-installing-liferay/08-installing-liferay-on-weblogic.markdown
discover/deployment/articles-dxp/02-installing-liferay/09-installing-liferay-on-websphere.markdown
discover/deployment/articles-dxp/09-liferay-connected-services/02-lcs-preconfiguration.markdown
discover/deployment/articles/02-installing-liferay/04-installing-liferay-on-tomcat.markdown
discover/deployment/articles/02-installing-liferay/05-installing-liferay-on-wildfly.markdown
discover/deployment/articles/06-upgrading-liferay/03-running-the-upgrade-process.markdown

https://issues.liferay.com/browse/LRDOCS-6387

LRDOCS-6387 7.0: Liferay requires GMT and UTF-8 JVM args

---

discover/deployment/articles/01-installation-and-setup/12-installing-liferay-on-mulesoft-tcat.markdown
discover/deployment/articles/01-installation-and-setup/13-installing-liferay-on-glassfish-4.markdown
discover/deployment/articles/01-installation-and-setup/15-installing-liferay-on-tomcat-7.markdown
discover/deployment/articles/01-installation-and-setup/16-installing-liferay-on-oracle-weblogic-12c.markdown
discover/deployment/articles/04-managing-liferay-with-liferay-connected-services/01-lcs-preconfiguration.markdown

https://issues.liferay.com/browse/LRDOCS-6387

LRDOCS-6387 use UTF-8

---

develop/tutorials/articles/02-from-liferay-6-to-liferay-7/07-upgrading-plugins-to-liferay-7/05-upgrading-hook-plugins/04-upgrading-core-language-key-override-hooks.markdown

https://issues.liferay.com/browse/LRDOCS-6316

LRDOCS-6316 7.1 fix link to creating a resource bundler loader

---

develop/tutorials/articles/02-from-liferay-6-to-liferay-7/07-upgrading-plugins-to-liferay-7/05-upgrading-hook-plugins/04-upgrading-core-language-key-override-hooks.markdown

https://issues.liferay.com/browse/LRDOCS-6316

LRDOCS-6316 7.0 fix link to creating resource bundle loader

---

discover/portal/articles/190-managing-users/02-roles-and-permissions/00-intro.markdown

https://issues.liferay.com/browse/LRDOCS-5348?filter=-1

LRDOCS-5348 asset level permissions

---

develop/reference/articles/10-gradle/13-js-transpiler-gradle-plugin.markdown
develop/reference/articles/12-project-templates/12-npm-angular-portlet-template.markdown
develop/reference/articles/12-project-templates/13-npm-billboardjs-portlet-template.markdown
develop/reference/articles/12-project-templates/14-npm-isomorphic-portlet-template.markdown
develop/reference/articles/12-project-templates/15-npm-jquery-portlet-template.markdown
develop/reference/articles/12-project-templates/16-npm-metaljs-portlet-template.markdown
develop/reference/articles/12-project-templates/17-npm-portlet-template.markdown
develop/reference/articles/12-project-templates/18-npm-react-portlet-template.markdown
develop/reference/articles/12-project-templates/19-npm-vuejs-portlet-template.markdown
develop/reference/articles/13-sample-projects/01-apps/03-npm-samples/00-intro.markdown
develop/reference/articles/13-sample-projects/01-apps/03-npm-samples/01-angular-npm-portlet.markdown
develop/reference/articles/13-sample-projects/01-apps/03-npm-samples/02-billboardjs-npm-portlet.markdown
develop/reference/articles/13-sample-projects/01-apps/03-npm-samples/03-isomorphic-npm-portlet.markdown
develop/reference/articles/13-sample-projects/01-apps/03-npm-samples/04-jquery-npm-portlet.markdown
develop/reference/articles/13-sample-projects/01-apps/03-npm-samples/05-metaljs-npm-portlet.markdown
develop/reference/articles/13-sample-projects/01-apps/03-npm-samples/06-react-npm-portlet.markdown
develop/reference/articles/13-sample-projects/01-apps/03-npm-samples/07-simple-npm-portlet.markdown
develop/reference/articles/13-sample-projects/01-apps/03-npm-samples/08-vuejs-npm-portlet.markdown
develop/tutorials/articles/110-portlets/15-javascript/02-es2015/00-es2015-intro.markdown
develop/tutorials/articles/110-portlets/15-javascript/04-npm/00-npm-portlets-intro.markdown

@sez11a these are the minifier notes per support's feedback. The customer is waiting for these doc updates to be published, so please publish as soon as you can. Thanks!
cc @codyhoag

LRDOCS-6320 gradle docs update

---

develop/tutorials/articles/340-testing/00-testing-intro.markdown

https://issues.liferay.com/browse/LRDOCS-4653

LRDOCS-4653 Liferay lets you test using the framework you want

---

develop/reference/articles/12-page-fragments/02-embedding-widgets.markdown

https://issues.liferay.com/browse/LRDOCS-6370

LRDOCS-6370 Fixed embedded widget tags

---

develop/reference/articles/04-front-end/05-freemarker-taglib-macros.markdown
develop/tutorials/articles/210-front-end-taglibs/00-front-end-taglibs-intro.markdown
develop/tutorials/articles/210-front-end-taglibs/05-chart-taglibs/00-using-chart-taglibs-intro.markdown

LRDOCS-6416 Chart taglib is not available as a FreeMarker macro

---

develop/tutorials/articles/160-search/03-indexers.markdown

https://issues.liferay.com/browse/LRDOCS-6391, content courtesy of @lipusz.

LRDOCS-6391, indexer framework improvements

---

develop/tutorials/articles/120-customizing/01-customizing-jsps/04-jsp-overrides-using-fragments.markdown
develop/tutorials/articles/380-troubleshooting/00-troubleshooting-intro.markdown
develop/tutorials/articles/380-troubleshooting/12-jsp-fragment-unresolved-requirement.markdown

https://issues.liferay.com/browse/LRDOCS-6020

LRDOCS-6020 7.1: explicitly exclude importing fragment host internal packages

---

develop/tutorials/articles/111-customizing/01-overriding-jsps/04-jsp-overrides-using-fragments.markdown

https://issues.liferay.com/browse/LRDOCS-6020

LRDOCS-6020 7.0: explicitly exclude importing fragment host internal packages

---

discover/portal/articles/09-collaboration-suite/02-managing-events-and-calendar-resources.markdown

this was sent to liferay-docs/6.2.x back in september. just happened to run across it and figured i'd take 30 seconds to send it in. cc @natocesarrego

6.2 old fix from workflow sme

---

develop/tutorials/articles-dxp/225-analytics/00-intro.markdown

For review and placement in The Bag of Holding.

LRDOCS-6355 Analytics Cloud custom asset tracking tutorial

---

developer/appdev/articles/01-web-front-ends/02-angular-widget/02-developing-an-angular-application.markdown

@sez11a this adds the proper language and SF for some of the remaining Angular code blocks

LRDOCS-6299 angular appdev SF code blocks

---

deployment/articles/01-deploying-liferay/03-preparing-for-install.markdown

https://issues.liferay.com/browse/LRDOCS-6439

LRDOCS-6439 7.2: On Sybase, allow nulls by default

---

discover/deployment/articles/01-deploying-liferay/01-preparing-for-install.markdown

https://issues.liferay.com/browse/LRDOCS-6439

LRDOCS-6439 7.1: On Sybase, allow null values by default

---

discover/deployment/articles/02-installing-liferay/01-preparing-for-install.markdown

https://issues.liferay.com/browse/LRDOCS-6439

LRDOCS-6439 7.0: On Sybase, allow nulls by default

---

discover/deployment/articles/06-upgrading-to-liferay-7-1/02-preparing-for-upgrade-to-liferay-7-1/00-preparing-for-upgrade-to-liferay-7-1-intro.markdown
discover/deployment/articles/06-upgrading-to-liferay-7-1/03-running-the-upgrade-process/01-running-the-upgrade-tool.markdown

Mention setting dl.store.impl in portal-upgrade-ext.properties and add more details on updating the documents and media store.
https://issues.liferay.com/browse/LRDOCS-6409

LRDOCS-6409 7.1: Set dl.store.impl property in portal-upgrade-ext.properties

---

discover/deployment/articles/06-upgrading-liferay/02-preparing-for-upgrade.markdown
discover/deployment/articles/06-upgrading-liferay/03-running-the-upgrade-process.markdown

Mention setting dl.store.impl in portal-upgrade-ext.properties and add more details on updating the documents and media store.
https://issues.liferay.com/browse/LRDOCS-6409

LRDOCS-6409 7.0: setting dl.store.impl in portal-upgrade-ext.properties

---

develop/reference/articles/03-back-end/03-portlet-descriptor-to-osgi-service-property-map.markdown
develop/tutorials/articles/110-portlets/01-liferay-mvc-portlet/00-liferay-mvc-portlet-intro.markdown
develop/tutorials/articles/110-portlets/04-spring-mvc/01-configuring-a-spring-mvc-portlet.markdown

https://issues.liferay.com/browse/LRDOCS-6498

LRDOCS-6498 7.1: Explain how Liferay uses portlet name to create portletId

---

discover/deployment/articles/04-securing-liferay/07-openid-connect-authentication.markdown

https://issues.liferay.com/browse/LRDOCS-5609

7.1.x | LRDOCS-5609 Fix FQCN for OpenIdConnectConfiguration

---

develop/tutorials/articles/100-tooling/04-liferay-workspace/05-managing-the-target-platform-for-liferay-workspace.markdown
develop/tutorials/articles/100-tooling/04-liferay-workspace/06-validating-modules-against-the-target-platform/00-intro.markdown

https://issues.liferay.com/browse/LRDOCS-6523

LRDOCS-6523 Target Platform is fully supported | 7.0.x

---

develop/tutorials/articles/100-tooling/04-liferay-workspace/05-managing-the-target-platform-for-liferay-workspace.markdown
develop/tutorials/articles/100-tooling/04-liferay-workspace/07-validating-modules-against-the-target-platform/00-intro.markdown

https://issues.liferay.com/browse/LRDOCS-6523

LRDOCS-6523 Target Platform is fully supported | 7.1.x

---

discover/portal/articles/210-setting-up/03-script-console/03-leveraging-the-script-engine-in-workflow.markdown

Packages were updated in this `liferay-portal` commit: liferay/liferay-portal@6627dad06cbdd97166bde81e239857859751cdf9

LRDOCS-6519 Update asset package paths | 7.1.x

---

user/articles/190-managing-users/01-users-and-organizations/05-managing-organizations.markdown

https://issues.liferay.com/browse/LRDOCS-5812?filter=-1

LRDOCS-5812 organization form

---

develop/tutorials/articles/02-from-liferay-6-to-liferay-7/07-upgrading-plugins-to-liferay-7/02-resolving-a-plugins-dependencies.markdown
develop/tutorials/articles/170-assets/01-adding-updating-and-deleting-assets.markdown
develop/tutorials/articles/180-themes-and-layout-templates/01-themes/02-developing-themes/15-injecting-additional-context-variables-and-functionality-into-your-templates.markdown
develop/tutorials/articles/240-product-navigation/01-customizing-the-product-menu/01-adding-custom-panel-categories.markdown
develop/tutorials/articles/250-collaboration/03-adaptive-media/00-intro.markdown
develop/tutorials/articles/360-osgi-basics-for-liferay-development/05-resolving-third-party-package-dependencies.markdown

liferay#506
liferay#505
liferay#501
liferay#499
liferay#487
liferay#484
Also, please close liferay#503. This was duplicated by another PR.

Liferay PRs | 7.1.x

---

develop/tutorials/articles/04-developing-a-web-application/07-permissions/04-checking-permissions-jsps.markdown

https://issues.liferay.com/browse/LRDOCS-6532
Replaced the bad snippet from the step. This appears to be the sole cause of the issue explained here: https://community.liferay.com/forums/-/message_boards/message/112325264#_com_liferay_message_boards_web_portlet_MBPortlet_message_112871092

LRDOCS-6532 Fixed incorrect permissions code in learning path

---

discover/deployment/articles/06-upgrading-to-liferay-7-1/05-upgrading-a-sharded-environment/00-upgrading-a-sharded-environment-intro.markdown

https://issues.liferay.com/browse/LRDOCS-4820

LRDOCS-4820 7.1: Improve upgrading a sharded environment

---

discover/deployment/articles/06-upgrading-liferay/04-upgrading-sharding.markdown

https://issues.liferay.com/browse/LRDOCS-4820

LRDOCS-4820 7.0: improve upgrading a sharded environment

---

discover/deployment/articles/08-liferay-enterprise-search/03-tuning-scaling-elasticsearch.markdown

https://issues.liferay.com/browse/LRDOCS-6530

LRDOCS-6530

---

discover/deployment/articles/03-configuring-liferay/07-securing-liferay/10-opensso-authentication.markdown

https://issues.liferay.com/browse/LRDOCS-5842
Demanded by https://issues.liferay.com/browse/BPR-23343.
Cheers,
Tibor

LRDOCS-5842 Update OpenSSO doc with OpenAM 13 support related changes

---

discover/deployment/articles/05-configuring-for-high-availability/01-liferay-clustering.markdown

https://issues.liferay.com/browse/LRDOCS-6548

LRDOCS-6548 6.2: S3 requires jets3t upgrade to support signature version 4

---

discover/deployment/articles/03-configuring-liferay/02-document-repository.markdown

https://issues.liferay.com/browse/LRDOCS-6548

LRDOCS-6548 7.0: S3 aws signature version 4 support

---

discover/deployment/articles/03-configuring-liferay/02-document-repository-configuration/03-using-s3-store.markdown

https://issues.liferay.com/browse/LRDOCS-6548

LRDOCS-6548 7.1: S3 aws signature version 4 support

---

deployment/articles/05-upgrading-to-liferay-7-2/01-upgrading-to-liferay-7-2-intro.markdown

https://issues.liferay.com/browse/LRDOCS-6525

LRDOCS-6525 7.2: liferay upgrade intro

---

deployment/articles/05-upgrading-to-liferay-7-2/01-upgrading-to-liferay-7-2-intro.markdown
deployment/articles/05-upgrading-to-liferay-7-2/02-planning-for-deprecated-apps.markdown

https://issues.liferay.com/browse/LRDOCS-6526

LRDOCS-6526 7.2: planning for deprecated apps

---

discover/deployment/articles/08-liferay-enterprise-search/02-configuring-elasticsearch.markdown

https://issues.liferay.com/browse/LRDOCS-6500, basically the same changes I made for 7.1.x, ported to 7.0.x

LRDOCS-6500, for 7.0.x

---

discover/deployment/articles/02-installing-search-engine/01-elasticsearch/03-advanced-configuration.markdown

https://issues.liferay.com/browse/LRDOCS-6500, cc @lipusz @bryanengler

LRDOCS-6500 for 7.1

---

distribute/publish/articles/01-publishing-your-app/02-preparing-your-app/01-marketplace-app-metadata-guidelines.markdown

https://issues.liferay.com/browse/LRDOCS-6581

LRDOCS-6581 7.1 Marketplace: demo site must be valid. Content must not plagiarize.

---

deployment/articles/05-upgrading-to-liferay-7-2/01-upgrading-to-liferay-7-2-intro.markdown
deployment/articles/05-upgrading-to-liferay-7-2/04-preparing-to-upgrade-the-liferay-database.markdown

https://issues.liferay.com/browse/LRDOCS-6116

LRDOCS-6116 7.2: preparing to upgrade the liferay database

---

deployment/articles/05-upgrading-to-liferay-7-2/01-upgrading-to-liferay-7-2-intro.markdown
deployment/articles/05-upgrading-to-liferay-7-2/05-preparing-a-new-liferay-server.markdown

https://issues.liferay.com/browse/LRDOCS-6431

LRDOCS-6431 7.2 preparing a new liferay server for data upgrade

---

deployment/articles/05-upgrading-to-liferay-7-2/01-upgrading-to-liferay-7-2-intro.markdown
deployment/articles/05-upgrading-to-liferay-7-2/07-executing-post-upgrade-tasks.markdown

https://issues.liferay.com/browse/LRDOCS-6120

LRDOCS-6120 7.2: Executing post upgrade tasks

---

deployment/articles/05-upgrading-to-liferay-7-2/01-upgrading-to-liferay-7-2-intro.markdown
deployment/articles/05-upgrading-to-liferay-7-2/06-upgrading-the-liferay-database/01-upgrading-the-liferay-database-intro.markdown

https://issues.liferay.com/browse/LRDOCS-6117

LRDOCS-6117 7.2: upgrading the liferay data

---

deployment/articles/05-upgrading-to-liferay-7-2/01-upgrading-to-liferay-7-2-intro.markdown
deployment/articles/05-upgrading-to-liferay-7-2/06-upgrading-the-liferay-database/01-upgrading-the-liferay-database-intro.markdown
deployment/articles/05-upgrading-to-liferay-7-2/06-upgrading-the-liferay-database/03-configuring-the-data-upgrade.markdown

https://issues.liferay.com/browse/LRDOCS-6528

LRDOCS-6528 7.2: configuring the data upgrade

---

deployment/articles/05-upgrading-to-liferay-7-2/01-upgrading-to-liferay-7-2-intro.markdown
deployment/articles/05-upgrading-to-liferay-7-2/06-upgrading-the-liferay-database/01-upgrading-the-liferay-database-intro.markdown
deployment/articles/05-upgrading-to-liferay-7-2/06-upgrading-the-liferay-database/04-upgrading-the-core-using-the-upgrade-tool.markdown

https://issues.liferay.com/browse/LRDOCS-6118

LRDOCS-6118 7.2: upgrading the core using the upgrade tool

---

deployment/articles/05-upgrading-to-liferay-7-2/01-upgrading-to-liferay-7-2-intro.markdown
deployment/articles/05-upgrading-to-liferay-7-2/06-upgrading-the-liferay-database/01-upgrading-the-liferay-database-intro.markdown
deployment/articles/05-upgrading-to-liferay-7-2/06-upgrading-the-liferay-database/05-upgrading-modules-using-gogo-shell.markdown

https://issues.liferay.com/browse/LRDOCS-6119

LRDOCS-6119 7.2: upgrading modules using gogo shell

---

deployment/articles/05-upgrading-to-liferay-7-2/01-upgrading-to-liferay-7-2-intro.markdown
deployment/articles/05-upgrading-to-liferay-7-2/08-upgrading-a-sharded-environment.markdown

https://issues.liferay.com/browse/LRDOCS-6121

LRDOCS-6121 7.2 upgrading a sharded environment

---

developer/reference/articles-dxp/tooling/dev-studio/02-installing-dev-studio.markdown
developer/reference/articles-dxp/tooling/maven/03-installing-local-liferay-maven-artifacts.markdown

https://issues.liferay.com/browse/LRDOCS-6574

LRDOCS-6574 DXP-only Tooling articles

---

developer/customization/articles/01-liferay-customization.markdown
developer/customization/articles/placeholder.txt

https://issues.liferay.com/browse/LRDOCS-6552

LRDOCS-6552 7.2:  Liferay Customization intro

---

develop/reference/articles/04-front-end/06-setting-up-your-npm-environment.markdown
develop/tutorials/articles/180-themes-and-layout-templates/01-themes/01-creating-themes/00-creating-themes-intro.markdown

@sez11a I've highlighted the environment variable code snippets as `properties` files, since that was the closest language for prismJS that I could find. let me know if you think this should be different. Thanks.
7.2 sent in https://github.com/sez11a/liferay-docs/pull/4097

LRDOCS-6600 port npm config info from 7.0 to 7.1 reference docs

---

developer/reference/articles/front-end/03-setting-up-your-npm-environment.markdown
developer/reference/articles/front-end/05-setting-up-your-npm-environment.markdown
developer/reference/articles/tooling/theme-generator/02-installing-the-theme-generator-and-creating-themes.markdown

7.1 sent in https://github.com/sez11a/liferay-docs/pull/4096

LRDOCS-6600 port npm config info from 7.0 to 7.2 reference docs

---

developer/frameworks/articles/290-configuration/00-configuration-intro.markdown
developer/frameworks/articles/290-configuration/01-configuration-intro.markdown

https://issues.liferay.com/browse/LRDOCS-6629

LRDOCS-6629 Instance Settings

---

deployment/articles/05-upgrading-to-liferay-7-2/01-upgrading-to-liferay-7-2-intro.markdown

https://issues.liferay.com/browse/LRDOCS-6301
cc @gamerson @codyhoag

LRDOCS-6301 7.2: add liferay upgrade plan steps to the data upgrade intro

---

deployment/articles/04-securing-liferay/07-openid-connect-authentication.markdown
developer/customization/articles/02-fundamentals/01-fundamentals-intro.markdown
developer/customization/articles/02-fundamentals/02-configuring-dependencies/01-configuring-dependencies-intro.markdown

https://issues.liferay.com/browse/LRDOCS-6077

LRDOCS-6077 7.2: Configuring Dependencies intro

---

developer/customization/articles/02-fundamentals/01-fundamentals-intro.markdown

https://issues.liferay.com/browse/LRDOCS-6552

LRDOCS-6552 7.2: Customization > Fundamentals intro

---

developer/customization/articles/02-fundamentals/01-fundamentals-intro.markdown
developer/customization/articles/02-fundamentals/04-importing-packages.markdown

https://issues.liferay.com/browse/LRDOCS-6080

LRDOCS-6080 7.2: port Importing Packages

---

developer/customization/articles/02-fundamentals/01-fundamentals-intro.markdown
developer/customization/articles/02-fundamentals/05-exporting-packages.markdown

https://issues.liferay.com/browse/LRDOCS-6081

LRDOCS-6081 7.2: port Exporting Packages

---

developer/customization/articles/02-fundamentals/01-fundamentals-intro.markdown
developer/customization/articles/02-fundamentals/06-semantic-versioning.markdown

https://issues.liferay.com/browse/LRDOCS-6082

LRDOCS-6082 7.2: port Semantic Versioning

---

developer/appdev/articles/02-services-development/01-services-development-intro.markdown

Here's a placeholder intro to merge so that Nick and I can merge into our REST Builder and Service Builder branches. 
No need to close the intro ticket, until the intro is done.
cc/ @ngaskill

LRDOCS-6690 7.2: services development intro placeholder

---

discover/deployment/articles-dxp/08-liferay-enterprise-search/08-xpack-security.markdown
discover/deployment/articles-dxp/08-liferay-enterprise-search/09-xpack-monitoring.markdown
discover/deployment/articles-dxp/08-liferay-enterprise-search/10-xpack-elasticsearch-6.1/00-xpack-security-61-intro.markdown
discover/deployment/articles-dxp/08-liferay-enterprise-search/10-xpack-elasticsearch-6.1/01-xpack-monitoring-61.markdown
discover/deployment/articles/02-installing-liferay/10-configuring-search.markdown
discover/deployment/articles/08-liferay-enterprise-search/02-configuring-elasticsearch.markdown
discover/deployment/articles/08-liferay-enterprise-search/07-upgrading-to-elasticsearch-6.markdown

https://issues.liferay.com/browse/LRDOCS-6537, we had gone through a similar process for 7.1, so I updated the 7.0 steps based on that work. They are waiting on docs to release, so please merge as quickly as possible. cc @lipusz @xbrianlee

Elasticsearch 6.5 | Liferay 7.0 | LRDOCS-6537

---

develop/tutorials/articles/02-from-liferay-6-to-liferay-7/07-upgrading-plugins-to-liferay-7/07-upgrading-62-layout-templates-to-71.markdown
develop/tutorials/articles/03-from-liferay-70-to-71/00-from-liferay-70-to-71-intro.markdown
develop/tutorials/articles/03-from-liferay-70-to-71/07-upgrading-70-layout-templates-to-71.markdown
develop/tutorials/articles/180-themes-and-layout-templates/02-layout-templates/05-upgrading-6-2-layout-templates-to-7-1.markdown
develop/tutorials/articles/180-themes-and-layout-templates/02-layout-templates/06-upgrading-7-0-layout-templates-to-7-1.markdown
develop/tutorials/articles/320-wysiwyg-editors/04-alloy-editor/01-adding-buttons-to-the-alloyeditor/00-adding-buttons-to-the-alloy-editor-intro.markdown

@sez11a this includes these tickets:
LRDOCS-6672 AlloyEditor fix broken link
LRDOCS-6264 Upgrading layout templates to 7.1
cc @jhinkey

LRDOCS-6672 fix 7.1 link and create upgrading layout templates

---

develop/reference/articles/09-project-templates/rest-template.markdown

https://issues.liferay.com/browse/LRDOCS-6702

LRDOCS-6702 Note REST project template issue with BOMs | 7.1.x

---

develop/tutorials/articles/120-service-builder/02-service-builder-persistence/05-developing-custom-sql-queries.markdown

https://issues.liferay.com/browse/LRDOCS-6704

LRDOCS-6704 7.0: Fix - Replace CustomSQL with CustomSQLUtil

---

discover/portal/articles/150-setting-up-liferay/01-system-settings/03-server-admin.markdown

https://issues.liferay.com/browse/LRDOCS-6867

LRDOCS-6867 7.0: Fix file store data migration instructions 

---

develop/tutorials/articles/100-tooling/05-maven/02-generating-new-projects-using-archetypes.markdown

https://issues.liferay.com/browse/LRDOCS-6859

LRDOCS-6859 Fix erroneous Maven archetype message | 7.0.x

---

develop/tutorials/articles/100-tooling/05-maven/02-generating-new-projects-using-archetypes.markdown

https://issues.liferay.com/browse/LRDOCS-6859

LRDOCS-6859 Fix erroneous Maven archetype message | 7.1.x

---

deployment/articles/05-upgrading-to-liferay-7-2/06-upgrading-the-liferay-database/02-tuning-for-the-data-upgrade.markdown

https://issues.liferay.com/browse/LRDOCS-6432

LRDOCS-6432 7.2: tuning your database for the upgrade

---

developer/appdev/articles/02-services-development/01-service-builder/01-service-builder-intro.markdown
developer/appdev/articles/02-services-development/01-service-builder/02-creating-a-service-builder-project.markdown
developer/appdev/articles/02-services-development/01-services-development-intro.markdown

https://issues.liferay.com/browse/LRDOCS-6716

LRDOCS-6716 7.2: creating service builder projects

---

developer/reference/articles-dxp/customization-with-ext/02-customizing-core-functionality-with-ext/01-intro.markdown
developer/reference/articles-dxp/customization-with-ext/04-extending-core-classes-using-spring-with-ext-plugins.markdown
developer/reference/articles-dxp/customization-with-ext/05-overriding-core-classes-with-ext-plugins.markdown
developer/reference/articles-dxp/customization-with-ext/06-adding-to-the-web-xml-with-ext-plugins.markdown
developer/reference/articles-dxp/customization-with-ext/07-modifying-the-web-xml-with-ext-plugins.markdown
developer/reference/articles/customization-with-ext/01-intro.markdown
developer/reference/articles/customization-with-ext/02-customizing-core-functionality-with-ext/01-intro.markdown
developer/reference/articles/customization-with-ext/02-customizing-core-functionality-with-ext/02-creating-an-ext-plugin.markdown
developer/reference/articles/customization-with-ext/02-customizing-core-functionality-with-ext/03-anatomy-of-an-ext-plugin.markdown
developer/reference/articles/customization-with-ext/02-customizing-core-functionality-with-ext/04-developing-an-ext-plugin.markdown
developer/reference/articles/customization-with-ext/02-customizing-core-functionality-with-ext/05-deploying-an-ext-plugin.markdown
developer/reference/articles/customization-with-ext/02-customizing-core-functionality-with-ext/06-redeploying-an-ext-plugin.markdown
developer/reference/articles/customization-with-ext/03-customizing-osgi-modules-with-ext/01-intro.markdown
developer/reference/articles/customization-with-ext/03-customizing-osgi-modules-with-ext/02-creating-an-ext-module.markdown
developer/reference/articles/customization-with-ext/03-customizing-osgi-modules-with-ext/03-developing-an-ext-module.markdown
developer/reference/articles/customization-with-ext/03-customizing-osgi-modules-with-ext/04-deploying-an-ext-module.markdown

https://issues.liferay.com/browse/LRDOCS-6839

LRDOCS-6839 Customization with Ext

---

develop/tutorials/articles/120-service-builder/02-service-builder-persistence/08-connecting-service-builder-to-external-data-sources.markdown

https://issues.liferay.com/browse/LRDOCS-6883

LRDOCS-6883 7.0: Service Builder module's entities bind to same data source

---

develop/tutorials/articles/130-service-builder/02-service-builder-persistence/09-connecting-service-builder-to-external-data-sources.markdown

https://issues.liferay.com/browse/LRDOCS-6883

LRDOCS-6883 7.1: Service Builder's entities are bound to the same datasource

---

discover/portal/articles/120-search/06-search-configuration.markdown

https://issues.liferay.com/browse/LRDOCS-6879, cc @lipusz

7.1 | LRDOCS-6879 | Add config file names for each sys settings entry

---

developer/customization/articles/02-fundamentals/02-configuring-dependencies/05-understanding-excluded-jars.markdown

https://issues.liferay.com/browse/LRDOCS-6697

LRDOCS-6697 7.2: port Understanding Excluded JARs

---

developer/frameworks/articles/140-application-security/01-intro.markdown
developer/frameworks/articles/140-application-security/02-application-permissions/01-application-permissions-intro.markdown
developer/frameworks/articles/140-application-security/02-application-permissions/02-defining-permissions.markdown
developer/frameworks/articles/140-application-security/02-application-permissions/03-registering-permissions.markdown
developer/frameworks/articles/140-application-security/02-application-permissions/04-associate-permissions-resources.markdown
developer/frameworks/articles/140-application-security/02-application-permissions/05-check-permissions.markdown
developer/frameworks/articles/140-application-security/04-authentication-pipelines/01-intro.markdown
developer/frameworks/articles/140-application-security/04-authentication-pipelines/02-auto-login.markdown
developer/frameworks/articles/140-application-security/04-authentication-pipelines/03-authentication-pipelines.markdown
developer/frameworks/articles/140-application-security/04-authentication-pipelines/04-custom-login-portlet.markdown
developer/frameworks/articles/140-application-security/06-service-access-policies.markdown
developer/frameworks/articles/290-configuration/01-configuration-intro.markdown
developer/frameworks/articles/290-configuration/08-upgrading-configurable-apps.markdown
developer/frameworks/articles/290-configuration/10-upgrading-a-legacy-app.markdown

https://issues.liferay.com/browse/LRDOCS-6855

LRDOCS-6855 upgrading a legacy app

---

developer/customization/articles/02-fundamentals/02-configuring-dependencies/04-resolving-third-party-library-package-dependencies.markdown

https://issues.liferay.com/browse/LRDOCS-6079

LRDOCS-6079 7.2 port Resolving third party lib deps

---

developer/reference/articles/03-back-end/01-back-end-intro.markdown
developer/reference/articles/03-back-end/03-portlet-descriptor-to-osgi-service-property-map.markdown

https://issues.liferay.com/browse/LRDOCS-6211

LRDOCS-6211 7.2 port Portlet descriptor to osgi property map

---

deployment/articles/01-deploying-liferay/03-preparing-for-install.markdown
deployment/articles/01-deploying-liferay/04-installing-liferay.markdown
deployment/articles/01-deploying-liferay/05-installing-liferay-on-tomcat.markdown
deployment/articles/05-upgrading-to-liferay-7-2/05-preparing-a-new-liferay-server.markdown
deployment/articles/100-reference/05-database-templates.markdown

Updated the Database Templates
Update the server prep instructions mentioning driver update and JCR store migration to do before data upgrade.
https://issues.liferay.com/browse/LRDOCS-6863
https://issues.liferay.com/browse/LRDOCS-6853

LRDOCS-6853 LRDOCS-6863 7.2: MySQL driver. Update driver & migrate from JCR store.

---

developer/reference/articles/breaking-changes.markdown

https://issues.liferay.com/browse/LRDOCS-6875

LRDOCS-6875 Breaking Changes for Liferay 7.2

---

developer/reference/articles/tooling/maven/99-upgrading-your-maven-build-environment.markdown

https://issues.liferay.com/browse/LRDOCS-6876

LRDOCS-6876 Upgrading Maven Build (not to workspace)

---

developer/frameworks/articles/front-end-development/02-themes/03-developing-themes/03-building-themes.markdown
developer/frameworks/articles/front-end-development/02-themes/03-developing-themes/04-deploying-and-applying-themes.markdown
developer/frameworks/articles/front-end-development/02-themes/03-developing-themes/07-configuring-your-themes-app-server.markdown
developer/frameworks/articles/front-end-development/02-themes/03-developing-themes/09-automatically-deploying-theme-changes.markdown
developer/frameworks/articles/front-end-development/02-themes/04-extending-themes/02-installing-themelets-in-your-theme.markdown
developer/frameworks/articles/front-end-development/02-themes/04-extending-themes/05-changing-the-base-theme.markdown
developer/frameworks/articles/front-end-development/02-themes/04-extending-themes/06-copying-an-existing-themes-files.markdown
developer/frameworks/articles/front-end-development/02-themes/04-extending-themes/07-listing-your-themes-extensions.markdown
developer/reference/articles/tooling/theme-generator/02-installing-the-theme-generator-and-creating-themes.markdown

@sez11a please publish this update as soon as you can. Training wants to point to it.

LRDOCS-6881 Note that Gulp is included as a dependency

---

deployment/articles/01-deploying-liferay/03-preparing-for-install.markdown

https://issues.liferay.com/browse/LRDOCS-6898

LRDOCS-6898 7,2: Recommend heap size 2gb

---

user/articles/120-search/02-what-new-search.markdown

https://issues.liferay.com/browse/LRDOCS-6854, What's New in Search. cc @lipusz

LRDOCS-6854 | What's New in Search | 7.2 User Guide

---

deployment/articles-dxp/01-saml/01-intro.markdown
deployment/articles-dxp/01-saml/04-setting-up-service-provider.markdown

Hey Rich,
The 5.0.0 version of the app contain some long-awaited features so I thought we should highlight it in the doc as well.
For
>  * Extension point for developers to customize which Identity Providers to display end-users to sign in with
we'll need to add the content of https://issues.liferay.com/browse/LPS-88090 to a new sub-page.
Regards,
Tibor

7.2 | LPS-84196 What's new section for SAML + minor edits

---

developer/customization/articles/02-fundamentals/03-felix-gogo-shell.markdown

https://issues.liferay.com/browse/LRDOCS-6708

LRDOCS-6708 Gogo Shell

---

developer/tutorials/articles/03-upgrading-code-to-liferay-7.2/08-upgrading-themes/02-upgrading-6.2-themes-7.2/04-updating-6.2-css-code/02-updating-bootstrap-rules-and-font-awesome-imports.markdown

Fix TOC issues that were generated before TOC logic was fixed

---

deployment/articles/05-upgrading-to-liferay-7-2/99-deprecated-apps-in-7-2-what-to-do.markdown

LRDOCS-6122 add Resources Importer

---

deployment/articles/03-installing-a-search-engine/02-elasticsearch/07-backing-up-es.markdown

https://issues.liferay.com/browse/LRDOCS-6940 straight conversion with some code block editing and mild textual massaging. Discussed with @lipusz over slack.

7.2 Deployment Conversion | Bakcing up Elasticsearch | LRDOCS-6940

---

user/articles/120-search/01-search-configuration-intro.markdown

https://issues.liferay.com/browse/LRDOCS-6949, this concludes the new search user features for 7.2, I just added it to an existing article, which is the intro, which I also renumbered. Just a new visualization to report on. cc @lipusz, I didn't think a full review was needed here, though we'll need to circle back and break this article up, I think. It's kind of monstrous.

Search, 7.2 Improvement | Field Mappings | LRDOCS-6949

---

developer/frameworks/articles/configuration/10-upgrading-a-legacy-app.markdown
developer/frameworks/articles/localization/01-localization-intro.markdown
developer/frameworks/articles/localization/02-localizing-your-application.markdown

This is a How To on Localizing Your Application
https://issues.liferay.com/browse/LRDOCS-6064

LRDOCS-6064 7.2: Localizing Your Application

---

deployment/articles/05-upgrading-to-liferay-7-2/99-deprecated-apps-in-7-2-what-to-do.markdown

https://issues.liferay.com/browse/LRDOCS-6122, cc @jhinkey, @lipusz

App Deprecations, 7.2 | LRDOCS-6122 | Forms and Search

---

deployment/articles-dxp/03-installing-a-search-engine/03-enterprise-search/01-security/01-security-intro.markdown
deployment/articles-dxp/03-installing-a-search-engine/03-enterprise-search/02-monitoring/01-monitoring-intro.markdown
deployment/articles/03-installing-a-search-engine/02-elasticsearch/04-configuring-the-connector.markdown
deployment/articles/04-securing-liferay/05-ldap/01-ldap-servers-intro.markdown

ant convert-links on deployment section

---

user/articles/100-web-experience-management/03-building-a-site/07-configuring-widgets/02-look-and-feel-configuration.markdown

https://issues.liferay.com/browse/LRDOCS-6353

LRDOCS-6353 Remove "portlet link" reference from figure text

---

deployment/articles-dxp/06-maintaining-liferay/01-patching-liferay-dxp/01-patching-liferay-dxp-intro.markdown
deployment/articles-dxp/06-maintaining-liferay/01-patching-liferay-dxp/02-patching-basics/01-patching-basics-intro.markdown
deployment/articles-dxp/06-maintaining-liferay/01-patching-liferay-dxp/03-using-the-patching-tool/01-using-the-patching-tool-intro.markdown
deployment/articles-dxp/06-maintaining-liferay/01-patching-liferay-dxp/03-using-the-patching-tool/02-installing-patches.markdown
deployment/articles-dxp/06-maintaining-liferay/01-patching-liferay-dxp/03-using-the-patching-tool/03-working-with-patches.markdown
deployment/articles-dxp/06-maintaining-liferay/01-patching-liferay-dxp/04-configuring-the-patching-tool/01-configuring-the-patching-tool-intro.markdown
deployment/articles-dxp/06-maintaining-liferay/01-patching-liferay-dxp/04-configuring-the-patching-tool/02-patching-tool-basic-configuration.markdown
deployment/articles-dxp/06-maintaining-liferay/01-patching-liferay-dxp/04-configuring-the-patching-tool/03-patching-tool-advanced-configuration.markdown
deployment/articles-dxp/06-maintaining-liferay/01-patching-liferay-dxp/04-configuring-the-patching-tool/04-installing-patches-on-the-liferay-war.markdown
deployment/articles-dxp/06-maintaining-liferay/01-patching-liferay-dxp/05-keeping-up-with-fix-packs/01-keeping-up-with-fix-packs-intro.markdown
deployment/articles-dxp/100-reference/06-comparing-patch-levels.markdown
deployment/articles-dxp/100-reference/07-patching-tool-configuration-properties.markdown
deployment/articles/06-maintaining-liferay/01-maintaining-liferay-intro.markdown
deployment/articles/06-maintaining-liferay/02-backing-up-a-liferay-installation.markdown

@sez11a this includes these tickets:
LRDOCS-6182 - LRDOCS-6186
LRDOCS-6692 and LRDOCS-6693
cc @jhinkey

LRDOCS-6182 port Maintaining Liferay articles to 7.2

---

deployment/articles/01-deploying-liferay/06-installing-liferay-portal-on-wildfly.markdown

@sez11a ,
Jim already reviewed this and asked me to create this PR.
Thanks

LRDOCS-6157

---

developer/customization/articles/02-fundamentals/06-semantic-versioning.markdown

https://issues.liferay.com/browse/LRDOCS-6082 (already closed)

LRDOCS-6082 7.2: fix links in semantic versioning customization doc

---

deployment/articles/02-configuring-liferay/04-liferay-portal-clustering/04-clustering-search.markdown
deployment/articles/03-installing-a-search-engine/01-intro.markdown
deployment/articles/03-installing-a-search-engine/02-elasticsearch/01-elasticsearch-intro.markdown
deployment/articles/03-installing-a-search-engine/02-elasticsearch/03-installing-elasticsearch.markdown
deployment/articles/03-installing-a-search-engine/02-elasticsearch/04-configuring-the-connector.markdown
developer/reference/articles/workflow/01-creating-workflow-definitions-intro.markdown
developer/reference/articles/workflow/02-workflow-nodes.markdown
developer/reference/articles/workflow/03-tasks.markdown
user/articles/05-setting-up/01-system-settings/03-server-administration/00-intro.markdown
user/articles/120-search/01-search-intro.markdown
user/articles/130-forms/04-form-fields.markdown
user/articles/130-forms/99-ddl/07-creating-display-templates.markdown

looked at the 7-1, 7.1, 7_1 links in my articles and fixed.

link fixing

---

discover/portal/articles/100-web-experience-management/05-publishing-content-dynamically/03-publishing-rss-feeds/01-configuring-rss-feeds.markdown

LRDOCS-6968 RSS Feeds Enablement | 7.1.x

---

user/articles/100-web-experience-management/06-publishing-content-dynamically/04-publishing-rss-feeds/02-configuring-rss-feeds.markdown
user/articles/100-web-experience-management/06-publishing-content-dynamically/04-publishing-rss-feeds/03-rss-publisher-widget.markdown

https://issues.liferay.com/browse/LRDOCS-6968

LRDOCS-6968 RSS Feeds Enablement

---

developer/frameworks/articles/info-framework/02-creating-information-list-provider.markdown

Remove special chars that were breaking build

---

deployment/articles/05-upgrading-to-liferay-7-2/99-deprecated-apps-in-7-2-what-to-do.markdown

Fix and improvement to deprecated apps.
cc/ @nicolelau

LRDOCS-6122 7.2: fix link and make Deprecated Apps and Features heading.

---

discover/deployment/articles/08-liferay-enterprise-search/02-configuring-elasticsearch.markdown

https://issues.liferay.com/browse/LRDOCS-6967, added the config file name for the Elasticsearch 6 Connector.

7.0 Elasticsearch Improvement | LRDOCS-6967

---

deployment/articles/03-installing-a-search-engine/01-intro.markdown
deployment/articles/03-installing-a-search-engine/02-elasticsearch/01-elasticsearch-intro.markdown
deployment/articles/03-installing-a-search-engine/02-elasticsearch/02-preparing-to-install.markdown
deployment/articles/03-installing-a-search-engine/02-elasticsearch/03-installing-elasticsearch.markdown
deployment/articles/100-reference/01-deployment-reference-intro.markdown
developer/customization/articles/liferay-forms/02-form-storage-adapters.markdown
developer/frameworks/articles/workflow/02-workflow-framework.markdown
user/articles/05-setting-up/03-script-console/03-leveraging-the-script-engine-in-workflow.markdown
user/articles/05-setting-up/03-script-console/04-script-examples.markdown
user/articles/120-search/01-search-intro.markdown
user/articles/120-search/06-search-results/05-results-behavior.markdown
user/articles/120-search/08-multilanguage-search.markdown
user/articles/130-forms/06-data-providers.markdown
user/articles/140-workflow/01-workflow-intro.markdown
user/articles/140-workflow/02-activating-workflow.markdown
user/articles/140-workflow/04-reviewing-assets.markdown

fixing bad links

---

deployment/articles/05-upgrading-to-liferay-7-2/01-upgrading-to-liferay-7-2-intro.markdown

https://issues.liferay.com/browse/LRDOCS-6978

LRDOCS-6978 Add Flexmark extensions so tooling can read outline

---

developer/frameworks/articles/front-end-development/07-javascript-module-loaders/01-javascript-module-loaders-intro.markdown
developer/frameworks/articles/front-end-development/07-javascript-module-loaders/02-loading-amd-modules-in-liferay.markdown
developer/frameworks/articles/front-end-development/07-javascript-module-loaders/03-using-external-libraries.markdown
developer/frameworks/articles/front-end-development/07-javascript-module-loaders/04-loading-modules-with-aui-script-tag/01-loading-modules-with-aui-script.markdown
developer/frameworks/articles/front-end-development/07-javascript-module-loaders/04-loading-modules-with-aui-script-tag/02-loading-aui-modules-with-aui.markdown
developer/frameworks/articles/front-end-development/07-javascript-module-loaders/04-loading-modules-with-aui-script-tag/03-loading-es2015-and-metal-modules-with-aui-script-tag.markdown
developer/frameworks/articles/front-end-development/07-javascript-module-loaders/04-loading-modules-with-aui-script-tag/04-loading-aui-es2015-metal-modules-with-aui.markdown

@sez11a this includes LRDOCS-6026 and LRDOCS-6049-6051

LRDOCS-6026 port JS module loaders docs to 7.2

---

develop/reference/articles/05-mobile/01-android-screenlets/22-ddm-form-screenlet-android.markdown
discover/portal/articles/100-web-experience-management/05-publishing-content-dynamically/03-publishing-rss-feeds/01-configuring-rss-feeds.markdown

https://issues.liferay.com/MOBILE-1137, thanks @victorlaerte

MOBILE-1337

---

developer/frameworks/articles/localization/03-using-language-module.markdown

LRDOCS-6067 Using a Language Module

---

user/articles-dxp/140-workflow/07-workflow-designer/03-workflow-designer-nodes.markdown
user/articles-dxp/140-workflow/07-workflow-designer/05-workflow-designer-tasks.markdown

fixed a couple more links in articles-dxp

fixed 2 links

---

developer/reference/articles/gradle-plugins/target-platform-gradle-plugin.markdown

https://issues.liferay.com/browse/LRDOCS-6903

LRDOCS-6903 Update Target Platform Gradle plugin

---

developer/reference/articles/breaking-changes.markdown

brianchandotcom/liferay-portal#74290

LPS-87868 New breaking change

---

deployment/articles/05-upgrading-to-liferay-7-2/01-upgrading-to-liferay-7-2-intro.markdown

https://issues.liferay.com/browse/LRDOCS-6525

LRDOCS-6525 link the installation upgrade docs to the code upgrade tutorial

---

developer/reference/articles/tooling/01-creating-a-project.markdown
developer/reference/articles/tooling/02-deploying-a-project.markdown
developer/reference/articles/tooling/blade-cli/03-installing-blade-cli-with-proxy-requirements.markdown
developer/reference/articles/tooling/blade-cli/04-managing-your-liferay-server-with-blade-cli.markdown
developer/reference/articles/tooling/blade-cli/05-generating-project-samples-with-blade-cli.markdown
developer/reference/articles/tooling/blade-cli/06-updating-blade-cli.markdown
developer/reference/articles/tooling/blade-cli/100-common-errors-with-blade-cli-installation.markdown
developer/reference/articles/tooling/dev-studio/03-setting-proxy-requirements-for-dev-studio.markdown
developer/reference/articles/tooling/dev-studio/07-searching-liferay-portal-source-with-dev-studio.markdown
developer/reference/articles/tooling/dev-studio/08-debugging-liferay-portal-source-with-dev-studio.markdown
developer/reference/articles/tooling/liferay-workspace/03-creating-a-liferay-workspace.markdown
developer/reference/articles/tooling/liferay-workspace/05-setting-proxy-requirements-for-liferay-workspace.markdown
developer/reference/articles/tooling/liferay-workspace/06-adding-a-liferay-bundle-to-workspace.markdown
developer/reference/articles/tooling/liferay-workspace/10-managing-the-target-platform/01-intro.markdown
developer/reference/articles/tooling/liferay-workspace/11-validating-modules-against-the-target-platform/01-intro.markdown
developer/reference/articles/tooling/liferay-workspace/11-validating-modules-against-the-target-platform/06-how-to-resolve-common-output-errors-reported-by-the-resolve-task.markdown
developer/reference/articles/tooling/liferay-workspace/13-updating-liferay-workspace.markdown
developer/reference/articles/tooling/maven/99-upgrading-your-maven-build-environment.markdown

https://issues.liferay.com/browse/LRDOCS-6365
https://issues.liferay.com/browse/LRDOCS-6369
https://issues.liferay.com/browse/LRDOCS-6414
https://issues.liferay.com/browse/LRDOCS-6912
https://issues.liferay.com/browse/LRDOCS-6913
https://issues.liferay.com/browse/LRDOCS-6917
Also added new syntax highlighting for articles that were converted early in 7.2 conversion process.

LRDOCS-6917 Tooling Updates

---

developer/frameworks/articles/dependency-injection/02-cdi-dependency-injection.markdown
developer/reference/articles/cdi-portlet-predefined-beans.markdown

Hi Rich,
These articles are for dev > frameworks and dev > reference. Thanks!
https://issues.liferay.com/browse/LRDOCS-4674 CDI Dependency Injection (frameworks)
https://issues.liferay.com/browse/LRDOCS-6914 CDI Portlet Predefined Beans (reference)

  LRDOCS-4674   LRDOCS-6914 7.2: CDI

---

developer/appdev/articles/02-web-front-ends/08-liferay-mvc-portlet/01-liferay-mvc-portlet-intro.markdown

https://issues.liferay.com/browse/LRDOCS-6131

LRDOCS-6131 7.2: port Liferay MVC Portlet intro

---

developer/frameworks/articles/user-associated-data/01-managing-uad-intro.markdown
developer/frameworks/articles/user-associated-data/02-implementing-uad.markdown

https://issues.liferay.com/browse/LRDOCS-7024, ported the GDPR dev doc.

7.2 Port | UAD Framework | LRDOCS-7024

---

discover/deployment/articles/02-advanced-portal-operation/06-upgrading-liferay.markdown

https://issues.liferay.com/browse/LRDOCS-7029

LRDOCS-7029 6.2 Fix: link to newly uploaded groovy scripts

---

deployment/articles/02-configuring-liferay/04-liferay-portal-clustering/05-enabling-cluster-link.markdown
developer/customization/articles/customizing-jsps/02-customizing-jsps-with-dynamic-includes.markdown
developer/customization/articles/customizing-jsps/03-jsp-overrides-using-portlet-filters.markdown
developer/customization/articles/overriding-osgi-services/02-examining-an-service-to-override.markdown
developer/customization/articles/overriding-osgi-services/03-creating-a-custom-osgi-service.markdown
developer/customization/articles/overriding-osgi-services/04-reconfiguring-components-to-use-your-osgi-service-reference.markdown

https://issues.liferay.com/browse/LRDOCS-7033
This updates these guides:
- Deployment
- Developer > Customization
Thanks!

LRDOCS-7033 7.2: Update links to core documents

---

develop/tutorials/articles/02-from-liferay-6-to-liferay-7/07-upgrading-plugins-to-liferay-7/04-upgrading-portlet-plugins/01-upgrading-a-genericportlet.markdown
develop/tutorials/articles/02-from-liferay-6-to-liferay-7/07-upgrading-plugins-to-liferay-7/04-upgrading-portlet-plugins/03-upgrading-portlets-that-use-service-builder.markdown
develop/tutorials/articles/02-from-liferay-6-to-liferay-7/07-upgrading-plugins-to-liferay-7/04-upgrading-portlet-plugins/04-upgrading-a-liferay-jsfportlet.markdown
develop/tutorials/articles/02-from-liferay-6-to-liferay-7/07-upgrading-plugins-to-liferay-7/04-upgrading-portlet-plugins/05-upgrading-a-servlet-based-portlet.markdown
develop/tutorials/articles/02-from-liferay-6-to-liferay-7/07-upgrading-plugins-to-liferay-7/04-upgrading-portlet-plugins/06-upgrading-a-spring-mvc-portlet.markdown
develop/tutorials/articles/120-customizing/01-customizing-jsps/01-customizing-jsps-with-dynamic-includes.markdown
develop/tutorials/articles/120-customizing/01-customizing-jsps/02-jsp-overrides-using-portlet-filters.markdown
develop/tutorials/articles/120-customizing/03-overriding-osgi-services/01-examining-an-service-to-override.markdown
develop/tutorials/articles/120-customizing/03-overriding-osgi-services/02-creating-a-custom-osgi-service.markdown
develop/tutorials/articles/120-customizing/03-overriding-osgi-services/03-reconfiguring-components-to-use-your-osgi-service-reference.markdown
develop/tutorials/articles/330-servlets/02-servlet-filters.markdown
develop/tutorials/articles/360-osgi-basics-for-liferay-development/07-using-the-wab-generator.markdown
discover/deployment/articles/03-configuring-liferay/03-liferay-portal-clustering/04-enabling-cluster-link.markdown

https://issues.liferay.com/browse/LRDOCS-7033
Guides:
- Developer > Tutorials
- Deployment

LRDOCS-7033 7.1: Update core document links

---

develop/tutorials/articles/02-from-liferay-6-to-liferay-7/07-upgrading-plugins-to-liferay-7/04-upgrading-portlet-plugins/01-upgrading-a-genericportlet.markdown
develop/tutorials/articles/02-from-liferay-6-to-liferay-7/07-upgrading-plugins-to-liferay-7/04-upgrading-portlet-plugins/02-upgrading-a-servlet-based-portlet.markdown
develop/tutorials/articles/02-from-liferay-6-to-liferay-7/07-upgrading-plugins-to-liferay-7/04-upgrading-portlet-plugins/04-upgrading-portlets-that-use-service-builder.markdown
develop/tutorials/articles/02-from-liferay-6-to-liferay-7/07-upgrading-plugins-to-liferay-7/04-upgrading-portlet-plugins/06-upgrading-a-struts-portlet.markdown
develop/tutorials/articles/02-from-liferay-6-to-liferay-7/07-upgrading-plugins-to-liferay-7/04-upgrading-portlet-plugins/07-upgrading-a-spring-mvc-portlet.markdown
develop/tutorials/articles/111-customizing/01-overriding-jsps/01-jsp-overrides-using-dynamic-includes.markdown
develop/tutorials/articles/111-customizing/01-overriding-jsps/02-jsp-overrides-using-portlet-filters.markdown
develop/tutorials/articles/280-testing/02-arquillian-extension-for-liferay-example/00-arquillian-extension-for-liferay-example-intro.markdown
develop/tutorials/articles/300-osgi-basics/04-overriding-service-references.markdown
develop/tutorials/articles/300-osgi-basics/05-using-the-wab-generator.markdown
discover/deployment/articles-dxp/03-configuring-liferay/03-liferay-clustering.markdown
discover/deployment/articles/03-configuring-liferay/03-liferay-clustering.markdown

https://issues.liferay.com/browse/LRDOCS-7033
Guides:
- Developer > Tutorials
- Deployment

LRDOCS-7033 7.0: Update links to core 7.0 documents

---

deployment/articles/05-upgrading-to-liferay-7-2/98-deprecated-apps-in-7-2-what-to-do.markdown
deployment/articles/05-upgrading-to-liferay-7-2/99-apps-in-maintenance-mode.markdown

https://issues.liferay.com/browse/LRDOCS-7011

LRDOCS-7011 7.2: put maint mode app content in new article

---

deployment/articles/04-securing-liferay/01-liferay-security-intro.markdown
developer/reference/articles/breaking-changes.markdown
developer/reference/articles/cdi-portlet-predefined-beans.markdown
developer/reference/articles/front-end/03-front-end-taglibs/03-liferay-frontend-taglibs/03-liferay-frontend-cards.markdown
developer/reference/articles/tooling/maven/06-deploying-liferay-maven-artifacts-to-a-repository.markdown
user/articles/100-web-experience-management/04-managing-content/02-web-content/03-designing-uniform-content/01-designing-structured-content-intro.markdown

https://issues.liferay.com/browse/LRDOCS-7038
affects these 7.2 guides
-----
deployment
developer > reference
user guide

LRDOCS-7038 7.2:  replace ldn and dm refs

---

deployment/articles/01-deploying-liferay/02-obtaining-liferay.markdown
deployment/articles/01-deploying-liferay/03-preparing-for-install.markdown
deployment/articles/01-deploying-liferay/06-installing-liferay-portal-on-wildfly.markdown
deployment/articles/04-securing-liferay/01-liferay-security-intro.markdown
developer/reference/articles/breaking-changes.markdown
developer/reference/articles/cdi-portlet-predefined-beans.markdown
developer/reference/articles/front-end/03-front-end-taglibs/03-liferay-frontend-taglibs/03-liferay-frontend-cards.markdown
developer/reference/articles/tooling/maven/06-deploying-liferay-maven-artifacts-to-a-repository.markdown
user/articles/100-web-experience-management/04-managing-content/02-web-content/03-designing-uniform-content/01-designing-structured-content-intro.markdown

https://issues.liferay.com/browse/LRDOCS-7046
\cc @jhinkey

LRDOCS-7046 Wildfly is no longer an available bundle

---

deployment/articles/01-deploying-liferay/02-obtaining-liferay.markdown
deployment/articles/01-deploying-liferay/03-preparing-for-install.markdown
deployment/articles/01-deploying-liferay/06-installing-liferay-portal-on-wildfly.markdown
deployment/articles/04-securing-liferay/01-liferay-security-intro.markdown
developer/appdev/articles/01-application-development-intro.markdown
developer/appdev/articles/02-web-front-ends/01-web-front-ends-intro.markdown
developer/appdev/articles/02-web-front-ends/05-bean-portlet/01-bean-portlet-intro.markdown
developer/appdev/articles/02-web-front-ends/06-jsf-portlet/02-developing-a-jsf-portlet-application.markdown
developer/appdev/articles/02-web-front-ends/08-liferay-mvc-portlet/01-liferay-mvc-portlet-intro.markdown
developer/appdev/articles/03-services-development/02-service-builder/01-service-builder-intro.markdown
developer/appdev/articles/99-troubleshooting-application-development-issues/artifact-versions-dependencies.markdown
developer/appdev/articles/99-troubleshooting-application-development-issues/connecting-to-jndi-data-sources.markdown
developer/appdev/articles/99-troubleshooting-application-development-issues/detecting-unresolved-osgi-components.markdown
developer/appdev/articles/99-troubleshooting-application-development-issues/disabling-cache-on-table-mapper-tables.markdown
developer/appdev/articles/99-troubleshooting-application-development-issues/resolving-cnfe-and-cdnfe-in-osgi-bundles.markdown
developer/frameworks/articles/front-end-development/02-themes/03-developing-themes/07-configuring-your-themes-app-server.markdown
developer/frameworks/articles/front-end-development/02-themes/03-developing-themes/10-creating-a-thumbnail-preview-for-your-theme.markdown
developer/frameworks/articles/front-end-development/02-themes/03-developing-themes/11-creating-color-schemes-for-your-theme.markdown
developer/frameworks/articles/front-end-development/05-creating-js-widgets-with-js-tooling/05-using-translation-features.markdown
developer/frameworks/articles/front-end-development/07-javascript-module-loaders/03-using-external-libraries.markdown
developer/frameworks/articles/portlets/07-using-javascript-in-your-portlets/02-using-esplus-modules-in-your-portlets.markdown
developer/frameworks/articles/wysiwyg-editors/04-alloy-editor/03-creating-new-buttons-for-alloyeditor/04-contributing-the-button-to-the-available-list.markdown
developer/reference/articles/breaking-changes.markdown
developer/reference/articles/cdi-portlet-predefined-beans.markdown
developer/reference/articles/front-end/03-front-end-taglibs/03-liferay-frontend-taglibs/03-liferay-frontend-cards.markdown
developer/reference/articles/tooling/maven/06-deploying-liferay-maven-artifacts-to-a-repository.markdown
user/articles/100-web-experience-management/04-managing-content/02-web-content/03-designing-uniform-content/01-designing-structured-content-intro.markdown

https://issues.liferay.com/browse/LRDOCS-7052
This is merged and published.

LRDOCS-7052 7.2: fix appdev links

---

developer/frameworks/articles/user-associated-data/01-managing-uad-intro.markdown

Based ona a comment from @dejuknow that I missed during normal SME review.

minor edit to UAD Framework intro

---

develop/new-articles/12-recycle-bin/01-recycling-entities/01-moving-entries-to-the-recycle-bin.markdown
develop/reference/articles/06-themes/02-theme-components-and-workflow.markdown
develop/tutorials/articles/01-introduction-to-liferay-development/01-fundamentals.markdown
develop/tutorials/articles/01-introduction-to-liferay-development/02-liferay-as-a-development-platform.markdown
develop/tutorials/articles/100-tooling/05-maven/06-deploying-liferay-maven-artifacts-to-a-repository.markdown
develop/tutorials/articles/110-portlets/05-jsf-portlets-with-liferay-faces/03-generating-a-jsf-project-manually/00-intro.markdown
develop/tutorials/articles/110-portlets/05-jsf-portlets-with-liferay-faces/03-generating-a-jsf-project-manually/05-developing-a-jsf-applications-behavior-and-ui.markdown
develop/tutorials/articles/140-application-security/04-authentication-pipelines/02-authentication-pipelines.markdown
develop/tutorials/articles/140-application-security/04-authentication-pipelines/03-custom-login-portlet.markdown
develop/tutorials/articles/160-search/03-indexers.markdown
develop/tutorials/articles/180-themes-and-layout-templates/01-themes/02-developing-themes/16-packaging-independent-ui-resources-for-your-site.markdown
develop/tutorials/articles/210-front-end-taglibs/02-liferay-frontend-taglibs/02-liferay-frontend-cards.markdown
develop/tutorials/articles/210-front-end-taglibs/02-liferay-util-taglibs/03-liferay-util-buffer.markdown
develop/tutorials/articles/210-front-end-taglibs/02-liferay-util-taglibs/05-liferay-util-get-url.markdown
develop/tutorials/articles/250-collaboration/02-documents-media-api/01-getting-started-dm-api.markdown
develop/tutorials/articles/270-forms/01-form-field-types/00-intro.markdown
develop/tutorials/articles/280-workflow/01-creating-workflow-definitions/00-creating-workflow-definitions-intro.markdown
develop/tutorials/articles/380-troubleshooting/17-troubleshooting-front-end-dev.markdown
discover/deployment/articles/04-securing-liferay/01-liferay-security-intro.markdown

https://issues.liferay.com/browse/LRDOCS-7038
Affects:
develop > Reference
develop > tutorials
deployment

LRDOCS-7038 7.1: update 7.1 links

---

develop/new-articles/12-recycle-bin/01-recycling-entities/01-moving-entries-to-the-recycle-bin.markdown
develop/reference/articles/06-themes/02-theme-components-and-workflow.markdown
develop/tutorials/articles/01-introduction-to-liferay-development/01-fundamentals.markdown
develop/tutorials/articles/01-introduction-to-liferay-development/02-liferay-as-a-development-platform.markdown
develop/tutorials/articles/100-tooling/05-maven/06-deploying-liferay-maven-artifacts-to-a-repository.markdown
develop/tutorials/articles/110-portlets/05-jsf-portlets-with-liferay-faces/03-generating-a-jsf-project-manually/00-intro.markdown
develop/tutorials/articles/110-portlets/05-jsf-portlets-with-liferay-faces/03-generating-a-jsf-project-manually/05-developing-a-jsf-applications-behavior-and-ui.markdown
develop/tutorials/articles/140-application-security/04-authentication-pipelines/02-authentication-pipelines.markdown
develop/tutorials/articles/140-application-security/04-authentication-pipelines/03-custom-login-portlet.markdown
develop/tutorials/articles/160-search/03-indexers.markdown
develop/tutorials/articles/180-themes-and-layout-templates/01-themes/02-developing-themes/16-packaging-independent-ui-resources-for-your-site.markdown
develop/tutorials/articles/200-integrating-with-front-end-frameworks/01-integrating-with-react.markdown
develop/tutorials/articles/200-integrating-with-front-end-frameworks/02-integrating-with-vue-js.markdown
develop/tutorials/articles/200-integrating-with-front-end-frameworks/03-integrating-with-angular-js.markdown
develop/tutorials/articles/210-front-end-taglibs/02-liferay-frontend-taglibs/02-liferay-frontend-cards.markdown
develop/tutorials/articles/210-front-end-taglibs/02-liferay-util-taglibs/03-liferay-util-buffer.markdown
develop/tutorials/articles/210-front-end-taglibs/02-liferay-util-taglibs/05-liferay-util-get-url.markdown
develop/tutorials/articles/250-collaboration/02-documents-media-api/01-getting-started-dm-api.markdown
develop/tutorials/articles/270-forms/01-form-field-types/00-intro.markdown
develop/tutorials/articles/280-workflow/01-creating-workflow-definitions/00-creating-workflow-definitions-intro.markdown
develop/tutorials/articles/380-troubleshooting/17-troubleshooting-front-end-dev.markdown
discover/deployment/articles/04-securing-liferay/01-liferay-security-intro.markdown

This includes LRDOCS-7044 as well
cc @jhinkey

LRDOCS-7043 fixes

---

develop/new-articles/12-recycle-bin/01-recycling-entities/01-moving-entries-to-the-recycle-bin.markdown
develop/reference/articles/06-themes/02-theme-components-and-workflow.markdown
develop/tutorials/articles/01-introduction-to-liferay-development/01-fundamentals.markdown
develop/tutorials/articles/01-introduction-to-liferay-development/02-liferay-as-a-development-platform.markdown
develop/tutorials/articles/100-tooling/05-maven/06-deploying-liferay-maven-artifacts-to-a-repository.markdown
develop/tutorials/articles/110-portlets/05-jsf-portlets-with-liferay-faces/03-generating-a-jsf-project-manually/00-intro.markdown
develop/tutorials/articles/110-portlets/05-jsf-portlets-with-liferay-faces/03-generating-a-jsf-project-manually/05-developing-a-jsf-applications-behavior-and-ui.markdown
develop/tutorials/articles/140-application-security/01-application-permissions/02-defining-permissions.markdown
develop/tutorials/articles/140-application-security/04-authentication-pipelines/02-authentication-pipelines.markdown
develop/tutorials/articles/140-application-security/04-authentication-pipelines/03-custom-login-portlet.markdown
develop/tutorials/articles/160-search/03-indexers.markdown
develop/tutorials/articles/180-themes-and-layout-templates/01-themes/02-developing-themes/16-packaging-independent-ui-resources-for-your-site.markdown
develop/tutorials/articles/200-integrating-with-front-end-frameworks/01-integrating-with-react.markdown
develop/tutorials/articles/200-integrating-with-front-end-frameworks/02-integrating-with-vue-js.markdown
develop/tutorials/articles/200-integrating-with-front-end-frameworks/03-integrating-with-angular-js.markdown
develop/tutorials/articles/210-front-end-taglibs/02-liferay-frontend-taglibs/02-liferay-frontend-cards.markdown
develop/tutorials/articles/210-front-end-taglibs/02-liferay-util-taglibs/03-liferay-util-buffer.markdown
develop/tutorials/articles/210-front-end-taglibs/02-liferay-util-taglibs/05-liferay-util-get-url.markdown
develop/tutorials/articles/250-collaboration/02-documents-media-api/01-getting-started-dm-api.markdown
develop/tutorials/articles/270-forms/01-form-field-types/00-intro.markdown
develop/tutorials/articles/280-workflow/01-creating-workflow-definitions/00-creating-workflow-definitions-intro.markdown
develop/tutorials/articles/380-troubleshooting/17-troubleshooting-front-end-dev.markdown
discover/deployment/articles/04-securing-liferay/01-liferay-security-intro.markdown

https://issues.liferay.com/browse/LRDOCS-6627 7.1.x
To start, here's Jesse's changes to "Clarify when default permissions are added to the database"
Jesse stated, "This bit of information (and anything else worth documenting from https://issues.liferay.com/browse/LPP-33437 or https://issues.liferay.com/browse/PTR-802) should also go into 7.0.x, 7.2.x, and master.
(I couldn't find the article corresponding to develop/tutorials/articles/140-application-security/01-application-permissions/02-defining-permissions.markdown in 7.2.x)"

LRDOCS-6627 7.1: Clarify when default permissions are added to the database

---

develop/tutorials/articles/01-introduction/00-intro.markdown
develop/tutorials/articles/04-themes/01-setting-up-the-theme/00-intro.markdown
develop/tutorials/articles/05-mobile/01-beginning-android-portal-development/01-setting-up-the-guestbook-portlet.markdown
develop/tutorials/articles/117-user-interfaces-with-the-liferayui-taglib/05-creating-a-navigation-menu-with-the-liferay-ui-icon-list-tag.markdown
develop/tutorials/articles/128-customizing-liferay-portal-with-hooks/99-advanced-customization-with-ext-plugins.markdown
develop/tutorials/articles/130-importing-resources/00-intro.markdown
develop/tutorials/articles/130-importing-resources/02-creating-plugins-to-share-structures-templates-and-more.markdown
develop/tutorials/articles/130-importing-resources/03-importing-resources-with-your-themes.markdown
discover/deployment/articles/01-installation-and-setup/00-installation-and-setup-intro.markdown
discover/portal/articles/01-what-is-liferay/00-what-is-liferay-intro.markdown

https://issues.liferay.com/browse/LRDOCS-7038
Affects: 6.2 > developer > tutorials

LRDOCS-7038 6.2: replace ldn and dm refs

---

develop/new-articles/12-recycle-bin/01-recycling-entities/01-moving-entries-to-the-recycle-bin.markdown
develop/tutorials/articles/01-introduction-to-liferay-development/01-fundamentals.markdown
develop/tutorials/articles/01-introduction-to-liferay-development/02-liferay-as-a-development-platform.markdown
develop/tutorials/articles/02-from-liferay-6-to-liferay-7/07-upgrading-plugins-to-liferay-7/06-upgrading-themes/02-upgrading-themes.markdown
develop/tutorials/articles/02-from-liferay-6-to-liferay-7/09-customization-with-ext-plugins/09-customization-with-ext-plugins-intro.markdown
develop/tutorials/articles/04-developing-an-android-app/01-beginning-android-portal-development/01-setting-up-the-guestbook-portlet.markdown
develop/tutorials/articles/05-developing-an-ios-app/01-beginning-ios-portal-development/01-setting-up-the-guestbook-portlet.markdown
develop/tutorials/articles/100-tooling/05-maven/06-deploying-liferay-maven-artifacts-to-a-repository.markdown
develop/tutorials/articles/110-portlets/04-jsf/03-creating-a-jsf-project-manually.markdown
develop/tutorials/articles/125-data-access/02-data-scopes.markdown
develop/tutorials/articles/195-forms/01-form-field-types/00-intro.markdown
develop/tutorials/articles/210-application-security/04-authentication-pipelines/02-authentication-pipelines.markdown
develop/tutorials/articles/210-application-security/04-authentication-pipelines/03-custom-login-portlet.markdown
develop/tutorials/articles/250-forms/03-form-navigator-extensions.markdown
develop/tutorials/articles/260-themes-and-layout-templates/01-themes/03-importing-resources-with-a-theme.markdown
develop/tutorials/articles/260-themes-and-layout-templates/01-themes/05-theme-contributors.markdown
develop/tutorials/articles/300-osgi-basics/04-overriding-service-references.markdown
discover/deployment/articles-dxp/03-configuring-liferay/03-liferay-clustering.markdown
discover/deployment/articles-dxp/08-liferay-enterprise-search/08-xpack-security.markdown
discover/deployment/articles-dxp/08-liferay-enterprise-search/09-xpack-monitoring.markdown
discover/deployment/articles/03-configuring-liferay/03-liferay-clustering.markdown
discover/deployment/articles/03-configuring-liferay/07-securing-liferay/00-intro.markdown
discover/deployment/articles/03-configuring-liferay/07-securing-liferay/01-liferay-security-overview.markdown
discover/portal/articles/02-content-sites/01-creating-basic-web-content/00-creating-basic-web-content-intro.markdown
discover/portal/articles/100-web-experience-management/02-creating-web-content/01-publishing-basic-web-content.markdown
discover/portal/articles/110-collaboration/00-collaboration-intro.markdown
discover/portal/articles/110-collaboration/02-collaborating/01-publishing-blogs.markdown
discover/portal/articles/110-collaboration/02-collaborating/03-mentioning-users.markdown
discover/portal/articles/110-collaboration/02-collaborating/04-working-together-with-the-wiki.markdown

LRDOCS-7088, fix LES download links for 7.0

---

develop/new-articles/12-recycle-bin/01-recycling-entities/01-moving-entries-to-the-recycle-bin.markdown
develop/reference/articles/06-themes/02-theme-components-and-workflow.markdown
develop/tutorials/articles/01-introduction-to-liferay-development/01-fundamentals.markdown
develop/tutorials/articles/01-introduction-to-liferay-development/02-liferay-as-a-development-platform.markdown
develop/tutorials/articles/02-from-liferay-6-to-liferay-7/07-upgrading-plugins-to-liferay-7/03-upgrading-the-liferay-maven-build.markdown
develop/tutorials/articles/100-tooling/05-maven/06-deploying-liferay-maven-artifacts-to-a-repository.markdown
develop/tutorials/articles/110-portlets/05-jsf-portlets-with-liferay-faces/03-generating-a-jsf-project-manually/00-intro.markdown
develop/tutorials/articles/110-portlets/05-jsf-portlets-with-liferay-faces/03-generating-a-jsf-project-manually/05-developing-a-jsf-applications-behavior-and-ui.markdown
develop/tutorials/articles/140-application-security/01-application-permissions/02-defining-permissions.markdown
develop/tutorials/articles/140-application-security/04-authentication-pipelines/02-authentication-pipelines.markdown
develop/tutorials/articles/140-application-security/04-authentication-pipelines/03-custom-login-portlet.markdown
develop/tutorials/articles/160-search/03-indexers.markdown
develop/tutorials/articles/180-themes-and-layout-templates/01-themes/02-developing-themes/16-packaging-independent-ui-resources-for-your-site.markdown
develop/tutorials/articles/200-integrating-with-front-end-frameworks/01-integrating-with-react.markdown
develop/tutorials/articles/200-integrating-with-front-end-frameworks/02-integrating-with-vue-js.markdown
develop/tutorials/articles/200-integrating-with-front-end-frameworks/03-integrating-with-angular-js.markdown
develop/tutorials/articles/210-front-end-taglibs/02-liferay-frontend-taglibs/02-liferay-frontend-cards.markdown
develop/tutorials/articles/210-front-end-taglibs/02-liferay-util-taglibs/03-liferay-util-buffer.markdown
develop/tutorials/articles/210-front-end-taglibs/02-liferay-util-taglibs/05-liferay-util-get-url.markdown
develop/tutorials/articles/250-collaboration/02-documents-media-api/01-getting-started-dm-api.markdown
develop/tutorials/articles/270-forms/01-form-field-types/00-intro.markdown
develop/tutorials/articles/280-workflow/01-creating-workflow-definitions/00-creating-workflow-definitions-intro.markdown
develop/tutorials/articles/380-troubleshooting/17-troubleshooting-front-end-dev.markdown
discover/deployment/articles/04-securing-liferay/01-liferay-security-intro.markdown

https://issues.liferay.com/browse/LRDOCS-6437

LRDOCS-6437 Fix Maven link | 7.1.x

---

develop/new-articles/12-recycle-bin/01-recycling-entities/01-moving-entries-to-the-recycle-bin.markdown
develop/reference/articles/06-themes/02-theme-components-and-workflow.markdown
develop/tutorials/articles/01-introduction-to-liferay-development/01-fundamentals.markdown
develop/tutorials/articles/01-introduction-to-liferay-development/02-liferay-as-a-development-platform.markdown
develop/tutorials/articles/100-tooling/05-maven/06-deploying-liferay-maven-artifacts-to-a-repository.markdown
develop/tutorials/articles/110-portlets/05-jsf-portlets-with-liferay-faces/03-generating-a-jsf-project-manually/00-intro.markdown
develop/tutorials/articles/110-portlets/05-jsf-portlets-with-liferay-faces/03-generating-a-jsf-project-manually/05-developing-a-jsf-applications-behavior-and-ui.markdown
develop/tutorials/articles/140-application-security/01-application-permissions/02-defining-permissions.markdown
develop/tutorials/articles/140-application-security/04-authentication-pipelines/02-authentication-pipelines.markdown
develop/tutorials/articles/140-application-security/04-authentication-pipelines/03-custom-login-portlet.markdown
develop/tutorials/articles/160-search/03-indexers.markdown
develop/tutorials/articles/180-themes-and-layout-templates/01-themes/02-developing-themes/16-packaging-independent-ui-resources-for-your-site.markdown
develop/tutorials/articles/200-integrating-with-front-end-frameworks/01-integrating-with-react.markdown
develop/tutorials/articles/200-integrating-with-front-end-frameworks/02-integrating-with-vue-js.markdown
develop/tutorials/articles/200-integrating-with-front-end-frameworks/03-integrating-with-angular-js.markdown
develop/tutorials/articles/210-front-end-taglibs/02-liferay-frontend-taglibs/02-liferay-frontend-cards.markdown
develop/tutorials/articles/210-front-end-taglibs/02-liferay-util-taglibs/03-liferay-util-buffer.markdown
develop/tutorials/articles/210-front-end-taglibs/02-liferay-util-taglibs/05-liferay-util-get-url.markdown
develop/tutorials/articles/250-collaboration/02-documents-media-api/01-getting-started-dm-api.markdown
develop/tutorials/articles/270-forms/01-form-field-types/00-intro.markdown
develop/tutorials/articles/280-workflow/01-creating-workflow-definitions/00-creating-workflow-definitions-intro.markdown
develop/tutorials/articles/380-troubleshooting/17-troubleshooting-front-end-dev.markdown
discover/deployment/articles/04-securing-liferay/01-liferay-security-intro.markdown
discover/portal/articles/100-web-experience-management/07-staging-content-for-publication/03-using-the-staging-environment/02-advanced-publication-with-staging.markdown

https://issues.liferay.com/browse/LRDOCS-6424

LRDOCS-6424 Theme Settings Staging | 7.1.x

---

developer/reference/articles/back-end/02-third-party-packages-portal-exports.markdown

LRDOCS-6210 port third party packages portal exports reference

---

discover/portal/articles/140-workflow/00-intro.markdown
discover/portal/articles/140-workflow/03-managing-workflows.markdown

https://issues.liferay.com/browse/LRDOCS-6273, went in with fp-12

LRDOCS-6273, the longheld bag of waiting workflow permissions thing

---

deployment/articles/01-deploying-liferay/03-preparing-for-install.markdown

https://issues.liferay.com/browse/LRDOCS-7041

LRDOCS-7041 7.2: Remove mention of Sybase

---

discover/deployment/articles/03-configuring-liferay/02-document-repository-configuration/04-using-cmis-store.markdown
discover/deployment/articles/06-upgrading-to-liferay-7-1/99-deprecated-apps/00-deprecated-apps-intro.markdown

Note the deprecations in the doc repo config and deprecated apps articles.
https://issues.liferay.com/browse/LRDOCS-6905 CMIS
https://issues.liferay.com/browse/LRDOCS-6853 JCR

LRDOCS-6905 LRDOCS-6853 7.1: note CMIS and JCR store deprecations

---

deployment/articles-dxp/08-lcs/03-lcs-preconfiguration.markdown

Update to LCS preconfiguration for 7.2

LRDOCS-7056 LCS 7.2

---

discover/deployment/articles-dxp/08-lcs/02-lcs-preconfiguration.markdown

Update to LCS preconfiguration for 7.1

LRDOCS-7056 LCS 7.1

---

discover/deployment/articles-dxp/09-liferay-connected-services/02-lcs-preconfiguration.markdown

Update to LCS preconfiguration for 7.0

LRDOCS-7056 LCS 7.0

---

developer/appdev/articles/02-web-front-ends/06-jsf-portlet/01-jsf-portlet-intro.markdown
developer/appdev/articles/02-web-front-ends/06-jsf-portlet/02-developing-a-jsf-portlet-application.markdown

https://issues.liferay.com/browse/LRDOCS-7121

LRDOCS-7121 Add content to JSF article that was reorganized from 7.1

---

developer/frameworks/articles/front-end-development/07-javascript-module-loaders/04-loading-modules-with-aui-script-tag/05-loading-bundled-npm-modules-in-your-portlets.markdown

LRDOCS-6018 Loading bundled npm modules in your portlets

---

discover/portal/articles/100-web-experience-management/02-building-a-site/01-site-management/01-understanding-site-management.markdown

https://issues.liferay.com/browse/LRDOCS-7001

LRDOCS-7001 Site Management Updates | 7.1.x

---

user/articles/100-web-experience-management/03-building-a-site/01-site-management/02-understanding-site-management.markdown

https://issues.liferay.com/browse/LRDOCS-7001

LRDOCS-7001 Site Management Updates

---

develop/reference/articles/12-project-templates/08-fragment-template.markdown

https://issues.liferay.com/browse/LRDOCS-7126

LRDOCS-7126 Fix Fragment Links | 7.0.x

---

develop/reference/articles/09-project-templates/fragment-template.markdown

https://issues.liferay.com/browse/LRDOCS-7126

LRDOCS-7126 Fix Fragment Links | 7.1.x

---

developer/reference/articles/02-project-templates/fragment-template.markdown

https://issues.liferay.com/browse/LRDOCS-7126

LRDOCS-7126 Fix Fragment Links

---

user/articles/100-web-experience-management/03-building-a-site/03-adding-pages-to-sites/03-content-pages/02-content-page-interface.markdown
user/articles/100-web-experience-management/03-building-a-site/03-adding-pages-to-sites/03-content-pages/04-content-page-propagation.markdown
user/articles/100-web-experience-management/04-managing-content/02-web-content/04-display-pages-for-web-content/02-creating-display-pages.markdown
user/articles/100-web-experience-management/04-managing-content/02-web-content/04-display-pages-for-web-content/03-display-page-template-example.markdown

https://issues.liferay.com/browse/LRDOCS-6926

LRDOCS-6926 New edit button for content/display page templates

---

user/articles/05-setting-up/03-script-console/03-leveraging-the-script-engine-in-workflow.markdown

just something i notced while looking at the published docs. example makes it seem like you could use something other than groovy

random workflow scripting fix

---

user/articles/100-web-experience-management/03-building-a-site/05-building-sites-with-templates/04-propagating-changes-from-site-templates.markdown

https://issues.liferay.com/browse/LRDOCS-6927

LRDOCS-6927 Propagation restraints for fragment-based pages

---

discover/portal/articles/100-web-experience-management/02-building-a-site/04-building-sites-with-templates/03-propagating-changes-from-site-templates.markdown

https://issues.liferay.com/browse/LRDOCS-6488

LRDOCS-6488 Propagation restraints for fragment-based pages | 7.1.x

---

develop/tutorials/articles/01-introduction-to-liferay-development/04-configuring-dependencies.markdown
develop/tutorials/articles/110-portlets/04-spring-mvc/02-deploying-a-spring-mvc-portlet.markdown
develop/tutorials/articles/360-osgi-basics-for-liferay-development/03-importing-packages.markdown
develop/tutorials/articles/360-osgi-basics-for-liferay-development/04-exporting-packages.markdown
develop/tutorials/articles/360-osgi-basics-for-liferay-development/05-resolving-third-party-package-dependencies.markdown

https://issues.liferay.com/browse/LRDOCS-7106

LRDOCS-7106 7.1 notes on including JARs

---

developer/appdev/articles/02-web-front-ends/07-spring-portlet-mvc/02-developing-a-portlet-using-portletmvc4spring.markdown
developer/customization/articles/02-fundamentals/02-configuring-dependencies/03-specifying-dependencies.markdown
developer/customization/articles/02-fundamentals/02-configuring-dependencies/04-resolving-third-party-library-package-dependencies.markdown
developer/customization/articles/02-fundamentals/04-importing-packages.markdown
developer/customization/articles/02-fundamentals/05-exporting-packages.markdown

https://issues.liferay.com/browse/LRDOCS-7106

LRDOCS-7106 7.2 notes on including JARs

---

deployment/articles-dxp/03-installing-a-search-engine/03-enterprise-search/01-security/01-security-intro.markdown

https://issues.liferay.com/browse/LRDOCS-7104

Config setting capitalization fix | LRDOCS-7104 | 7.2

---

discover/deployment/articles-dxp/02-installing-search-engine/02-enterprise-search/01-security/00-security-intro.markdown
discover/deployment/articles-dxp/02-installing-search-engine/02-enterprise-search/03-xpack-6.1/02-xpack-security-6_1.markdown

https://issues.liferay.com/browse/LRDOCS-7104

Config setting capitalization fix | LRDOCS-7104 | 7.1

---

discover/deployment/articles-dxp/08-liferay-enterprise-search/08-xpack-security.markdown
discover/deployment/articles-dxp/08-liferay-enterprise-search/10-xpack-elasticsearch-6.1/00-xpack-security-61-intro.markdown

https://issues.liferay.com/browse/LRDOCS-7104

Config setting capitalization fix | LRDOCS-7104 | 7.0

---

developer/frameworks/articles/segmentation-and-personalization/03-request-context-contributor.markdown
developer/frameworks/articles/segmentation-and-personalization/04-segment-criteria-contributors.markdown

https://issues.liferay.com/browse/LRDOCS-7177

7.2 Developer | Clean up misuse of the term Constructor| LRDOCS-7177

---

developer/frameworks/articles/web-experience-management/02-developing-fragments/03-page-fragments-desktop-tools.markdown

https://issues.liferay.com/browse/LRDOCS-7137

LRDOCS-7137 Fragments Toolkit preview command updates

---

user/articles-dxp/140-workflow/05-workflow-metrics-sla.markdown
user/articles-dxp/140-workflow/06-workflow-metrics-reports.markdown

https://issues.liferay.com/browse/LRDOCS-7153, cc @inacionery

7.2 User | Workflow Metrics Requires Elasticsearch | LRDOCS-7153

---

deployment/articles/02-configuring-liferay/04-liferay-portal-clustering/05-enabling-cluster-link.markdown

https://issues.liferay.com/browse/LRDOCS-7233

LRDOCS-7233 7.2 Update clustering docs for using JGroups 4.1

---

develop/tutorials/articles/09-maven/08-liferay-plugin-types-to-develop-with-maven.markdown
develop/tutorials/articles/11-apis/08-using-message-bus.markdown

https://issues.liferay.com/browse/LRDOCS-7239

LRDOCS-7239 Fix broken links that have old folder structure | 6.1.x

---

develop/tutorials/articles/126-themes-and-layout-templates/01-creating-a-theme-project-in-the-plugins-sdk.markdown
develop/tutorials/articles/126-themes-and-layout-templates/10-creating-a-layout-template-project-in-the-plugins-sdk.markdown
develop/tutorials/articles/128-customizing-liferay-portal-with-hooks/11-supporting-right-to-left-languages-in-plugins.markdown
distribute/publish/articles/00-publishing-your-app/01-planning-your-apps-distribution.markdown
distribute/publish/articles/00-publishing-your-app/02-preparing-your-app.markdown
distribute/publish/articles/00-publishing-your-app/04-understanding-the-app-review-process.markdown
distribute/publish/articles/00-publishing-your-app/05-managing-your-app.markdown

https://issues.liferay.com/browse/LRDOCS-7239

LRDOCS-7239 Fix broken links that have old folder structure | 6.2.x

---

user/articles/130-forms/01-forms-intro.markdown

https://issues.liferay.com/browse/LRDOCS-7204

7.2 | Fix Link to Kaleo Forms | LRDOCS-7204

---

discover/portal/articles/130-forms/00-intro.markdown

https://issues.liferay.com/browse/LRDOCS-7204

7.1 | Fix Link to Kaleo Forms | LRDOCS-7204

---

discover/portal/articles/120-forms/00-intro.markdown

https://issues.liferay.com/browse/LRDOCS-7204

7.0 | Fix Link to Kaleo Forms | LRDOCS-7204

---

deployment/articles/02-configuring-liferay/03-locales-and-encoding.markdown

https://issues.liferay.com/browse/LRDOCS-5904, cc @mwilliams2014

LRDOCS-5904 via Mike

---

discover/deployment/articles/03-configuring-liferay/01-locales-and-encoding-configuration/00-locales-and-encoding-configuration-intro.markdown

https://issues.liferay.com/browse/LRDOCS-5904, cc @mwilliams2014

LRDOCS-5904 (for 7.1.x) via Mike

---

user/articles/05-setting-up/03-script-console/03-leveraging-the-script-engine-in-workflow.markdown

https://issues.liferay.com/browse/LRDOCS-6963, cc @inacionery @rafaprax

7.2 User/Scripting | Injected Workflow Script Variables | LRDOCS-6963

---

developer/reference/articles/02-tooling/liferay-workspace/10-managing-the-target-platform/01-intro.markdown
developer/reference/articles/02-tooling/liferay-workspace/10-managing-the-target-platform/02-setting-the-target-platform.markdown

https://issues.liferay.com/browse/LRDOCS-7183

LRDOCS-7183 Target Platform clarifications

---

develop/tutorials/articles/100-tooling/04-liferay-workspace/08-leveraging-docker-in-liferay-workspace.markdown

https://issues.liferay.com/browse/LRDOCS-7228

LRDOCS-7228 Docker configs update | 7.1.x

---

developer/reference/articles/02-tooling/liferay-workspace/12-leveraging-docker/01-intro.markdown
developer/reference/articles/02-tooling/liferay-workspace/12-leveraging-docker/03-configuring-a-docker-container.markdown

https://issues.liferay.com/browse/LRDOCS-7228

LRDOCS-7228 Docker configs update

---

discover/deployment/articles/08-liferay-enterprise-search/02-configuring-elasticsearch.markdown

Just a basic link fix to external docs.

Fix Link to ES 2.4 docs

---

user/articles-dxp/160-segmentation-and-personalization/05-analaytics-cloud-segmentation.markdown

https://issues.liferay.com/browse/LRDOCS-7245

LRDOCS-7245 Segment Synchronization requires membership

---

developer/frameworks/articles/web-experience-management/01-web-experience-management-intro.markdown

https://issues.liferay.com/browse/LRDOCS-7176

LRDOCS-7176 Add WEM Frameworks intro text

---

user/articles/100-web-experience-management/03-building-a-site/06-configuring-sites/04-advanced-site-settings.markdown

https://issues.liferay.com/browse/LRDOCS-7166

LRDOCS-7166 Add Content Sharing global configuration details

---

develop/tutorials/articles/290-configuration/01-making-apps-configurable/05-reading-configurations-configuration-provider.markdown
discover/deployment/articles-dxp/02-installing-search-engine/02-enterprise-search/02-monitoring/00-monitoring-intro.markdown
discover/deployment/articles-dxp/02-installing-search-engine/02-enterprise-search/03-xpack-6.1/03-xpack-monitoring-6_1.markdown
discover/portal/articles/120-search/02-configuring-a-search-page.markdown
discover/portal/articles/210-setting-up/03-script-console/04-script-examples.markdown

https://issues.liferay.com/browse/LRDOCS-7256

7.1 | Fixing Links | LRDOCS-7256

---

discover/deployment/articles-dxp/08-liferay-enterprise-search/03-shield.markdown
discover/deployment/articles-dxp/08-liferay-enterprise-search/04-marvel.markdown
discover/deployment/articles/08-liferay-enterprise-search/05-solr.markdown
discover/deployment/articles/100-reference/intro.markdown
discover/deployment/articles/100-reference/shield-settings.markdown

https://issues.liferay.com/browse/LRDOCS-7256

7.0 | Fixing Links | LRDOCS-7256

---

develop/reference/articles/10-gradle/03-baseline-gradle-plugin.markdown
develop/reference/articles/13-sample-projects/01-apps/01-greedy-policy-option-portlet.markdown
develop/reference/articles/13-sample-projects/03-overrides/03-resource-bundle-override.markdown
develop/tutorials/articles-dxp/100-tooling/02-liferay-ide/01-installing-liferay-ide.markdown
develop/tutorials/articles-dxp/450-audience-targeting/02-creating-new-audience-targeting-rule-types.markdown
develop/tutorials/articles-dxp/450-audience-targeting/04-tracking-user-actions-with-audience-targeting.markdown
develop/tutorials/articles-dxp/450-audience-targeting/06-best-practices-for-rules.markdown
develop/tutorials/articles/100-tooling/03-blade-cli/03-creating-a-liferay-workspace-with-blade-cli.markdown
develop/tutorials/articles/100-tooling/04-liferay-workspace/06-validating-modules-against-the-target-platform/02-modifying-the-target-platforms-capabilities.markdown
develop/tutorials/articles/140-assets/05-rendering-an-asset.markdown
develop/tutorials/articles/270-product-navigation/03-extending-the-simulation-menu.markdown
discover/portal/articles-dxp/160-targeting-content-to-your-audience/02-managing-campaigns.markdown
discover/portal/articles-dxp/160-targeting-content-to-your-audience/03-using-the-audience-targeting-applications.markdown
discover/portal/articles-dxp/160-targeting-content-to-your-audience/05-audience-targeting-rules-reference.markdown
discover/portal/articles/100-web-experience-management/02-creating-web-content/02-designing-uniform-content.markdown
discover/portal/articles/100-web-experience-management/06-styling-apps-with-application-display-templates.markdown

https://issues.liferay.com/browse/LRDOCS-7258

LRDOCS-7258 Fix Links | 7.0.x

---

deployment/articles-dxp/06-maintaining-liferay/01-patching-liferay-dxp/02-patching-basics/01-patching-basics-intro.markdown

https://issues.liferay.com/browse/LRDOCS-7259

LRDOCS-7259 7.2: remove mention of service pack frequency

---

discover/deployment/articles-dxp/05-maintaining-liferay/01-patching-liferay-dxp/01-patching-basics/00-patching-basics-intro.markdown

https://issues.liferay.com/browse/LRDOCS-7259

LRDOCS-7259 7.1: service pack frequency varies

---

discover/deployment/articles-dxp/04-maintaining-liferay/01-patching-liferay/01-patching-basics/00-patching-basics-intro.markdown

https://issues.liferay.com/browse/LRDOCS-7259

LRDOCS-7259 7.0: remove mention of service pack scheduling

---

deployment/articles/03-installing-a-search-engine/03-solr/01-installing-solr-intro.markdown

https://issues.liferay.com/browse/LRDOCS-6986

Solr Release Update | CE Requires GA2 for Solr | LRDOCS-6986

---

user/articles/120-search/02-what-new-search/01-whats-new-search-intro.markdown
user/articles/120-search/03-configuring-a-search-page/01-configuring-a-search-page-intro.markdown
user/articles/120-search/04-searching-for-assets/01-searching-for-assets-intro.markdown
user/articles/120-search/07-search-insights/01-search-insights-intro.markdown
user/articles/120-search/08-multilanguage-search/01-multilanguage-search-intro.markdown
user/articles/120-search/09-search-configuration/01-search-configuration-intro.markdown
user/articles/160-segmentation-and-personalization/05-personalization-experience-managment.markdown

image paths

---

developer/frameworks/articles/data-engine/03-data-records.markdown
developer/frameworks/articles/data-engine/04-data-layouts.markdown

https://issues.liferay.com/browse/LRDOCS-7175, cc @marcelabc

Forms, 7.2 Data Engine Framework | DataRecords + DataLayouts | LRDOCS-7175

---

discover/deployment/articles-dxp/08-liferay-enterprise-search/08-xpack-security.markdown
discover/deployment/articles-dxp/08-liferay-enterprise-search/10-xpack-elasticsearch-6.1/00-xpack-security-61-intro.markdown

https://issues.liferay.com/browse/LRDOCS-7261

7.0 Deployment | XPack Clarification | LRDOCS-7261

---

discover/deployment/articles-dxp/02-installing-search-engine/02-enterprise-search/01-security/00-security-intro.markdown
discover/deployment/articles-dxp/02-installing-search-engine/02-enterprise-search/03-xpack-6.1/02-xpack-security-6_1.markdown

https://issues.liferay.com/browse/LRDOCS-7261

7.1 Deployment | XPack Clarification | LRDOCS-7261

---

deployment/articles-dxp/03-installing-a-search-engine/03-enterprise-search/01-security/01-security-intro.markdown

https://issues.liferay.com/browse/LRDOCS-7261

7.2 Deployment | XPack Clarification | LRDOCS-7261

---

develop/reference/articles/200-breaking-changes.markdown

Merged in brianchandotcom/liferay-portal-ee#26134

LRDOCS-7271 liferay-ui Taglib Breaking Change

---

developer/reference/articles/02-breaking-changes.markdown

brianchandotcom/liferay-portal#77170

LPS-90079 New breaking change

---

deployment/articles/05-upgrading-to-liferay-7-2/01-upgrading-to-liferay-7-2-intro.markdown

https://issues.liferay.com/browse/LRDOCS-7283

LRDOCS-7283 7.2: Clarify code upgrade path

---

developer/tutorials/articles/03-upgrading-code-to-liferay-7.2/06-upgrading-service-builder-services/03-converting-a-service-builder-module-from-spring-di-to-osgi-ds.markdown

https://issues.liferay.com/browse/LRDOCS-7170

LRDOCS-7170 Upgrade step for migrating Spring -> OSGi DS

---

deployment/articles-dxp/01-deploying-liferay/07-installing-liferay-portal-on-jboss-eap.markdown
deployment/articles-dxp/01-deploying-liferay/08-installing-liferay-on-weblogic.markdown
deployment/articles-dxp/01-deploying-liferay/09-installing-liferay-on-websphere.markdown
deployment/articles-dxp/01-saml/04-setting-up-service-provider.markdown
deployment/articles-dxp/02-configuring-liferay/08-dxp-configuration-and-tuning/01-intro.markdown
deployment/articles-dxp/06-maintaining-liferay/01-patching-liferay-dxp/03-using-the-patching-tool/03-working-with-patches.markdown
deployment/articles/05-upgrading-to-liferay-7-2/01-upgrading-to-liferay-7-2-intro.markdown

https://issues.liferay.com/browse/LRDOCS-7295

LRDOCS-7295 7.2 fix deployment links

---

develop/tutorials/articles/180-themes-and-layout-templates/01-themes/05-upgrading-7.0-themes-7.1/03-updating-css-code.markdown
develop/tutorials/articles/180-themes-and-layout-templates/01-themes/05-upgrading-7.0-themes-7.1/05-bootstrap-lexicon-compatibility-layer.markdown

LRDOCS-7299 Font icons are in compatibility layer in 7.1

---

develop/tutorials/articles/180-configuration/01-making-apps-configurable.markdown

https://issues.liferay.com/browse/LRDOCS-7298, the Meta.OCD annotation's ID property must be the FQCN of the confiugration class. cc @drewbrokke

USM 7.0 Developer, Configuration | LRDOCS-7298

---

develop/tutorials/articles/290-configuration/01-making-apps-configurable/00-intro.markdown

https://issues.liferay.com/browse/LRDOCS-7298, the Meta.OCD annotation's ID property must be the FQCN of the confiugration class. cc @drewbrokke

USM 7.1 Developer, Configuration | LRDOCS-7298

---

developer/frameworks/articles/data-engine/02-creating-data-definitions.markdown
developer/frameworks/articles/data-engine/03-creating-data-record-collections.markdown
developer/frameworks/articles/data-engine/03-data-records.markdown
developer/frameworks/articles/data-engine/04-data-layouts.markdown

https://issues.liferay.com/browse/LRDOCS-7300

Data Engine 7.2 | Fixing the Titles | LRDOCS-7300

---

develop/reference/articles/200-breaking-changes.markdown

https://issues.liferay.com/browse/LRDOCS-7294

LRDOCS-7294 Use correct JIRA tickets in breaking change

---

develop/tutorials/articles/230-web-experience-management/04-screen-navigation/02-customizing-liferay-apps.markdown

https://issues.liferay.com/browse/LRDOCS-7292

LRDOCS-7292 Typo | 7.1.x

---

developer/frameworks/articles/web-experience-management/04-screen-navigation/03-customizing-liferay-apps.markdown

https://issues.liferay.com/browse/LRDOCS-7292

LRDOCS-7292 Typo

---

build-site-common.xml

https://issues.liferay.com/browse/LRDOCS-6911

LRDOCS-6911 Delete metadata file | 7.0.x

---

build-common.xml

https://issues.liferay.com/browse/LRDOCS-6911

LRDOCS-6911 Delete metadata file | 7.1.x

---

build-common.xml

https://issues.liferay.com/browse/LRDOCS-6911
https://issues.liferay.com/browse/LRDOCS-7317

LRDOCS-7317 Fix GitHub URLs

---

en/deployment/articles-dxp/01-saml/02-setting-up-identity-provider.markdown

Community Fix | Saml 7.2 | Image Path

---

en/deployment/articles/05-upgrading-to-liferay-7-2/01-upgrading-to-liferay-7-2-intro.markdown

https://issues.liferay.com/browse/LRDOCS-7333

LRDOCS-7333 Show complete paths to 7.2

---

discover/deployment/articles/02-installing-liferay/04-installing-liferay-on-tomcat.markdown
discover/deployment/articles/02-installing-liferay/05-installing-liferay-on-wildfly.markdown

https://issues.liferay.com/browse/LRDOCS-6869

LRDOCS-6869 7.0 Deployment: OSGi JAR copies from the OSGI ZIP to the correct location

---

develop/tutorials/articles-dxp/100-tooling/05-maven/01-installing-liferay-maven-artifacts.markdown
develop/tutorials/articles/100-tooling/05-maven/01-installing-liferay-maven-artifacts.markdown
develop/tutorials/articles/100-tooling/08-liferay-upgrade-planner/01-liferay-upgrade-planner-intro.markdown

https://issues.liferay.com/browse/LRDOCS-7348

LRDOCS-7348 Maven artifact Zip no longer provided | 7.0.x

---

en/develop/reference/articles/10-sample-projects/01-apps/npm-samples/00-intro.markdown
en/develop/reference/articles/10-sample-projects/01-apps/service-builder-samples/00-intro.markdown
en/develop/reference/articles/1000-customization-with-ext/01-customizing-core-functionality-with-ext/00-intro.markdown

https://issues.liferay.com/browse/LRDOCS-7359

LRDOCS-7359 Fix links | 7.1.x

---

discover/portal/articles/100-web-experience-management/01-starting-site-development/02-creating-and-managing-pages.markdown

LRDOCS-7362 Page nesting does not determine friendly URL | 7.0.x

---

en/discover/portal/articles/100-web-experience-management/02-building-a-site/02-adding-pages-to-sites/01-creating-pages.markdown

LRDOCS-7362 Page nesting does not determine friendly URL | 7.1.x

---

en/user/articles/100-web-experience-management/03-building-a-site/03-adding-pages-to-sites/02-creating-pages/01-creating-pages-intro.markdown

LRDOCS-7362 Page nesting does not determine friendly URL

---

en/deployment/articles/100-reference/03-portal-properties.markdown
en/deployment/articles/100-reference/05-database-templates.markdown

https://issues.liferay.com/browse/LRDOCS-7360

LRDOCS-7360 7.2 Deployment: update MySQL driver and use GMT timezone in URL

---

en/developer/frameworks/articles/front-end-development/02-themes/05-clay-and-themes/02-customizing-atlas-and-clay-themes.markdown
en/developer/frameworks/articles/front-end-development/02-themes/05-clay-and-themes/04-using-clay-icons-in-your-theme.markdown
en/developer/reference/articles/02-front-end/03-front-end-taglibs/07-clay-taglibs/08-clay-icons.markdown

LRDOCS-7290 Document how to use Clay icons in your theme

---

en/deployment/articles/03-installing-a-search-engine/03-solr/01-installing-solr-intro.markdown

https://issues.liferay.com/browse/LRDOCS-7272, but the ticket is already closed. cc @lipusz

SP-1 Update, Solr connector upgrade needed with SP1/FP2 | LRDOCS-7272

---

en/user/articles-dxp/120-search/13-result-rankings.markdown

SP-1, remove deleted configuration from docs

---

en/user/articles/130-forms/06-data-providers.markdown

https://issues.liferay.com/browse/LRDOCS-7383. cc @natocesarrego

SP1/FP2 Forms Change | Data Providers Local Network Configuration | LRDOCS-7383

---

develop/tutorials/articles/114-workflow/notification-templates.markdown

The published article looks terrible, mostly due to bad table formatting. I think this will fix it (convert script for 6.2.x converts it properly at least). Obviously, no rush.

6.2.x Formatting Fix | Workflow

---

discover/deployment/articles/02-installing-liferay/04-installing-liferay-on-tomcat.markdown

https://issues.liferay.com/browse/LRDOCS-6869

LRDOCS-6869 7.0 Deployment: Remove JAR from checkpoint list

---

en/developer/appdev/articles/03-service-builder/02-creating-a-service-builder-project/02-creating-a-service-builder-project-intro.markdown
en/developer/appdev/articles/03-service-builder/03-creating-o-r-map/03-defining-global-service-info/01-defining-global-service-information-intro.markdown

https://issues.liferay.com/browse/LRDOCS-7367

LRDOCS-7367 7.2 AppDev: Mention how to create SB projects that use the Spring DI

---

develop/tutorials/articles/100-tooling/03-blade-cli/03-creating-a-liferay-workspace-with-blade-cli.markdown

https://issues.liferay.com/browse/LRDOCS-7366

LRDOCS-7366 Update default project version | 7.0.x

---

en/develop/tutorials/articles/100-tooling/03-blade-cli/03-creating-a-liferay-workspace-with-blade-cli.markdown
en/develop/tutorials/articles/100-tooling/03-blade-cli/04-creating-projects-with-blade-cli.markdown

https://issues.liferay.com/browse/LRDOCS-7366

LRDOCS-7366 Update default project version | 7.1.x

---

en/develop/tutorials/articles/02-from-liferay-6-to-liferay-7/07-upgrading-plugins-to-liferay-7/01-intro.markdown
en/develop/tutorials/articles/130-service-builder/02-service-builder-persistence/01-defining-an-object-relational-map-with-service-builder/02-defining-global-service-information.markdown

https://issues.liferay.com/browse/LRDOCS-5449

LRDOCS-5449 7.1 demonstrate databaseNameMaxLength for Service Builder

---

develop/tutorials/articles/02-from-liferay-6-to-liferay-7/07-upgrading-plugins-to-liferay-7/01-intro.markdown
develop/tutorials/articles/120-service-builder/02-service-builder-persistence/01-defining-an-object-relational-map-with-service-builder.markdown

https://issues.liferay.com/browse/LRDOCS-5449

LRDOCS-5449 7.0 demonstrate databaseNameMaxLength for Service Builder

---

en/developer/appdev/articles/03-service-builder/03-creating-o-r-map/03-defining-global-service-info/01-defining-global-service-information-intro.markdown

https://issues.liferay.com/browse/LRDOCS-5449

 LRDOCS-5449 7.2 demonstrate databaseNameMaxLength for Service Builder

---

en/user/articles/130-forms/06-data-providers.markdown

https://issues.liferay.com/browse/LRDOCS-3517 and https://issues.liferay.com/browse/LRDOCS-6918, data provider doc improvements for 7.2. Thanks for the information, @natocesarrego!

Forms 7.2 User Guide | Data Provider Improvements | LRDOCS-3517, LRDOCS-6918

---

en/discover/portal/articles/130-forms/06-data-providers.markdown

https://issues.liferay.com/browse/LRDOCS-3517 and https://issues.liferay.com/browse/LRDOCS-6918, data provider doc improvements for 7.1. Thanks for the information, @natocesarrego!

Forms 7.1 User Guide | Data Provider Improvements | LRDOCS-3517, LRDOCS-6918

---

en/developer/tutorials/articles/03-upgrading-code-to-liferay-7.2/05-fixing-upgrade-problems/02-resolving-a-projects-dependencies.markdown

Fixed the link to the reference article and replaced content that's already explained in _Configuring Dependencies_.
https://issues.liferay.com/browse/LRDOCS-7364

LRDOCS-7364 7.2 Fix link and replace duplicate content

---

en/developer/reference/articles/02-meaningful-schema-versioning.markdown

Schema versioning is more rigid now.
https://issues.liferay.com/browse/LRDOCS-7376

7.2: LRDOCS-7376 Update the schema version definitions

---

en/developer/frameworks/articles/data-engine/02-creating-data-definitions.markdown

https://issues.liferay.com/browse/LRDOCS-7322, cc @marcelabc @jeyvison

7.2 Data Engine Framework | Doc Bugs | LRDOCS-7322

---

develop/tutorials/articles/110-portlets/20-lexicon/07-using-lexicon-icons-in-your-app.markdown

Changed to new lexiconcss github pages. Community contribution https://github.com/liferay/liferay-docs/pull/543

Broken wedeploy link.

---

en/develop/tutorials/articles/320-wysiwyg-editors/04-alloy-editor/02-creating-new-buttons-for-alloyeditor/00-adding-buttons-to-alloyeditor-intro.markdown

https://github.com/liferay/liferay-docs/pull/538

Community fix 538

---

discover/portal/articles/100-web-experience-management/03-staging-content-for-publication/03-using-the-staging-environment.markdown

https://issues.liferay.com/browse/LRDOCS-7398

LRDOCS-7398 Typo

---

en/user/articles/110-collaboration/02-managing-documents-and-media/06-online-editing-office-365/02-configuring-office365-integration.markdown

Merge and edit of https://github.com/ngaskill/liferay-docs/pull/192
Thanks @cgoncas!

LRDOCS-7391 Office 365

---

discover/portal/articles/100-web-experience-management/01-starting-site-development/02-creating-and-managing-pages.markdown

LRDOCS-7362 Improve page hierarchy info | 7.0.x

---

en/discover/portal/articles/100-web-experience-management/02-building-a-site/02-adding-pages-to-sites/01-creating-pages.markdown

LRDOCS-7362 Improve page hierarchy info | 7.1.x

---

en/user/articles/100-web-experience-management/03-building-a-site/03-adding-pages-to-sites/02-creating-pages/01-creating-pages-intro.markdown

LRDOCS-7362 Improve page hierarchy info

---

en/user/articles/100-web-experience-management/03-building-a-site/03-adding-pages-to-sites/01-adding-pages-to-sites-intro.markdown

https://issues.liferay.com/browse/LRDOCS-7369

LRDOCS-7369 Content and Widget Page recommendations

---

en/developer/reference/articles/02-tooling/liferay-workspace/01-intro.markdown
en/developer/reference/articles/02-tooling/liferay-workspace/03-creating-a-liferay-workspace.markdown
en/developer/reference/articles/02-tooling/liferay-workspace/06-adding-a-liferay-bundle-to-workspace.markdown

https://issues.liferay.com/browse/LRDOCS-7312
https://issues.liferay.com/browse/LRDOCS-7340
https://issues.liferay.com/browse/LRDOCS-7353

LRDOCS-7312 Workspace Blade Updates

---

en/user/articles/120-search/08-multilanguage-search/01-multilanguage-search-intro.markdown

httpos://issues.liferay.com/browse/LRDOCS-7241, These were actually in GA1, no need to mention them as new SP1 behavior. cc @lipusz

Search User 7.2 | No need to mention SP1 | LRDOCS-7241

---

en/developer/reference/articles/02-front-end/05-liferay-js-apis/06-handling-ajax-requests.markdown

LRDOCS-7380 liferay util fetch

---

en/developer/customization/articles/50-liferay-forms/01-forms-intro.markdown

https://issues.liferay.com/browse/LRDOCS-6969 cc @natocesarrego

Forms 7.2 Customization Intro | LRDOCS-6969

---

en/deployment/articles-dxp/06-maintaining-liferay/01-patching-liferay-dxp/01-patching-liferay-dxp-intro.markdown

https://issues.liferay.com/browse/LRDOCS-7374

7.2 SP1 - LRDOCS-7374 Mention using blue-green technique during upgrade

---

en/deployment/articles/02-configuring-liferay/04-liferay-portal-clustering/05-enabling-cluster-link.markdown

https://issues.liferay.com/browse/LRDOCS-7389
cc/ @tinatian

7.2 SP1 - LRDOCS-7389 singleton_name removed from JGroups; use separate configs

---

en/developer/appdev/articles/01-application-development/01-application-development-intro.markdown
en/developer/appdev/articles/02-web-front-ends/07-spring-portlet-mvc/01-portlet-mvc-for-spring-intro.markdown

https://issues.liferay.com/browse/LRDOCS-7406

LRDOCS-7406 7.2: Fix source code links

---

en/developer/reference/articles/02-front-end/05-liferay-js-apis/02-theme-display.markdown
en/developer/reference/articles/02-front-end/05-liferay-js-apis/03-working-with-urls-in-js.markdown
en/developer/reference/articles/02-front-end/05-liferay-js-apis/04-javascript-utilities.markdown
en/developer/reference/articles/02-front-end/05-liferay-js-apis/07-working-with-addresses.markdown

LRDOCS-7381 Liferay JS Utilities

---

en/developer/frameworks/articles/front-end-development/02-themes/07-managing-theme-resources/03-preparing-and-organizing-web-content/01-preparing-and-organizing-web-content-for-the-importer-intro.markdown
en/user/articles/100-web-experience-management/04-managing-content/02-web-content/02-publishing-basic-web-content/03-using-the-web-content-editor.markdown
en/user/articles/100-web-experience-management/04-managing-content/02-web-content/02-publishing-basic-web-content/04-displaying-web-content.markdown
en/user/articles/100-web-experience-management/04-managing-content/02-web-content/03-designing-uniform-content/02-creating-structured-content/01-creating-structured-web-content-intro.markdown
en/user/articles/100-web-experience-management/04-managing-content/02-web-content/03-designing-uniform-content/02-creating-structured-content/03-configuring-structure-fields.markdown
en/user/articles/100-web-experience-management/04-managing-content/02-web-content/03-designing-uniform-content/02-creating-structured-content/04-structure-settings.markdown
en/user/articles/100-web-experience-management/04-managing-content/02-web-content/03-designing-uniform-content/03-designing-web-content-with-templates/01-designing-web-content-with-templates-intro.markdown
en/user/articles/100-web-experience-management/04-managing-content/02-web-content/04-display-pages-for-web-content/01-display-pages-for-web-content-intro.markdown

LRDOCS-7403 clarify templates are not required for web content

---

en/developer/tutorials/articles/03-upgrading-code-to-liferay-7.2/08-upgrading-themes/02-upgrading-6.2-themes-7.2/07-applying-clay-design-patterns/01-applying-clay-design-patterns-intro.markdown
en/developer/tutorials/articles/03-upgrading-code-to-liferay-7.2/08-upgrading-themes/03-upgrading-7.0-themes-7.2/05-bootstrap-lexicon-compatibility-layer.markdown

LRDOCS-7409 note CSS compatibility layer will be disabled

---

en/deployment/articles/05-upgrading-to-liferay-7-2/03-test-ugrading-a-liferay-backup-copy/02-pruning-the-database.markdown

https://issues.liferay.com/browse/LRDOCS-6610

LRDOCS-6610 7.2 upgrade moves web content images to the document library

---

develop/tutorials/articles/107-service-builder/19-customizing-model-entities-with-model-hints.markdown

https://issues.liferay.com/browse/LRDOCS-7014

LRDOCS-7014 6.2: fix table and syntax highlight XML.

---

en/discover/deployment/articles-dxp/01-deploying-liferay/07-installing-liferay-on-tc-server.markdown
en/discover/deployment/articles-dxp/01-deploying-liferay/08-installing-liferay-on-weblogic.markdown
en/discover/deployment/articles-dxp/01-deploying-liferay/09-installing-liferay-on-websphere.markdown
en/discover/deployment/articles/01-deploying-liferay/04-installing-liferay-portal-on-tomcat.markdown
en/discover/deployment/articles/01-deploying-liferay/05-installing-liferay-portal-on-wildfly.markdown

https://issues.liferay.com/browse/LRDOCS-7423

LRDOCS-7423 7.1 Deployment: update download instructions for DXP/Portal additional files

---

discover/deployment/articles-dxp/07-monitoring-liferay/01-basic-monitoring.markdown

https://issues.liferay.com/browse/LRDOCS-7417

LRDOCS-7417 7.0: mention rotating gc monitoring log files

---

en/discover/deployment/articles-dxp/07-monitoring-liferay/01-monitoring-garbage-collectcion-and-the-jvm.markdown

https://issues.liferay.com/browse/LRDOCS-7417

LRDOCS-7417 7.1: mention rotating gc monitoring log files

---

en/deployment/articles/02-configuring-liferay/04-liferay-portal-clustering/05-enabling-cluster-link.markdown

https://issues.liferay.com/browse/LRDOCS-7432

LRDOCS-7432 7.2: Give direct location to local tcp.xml

---

en/discover/deployment/articles/03-configuring-liferay/03-liferay-portal-clustering/04-enabling-cluster-link.markdown

https://issues.liferay.com/browse/LRDOCS-7432

LRDOCS-7432 7.1: Give direct location of local tcp.xml

---

en/deployment/articles/03-installing-a-search-engine/01-intro.markdown
en/user/articles-dxp/120-search/13-result-rankings.markdown
en/user/articles-dxp/140-workflow/06-workflow-metrics-reports.markdown
en/user/articles/05-setting-up/02-instance-settings/02-configuring-virtual-instance-settings/01-configuring-virtual-instance-settings-intro.markdown
en/user/articles/05-setting-up/03-script-console/03-leveraging-the-script-engine-in-workflow.markdown
en/user/articles/120-search/08-multilanguage-search/01-multilanguage-search-intro.markdown

Fixing some broken links and img refs

---

en/deployment/articles/02-configuring-liferay/02-configuring-mail.markdown

https://issues.liferay.com/browse/LRDOCS-7400

LRDOCS-7400 7.2: Configure default email senders

---

en/developer/appdev/articles/03-service-builder/03-creating-o-r-map/10-understanding-the-code-service-builder-generates/01-understanding-the-code-generated-by-service-builder-intro.markdown

https://issues.liferay.com/browse/LRDOCS-7442

LRDOCS-7442 SB may generate code requiring new dependencies

---

en/developer/tutorials/code/guestbook/04-web-front-end/com-liferay-docs-guestbook/modules/guestbook/guestbook-web/src/main/java/com/liferay/docs/guestbook/portlet/GuestbookPortlet.java
en/developer/tutorials/code/guestbook/04-web-front-end/com-liferay-docs-guestbook/modules/guestbook/guestbook-web/src/main/resources/META-INF/resources/guestbook/view.jsp

Hi Rich,
I resolved a couple compile errors when I built guestbook-web in the 04-web-front-end section. You must've fixed them in the later parts of the lesson. :-)
BTW - I was able to view the guestbook entity and finder cache for the cache configuration articles. 👍

7.2 fix code in guestbook-web in 04-web-front-end

---

en/developer/appdev/articles/99-troubleshooting-application-development-issues/resolving-cnfe-and-cdnfe-in-osgi-bundles.markdown

https://issues.liferay.com/browse/LRDOCS-7433

LRDOCS-7433 7.2: Fix resolving rt.jar package dependency

---

en/develop/tutorials/articles/380-troubleshooting/03-resolving-cnfe-and-cdnfe-in-osgi-bundles.markdown

https://issues.liferay.com/browse/LRDOCS-7433

LRDOCS-7433 7.1: resolve rt.jar package via system bundle

---

develop/tutorials/articles/310-troubleshooting/03-resolving-cnfe-and-cdnfe-in-osgi-bundles.markdown

https://issues.liferay.com/browse/LRDOCS-7433

LRDOCS-7433 7.0: resolve rt.jar package via system bundle

---

en/deployment/articles-dxp/06-maintaining-liferay/01-patching-liferay-dxp/03-using-the-patching-tool/02-installing-patches.markdown
en/deployment/articles-dxp/06-maintaining-liferay/01-patching-liferay-dxp/03-using-the-patching-tool/03-working-with-patches.markdown
en/deployment/articles-dxp/08-lcs/06-lcs-troubleshooting.markdown

https://issues.liferay.com/browse/LRDOCS-7449

LRDOCS-7449 7.2: Change LESA refs to Help Center

---

discover/deployment/articles-dxp/02-installing-liferay/10-trial-plugin-installation.markdown
discover/deployment/articles-dxp/04-maintaining-liferay/01-patching-liferay/02-using-the-patching-tool/00-using-the-patching-tool-intro.markdown
discover/deployment/articles-dxp/09-liferay-connected-services/05-lcs-troubleshooting.markdown

https://issues.liferay.com/browse/LRDOCS-7449

LRDOCS-7449 7.0: Replace LESA refs with Help Center

---

en/discover/deployment/articles-dxp/05-maintaining-liferay/01-patching-liferay-dxp/02-using-the-patching-tool/01-installing-patches.markdown
en/discover/deployment/articles-dxp/05-maintaining-liferay/01-patching-liferay-dxp/02-using-the-patching-tool/02-working-with-patches.markdown
en/discover/deployment/articles-dxp/08-lcs/05-lcs-troubleshooting.markdown

https://issues.liferay.com/browse/LRDOCS-7449

LRDOCS-7449 7.1: Replace LESA refs with Help Center

---

en/develop/tutorials/articles/210-front-end-taglibs/04-clay-taglibs/07-clay-icons.markdown

Supersedes https://github.com/liferay/liferay-docs/pull/552

Pr 552 edit

---

discover/portal/articles/125-workflow/01-enabling-workflow.markdown

https://issues.liferay.com/browse/LRDOCS-7463

Workflow, 7.0 | User isn't configurable at site scope | LRDOCS-7463

---

en/deployment/articles-dxp/03-installing-a-search-engine/03-enterprise-search/03-ltr/01-learning-to-rank-intro.markdown
en/deployment/articles-dxp/03-installing-a-search-engine/03-enterprise-search/03-ltr/02-configuring-learning-to-rank.markdown
en/deployment/articles/03-installing-a-search-engine/02-elasticsearch/01-elasticsearch-intro.markdown
en/deployment/articles/03-installing-a-search-engine/02-elasticsearch/03-installing-elasticsearch.markdown

https://issues.liferay.com/browse/LRDOCS-7450, cc @lipusz

Search 7.2 | Post-release edits | LRDOCS-7450

---

en/developer/frameworks/articles/front-end-development/02-themes/05-clay-and-themes/04-using-clay-icons-in-your-theme.markdown
en/developer/tutorials/articles/04-creating-a-theme/01-creating-a-theme-intro.markdown
en/developer/tutorials/articles/04-creating-a-theme/03-updating-the-header-and-logo.markdown
en/developer/tutorials/articles/04-creating-a-theme/05-defining-the-footer-and-navigation.markdown
en/developer/tutorials/articles/04-creating-a-theme/06-adding-a-color-scheme.markdown

@sez11a please merge as soon as possible. Thx!

LRDOCS-7470 update links and provide Zip file of resources

---

en/develop/tutorials/articles/100-tooling/08-liferay-upgrade-planner/01-liferay-upgrade-planner-intro.markdown
en/discover/deployment/articles/06-upgrading-to-liferay-7-1/00-upgrading-to-liferay-7-1-intro.markdown

https://issues.liferay.com/browse/LRDOCS-7474

LRDOCS-7474 7.1: Fix references to upgrade docs

---

develop/tutorials/articles/100-tooling/08-liferay-upgrade-planner/01-liferay-upgrade-planner-intro.markdown
discover/deployment/articles/06-upgrading-liferay/00-upgrading-liferay-intro.markdown

https://issues.liferay.com/browse/LRDOCS-7474

LRDOCS-7474 7.0: Fix upgrade doc references

---

en/deployment/articles-dxp/06-maintaining-liferay/01-patching-liferay-dxp/02-patching-basics/01-patching-basics-intro.markdown

https://issues.liferay.com/browse/LRDOCS-7411
cc/ @lipusz

LRDOCS-7411 7.2 security fix packs

---

en/discover/deployment/articles-dxp/05-maintaining-liferay/01-patching-liferay-dxp/01-patching-basics/00-patching-basics-intro.markdown

https://issues.liferay.com/browse/LRDOCS-7411

LRDOCS-7411 7.1: Mention DXP Security Fix Packs

---

discover/deployment/articles-dxp/04-maintaining-liferay/01-patching-liferay/01-patching-basics/00-patching-basics-intro.markdown

https://issues.liferay.com/browse/LRDOCS-7411

LRDOCS-7411 7.0: Mention DXP Security Fix Packs

---

en/deployment/articles-dxp/03-installing-a-search-engine/03-enterprise-search/02-monitoring/01-monitoring-intro.markdown
en/deployment/articles/03-installing-a-search-engine/02-elasticsearch/07-security.markdown
en/deployment/articles/03-installing-a-search-engine/02-elasticsearch/11-upgrading-to-elasticsearch-73.markdown

https://issues.liferay.com/browse/LRDOCS-7459, https://issues.liferay.com/browse/LRDOCS-7462, cc @lipusz

Search 7.2, Reorganizing settings and correcting blacklist info | LRDOCS-7459 | LRDOCS-7462

---

en/deployment/articles-dxp/01-deploying-liferay/09-installing-liferay-on-websphere.markdown

LPP-35559 - remove LCS Boot Delegation.

---

discover/deployment/articles-dxp/08-liferay-enterprise-search/03-shield.markdown

https://issues.liferay.com/browse/LRDOCS-7482 firx broken shield links

7.0 Deployment | Fix Shield Links | LRDOCS-7482

---

en/deployment/articles/05-upgrading-to-liferay-7-2/99-apps-in-maintenance-mode.markdown

Note: Reports will be added when it is ready for release.

LRDOCS-7354 Add Liferay Drools to maintenance list

---

develop/tutorials/articles/115-mobile/04-mobile-sdk/03-invoking-liferay-services-in-your-android-app.markdown
develop/tutorials/articles/115-mobile/04-mobile-sdk/08-invoking-liferay-services-in-your-ios-app.markdown
develop/tutorials/articles/115-mobile/04-mobile-sdk/09-invoking-services-asynchronously-from-your-ios-app.markdown
develop/tutorials/articles/115-mobile/04-mobile-sdk/10-sending-your-ios-apps-requests-using-batch-processing.markdown
develop/tutorials/articles/120-service-builder/02-service-builder-persistence/04-understanding-service-context.markdown
develop/tutorials/articles/130-web-services/01-service-builder-web-services/03-service-security-layers.markdown
develop/tutorials/articles/130-web-services/01-service-builder-web-services/06-json-web-services-invoker.markdown
develop/tutorials/articles/130-web-services/01-service-builder-web-services/07-json-web-services-invocation-examples.markdown
develop/tutorials/articles/130-web-services/01-service-builder-web-services/09-soap-web-services.markdown
develop/tutorials/articles/244-liferay-js-api/04-invoking-liferay-services.markdown
discover/deployment/articles-dxp/09-liferay-connected-services/05-lcs-troubleshooting.markdown
discover/deployment/articles/03-configuring-liferay/07-securing-liferay/10-opensso-authentication.markdown
discover/deployment/articles/04-maintaining-liferay/05-securing-liferays-remote-services.markdown
discover/portal/articles-dxp/110-collaboration/01-managing-documents-and-media/05-administering-liferay-sync.markdown
discover/portal/articles-dxp/130-managing-users/07-auditing-users.markdown
discover/portal/articles/100-web-experience-management/02-creating-web-content/02-designing-uniform-content.markdown
discover/portal/articles/110-collaboration/01-managing-documents-and-media/05-administering-liferay-sync.markdown
discover/portal/articles/110-collaboration/02-collaborating/02-creating-forums-with-message-boards.markdown
discover/portal/articles/120-forms/01-forms/02-advanced-forms.markdown
discover/portal/articles/150-setting-up-liferay/02-instance-settings/02-instance-settings.markdown
discover/portal/articles/150-setting-up-liferay/04-scripting/02-running-scripts-from-script-console.markdown

https://issues.liferay.com/browse/LRDOCS-7401

LRDOCS-7401 7.0: Replace references to "test@liferay.com" email

---

en/develop/reference/articles/web-services/01-json-web-services-invocation-examples-intro.markdown
en/develop/tutorials/articles/130-service-builder/02-service-builder-persistence/05-understanding-service-context.markdown
en/develop/tutorials/articles/140-application-security/04-authentication-pipelines/02-authentication-pipelines.markdown
en/develop/tutorials/articles/150-web-services/01-headless-apis/02-discover-api.markdown
en/develop/tutorials/articles/150-web-services/01-headless-apis/03-invoke-service.markdown
en/develop/tutorials/articles/150-web-services/01-headless-apis/04-authenticated-requests.markdown
en/develop/tutorials/articles/150-web-services/01-headless-apis/05-collections/02-getting-collections.markdown
en/develop/tutorials/articles/150-web-services/01-headless-apis/05-collections/03-pagination.markdown
en/develop/tutorials/articles/150-web-services/01-headless-apis/05-collections/04-collection-to-elements.markdown
en/develop/tutorials/articles/150-web-services/01-headless-apis/06-api-formats.markdown
en/develop/tutorials/articles/150-web-services/01-headless-apis/08-filter-and-sort.markdown
en/develop/tutorials/articles/150-web-services/01-headless-apis/09-restrict-properties.markdown
en/develop/tutorials/articles/150-web-services/01-headless-apis/10-multipart.markdown
en/develop/tutorials/articles/150-web-services/02-service-builder-web-services/03-service-security-layers.markdown
en/develop/tutorials/articles/150-web-services/02-service-builder-web-services/06-json-web-services-invoker.markdown
en/develop/tutorials/articles/150-web-services/02-service-builder-web-services/09-soap-web-services.markdown
en/develop/tutorials/articles/185-liferay-js-apis/04-invoking-liferay-services.markdown
en/develop/tutorials/articles/220-mobile/04-mobile-sdk/01-android-mobile-sdk/02-invoking-liferay-services-in-your-android-app.markdown
en/develop/tutorials/articles/220-mobile/04-mobile-sdk/02-ios-mobile-sdk/02-invoking-liferay-services-in-your-ios-app.markdown
en/develop/tutorials/articles/220-mobile/04-mobile-sdk/02-ios-mobile-sdk/03-invoking-services-asynchronously-from-your-ios-app.markdown
en/develop/tutorials/articles/220-mobile/04-mobile-sdk/02-ios-mobile-sdk/04-sending-your-ios-apps-requests-using-batch-processing.markdown
en/develop/tutorials/articles/220-mobile/04-mobile-sdk/02-ios-mobile-sdk/05-oauth-ios.markdown
en/discover/deployment/articles/04-securing-liferay/10-openam-authentication.markdown
en/discover/portal/articles/110-collaboration/02-sync/01-administering-sync/04-sync-security.markdown
en/discover/portal/articles/110-collaboration/04-collaborating/02-message-boards/02-configuring-message-boards.markdown
en/discover/portal/articles/110-collaboration/04-collaborating/02-message-boards/05-mb-subscriptions-lists.markdown
en/discover/portal/articles/130-forms/06-data-providers.markdown
en/discover/portal/articles/130-forms/16-form-notifications.markdown
en/discover/portal/articles/210-setting-up/02-instance-settings/06-email-and-content.markdown
en/discover/portal/articles/210-setting-up/03-script-console/04-script-examples.markdown

https://issues.liferay.com/browse/LRDOCS-7401

LRDOCS-7401 7.1: Replace references to "test@liferay.com" email

---

en/developer/appdev/articles/02-web-front-ends/02-angular-widget/01-developing-an-angular-application-intro.markdown
en/developer/appdev/articles/02-web-front-ends/04-vue-widget/01-developing-a-vue-application-intro.markdown
en/developer/reference/articles/02-tooling/liferay-js-generator/06-adapting-apps-for-liferay.markdown

LRDOCS-7489 document Vue CLI support and wordsmith

---

en/developer/tutorials/articles/03-upgrading-code-to-liferay-7.2/10-upgrading-frameworks-and-features/04-upgrading-service-builder.markdown

https://issues.liferay.com/browse/LRDOCS-7502
cc/ @gamerson

LRDOCS-7502 7.2 Tutorials: Fix Service Builder Upgrade's cross references

---

en/deployment/articles/05-upgrading-to-liferay-7-2/01-upgrading-to-liferay-7-2-intro.markdown

https://issues.liferay.com/browse/LRDOCS-7506

LRDOCS-7506 7.2: Warn about issue upgrading from 71 SP3 to 7.2

---

discover/deployment/articles-dxp/08-liferay-enterprise-search/04-marvel.markdown

https://issues.liferay.com/browse/LRDOCS-5272 courtesy of @lipusz

Search 7.0.x | Fix Link | LRDOCS-5272

---

en/developer/frameworks/articles/configuration/01-configuration-intro.markdown
en/developer/frameworks/articles/web-experience-management/02-page-fragments/06-creating-contributed-fragment-collection.markdown
en/developer/frameworks/articles/web-services/02-headless-apis/04-authenticated-requests.markdown
en/developer/frameworks/articles/web-services/02-headless-apis/08-filter-and-sort.markdown
en/developer/frameworks/articles/web-services/04-graphql/04-authenticated-requests.markdown
en/developer/frameworks/articles/web-services/04-graphql/09-filter-and-sort.markdown
en/developer/frameworks/articles/web-services/05-rest-builder/01-intro.markdown

https://issues.liferay.com/browse/LRDOCS-7410

User & Sys Mgmt 7.2 Dev | Config Framework | Minor Bug | LRDOCS-7410

---

en/deployment/articles/01-deploying-liferay/05-installing-liferay-on-tomcat.markdown

https://issues.liferay.com/browse/LRDOCS-7509

LRDOCS-7509 7.2 Update osgi subfolders

---

en/developer/reference/articles/02-liferay-faces/02-liferay-faces-version-scheme.markdown

Faces Version Scheme updates

---

en/discover/portal/articles-dxp/160-targeting-content-to-your-audience/00-targeting-content-to-your-audience-intro.markdown

Ports note from https://github.com/jrao/liferay-docs/pull/73 to 7.1.x

LRDOCS-4011 add note

---

en/developer/frameworks/articles/front-end-development/02-themes/10-troubleshooting-themes/01-troubleshooting-themes-intro.markdown
en/developer/frameworks/articles/localization/03-localization-settings.markdown

Will port 7.2 info to Liferay Learn for 7.3
7.1 updates sent in https://github.com/sez11a/liferay-docs/pull/4760 
cc @izaera

LRDOCS-7623 document no-flip decoration for RTL languages

---

en/deployment/articles/01-deploying-liferay/05-installing-liferay-on-tomcat.markdown

https://issues.liferay.com/browse/LRDOCS-7700

LRDOCS-7700 master: fix tomcat context

---

en/discover/deployment/articles/01-deploying-liferay/04-installing-liferay-portal-on-tomcat.markdown

https://issues.liferay.com/browse/LRDOCS-7700

LRDOCS-7700 7.1.x: fix tomcat context

---

discover/deployment/articles/02-installing-liferay/04-installing-liferay-on-tomcat.markdown

https://issues.liferay.com/browse/LRDOCS-7700

LRDOCS-7700 7.0.x: fix tomcat context

---

discover/portal/articles/150-setting-up-liferay/06-using-web-services-for-remote-portlets.markdown

https://issues.liferay.com/browse/LRDOCS-7675

LRDOCS-7675 7.0 WSRP and encryption

---

discover/deployment/articles/02-advanced-portal-operation/08-using-web-services-for-remote-portlets.markdown

https://issues.liferay.com/browse/LRDOCS-7675

LRDOCS-7675 6.2 WSRP encryption is not supported

---

en/developer/frameworks/articles/search/03-queries-and-filters/01-queries-and-filters-intro.markdown

https://issues.liferay.com/browse/LRDOCS-7711, deals with some low-hanging fruit of a larger issue brought to the search team's attention via a DXP customer. It would be nice if this moved quickly so we can show good faith to the customer (there's a meeting with them Friday Mar 13). cc @lipusz @joshuacords

Search 7.2 | Queries and Filters | LRDOCS-7711

---

en/discover/deployment/articles/03-configuring-liferay/02-document-repository-configuration/00-document-repository-configuration-intro.markdown
en/discover/deployment/articles/03-configuring-liferay/02-document-repository-configuration/01-using-simple-file-system-store.markdown
en/discover/deployment/articles/03-configuring-liferay/02-document-repository-configuration/02-using-advanced-file-system-store.markdown
en/discover/deployment/articles/03-configuring-liferay/02-document-repository-configuration/03-using-s3-store.markdown
en/discover/deployment/articles/03-configuring-liferay/02-document-repository-configuration/04-using-cmis-store.markdown
en/discover/portal/articles/210-setting-up/01-system-settings/02-config-files/01-creating-config-files.markdown

https://issues.liferay.com/browse/LRDOCS-7664

 LRDOCS-7664 PTR-1535 7.1.x: Applying config files to each node isn't required

---

en/developer/reference/articles-dxp/02-tooling/dev-studio/02-installing-dev-studio.markdown
en/developer/reference/articles/02-tooling/dev-studio/02-installing-dev-studio.markdown

https://issues.liferay.com/browse/LRDOCS-7604

LRDOCS-7604 master: Fix context to Eclipse instead of Dev Studio

---

en/develop/reference/articles/12-page-fragments/02-embedding-widgets.markdown
en/develop/tutorials/articles/210-front-end-taglibs/05-chart-taglibs/04-spline-charts.markdown
en/develop/tutorials/articles/320-wysiwyg-editors/04-alloy-editor/01-adding-buttons-to-the-alloyeditor/00-adding-buttons-to-the-alloy-editor-intro.markdown
en/develop/tutorials/articles/320-wysiwyg-editors/04-alloy-editor/02-creating-new-buttons-for-alloyeditor/02-creating-the-buttons-jsx-file.markdown

@sez11a this includes fixes for LRDOCS-7649 and LRDOCS-7753

LRDOCS-7753 bug fixes

---

en/deployment/articles-dxp/01-deploying-liferay/08-installing-liferay-on-weblogic.markdown

I updated it with the content we're using for 7.x on Liferay Learn. Thanks.

7.2 fix note on SSL with Node Manager

---

en/discover/deployment/articles-dxp/01-deploying-liferay/08-installing-liferay-on-weblogic.markdown

I updated it with the content we're using for 7.x on Liferay Learn. Thanks.

7.1 fix note on using ssl with node manager

---

discover/deployment/articles-dxp/02-installing-liferay/08-installing-liferay-on-weblogic.markdown

I updated it with the content we're using for 7.x on Liferay Learn. Thanks.

7.0 fix note on using ssl with node manager

---

en/discover/deployment/articles-dxp/08-lcs/00-intro.markdown
en/discover/deployment/articles-dxp/08-lcs/01-getting-started.markdown
en/discover/deployment/articles-dxp/08-lcs/02-lcs-preconfiguration.markdown
en/discover/deployment/articles-dxp/08-lcs/03-registration.markdown
en/discover/deployment/articles-dxp/08-lcs/04-using-lcs/00-intro.markdown
en/discover/deployment/articles-dxp/08-lcs/04-using-lcs/01-lcs-property-storage.markdown
en/discover/deployment/articles-dxp/08-lcs/04-using-lcs/02-managing-lcs-users.markdown
en/discover/deployment/articles-dxp/08-lcs/04-using-lcs/03-lcs-dashboard.markdown
en/discover/deployment/articles-dxp/08-lcs/04-using-lcs/04-lcs-environments.markdown
en/discover/deployment/articles-dxp/08-lcs/04-using-lcs/05-lcs-servers.markdown
en/discover/deployment/articles-dxp/08-lcs/04-using-lcs/06-lcs-account.markdown
en/discover/deployment/articles-dxp/08-lcs/04-using-lcs/07-lcs-subscriptions.markdown
en/discover/deployment/articles-dxp/08-lcs/04-using-lcs/08-lcs-tokens.markdown
en/discover/deployment/articles-dxp/08-lcs/05-lcs-troubleshooting.markdown

https://issues.liferay.com/browse/LRDOCS-7733

Update LCS for warning messages (7.1 branch)

---

en/deployment/articles-dxp/08-lcs/01-intro.markdown
en/deployment/articles-dxp/08-lcs/02-getting-started.markdown
en/deployment/articles-dxp/08-lcs/03-lcs-preconfiguration.markdown
en/deployment/articles-dxp/08-lcs/04-registration.markdown
en/deployment/articles-dxp/08-lcs/05-using-lcs/01-intro.markdown
en/deployment/articles-dxp/08-lcs/05-using-lcs/02-lcs-property-storage.markdown
en/deployment/articles-dxp/08-lcs/05-using-lcs/03-managing-lcs-users.markdown
en/deployment/articles-dxp/08-lcs/05-using-lcs/04-lcs-dashboard.markdown
en/deployment/articles-dxp/08-lcs/05-using-lcs/05-lcs-environments.markdown
en/deployment/articles-dxp/08-lcs/05-using-lcs/06-lcs-servers.markdown
en/deployment/articles-dxp/08-lcs/05-using-lcs/07-lcs-account.markdown
en/deployment/articles-dxp/08-lcs/05-using-lcs/08-lcs-subscriptions.markdown
en/deployment/articles-dxp/08-lcs/05-using-lcs/09-lcs-tokens.markdown
en/deployment/articles-dxp/08-lcs/06-lcs-troubleshooting.markdown

https://issues.liferay.com/browse/LRDOCS-7762

LRDOCS-7762

---

en/developer/frameworks/articles/search/02-aggregations/03-statistical-aggregations.markdown

https://issues.liferay.com/browse/LRDOCS-7232 Thanks to @lipusz for discovering that some of our work on this never made it in due to my automated (read, lazy) attempt to wave away a merge conflict.

LRDOCS-7232 | Statistical Aggregations prove I am no git wizard,

---

en/deployment/articles-dxp/03-installing-a-search-engine/03-enterprise-search/02-monitoring/01-monitoring-intro.markdown
en/deployment/articles/03-installing-a-search-engine/02-elasticsearch/07-security.markdown

https://issues.liferay.com/browse/LRDOCS-7842, lightly edited Tibor's original PR to me: https://github.com/rbohl/liferay-docs/pull/159
Additional similar PRs may be sent for 7.1 and 7.0.

7.2 Elasticsearch Configuration Improvements | LRDOCS-7842

---

discover/deployment/articles/04-managing-liferay-with-liferay-connected-services/00-managing-liferay-with-liferay-connected-services-intro.markdown
discover/deployment/articles/04-managing-liferay-with-liferay-connected-services/01-lcs-preconfiguration.markdown
discover/deployment/articles/04-managing-liferay-with-liferay-connected-services/02-connecting-to-lcs.markdown
discover/deployment/articles/04-managing-liferay-with-liferay-connected-services/03-using-lcs.markdown

LRDOCS-7760 - Update LCS features deprecation message

---

en/developer/frameworks/articles/search/03-queries-and-filters/01-queries-and-filters-intro.markdown
en/developer/frameworks/articles/search/03-queries-and-filters/02-building-search-queries-and-filters.markdown

https://issues.liferay.com/browse/LRDOCS-7605, with more improvements (indeed, a whole new Liferay Learn article or section of articles) planned on LRDOCS-7885. cc @lipusz @joshuacords

Queries and Filters | Bug Fixing and Adding Details | LRDOCS-7605

---

discover/deployment/articles/02-installing-liferay/10-configuring-search.markdown
discover/deployment/articles/08-liferay-enterprise-search/07-upgrading-to-elasticsearch-6.markdown

https://issues.liferay.com/browse/LRDOCS-7879
cc @lipusz

7.0 Deployment guide | Defer to the Compatibility Matrix for ES Version Support | LRDOCS-7879

---

en/deployment/articles-dxp/01-deploying-liferay/07-installing-liferay-portal-on-jboss-eap.markdown
en/deployment/articles-dxp/01-deploying-liferay/08-installing-liferay-on-weblogic.markdown
en/deployment/articles-dxp/01-deploying-liferay/09-installing-liferay-on-websphere.markdown
en/deployment/articles-dxp/02-configuring-liferay/08-dxp-configuration-and-tuning/01-intro.markdown
en/deployment/articles/01-deploying-liferay/05-installing-liferay-on-tomcat.markdown
en/deployment/articles/01-deploying-liferay/06-installing-liferay-portal-on-wildfly.markdown
en/deployment/articles/02-configuring-liferay/04-liferay-portal-clustering/02-point-all-nodes-to-the-same-liferay-portal-database.markdown
en/deployment/articles/02-configuring-liferay/04-liferay-portal-clustering/05-enabling-cluster-link.markdown
en/deployment/articles/05-upgrading-to-liferay-7-2/06-upgrading-the-liferay-database/03-configuring-the-data-upgrade.markdown
en/deployment/articles/05-upgrading-to-liferay-7-2/08-upgrading-a-sharded-environment.markdown
en/deployment/articles/100-reference/05-database-templates.markdown

Update the driver and add serverTimezone=GMT to the mysql URLs.
Includes Wildfly fix to keep Weld config https://issues.liferay.com/browse/LRDOCS-7898

7.2 Use com.mysql.cj.jdbc.Driver

---

en/developer/appdev/articles/02-web-front-ends/05-liferay-mvc-portlet/02-creating-an-mvc-portlet.markdown
en/developer/appdev/articles/02-web-front-ends/07-jsf-portlet/02-developing-a-jsf-portlet-application.markdown
en/developer/appdev/articles/02-web-front-ends/08-bean-portlet/01-bean-portlet-intro.markdown
en/developer/frameworks/articles/portlets/01-portlets-intro.markdown
en/developer/reference/articles/02-portlet-3-opt-in.markdown

Demonstrate how to "opt in" to the Portlet 3.0 API.
https://issues.liferay.com/browse/LRDOCS-7862

LRDOCS-7862 Portlet 3 opt in

---

en/discover/deployment/articles/01-deploying-liferay/05-installing-liferay-portal-on-wildfly.markdown

https://github.com/sez11a/liferay-docs/pull/4797

LRDOCS-7898 keep weld config

---

en/user/articles/140-workflow/03-managing-workflows.markdown

https://issues.liferay.com/browse/LRDOCS-7924, cc @inacionery

Add Security Awareness Info to 7.2 | LRDOCS-7924

---

en/discover/portal/articles/140-workflow/03-managing-workflows.markdown

https://issues.liferay.com/browse/LRDOCS-7923 cc @inacionery

Only Regular Admins can add workflows | LRDOCS-7923

---

en/discover/deployment/articles/06-upgrading-to-liferay-7-1/03-running-the-upgrade-process/02-gogo-shell-commands-for-module-upgrades.markdown

https://issues.liferay.com/browse/LRDOCS-7950

LRDOCS-7950 7.1.x Fix upgrade command names

---

discover/deployment/articles/06-upgrading-liferay/03-running-the-upgrade-process.markdown

https://issues.liferay.com/browse/LRDOCS-7950

LRDOCS-7950 7.0.x  Fix upgrade command names

---

discover/deployment/articles-dxp/07-monitoring-liferay/01-basic-monitoring.markdown

https://issues.liferay.com/browse/LRDOCS-7952

LRDOCS-7952 7.0.x list JVM args for remote console

---

en/discover/deployment/articles-dxp/07-monitoring-liferay/01-monitoring-garbage-collectcion-and-the-jvm.markdown

https://issues.liferay.com/browse/LRDOCS-7952

LRDOCS-7952 list JVM args for remote Console

---

en/developer/frameworks/articles/web-experience-management/02-page-fragments/02-developing-a-fragment.markdown

LRDOCS-7944 add warning about inline base64 images

---

discover/deployment/articles/08-liferay-enterprise-search/02-configuring-elasticsearch.markdown

https://issues.liferay.com/browse/LRDOCS-7739, Thanks to @lipusz! [FYI, The links were good Tibor]

Link fixing | LRDOCS-7739

---

en/discover/deployment/articles/01-deploying-liferay/10-installing-elasticsearch.markdown

https://issues.liferay.com/browse/LRDOCS-6907, thanks to @lipusz!

Fix Link to Elastic | LRDOCS-6907

---

en/deployment/articles/03-installing-a-search-engine/02-elasticsearch/03-installing-elasticsearch.markdown
en/deployment/articles/03-installing-a-search-engine/02-elasticsearch/11-upgrading-to-elasticsearch-73.markdown

- https://issues.liferay.com/browse/LRDOCS-7957
- https://issues.liferay.com/browse/LRDOCS-7958
Thanks @adamzsolnay and @lipusz!

7.2 Search Deployment Fixes | LRDOCS-7957 && LRDOCS-7958

---

en/developer/reference/articles/02-breaking-changes.markdown

@sez11a this includes an aside redirecting the user to the updated docs on Liferay Learn and stating that they will no longer be maintained on Help Center.

LRDOCS-7881 port latest 7.2 Breaking Changes

---

en/develop/tutorials/articles/280-workflow/00-intro.markdown
en/discover/deployment/articles/06-upgrading-to-liferay-7-1/02-preparing-for-upgrade-to-liferay-7-1/00-preparing-for-upgrade-to-liferay-7-1-intro.markdown
en/discover/portal/articles/140-workflow/00-intro.markdown
en/discover/portal/articles/140-workflow/03-managing-workflows.markdown

https://issues.liferay.com/browse/LRDOCS-7631

LRDOCS-7631 update links to 7.1 DXP articles

---

develop/tutorials/articles/03-developing-a-web-application/11-workflow/00-intro.markdown
discover/deployment/articles-dxp/02-installing-liferay/11-activating-liferay-dxp.markdown
discover/deployment/articles-dxp/04-maintaining-liferay/01-patching-liferay/01-patching-tool-configuration/03-installing-patches-on-the-liferay-de-war.markdown
discover/portal/articles/150-setting-up-liferay/01-system-settings/03-server-admin.markdown

https://issues.liferay.com/browse/LRDOCS-7631

LRDOCS-7631 update links to 7.0 DXP articles

---

en/user/articles/01-the-liferay-distinction/01-the-liferay-distinction-intro.markdown

https://issues.liferay.com/browse/LRDOCS-7808

LRDOCS-7808 Fix broken section links in 7.2's "The Liferay Distinction"

---

devGuide/en/chapters/02-liferays-developer-tools.markdown
userGuide/en/chapters/16-installation-and-setup.markdown

https://issues.liferay.com/browse/LRDOCS-7834

LRDOCS-7834 Update links to download 6.2 EE from Help Center

---

en/developer/customization/articles/50-customizing-jsps/05-core-jsp-overrides-using-customjspbag.markdown

https://issues.liferay.com/browse/LRDOCS-7543

LRDOCS-7543 Remove references to a non-existent 7.2 Custom JSP Bag sample

---

en/develop/tutorials/articles/120-customizing/01-customizing-jsps/05-core-jsp-overrides-using-customjspbag.markdown

https://issues.liferay.com/browse/LRDOCS-7543

LRDOCS-7543 Remove references to a non-existent 7.1 custom JSP bag sample

---

develop/tutorials/articles/120-service-builder/01-introduction-to-service-builder/01-introduction-to-service-builder-intro.markdown

https://issues.liferay.com/browse/LRDOCS-7598

LRDOCS-7598 7.0.x - link to 7.0 distributed caching docs

---

en/discover/deployment/articles-dxp/01-deploying-liferay/06-installing-liferay-portal-on-jboss-eap.markdown
en/discover/deployment/articles-dxp/01-deploying-liferay/07-installing-liferay-on-tc-server.markdown
en/discover/deployment/articles-dxp/01-deploying-liferay/08-installing-liferay-on-weblogic.markdown
en/discover/deployment/articles-dxp/01-deploying-liferay/09-installing-liferay-on-websphere.markdown
en/discover/deployment/articles/01-deploying-liferay/01-preparing-for-install.markdown
en/discover/deployment/articles/01-deploying-liferay/02-installing-liferay.markdown
en/discover/deployment/articles/01-deploying-liferay/04-installing-liferay-portal-on-tomcat.markdown
en/discover/deployment/articles/01-deploying-liferay/05-installing-liferay-portal-on-wildfly.markdown

https://issues.liferay.com/browse/LRDOCS-7663

LRDOCS-7663 7.1.x Add JDK req and JDK 11 note, and reference compatibility matrix

---

en/discover/deployment/articles-dxp/01-deploying-liferay/08-installing-liferay-on-weblogic.markdown
en/discover/deployment/articles-dxp/01-deploying-liferay/09-installing-liferay-on-websphere.markdown

https://issues.liferay.com/browse/LRDOCS-7737

LRDOCS-7737 7.1.x On Websphere, install portlet jar as server associated shared library

---

discover/deployment/articles/02-installing-liferay/01-preparing-for-install.markdown

https://issues.liferay.com/browse/LRDOCS-7663

LRDOCS-7663 7.0.x jdk 8 is required. Link to matrix.

---

en/developer/customization/articles/01-liferay-customization-intro.markdown
en/developer/customization/articles/03-architecture/08-finding-extension-points.markdown

@ngriffin7a, thanks for pointing these out!

Fix customization article links and uncomment architecture bullet

---

en/developer/reference/articles/02-sample-projects/02-apps/service-builder-samples/service-builder-jdbc.markdown

https://issues.liferay.com/browse/LRDOCS-7544

LRDOCS-7544 7.2 Note the Spring XML file and service.xml that the sample provides.

---

en/developer/appdev/articles/03-service-builder/03-creating-o-r-map/98-connecting-service-builder-to-an-external-database/01-connecting-service-builder-to-an-external-database-intro.markdown
en/developer/appdev/articles/03-service-builder/03-creating-o-r-map/98-connecting-service-builder-to-an-external-database/02-datasource-connect-using-a-datasourceprovider.markdown
en/developer/appdev/articles/03-service-builder/03-creating-o-r-map/98-connecting-service-builder-to-an-external-database/03-datasource-connect-using-spring-beans.markdown

Add steps to ...
1. Specify database and data source in the service.xml
2. Create database manually
https://issues.liferay.com/browse/LRDOCS-7561

LRDOCS-7561 7.2: Fix external data source steps

---

en/develop/tutorials/articles/130-service-builder/02-service-builder-persistence/08-connecting-service-builder-to-external-data-sources.markdown

Add steps to ...
1. Specify database and data source in the service.xml
2. Create database manually
https://issues.liferay.com/browse/LRDOCS-7561

LRDOCS-7561 7.1: Fix external data source steps

---

en/develop/reference/articles/10-sample-projects/01-apps/service-builder-samples/service-builder-jdbc.markdown

Note the Spring XML file and service.xml that the sample provides and reference "Connecting the Data Source Using Spring Beans".
https://issues.liferay.com/browse/LRDOCS-7544

LRDOCS-7544 7.1 Note the Spring XML file and service.xml that the sample provides.

---

en/developer/customization/articles/02-fundamentals/02-configuring-dependencies/04-resolving-third-party-library-package-dependencies.markdown
en/developer/customization/articles/02-fundamentals/04-importing-packages/01-importing-packages-intro.markdown

https://issues.liferay.com/browse/LRDOCS-8041

LRDOCS-8041 7.2 preserve auto-detected package imports

---

en/develop/tutorials/articles/360-osgi-basics-for-liferay-development/03-importing-packages.markdown
en/develop/tutorials/articles/360-osgi-basics-for-liferay-development/05-resolving-third-party-package-dependencies.markdown

https://issues.liferay.com/browse/LRDOCS-8041

LRDOCS-8041 7.1.x Preserve auto-detected package imports

---

develop/tutorials/articles/300-osgi-basics/03-adding-third-party-libraries-to-a-module.markdown
develop/tutorials/articles/300-osgi-basics/06-importing-packages.markdown

https://issues.liferay.com/browse/LRDOCS-8041

LRDOCS-8041 7.0.x Preserve auto-detected package imports

---

en/developer/appdev/articles/99-troubleshooting-application-development-issues/01-troubleshooting-application-development-issues-intro.markdown

https://issues.liferay.com/browse/LRDOCS-8057

LRDOCS-8057 Fix Troubleshooting links

---

en/discover/deployment/articles-dxp/02-installing-search-engine/02-enterprise-search/00-intro.markdown
en/discover/deployment/articles-dxp/02-installing-search-engine/02-enterprise-search/01-security/00-security-intro.markdown
en/discover/deployment/articles-dxp/02-installing-search-engine/02-enterprise-search/02-monitoring/00-monitoring-intro.markdown
en/discover/deployment/articles-dxp/02-installing-search-engine/02-enterprise-search/03-xpack-6.1/00-xpack-6_1-intro.markdown
en/discover/deployment/articles-dxp/02-installing-search-engine/02-enterprise-search/03-xpack-6.1/02-xpack-security-6_1.markdown
en/discover/deployment/articles-dxp/02-installing-search-engine/02-enterprise-search/03-xpack-6.1/03-xpack-monitoring-6_1.markdown
en/discover/portal/articles/120-search/03-searching-for-assets.markdown

https://issues.liferay.com/browse/LRDOCS-8051
https://issues.liferay.com/browse/LRDOCS-8038

search 7.1 | various fixes | LRDOCS-8051/8038

---

en/user/articles/120-search/04-searching-for-assets/01-searching-for-assets-intro.markdown

https://issues.liferay.com/browse/LRDOCS-8038

search 7.2 | bad markdown | LRDOCS-8038

---

en/distribute/publish/articles/01-publishing-your-app/04-understanding-the-app-review-process/00-understanding-the-app-review-process-intro.markdown
en/user/articles/05-setting-up/01-system-settings/03-server-administration/02-server-admin-external-services.markdown

https://issues.liferay.com/browse/LRDOCS-7672

usm 7.2 | bad markdown arrows | LRDOCS-7672

---

discover/deployment/articles-dxp/08-liferay-enterprise-search/08-xpack-security.markdown
discover/deployment/articles-dxp/08-liferay-enterprise-search/09-xpack-monitoring.markdown
discover/deployment/articles-dxp/08-liferay-enterprise-search/10-xpack-elasticsearch-6.1/00-xpack-security-61-intro.markdown
discover/deployment/articles-dxp/08-liferay-enterprise-search/10-xpack-elasticsearch-6.1/01-xpack-monitoring-61.markdown

https://issues.liferay.com/browse/LRDOCS-8051
cc @lipusz

search 7.0 | no more les tiers | LRDOCS-8051

---

en/developer/appdev/articles/03-service-builder/03-creating-o-r-map/98-connecting-service-builder-to-an-external-database/03-datasource-connect-using-spring-beans.markdown
en/developer/reference/articles/02-sample-projects/02-apps/service-builder-samples/service-builder-jndi.markdown
en/distribute/publish/articles/01-publishing-your-app/04-understanding-the-app-review-process/00-understanding-the-app-review-process-intro.markdown

https://issues.liferay.com/browse/LRDOCS-7964

LRDOCS-7964 Update JNDI External Datasource articles with bug info and imrpovements

---

en/developer/customization/articles/50-liferay-forms/02-form-storage-adapters.markdown
en/developer/customization/articles/50-liferay-forms/03-creating-form-storage-adapters.markdown
en/distribute/publish/articles/01-publishing-your-app/04-understanding-the-app-review-process/00-understanding-the-app-review-process-intro.markdown

https://issues.liferay.com/browse/LRDOCS-7447

forms 7.2 | link to help center version | LRDOCS-7447

---

en/user/articles-dxp/10-managing-users/11-auditing-users/03-configuring-user-audits.markdown

https://issues.liferay.com/browse/LRDOCS-8177

LRDOCS-8177 Put configs into [Liferay Home]/osgi/configs/

---

discover/portal/articles/130-managing-users/05-roles-and-permissions.markdown

usm 7.0.x | typo in roles and permissions

---

discover/deployment/articles/02-installing-liferay/01-preparing-for-install.markdown

https://issues.liferay.com/browse/LRDOCS-8283

LRDOCS-8283 | 7.0.x - liferay reads/writes data

---

en/discover/deployment/articles/01-deploying-liferay/01-preparing-for-install.markdown

https://issues.liferay.com/browse/LRDOCS-8283

LRDOCS-8283 | 7.1.x - liferay reads/writes data

---

en/developer/tutorials/articles/03-upgrading-code-to-liferay-7.2/01-intro.markdown
en/developer/tutorials/articles/03-upgrading-code-to-liferay-7.2/02-upgrading-your-development-environment.markdown

https://issues.liferay.com/browse/LRDOCS-8305
@yanan @gamerson - Please see the follow-up commits. I removed the superseded section and fixed the link to the workspace settings section. Thanks.

LRDOCS-8305 Fix upgrade planner steps

---

en/discover/deployment/articles/06-upgrading-to-liferay-7-1/03-running-the-upgrade-process/01-running-the-upgrade-tool.markdown

https://issues.liferay.com/browse/LRDOCS-8044

7.1.x: LRDOCS-8044 use relative paths

---

discover/deployment/articles/06-upgrading-liferay/03-running-the-upgrade-process.markdown

https://issues.liferay.com/browse/LRDOCS-8044

LRDOCS-8044 7.0.x: use relative paths

---

en/discover/deployment/articles-dxp/01-deploying-liferay/06-installing-liferay-portal-on-jboss-eap.markdown
en/discover/deployment/articles/01-deploying-liferay/05-installing-liferay-portal-on-wildfly.markdown

https://issues.liferay.com/browse/LRDOCS-8316

LRDOCS-8316 7.1.x: Configure JSPs on JBoss/Wildfly for Java 8

---

discover/deployment/articles-dxp/02-installing-liferay/06-installing-liferay-on-jboss-eap.markdown
discover/deployment/articles/02-installing-liferay/05-installing-liferay-on-wildfly.markdown

https://issues.liferay.com/browse/LRDOCS-8316

LRDOCS-8316 7.0.x: Configure JSPs on JBoss for Java 8

---

en/developer/tutorials/articles/03-upgrading-code-to-liferay-7.2/01-intro.markdown
en/developer/tutorials/articles/03-upgrading-code-to-liferay-7.2/02-upgrading-your-development-environment.markdown

https://issues.liferay.com/browse/LRDOCS-8306

LRDOCS-8306  Upgrade planner: Migrate cfg to config

---

en/deployment/articles/02-configuring-liferay/07-content-delivery-network.markdown
en/deployment/articles/03-installing-a-search-engine/01-intro.markdown
en/deployment/articles/05-upgrading-to-liferay-7-2/98-deprecated-apps-in-7-2-what-to-do.markdown
en/deployment/articles/05-upgrading-to-liferay-7-2/99-apps-in-maintenance-mode.markdown
en/developer/customization/articles/02-fundamentals/01-fundamentals-intro.markdown
en/developer/customization/articles/02-fundamentals/02-configuring-dependencies/01-configuring-dependencies-intro.markdown
en/developer/customization/articles/02-fundamentals/04-importing-packages/01-importing-packages-intro.markdown
en/developer/customization/articles/02-fundamentals/05-exporting-packages/01-exporting-packages-intro.markdown
en/developer/customization/articles/02-fundamentals/06-semantic-versioning/01-semantic-versioning-intro.markdown
en/user/articles/05-setting-up/03-script-console/00-intro.markdown
en/user/articles/05-setting-up/03-script-console/01-invoking-liferay-services-from-scripts.markdown
en/user/articles/05-setting-up/03-script-console/02-running-scripts-from-script-console.markdown
en/user/articles/05-setting-up/03-script-console/03-leveraging-the-script-engine-in-workflow.markdown
en/user/articles/05-setting-up/03-script-console/04-script-examples.markdown
en/user/articles/200-managing-apps/01-managing-apps-intro.markdown
en/user/articles/200-managing-apps/02-managing-and-configuring-apps.markdown
en/user/articles/200-managing-apps/03-using-the-liferay-marketplace.markdown
en/user/articles/200-managing-apps/04-installing-apps-manually.markdown
en/user/articles/200-managing-apps/05-app-types.markdown
en/user/articles/200-managing-apps/06-blacklisting-osgi-bundles-and-components.markdown

At the tops of several core articles, I added asides that link to the latest version of articles on Liferay Learn. Thanks!

Link to core liferay learn articles - part 2

---

en/discover/deployment/articles/03-configuring-liferay/06-content-delivery-network/00-content-delivery-network-intro.markdown

https://issues.liferay.com/browse/LRDOCS-8052

LRDOCS-8052 7.1.x: improve cdn field instructions

---

discover/deployment/articles/03-configuring-liferay/06-content-delivery-network.markdown

https://issues.liferay.com/browse/LRDOCS-8052

LRDOCS-8052 7.0.x: improve cdn host field instructions

---

en/deployment/articles-dxp/03-installing-a-search-engine/03-enterprise-search/01-les-intro.markdown
en/deployment/articles-dxp/03-installing-a-search-engine/03-enterprise-search/02-monitoring/01-monitoring-intro.markdown
en/deployment/articles-dxp/03-installing-a-search-engine/03-enterprise-search/03-ltr/01-learning-to-rank-intro.markdown
en/deployment/articles/03-installing-a-search-engine/02-elasticsearch/07-security.markdown
en/deployment/articles/03-installing-a-search-engine/02-elasticsearch/08-backing-up-es.markdown
en/deployment/articles/03-installing-a-search-engine/02-elasticsearch/09-upgrading-to-elasticsearch_65.markdown
en/deployment/articles/03-installing-a-search-engine/02-elasticsearch/10-upgrading-to-elasticsearch_68.markdown
en/deployment/articles/03-installing-a-search-engine/02-elasticsearch/11-upgrading-to-elasticsearch-73.markdown
en/deployment/articles/03-installing-a-search-engine/03-solr/01-installing-solr-intro.markdown
en/deployment/articles/03-installing-a-search-engine/03-solr/02-installing-solr-basic.markdown

https://issues.liferay.com/browse/LRDOCS-8432
cc @lipusz

search 7.2 | the les apps were renamed | LRDOCS-8432

---

en/discover/deployment/articles-dxp/02-installing-search-engine/02-enterprise-search/00-intro.markdown
en/discover/deployment/articles-dxp/02-installing-search-engine/02-enterprise-search/01-security/00-security-intro.markdown
en/discover/deployment/articles-dxp/02-installing-search-engine/02-enterprise-search/02-monitoring/00-monitoring-intro.markdown
en/discover/deployment/articles-dxp/02-installing-search-engine/02-enterprise-search/03-xpack-6.1/00-xpack-6_1-intro.markdown
en/discover/deployment/articles-dxp/02-installing-search-engine/02-enterprise-search/03-xpack-6.1/02-xpack-security-6_1.markdown
en/discover/deployment/articles-dxp/02-installing-search-engine/02-enterprise-search/03-xpack-6.1/03-xpack-monitoring-6_1.markdown
en/discover/deployment/articles/02-installing-search-engine/01-elasticsearch/06-backing-up-es.markdown
en/discover/deployment/articles/02-installing-search-engine/03-installing-solr/01-installing-solr-basic.markdown

https://issues.liferay.com/browse/LRDOCS-8432
cc @sez11a

search 7.1 | the les apps were renamed | LRDOCS-8432

---

discover/deployment/articles-dxp/08-liferay-enterprise-search/08-xpack-security.markdown
discover/deployment/articles-dxp/08-liferay-enterprise-search/09-xpack-monitoring.markdown
discover/deployment/articles-dxp/08-liferay-enterprise-search/10-xpack-elasticsearch-6.1/00-xpack-security-61-intro.markdown
discover/deployment/articles-dxp/08-liferay-enterprise-search/10-xpack-elasticsearch-6.1/01-xpack-monitoring-61.markdown

https://issues.liferay.com/browse/LRDOCS-8432
cc @lipusz

search 7.0 | the les apps were renamed | LRDOCS-8432

---

en/developer/reference/articles/02-liferay-faces/02-liferay-faces-version-scheme.markdown

https://issues.liferay.com/browse/LRDOCS-8421

7.2.x LRDOCS-8421: Update JSF AlloyUI version scheme

---

en/discover/deployment/articles/06-upgrading-to-liferay-7-1/03-running-the-upgrade-process/01-running-the-upgrade-tool.markdown

https://issues.liferay.com/browse/LRDOCS-8292

7.1.x LRDOCS-8292: update tool download instructions

---

en/deployment/articles/03-installing-a-search-engine/01-intro.markdown
en/deployment/articles/03-installing-a-search-engine/02-elasticsearch/01-elasticsearch-intro.markdown
en/deployment/articles/03-installing-a-search-engine/02-elasticsearch/02-preparing-to-install.markdown
en/deployment/articles/03-installing-a-search-engine/02-elasticsearch/03-installing-elasticsearch.markdown
en/deployment/articles/03-installing-a-search-engine/02-elasticsearch/04-configuring-the-connector.markdown
en/deployment/articles/03-installing-a-search-engine/02-elasticsearch/07-security.markdown

As a followup to the new articles on LL (LRDOCS-7786), I linked (updated the links) to these Liferay Learn search articles.
cc/ @rbohl

LRDOCS-7786 Link to search installation on Liferay Learn

---

en/deployment/articles/01-deploying-liferay/06-installing-liferay-portal-on-wildfly.markdown

https://issues.liferay.com/browse/LRDOCS-8582

LRDOCS-8582 master Fix: Wildfly install broken link

---

en/deployment/articles/03-installing-a-search-engine/02-elasticsearch/11-upgrading-to-elasticsearch-73.markdown

in the bundle blacklist, add old lpkg name too

---

.vscode/settings.json
discover/portal/articles-dxp/160-targeting-content-to-your-audience/00-targeting-content-to-your-audience-intro.markdown

- Remove unexpected characters in 7.0.x version of 00-targeting-content-to-your-audience-intro.markdown.
- Adding .vscode extension to .gitignore file in Help Center repo.

LRDOCS-8589 markdown visible in help center 7.0 document

---

en/discover/portal/articles-dxp/160-targeting-content-to-your-audience/00-targeting-content-to-your-audience-intro.markdown

Remove unexpected characters in 7.1.x version of 00-targeting-content-to-your-audience-intro.markdown.

LRDOCS-8589-Markdown-visible-in-Help-Center-7.1-document

---

en/user/articles/100-web-experience-management/03-building-a-site/06-configuring-sites/03-site-social-settings.markdown

https://issues.liferay.com/browse/LRDOCS-8687

LRDOCS-8687 7.2.x: Fix caption for site Languages tab

---

en/discover/portal/articles/100-web-experience-management/02-building-a-site/05-configuring-sites/02-site-social-settings.markdown

https://issues.liferay.com/browse/LRDOCS-8687

LRDOCS-8687 7.1.x: Fix language settings caption

---

en/developer/tutorials/articles/03-upgrading-code-to-liferay-7.2/05-fixing-upgrade-problems/02-resolving-a-projects-dependencies.markdown
en/developer/tutorials/articles/03-upgrading-code-to-liferay-7.2/07-upgrading-customization-plugins/05-upgrading-service-wrapper-hooks.markdown
en/developer/tutorials/articles/03-upgrading-code-to-liferay-7.2/07-upgrading-customization-plugins/12-upgrading-struts-action-hooks.markdown
en/developer/tutorials/articles/03-upgrading-code-to-liferay-7.2/08-upgrading-themes/02-upgrading-6.2-themes-7.2/01-upgrading-6.2-themes-to-7.1-intro.markdown
en/developer/tutorials/articles/03-upgrading-code-to-liferay-7.2/11-upgrading-portlets/05-upgrading-a-servlet-based-portlet.markdown
en/developer/tutorials/articles/03-upgrading-code-to-liferay-7.2/13-upgrading-ext-plugins.markdown

LRDOCS-8698 master: Fix and update links in code upgrade

---

en/discover/deployment/articles-dxp/01-deploying-liferay/06-installing-liferay-portal-on-jboss-eap.markdown
en/discover/deployment/articles/01-deploying-liferay/05-installing-liferay-portal-on-wildfly.markdown
ja/discover/deployment/articles-dxp/01-deploying-liferay/06-installing-liferay-portal-on-jboss-eap.markdown
ja/discover/deployment/articles/01-deploying-liferay/05-installing-liferay-portal-on-wildfly.markdown

https://issues.liferay.com/browse/LRDOCS-8701

LRDOCS-8701 7.1.x Fix: Use portal-kernel's PortalLoginModule

---

discover/deployment/articles-dxp/02-installing-liferay/06-installing-liferay-on-jboss-eap.markdown
discover/deployment/articles/02-installing-liferay/05-installing-liferay-on-wildfly.markdown

https://issues.liferay.com/browse/LRDOCS-8701

LRDOCS-8701 7.0.x Fix: Use portal-kernel's JAAS PortalLoginModule

---

en/developer/appdev/articles/02-web-front-ends/05-liferay-mvc-portlet/01-liferay-mvc-portlet-intro.markdown
en/developer/appdev/articles/02-web-front-ends/05-liferay-mvc-portlet/02-creating-an-mvc-portlet.markdown
en/developer/appdev/articles/02-web-front-ends/05-liferay-mvc-portlet/05-mvc-action-command.markdown
en/developer/appdev/articles/02-web-front-ends/05-liferay-mvc-portlet/06-mvc-render-command.markdown
en/developer/appdev/articles/02-web-front-ends/05-liferay-mvc-portlet/07-mvc-resource-command.markdown
en/developer/appdev/articles/03-service-builder/03-creating-o-r-map/99-migrating-a-service-builder-module-from-spring-di-to-osgi-ds/01-migrating-a-service-builder-module-from-spring-di-to-osgi-ds-intro.markdown
en/developer/appdev/articles/03-service-builder/09-advanced-queries/03-defining-a-custom-finder-method.markdown
en/developer/frameworks/articles/dependency-injection/declarative-services.markdown
en/developer/frameworks/articles/dependency-injection/service-trackers-for-osgi-services.markdown

https://issues.liferay.com/browse/LRDOCS-8713

LRDOCS-8713 72x Fix: FinderImpl must be a component

---

en/develop/tutorials/articles/130-service-builder/02-service-builder-persistence/10-dynamic-query/01-defining-a-custom-finder-method.markdown

https://issues.liferay.com/browse/LRDOCS-8713

LRDOCS-8713 71x Fix: Make the custom finder a component

---

develop/tutorials/articles/120-service-builder/02-service-builder-persistence/06-developing-custom-sql-queries.markdown

https://issues.liferay.com/browse/LRDOCS-8713

LRDOCS-8713 70x Fix: Make the finder a component

---

discover/deployment/articles/02-installing-liferay/05-installing-liferay-on-wildfly.markdown

https://issues.liferay.com/browse/LRDOCS-8724

LRDOCS-8724 7.0.x Fix: Wildfly uses jsp-config element

---

en/user/articles/170-content-publication-management/02-staging/01-intro.markdown
en/user/articles/170-content-publication-management/02-staging/02-enabling-staging/01-intro.markdown
en/user/articles/170-content-publication-management/02-staging/02-enabling-staging/02-enabling-local-live-staging.markdown
en/user/articles/170-content-publication-management/02-staging/02-enabling-staging/03-enabling-remote-live-staging.markdown
en/user/articles/170-content-publication-management/02-staging/02-enabling-staging/04-configuring-servers-for-remote-live-staging.markdown
en/user/articles/170-content-publication-management/02-staging/02-enabling-staging/05-enabling-page-versioning-and-staged-content.markdown
en/user/articles/170-content-publication-management/02-staging/03-publishing-staged-content-efficiently/01-publishing-staged-content-efficiently-intro.markdown
en/user/articles/170-content-publication-management/02-staging/04-using-the-staging-environment/01-intro.markdown
en/user/articles/170-content-publication-management/02-staging/04-using-the-staging-environment/02-staging-content.markdown
en/user/articles/170-content-publication-management/02-staging/04-using-the-staging-environment/03-advanced-publication-with-staging.markdown
en/user/articles/170-content-publication-management/02-staging/04-using-the-staging-environment/04-managing-content-types-in-staging.markdown
en/user/articles/170-content-publication-management/02-staging/04-using-the-staging-environment/05-staging-processes-and-templates.markdown
en/user/articles/170-content-publication-management/02-staging/05-disabling-staging/01-disabling-staging-intro.markdown
en/user/articles/170-content-publication-management/02-staging/06-publishing-single-assets-from-staged-site/01-publishing-single-assets-from-staged-site-intro.markdown
en/user/articles/170-content-publication-management/02-staging/07-organizing-pages-for-staging/01-intro.markdown
en/user/articles/170-content-publication-management/02-staging/07-organizing-pages-for-staging/02-using-multi-and-single-page-variations.markdown
en/user/articles/170-content-publication-management/02-staging/07-organizing-pages-for-staging/03-creating-multi-and-single-page-variations.markdown
en/user/articles/170-content-publication-management/02-staging/07-organizing-pages-for-staging/04-merging-site-pages-variations.markdown
en/user/articles/170-content-publication-management/02-staging/08-managing-staging-permissions/01-intro.markdown

This commit adds an aside to each ported Staging article for 7.2 in partial fulfillment of [LRDOCS-8692](https://issues.liferay.com/browse/LRDOCS-8692).

LRDOCS-8692 Adds Aside to Ported Staging Articles - 7.2

---

en/discover/portal/articles/100-web-experience-management/07-staging-content-for-publication/01-enabling-staging/02-enabling-remote-live-staging.markdown

This commit makes a minor edit to the Enabling Remote Live Staging article (7.1) to address [LRDOCS-8692](https://issues.liferay.com/browse/LRDOCS-8692).

LRDOCS-8692 edit to Enabling Remote Live Staging article for 7.1

---

en/discover/deployment/articles/05-maintaining-liferay/02-backing-up-a-liferay-installation.markdown
en/discover/deployment/articles/06-upgrading-to-liferay-7-1/02-preparing-for-upgrade-to-liferay-7-1/00-preparing-for-upgrade-to-liferay-7-1-intro.markdown

https://issues.liferay.com/browse/LRDOCS-8909

7.1.x LRDOCS-8909 Back up the file store, copy to new installation, and configure it

---

discover/deployment/articles/05-backing-up-liferay/00-backing-up-liferay-intro.markdown
discover/deployment/articles/06-upgrading-liferay/02-preparing-for-upgrade.markdown

https://issues.liferay.com/browse/LRDOCS-8909

7.0.x LRDOCS-8909 Back up the file store, copy to new installation, and configure it

---

en/discover/deployment/articles-dxp/01-deploying-liferay/08-installing-liferay-on-weblogic.markdown

https://issues.liferay.com/browse/LRDOCS-8557

7.1.x LRDOCS-8557: Use a setUserOverridesLate.sh script instead of the setDomainEnv.sh and startWebLogic.sh

---

discover/deployment/articles-dxp/02-installing-liferay/08-installing-liferay-on-weblogic.markdown

https://issues.liferay.com/browse/LRDOCS-8557

7.0.x LRDOCS-8557: Use a setUserOverridesLate.sh script instead of the setDomainEnv.sh and startWebLogic.sh

---

en/discover/portal/articles/100-web-experience-management/05-publishing-content-dynamically/02-using-the-asset-publisher/03-configuring-display-settings.markdown

[LRDOCS-7930](https://issues.liferay.com/browse/LRDOCS-7930) [subtask for 7.1](https://issues.liferay.com/browse/LRDOCS-8847).
- Adding information about the updated article in liferay-learn.

LRDOCS-7930 [7.1 update] Incorrect information in Small Image Links.

---

en/user/articles/100-web-experience-management/03-building-a-site/02-site-management/02-understanding-site-management.markdown

This is subtask 7.2 for [LRDOCS-8315](https://issues.liferay.com/browse/LRDOCS-8315) proposed changes.
- Update broken 'Site Admin Portlet' URL.

LRDOCS-8315 Fix broken Sites Admin Portlet cross-link - 7.2

---

en/discover/portal/articles/100-web-experience-management/02-building-a-site/01-site-management/01-understanding-site-management.markdown

This is subtask 7.1 for [LRDOCS-8315](https://issues.liferay.com/browse/LRDOCS-8854) proposed changes.
- Update broken 'Site Admin Portlet' URL.

LRDOCS-8315 Fix broken Sites Admin Portlet cross-link - 7.1

---

en/developer/reference/articles/02-workflow/02-workflow-nodes.markdown
en/developer/reference/articles/02-workflow/03-tasks.markdown
en/user/articles-dxp/140-workflow/07-workflow-designer/03-workflow-designer-nodes.markdown

https://issues.liferay.com/browse/LRDOCS-8548
sending to liferay-docs master since these Kaleo Designer docs aren't yet available on Liferay Learn

workflow 7.2 | im and pm are nonfunctional notification types | LRDOCS-8548

---

en/develop/tutorials/articles/280-workflow/01-creating-workflow-definitions/01-workflow-nodes.markdown
en/develop/tutorials/articles/280-workflow/01-creating-workflow-definitions/02-tasks.markdown
en/discover/portal/articles-dxp/140-workflow/01-workflow-designer/02-workflow-designer-nodes.markdown

https://issues.liferay.com/browse/LRDOCS-8548

workflow 7.1.x | im and pm are nonfunctional notification types | LRDOCS-8548

---

discover/portal/articles-dxp/125-workflow/02-kaleo-designer/02-kaleo-designer-worklfow-nodes.markdown

https://issues.liferay.com/browse/LRDOCS-8548

workflow 7.0.x | im and pm are nonfunctional notification types | LRDOCS-8548

---

en/deployment/articles-dxp/03-installing-a-search-engine/03-enterprise-search/01-les-intro.markdown
en/deployment/articles-dxp/03-installing-a-search-engine/03-enterprise-search/02-monitoring/01-monitoring-intro.markdown
en/deployment/articles-dxp/03-installing-a-search-engine/03-enterprise-search/03-ltr/01-learning-to-rank-intro.markdown
en/deployment/articles-dxp/03-installing-a-search-engine/03-enterprise-search/03-ltr/02-configuring-learning-to-rank.markdown
en/deployment/articles/03-installing-a-search-engine/02-elasticsearch/01-elasticsearch-intro.markdown
en/deployment/articles/03-installing-a-search-engine/02-elasticsearch/03-installing-elasticsearch.markdown

https://issues.liferay.com/browse/LRDOCS-8840
cc @lipusz

search 7.2 | reference the new search eng compat matrix | LRDOCS-8840

---

discover/deployment/articles-dxp/08-liferay-enterprise-search/04-marvel.markdown
discover/deployment/articles-dxp/08-liferay-enterprise-search/09-xpack-monitoring.markdown
discover/deployment/articles-dxp/08-liferay-enterprise-search/10-xpack-elasticsearch-6.1/01-xpack-monitoring-61.markdown

https://issues.liferay.com/browse/LRDOCS-8840
cc @lipusz

search 7.0.x | reference the new search eng compat matrix | LRDOCS-8840

---

en/discover/deployment/articles-dxp/02-installing-search-engine/02-enterprise-search/03-xpack-6.1/03-xpack-monitoring-6_1.markdown
en/discover/deployment/articles/01-deploying-liferay/10-installing-elasticsearch.markdown
en/discover/deployment/articles/02-installing-search-engine/00-intro.markdown
en/discover/deployment/articles/02-installing-search-engine/01-elasticsearch/07-installing-elasticsearch-6.1/00-installing-elasticsearch-6_1-intro.markdown

https://issues.liferay.com/browse/LRDOCS-8840
cc @lipusz

search 7.1.x | reference the new search eng compat matrix | LRDOCS-8840

---

en/user/articles/100-web-experience-management/03-building-a-site/06-configuring-sites/02-configuring-site-settings.markdown

This PR refers to [LRDOCS-8895](https://issues.liferay.com/browse/LRDOCS-8895) and updates the 7.2 [Configure Site Settings](https://help.liferay.com/hc/en-us/articles/360029132491-Configuring-Site-Settings#site-url) article.
- Update wrong path to Home URL setting.

LRDOCS-8895 Update 7.2 'Instance Configuration' doc.

---

en/user/articles/100-web-experience-management/03-building-a-site/03-adding-pages-to-sites/03-content-pages/03-content-page-interface.markdown

This PR proposes the following changes (from [LRDOCS-8816](https://issues.liferay.com/browse/LRDOCS-8816))
- Add admonition with link to the most up-to-date article version in liferay-learn repo.
- Fix wording.

LRDOCS-8816 Missing words in 'Content Page Management Interface'

---

en/user/articles/140-workflow/01-workflow-intro.markdown
en/user/articles/140-workflow/02-activating-workflow.markdown
en/user/articles/140-workflow/03-managing-workflows.markdown
en/user/articles/140-workflow/04-reviewing-assets.markdown

use the aside tag to direct the reader to liferay learn
cc @rafaprax @naraandrade

workflow 7.2 | point to liferay learn | lrdocs-0000

---

en/discover/deployment/articles/06-upgrading-to-liferay-7-1/03-running-the-upgrade-process/01-running-the-upgrade-tool.markdown

https://issues.liferay.com/browse/LRDOCS-9136

LRDOCS-9136 7.1.x: Admonish users to migrate their "locales" property.

---

discover/deployment/articles/06-upgrading-liferay/03-running-the-upgrade-process.markdown

https://issues.liferay.com/browse/LRDOCS-9136

LRDOCS-9136 7.0.x: Admonish users to migrate their "locales" property.

---

en/deployment/articles-dxp/02-configuring-liferay/08-dxp-configuration-and-tuning/01-intro.markdown
en/deployment/articles-dxp/02-configuring-liferay/08-dxp-configuration-and-tuning/02-jvm-tuning.markdown

https://issues.liferay.com/browse/LRDOCS-7716
https://issues.liferay.com/browse/LRDOCS-7848

LRDOCS-8716 LRDOCS-8848 master: Link to updated doc in Liferay Learn

---

en/developer/frameworks/articles/portlets/01-portlets-intro.markdown
en/developer/reference/articles/02-portlet-descriptor-to-osgi-service-property-map.markdown
en/developer/reference/articles/02-third-party-packages-portal-exports.markdown

https://issues.liferay.com/browse/LRDOCS-8420
https://issues.liferay.com/browse/LRDOCS-8510
Thanks!

LRDOCS-8420 LRDOCS-8510 Link to Liferay Learn articles

---

en/deployment/articles/05-upgrading-to-liferay-7-2/02-planning-for-deprecated-apps.markdown

https://issues.liferay.com/browse/LRDOCS-8133

LRDOCS-8133 Update link to deprecations doc on learn

---

en/deployment/articles/02-configuring-liferay/02-configuring-mail.markdown

https://issues.liferay.com/browse/LRDOCS-8873

LRDOCS-8873 fix formatting

---

en/develop/tutorials/articles/380-troubleshooting/06-adjusting-module-logging.markdown

https://issues.liferay.com/browse/LRDOCS-9131

LRDOCS-9131 7.1.x: Fix log level order

---

discover/portal/articles/150-setting-up-liferay/04-scripting/00-intro.markdown
discover/portal/articles/150-setting-up-liferay/04-scripting/01-invoking-liferay-services-from-scripts.markdown

https://issues.liferay.com/browse/LRDOCS-8810

LRDOCS-8810 7.0.x: Remove mentioning the archived scripting languages

---

en/user/articles-dxp/160-segmentation-and-personalization/05-analaytics-cloud-segmentation.markdown

https://issues.liferay.com/browse/LRDOCS-9297

LRDOCS-9297 Broken Link

---

en/developer/appdev/articles/02-web-front-ends/07-jsf-portlet/02-developing-a-jsf-portlet-application.markdown

https://issues.liferay.com/browse/LRDOCS-9380

LRDOCS-9380 Remove Portlet 3 opt-in step as the JSR is not yet final

---

discover/portal/articles-dxp/110-collaboration/01-managing-documents-and-media/03-using-a-sharepoint-repository/01-creating-a-sharepoint-application.markdown

This PR capitalizes the Scope attribute in the Creating a Sharepoint Application article, per [LRDOCS-9279](https://issues.liferay.com/browse/LRDOCS-9279).

LRDOCS-9279 corrects Creating a Sharepoint Application article

---

en/deployment/articles/03-installing-a-search-engine/03-solr/01-installing-solr-intro.markdown
en/deployment/articles/03-installing-a-search-engine/03-solr/02-installing-solr-basic.markdown
en/deployment/articles/03-installing-a-search-engine/03-solr/03-installing-solr-solrcloud.markdown
en/deployment/articles/03-installing-a-search-engine/03-solr/04-solr-settings.markdown

https://issues.liferay.com/browse/LRDOCS-9452
cc @lipusz

search 7.2 | alert to see liferay learn | LRDOCS-9452

---

en/discover/deployment/articles/02-installing-search-engine/03-installing-solr/00-installing-solr-intro.markdown
en/discover/deployment/articles/02-installing-search-engine/03-installing-solr/01-installing-solr-basic.markdown
en/discover/deployment/articles/02-installing-search-engine/03-installing-solr/02-installing-solr-solrcloud.markdown

https://issues.liferay.com/browse/LRDOCS-9452
cc @lipusz

search 7.1.x | add note about solr 8 | LRDOCS-9452

---

en/discover/deployment/articles-dxp/02-installing-search-engine/02-enterprise-search/00-intro.markdown
en/discover/deployment/articles-dxp/02-installing-search-engine/02-enterprise-search/01-security/00-security-intro.markdown
en/discover/deployment/articles/02-installing-search-engine/01-elasticsearch/08-installing-elasticsearch-7/00-installing-elasticsearch-7-intro.markdown
en/discover/deployment/articles/02-installing-search-engine/01-elasticsearch/08-installing-elasticsearch-7/01-upgrading-to-elasticsearch-7.markdown

https://issues.liferay.com/browse/LRDOCS-7722
This pairs with https://github.com/sez11a/liferay-learn/pull/490 to cover setting up LES Cross-Cluster Replication on 7.1.
cc @lipusz

search 7.1 | CCR for 7.1 | LRDOCS-7722

---

en/developer/frameworks/articles/back-end-frameworks/01-intro.markdown
en/developer/frameworks/articles/back-end-frameworks/05-message-bus/01-intro.markdown
en/developer/frameworks/articles/back-end-frameworks/05-message-bus/02-creating-destination.markdown
en/developer/frameworks/articles/back-end-frameworks/05-message-bus/03-message-bus-event-listeners.markdown
en/developer/frameworks/articles/back-end-frameworks/05-message-bus/04-registering-message-listeners.markdown
en/developer/frameworks/articles/back-end-frameworks/05-message-bus/05-creating-a-message.markdown
en/developer/frameworks/articles/back-end-frameworks/05-message-bus/06-sending-a-message.markdown
en/developer/frameworks/articles/back-end-frameworks/05-message-bus/07-sending-messages-cluster.markdown

https://issues.liferay.com/browse/LRDOCS-8956

LRDOCS-8956 Link to learn.liferay.com Message Bus articles

---

en/deployment/articles-dxp/03-installing-a-search-engine/03-enterprise-search/01-les-intro.markdown

https://issues.liferay.com/browse/LRDOCS-9516
cc @lipusz

search 7.2 | deemphasize xpack | LRDOCS-9516

---

en/develop/reference/articles/200-breaking-changes.markdown

https://issues.liferay.com/browse/LRDOCS-7856

LRDOCS-7856 7.1.x Update breaking changes and extend past 80 columns

---

discover/deployment/articles/01-installation-and-setup/02-obtaining-liferay-portal.markdown
discover/deployment/articles/01-installation-and-setup/11-installing-liferay-on-an-existing-application-server.markdown
discover/deployment/articles/01-installation-and-setup/12-installing-liferay-on-mulesoft-tcat.markdown
discover/deployment/articles/01-installation-and-setup/13-installing-liferay-on-glassfish-4.markdown
discover/deployment/articles/01-installation-and-setup/14-installing-liferay-on-jboss-7.1.markdown
discover/deployment/articles/01-installation-and-setup/15-installing-liferay-on-tomcat-7.markdown
discover/deployment/articles/01-installation-and-setup/16-installing-liferay-on-oracle-weblogic-12c.markdown
discover/deployment/articles/01-installation-and-setup/21-understanding-liferays-releases.markdown
discover/deployment/articles/02-advanced-portal-operation/05-patching-liferay.markdown
discover/deployment/articles/02-advanced-portal-operation/06-upgrading-liferay.markdown
discover/deployment/articles/04-managing-liferay-with-liferay-connected-services/01-lcs-preconfiguration.markdown
discover/deployment/articles/05-configuring-for-high-availability/01-liferay-clustering.markdown

https://issues.liferay.com/browse/LRDOCS-9545

LRDOCS-9545 6.2.x: Download DXP from the Help Center

---

discover/deployment/articles-dxp/02-installing-liferay/06-installing-liferay-on-jboss-eap.markdown
discover/deployment/articles-dxp/02-installing-liferay/07-installing-liferay-on-tcserver.markdown
discover/deployment/articles-dxp/02-installing-liferay/08-installing-liferay-on-weblogic.markdown
discover/deployment/articles-dxp/02-installing-liferay/09-installing-liferay-on-websphere.markdown
discover/deployment/articles/02-installing-liferay/01-preparing-for-install.markdown
discover/deployment/articles/02-installing-liferay/04-installing-liferay-on-tomcat.markdown
discover/deployment/articles/02-installing-liferay/05-installing-liferay-on-wildfly.markdown
discover/deployment/articles/06-upgrading-liferay/03-running-the-upgrade-process.markdown

https://issues.liferay.com/browse/LRDOCS-9545

LRDOCS-9545 7.0.x: Download DXP and additional files form the Help Center

---

en/discover/deployment/articles-dxp/01-deploying-liferay/06-installing-liferay-portal-on-jboss-eap.markdown
en/discover/deployment/articles-dxp/01-deploying-liferay/07-installing-liferay-on-tc-server.markdown
en/discover/deployment/articles-dxp/01-deploying-liferay/08-installing-liferay-on-weblogic.markdown
en/discover/deployment/articles-dxp/01-deploying-liferay/09-installing-liferay-on-websphere.markdown
en/discover/deployment/articles/01-deploying-liferay/01-preparing-for-install.markdown
en/discover/deployment/articles/01-deploying-liferay/04-installing-liferay-portal-on-tomcat.markdown
en/discover/deployment/articles/01-deploying-liferay/05-installing-liferay-portal-on-wildfly.markdown
en/discover/deployment/articles/06-upgrading-to-liferay-7-1/03-running-the-upgrade-process/01-running-the-upgrade-tool.markdown

https://issues.liferay.com/browse/LRDOCS-9545

LRDOCS-9545 7.1.x: Download DXP from the Help Center

---

en/discover/portal/articles/100-web-experience-management/07-staging-content-for-publication/01-enabling-staging/03-configuring-servers-for-remote-live-staging.markdown

This PR removes an inaccurate admonition from Remote Live Staging documentation, per [LRDOCS-9690](https://issues.liferay.com/browse/LRDOCS-9690).

LRDOCS-9690 removes incorrect admonition from 7.1 article

---

bin/update-liferay-learn-links.sh

**Usage:**
```bash
./bin/update_liferay_learn_links.sh path/to/properties/file
```
For example,
```bash
cd liferay-learn
cat ./site/docs/redirects_keep.properties ./site/docs/redirects_new.properties > ~/redirects.properties
cd ../liferay-docs
./bin/update_liferay_learn_links.sh ~/redirects.properties
```
https://issues.liferay.com/browse/LRDOCS-10071

LRDOCS-10071 script to update liferay learn links using redirects props file

---

en/develop/tutorials/articles/01-introduction-to-liferay-development/06-frontend-development-in-liferay/00-frontend-development-in-liferay-intro.markdown

[LRDOCS-8298](https://issues.liferay.com/browse/LRDOCS-8298)
This PR fixes two broken links.

LRDOCS-8298 fixes links for 7.1.x

---

en/developer/frameworks/articles/liferay-forms/01-intro.markdown

This PR removes placeholder text, per [LRDOCS-8355](https://issues.liferay.com/browse/LRDOCS-8355).

LRDOCS-8355 removes placeholder text

---

en/develop/tutorials/articles/200-integrating-with-front-end-frameworks/04-creating-and-bundling-javascript-portlets-with-js-tooling/03-configuring-system-and-instance-settings-for-your-js-portlets.markdown
en/discover/deployment/articles/02-installing-search-engine/01-elasticsearch/00-intro.markdown

https://issues.liferay.com/browse/LRDOCS-8758
cc @lipusz, for 7.1

search 7.1 | clarify statement on embedded ealsticsearch | LRDOCS-8758

---

discover/deployment/articles/08-liferay-enterprise-search/02-configuring-elasticsearch.markdown

https://issues.liferay.com/browse/LRDOCS-8758
cc @lipusz for 7.0

search 7.0 | clarify statement on embedded ealsticsearch | LRDOCS-8758

---

discover/deployment/articles-dxp/03-configuring-liferay/07-securing-liferay/01-saml/02-setting-up-service-provider.markdown
discover/portal/articles/120-forms/01-forms/02-advanced-forms.markdown
discover/portal/articles/120-forms/02-creating-simple-applications/01-creating-data-definitions.markdown

https://issues.liferay.com/browse/LRDOCS-7456
I know, it's 7.0. Even worse, this tiny issue has made following our DDL example impossible. If it was just cosmetic I wouldn't send it.

ddl 7.0 | broken image | LRDOCS-7456

---

en/user/articles/110-collaboration/03-sync/03-sync-desktop/02-install-configure-sync-desktop.markdown
en/user/articles/110-collaboration/03-sync/04-sync-mobile/01-intro.markdown

Simple link fix for 7.2 documentation, per [LRDOCS-11454](https://liferay.atlassian.net/browse/LRDOCS-11454)

LRDOCS-11454 fixes links

---

en/developer/tutorials/articles/02-developing-a-web-application/04-building-the-web-front-end/11-displaying-guestbook-entries.markdown

Jira Ticket: https://liferay.atlassian.net/browse/LRDOCS-9137
Related article: https://help.liferay.com/hc/pt/articles/360033253231-Displaying-Guestbook-Entries#creating-an-actions-jsp
The article's format was wrong in one of the code blocks.
Changes made:
- Fix code snippet
Thank you, @abhnerramos, for [reviewing](https://github.com/abhnerramos/liferay-docs/pull/4) this PR.

LRDOCS-9137 Bad Formatting on jsp code in Displaying Guestbook Entries

---

en/user/articles-dxp/160-segmentation-and-personalization/05-analaytics-cloud-segmentation.markdown

Related issue: [LRDOCS-9871](https://liferay.atlassian.net/browse/LRDOCS-9871)
Link to Creating Segments doesn't work
- Changed link
Article in question - [Using Analytics Cloud With User Segments](https://help.liferay.com/hc/en-us/articles/360029041751-Using-Analytics-Cloud-With-User-Segments)

LRDOCS-9871 Fix link

---

en/develop/tutorials/articles/210-front-end-taglibs/05-chart-taglibs/00-using-chart-taglibs-intro.markdown
en/develop/tutorials/articles/210-front-end-taglibs/05-chart-taglibs/01-bar-charts.markdown
en/develop/tutorials/articles/210-front-end-taglibs/05-chart-taglibs/02-line-charts.markdown
en/develop/tutorials/articles/210-front-end-taglibs/05-chart-taglibs/03-scatter-charts.markdown
en/develop/tutorials/articles/210-front-end-taglibs/05-chart-taglibs/04-spline-charts.markdown
en/develop/tutorials/articles/210-front-end-taglibs/05-chart-taglibs/05-step-charts.markdown
en/develop/tutorials/articles/210-front-end-taglibs/05-chart-taglibs/06-combination-charts.markdown
en/develop/tutorials/articles/210-front-end-taglibs/05-chart-taglibs/07-donut-charts.markdown
en/develop/tutorials/articles/210-front-end-taglibs/05-chart-taglibs/08-gauge-charts.markdown
en/develop/tutorials/articles/210-front-end-taglibs/05-chart-taglibs/09-pie-charts.markdown
en/develop/tutorials/articles/210-front-end-taglibs/05-chart-taglibs/10-geomap-charts.markdown
en/develop/tutorials/articles/210-front-end-taglibs/05-chart-taglibs/11-predictive-charts.markdown
en/develop/tutorials/articles/210-front-end-taglibs/05-chart-taglibs/12-refreshing-charts-to-reflect-real-time-data.markdown

Related issues: [LRDOCS-7645](https://liferay.atlassian.net/browse/LRDOCS-7645) [LRDOCS-7647](https://liferay.atlassian.net/browse/LRDOCS-7647) [LRDOCS-7648](https://liferay.atlassian.net/browse/LRDOCS-7648)
Lots of improvements could have been made in the Related Topics of the Charts' articles. Some of the links throught these pages weren't working or led to the wrong places.
- Changed references in Related Topics
- Fixed Related Topics links that led to the wrong page
- Fixed all links to javadocs
- Fixed links to clay repo

LRDOCS-7645 LRDOCS-7647 LRDOCS-7648 Multiple Issues in Charts 7.1

---

en/developer/reference/articles/02-front-end/03-front-end-taglibs/08-chart-taglibs/01-using-chart-taglibs-intro.markdown
en/developer/reference/articles/02-front-end/03-front-end-taglibs/08-chart-taglibs/02-bar-charts.markdown
en/developer/reference/articles/02-front-end/03-front-end-taglibs/08-chart-taglibs/03-line-charts.markdown
en/developer/reference/articles/02-front-end/03-front-end-taglibs/08-chart-taglibs/04-scatter-charts.markdown
en/developer/reference/articles/02-front-end/03-front-end-taglibs/08-chart-taglibs/05-spline-charts.markdown
en/developer/reference/articles/02-front-end/03-front-end-taglibs/08-chart-taglibs/06-step-charts.markdown
en/developer/reference/articles/02-front-end/03-front-end-taglibs/08-chart-taglibs/07-combination-charts.markdown
en/developer/reference/articles/02-front-end/03-front-end-taglibs/08-chart-taglibs/08-donut-charts.markdown
en/developer/reference/articles/02-front-end/03-front-end-taglibs/08-chart-taglibs/09-gauge-charts.markdown
en/developer/reference/articles/02-front-end/03-front-end-taglibs/08-chart-taglibs/10-pie-charts.markdown
en/developer/reference/articles/02-front-end/03-front-end-taglibs/08-chart-taglibs/11-geomap-charts.markdown
en/developer/reference/articles/02-front-end/03-front-end-taglibs/08-chart-taglibs/12-predictive-charts.markdown
en/developer/reference/articles/02-front-end/03-front-end-taglibs/08-chart-taglibs/13-refreshing-charts-to-reflect-real-time-data.markdown

Related issues: [LRDOCS-7645](https://liferay.atlassian.net/browse/LRDOCS-7645) [LRDOCS-7647](https://liferay.atlassian.net/browse/LRDOCS-7647) [LRDOCS-7648](https://liferay.atlassian.net/browse/LRDOCS-7648)
Lots of improvements could have been made in the Related Topics of the Charts' articles. Some of the links throught these pages weren't working or led to the wrong places.
- Changed references in Related Topics
- Fixed Related Topics links that led to the wrong page
- Fixed all links to javadocs
- Fixed links to clay repo

LRDOCS-7645 LRDOCS-7647 LRDOCS-7648 Multiple Issues in Charts 7.2

---

en/deployment/articles/05-upgrading-to-liferay-7-2/08-upgrading-a-sharded-environment.markdown

Jira ticket: https://liferay.atlassian.net/browse/LRDOCS-12509
Related article: https://help.liferay.com/hc/en-us/articles/360029032031-Upgrading-a-Sharded-Environment
The doc contained a piece of text that didn't have any purpose and was polluting the article.
Changes made: 
- Erase unused text.
___
Thanks, @abhnerramos, for [reviewing](https://github.com/abhnerramos/liferay-docs/pull/14) this PR!

LRDOCS-12509 Remove unusual text below title in Upgrading a Sharded Environment

---

en/user/articles/10-managing-users/02-users-and-organizations/03-advanced-user-management.markdown

Jira Ticket: https://liferay.atlassian.net/browse/LRDOCS-9658
Related article: https://help.liferay.com/hc/en-us/articles/360028721712-User-Management-Additional-Topics
The ticket reported an incorrect link in the article.
Changes made: 
- Fix all broken links in the article; and
___
Thanks, @abhnerramos, for [reviewing](https://github.com/abhnerramos/liferay-docs/pull/13) this PR.

LRDOCS-9658 Broken link to custom fields

---

en/develop/tutorials/articles/250-collaboration/03-adaptive-media/03-changing-image-scaling.markdown

Related issue: [LRDOCS-8837](https://liferay.atlassian.net/browse/LRDOCS-8837)
Multiples leading to 404s
- Changed multiple links
Article in question - [Changing Adaptive Media's Image Scaling](https://help.liferay.com/hc/en-us/articles/360018161571-Changing-Adaptive-Media-s-Image-Scaling)

LRDOCS-8837 Fix Links to Discontinued Repo

---

en/user/articles-dxp/120-search/13-result-rankings.markdown

https://issues.liferay.com/browse/LRDOCS-12697
cc @lipusz

LRDOCS-12697, fix incorrect statement on synonym sets and results rankings

---

discover/portal/articles/110-collaboration/01-managing-documents-and-media/01-publishing-files/03-accessing-google-docs.markdown

Related Issue: https://liferay.atlassian.net/browse/LRDOCS-7356
I am not sure if it's going to work and the problem is silly but I wanted to get rid of the ticket.

03-accessing-google-docs.markdown altered TM symbol

---

en/developer/frameworks/articles/portlets/01-portlets-intro.markdown

As requested on the [ticket](https://liferay.atlassian.net/browse/LRDOCS-12102), fixed the broken link to Liferay Learn Portlet article.

LRDOCS-12102 Fix Liferay Learn Portlet Link
